### ISSUE TITLE
Research and design for versioning, update and upgrades

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#10]
One of the main feature we want to provide with this version of 0-OS is the "auto-update". The idea is that the system needs to be able to update itself and each of its component with the minimum downtime possible for the workloads. Minimum in most case would be no downtime at all.

Keeping this in mind actually drives quite a bit the design decision to make for all module of 0-OS.
One of them I would like to discuss here is how are we going to handle versioning of the system.

Since every component is by definition modular and choose be able to be change in place with another one or another version, a single version for the OS is not going to be something meaningful.  So instead of sticking with plain version I had another idea.
Having 3 "flavor" of 0-OS, main, dev and test like tfchain does.

Having these 3 "flavor" will allow to actually have different network into the grid:
- Dev: ephemeral network only setup to develop and test new features. Can be created and reset at anytime
- Test: Mostly stable feature that needs to be tested at scale, allow preview and test of new features. Always the latest greatest. This network can be rest sometimes, by should be relatively stable.
- Main: Released of stable version. Used to run the real grid with real money. Cannot be reset ever. Only stable and battle tested feature reach this level.

This allow each component to progress at its own pace, have a separate semantic version. A flavor will be composed of different version of each modules. Once a new version of a module is ready, it will just make its way trough the 3 flavor from dev to main.

Each "flavor" will actually create a separate grid, the node will always ever connect to other node with the same "version". This simplify the code cause you know you don't have to deal with different version and can be sure of the feature of the node you're talking too.

The flow of a new feature will bubble up from dev to main. Every time a new feature is upgraded to the next level, all the node in this network will receive the update automatically.
This makes upgrading a network trivial and also ensure that upgrade procedure are at least tested at scale 2 time before reaching main net.

**Comment by maxux** [comment]
This approach looks good to me. We need, in addition, to define what should be versioned and how we will upgrade it.

We need well defined way to upgrade different parts, like host (cores, userland tools, hypervisor, drivers, kernel, ...), and running subsystems (containers, vm, ...)

**Comment by zaibon** [comment]
> We need well defined way to upgrade different parts, like host (cores, userland tools, hypervisor, drivers, kernel, ...), and running subsystems (containers, vm, ...)

Indeed this is a very important part I want to get right from the beginning. 

First thing I think is to decide how are we going to publish what version of each component each "flavor" will have to run. Some kind of metadata service which all the node can query daily to know if there is some new goodies for them to run. Something equivalent to an `apt-get update`.

Then once we know there are some upgrade available, we could also have different upgrade procedure depending on the component. Some component which are 100% stateless can probably be upgrade immediately. While some other component might need to wait for a more "quite" time to upgrade since it would imply a small downtime.

Then we also need to define what is the medium we will use to get the new component on the node. Flist could be used. That would do something like:
- discover upgrade are available
- mount the flist component of the new version in a temporary location
- copy the component in place to the filesystem
- if required, restart the processes
- umount the flist

Now doing it like this implies that at each boot, all the required component will have to be downloaded like that. Since all the new component won't be available in the kernel image. This doesn't sounds like a super great way to do things, since if for some reason the node is offline for a bit. It simply won't be able to fully boot. To avoid this that would mean we need to have some kind of installation procedure since we need to have a disk where to put all of these things.
In the first version we avoid this install step cause everything was included in the kernel image. But this force a hard reboot to update anything, so we don't want to go there again.

**Comment by maxux** [comment]
I'm still completely against installing something on disk. This was the main feature from the beginning and I don't see any good reason to move on. This still provide the flexibility we have (no risk of root corruption except if memory is corrupted, always up-to-date image when booting, no disk needed for basic usage, ...).

But I think we can find a good mix between live environment (no setup) and version control.

The live image could contains a more restricted set of things, and get only minimal tools: hardware initialization, reaching internet, quering for available software.

It's already a requirement that if your node doesn't have internet, nothing will start anyway (it already works like this, if internet is not reachable, no service starts). I don't see any reason why downloading needed stuff at that time is a problem.

As soon as this stage is ready, the cycle you suggest can be put in place.

Note: if you want to upgrade kernel, you'll need to reboot anyway, that will never change. Modules could be upgraded without a reboot, but I discourage to do this :p

**Comment by zaibon** [comment]
The problem with this way of working is that its kills the internet connection of farms of a certain size when all the machine boot at the same time for example.

Also, I find it stupid to have to re-download something that we would already have present last time we were running. So what I'm thinking about is not really a full installation, but at least have a cache that can keep the binaries of the different module on disk. So at boot we can check if there is an update available. If not, we just re-use what's in the cache. If the cache is cold, then we re-download.

> It's already a requirement that if your node doesn't have internet, nothing will start anyway (it already works like this, if internet is not reachable, no service starts).

This is indeed the case now, but I think we can improve on this a bit. Imagine a farm of nodes in a location where internet connection is not super stable. It could be that for a period of time, the internet is not reachable, but the LAN of the farm is working. I think that would be nice that all the services can already be started at this point. It could be there are some workload that doesn't requires internet that can already start running.

**Comment by maxux** [comment]
If we can put in place a real p2p system, bandwidth within the same LAN would not be a problem anymore.

If you want to reuse something already downloaded, we need to ensure all checksum etc. The idea downloading everything and not storing anything is to avoid any possible corruption/modification by downloading latest version each time.

**Comment by zaibon** [comment]
I started computing everything that has been said here into specs: https://github.com/threefoldtech/zosv2/pull/32

I'll close the issue here to continue the discussion on the draft PR
