### ISSUE TITLE
Failed to deploy network in time

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/zos#1008]
**Explorer:** testnet
**workload:** https://explorer.testnet.grid.tf/api/v1/reservations/workloads/493452

After 10 mins waiting, it failed to deploy, seems nodes doesn't accept network reservations.

**Comment by m-motawea** [comment]
doesn't respond to containers as well
https://explorer.testnet.grid.tf/api/v1/reservations/workloads/493621

**Comment by zaibon** [comment]
@maxux seems provisiond is stuck on some connection to zdb. Please check the zdb on node `72CP8QPhMSpF7MbSvNR1TYZFbTnbRiuyvq5xwcoRNAib`.

**Comment by maxux** [comment]
After investigation, there is a container which have a zombie process (`sync`) which cannot be killed. Container cannot be stopped and current code waits forever for container (in `contd`) to get stopped before handling others commands.

I have a hotfix which doesn't block `contd` forever by returning an error if process cannot be killed after some time, but this lead to a forever retry of decommission after that. At least, provision are not blocked anymore and node can still work, but not in good condition.

What I suggest is implementing a `fatal error without (direct) retry` flag which would notify that decommission were blocked by a system error, and we can't do anything for now and try again later...

In this case, I don't know what caused the `sync` to block, I don't see anything on `dmesg` but maybe one disk is corrupted and unless we can unblock kernel with this device, the process will never dies (except with a `reboot`).

**Comment by m-motawea** [comment]
this node on testnet is not accepting workloads as well
3dAnxcykEDgKVQdTRKmktggL2MZbm3CPSdS9Tdoy4HAF
