### ISSUE TITLE
Flist process stopped

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/zos#1017]
node: `A7FmQZ72h7FzjkJMGXmzLDFyfyxzitDZYuernGG97nv7` on Freefarm testnet

```
[-] containerd: time="2020-10-27T10:13:00.182502732Z" level=error msg="apply change" error="OCI runtime create failed: container_linux.go:346: starting container process caused \"process_linux.go:449: container init caused \\\"rootfs_linux.go:58: mounting \\\\\\\"proc\\\\\\\" to rootfs \\\\\\\"/var/cache/modules/flistd/mountpoint/476131-1\\\\\\\" at \\\\\\\"/proc\\\\\\\" caused \\\\\\\"mkdir /var/cache/modules/flistd/mountpoint/476131-1/proc: transport endpoint is not connected\\\\\\\"\\\"\": unknown"
```

**Comment by muhamadazmy** [comment]
This is not handled in a way if that happen the container will get decomissioned, but we need to figure out the cause of this crash of the filesystem.

**Comment by muhamadazmy** [comment]
It seems the FS for this container was started on `2020-09-08`. so 2 releases ago. 

The problem is we can't update 0-fs version while it's running, so fixes are only gonna apply for new reservations. 
We need to figure out if the same issue is still persisted for newer reservations.

**Comment by DylanVerstraete** [comment]
I can't find any other occurrences. Maybe this was an isolated event?

**Comment by DylanVerstraete** [comment]
Closing because I cannot reproduce nor find any other occurrences.
