### ISSUE TITLE
error failed to initialize virtual disk module error

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#1023]
`  2020-10-28 12:02:11  
[+] storaged: 2020-10-28T11:02:11Z error failed to initialize virtual disk module error="Not enough space left in pools of this type ssd" limited-cache=false`

466X86s2ctLmL2Q6R7SrJ4VBMyt9h9zJDCSZhHUSQ9py

**Comment by DylanVerstraete** [comment]
This error can occur when storaged boots and the timeout of 1 minute to start everything is exceeded. I looked at this node, storaged booted correctly after.

The timeout can exceed 1 minute if the nodes has alot of disks that are turned off at the moment storaged boots. When this timeout exceeds 1 minute, storaged tries to boot again until successful.

**Comment by zaibon** [comment]
I'm not sure I understand the PR that is linked to this issue. How does checking if disk are down improves things ?

Shouldn't we also tweak the timeout ?

**Comment by DylanVerstraete** [comment]
I was mistaken, the error occurred on a node that had only 2 disks so it was not the disk shutdown causing this log error. 

This function was called when storaged initializes, and returns an error if it tries to list the volumes of a pool that are not mounted.
https://github.com/threefoldtech/zos/blob/4bc3be0f7604f9f49126bb76de9f35792a08b65f/pkg/storage/storage.go#L458
