### ISSUE TITLE
could not unmount flist error="stat /var/cache/modules/flistd/mountpoint/486386-1: no such file or directory"

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#1024]
on node 3dAnxcykEDgKVQdTRKmktggL2MZbm3CPSdS9Tdoy4HAF
6m9gFPTYLRiCH7FD8yU5VWwXZdfegKUvXZgrJoS1EJfQ
2fi9ZZiBGW4G9pnrN656bMfW6x55RSoHDeMrd9pgSA8T

**Comment by DylanVerstraete** [comment]
Should be fixed in: https://github.com/threefoldtech/zos/commit/fb5911d0fb3cee40ac4a2f61f50c05f0d57acaa0
