### ISSUE TITLE
error failed to inspect container for decomission error="container \"492237-1\" in namespace \"ns715\": not found" container=492237-1

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#1025]
on node 3dAnxcykEDgKVQdTRKmktggL2MZbm3CPSdS9Tdoy4HAF
6m9gFPTYLRiCH7FD8yU5VWwXZdfegKUvXZgrJoS1EJfQ

**Comment by DylanVerstraete** [comment]
Issue not seen anymore after the `v0.4.5-rc3` got released on testnet:

http://10.4.0.250:3000/explore?orgId=1&left=%5B%22now-6h%22,%22now%22,%22Loki%22,%7B%22expr%22:%22%7Bnode%3D%5C%226m9gFPTYLRiCH7FD8yU5VWwXZdfegKUvXZgrJoS1EJfQ%5C%22,%20level%3D%5C%22error%5C%22%7D%22%7D,%7B%22mode%22:%22Logs%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D

**Comment by zaibon** [comment]
verified, I cannot reproduce anymore on any of the 2 nodes mentionned
