### ISSUE TITLE
Seems a K8S VM died

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#1042]
Workload: https://explorer.testnet.grid.tf/api/v1/reservations/workloads/494296
I cannot reach this k8s VM anymore. I did checked on the node if I could see the firecracker process of this node but it was not there.
I then checked the dmesg of the node and found this:
```
[16630894.598523] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/,task=firecracker,pid=3120,uid=0
[16630894.598536] Out of memory: Killed process 3120 (firecracker) total-vm:4202960kB, anon-rss:4175940kB, file-rss:0kB, shmem-rss:4kB, UID:0 pgtables:8240kB oom_score_adj:0
[16630894.850221] oom_reaper: reaped process 3120 (firecracker), now anon-rss:0kB, file-rss:16kB, shmem-rss:4kB
```
I cannot be sure this is indeed my missing VM, but firecracker has indeed been killed by the kernel for using too much memory. 

It seems vmd should watch these event and restart the vm when possible.

**Comment by zaibon** [comment]
I had another occurrence of the issue: https://explorer.testnet.grid.tf/api/v1/reservations/workloads/494305
I did not find a OOM error this time, but the firecracker process also does not exist on the node anymore.

**Comment by zaibon** [comment]
So I think there are 2 things to take in account here.
1. We should probably configure the OOM to be nicer with the firecracker processes.
2. We should start do capacity planning for the memory of the node. Today we always accept any workload without checking if there are still enough free memory for it. Which in would trigger the OOM more often.

**Comment by xmonader** [comment]
seems I've the same problem

http://explorer.testnet.grid.tf/api/v1/reservations/workloads/507585
http://explorer.testnet.grid.tf/api/v1/reservations/workloads/507586
http://explorer.testnet.grid.tf/api/v1/reservations/workloads/507587

edit: I added access "again" and now could reach the cluster and ssh into it

**Comment by dmahmouali** [comment]
Also, I can't ssh but can run `kubectl` comments from my local machine

wids: 
- [506853](http://explorer.testnet.grid.tf/api/v1/reservations/workloads/506853)
- [506854](http://explorer.testnet.grid.tf/api/v1/reservations/workloads/506854)
- [506855](http://explorer.testnet.grid.tf/api/v1/reservations/workloads/506855)
---
After added access to the network, I can reach the cluster and ssh.

**Comment by zaibon** [comment]
@xmonader @dmahmouali if you can reach the VM again after fixing your network. This is not the same issue. Please open a another one.

**Comment by muhamadazmy** [comment]
I suspect (with no solid evidence) that this is related to the issue we had on the access node on testnet that it didn't redeploy all the reservations after the reboot. And adding an access basically created a new reservation that got deployed with the correct network resource setup.
