### ISSUE TITLE
zui: smaller resolution (no framebuffer) + always run on node boot

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#1043]
We get many complains that nodes when booted they only see some logs then the node is stuck. We don't immediately see an issue with the node because zui is not booted yet so we have no idea if it's stuck. the problem is:
- ZUI has dependency (in zinit config file) on other daemon that might fail to start, like storaged and networking
- ZUI **SHOULD NOT** have dependencies on those daemons , instead it should show:
  - Status of core services (storage, networked, etc...)
  - Logs from those services in case they are not booted (error logs)
  - Basic network information, like IP addresses, node ID, etc...

- ZUI must run with no framebuffer in case of nodes with no GPU

**Comment by maxux** [comment]
Here is a modified version of `zui` which fit in `80x24`

![image](https://user-images.githubusercontent.com/4141584/98665727-570eb380-234c-11eb-97b0-cc5f1342cf1f.png)

This is an example and is not ready, but this an example of what we could provide.

**Comment by zaibon** [comment]
is there a way the storage pool content would scroll ? cause on a normal node we would have way more pools then just 2.

**Comment by maxux** [comment]
Well, should we display all pools ? As soon as node is registered, you should see theses information remotely. We could maybe show aggregated value (like how many pools there are, and total used/free).

**Comment by DylanVerstraete** [comment]
> Well, should we display all pools ? As soon as node is registered, you should see theses information remotely. We could maybe show aggregated value (like how many pools there are, and total used/free).

I aggree showing the total storage used / free is a better solution. Some nodes have +20 storage pools, this would be a huge list even if it's scrollable

**Comment by muhamadazmy** [comment]
> > Well, should we display all pools ? As soon as node is registered, you should see theses information remotely. We could maybe show aggregated value (like how many pools there are, and total used/free).
> 
> I aggree showing the total storage used / free is a better solution. Some nodes have +20 storage pools, this would be a huge list even if it's scrollable

Make it grouped into only 2 lines one for HDD, and one for SSD

**Comment by DylanVerstraete** [comment]
Something like this? 
```
Storage
Disktype                         TOTAL               USED
SSD                               50gb                  5%
HDD                               2TB                   40%
```

**Comment by zaibon** [comment]
All the information is available online when the node behave properly ^^
The point of this view is to give some insight to the farmer to see help debug and a quick glance on the status of the node. 
So yes, if we have a section storage pool we should them all or we don't show that section at all. It is useless to have only 2 pools and will make it just confusing.

**Comment by maxux** [comment]
We can maybe have different pane (or to make it easier, different tty) with
one dedicated to storage pool ? So we have full size available for pools.

**Comment by DylanVerstraete** [comment]
@muhamadazmy and I aggreed to leave out the capacity pools for now.

It looks like this now:
![Screenshot from 2020-11-10 15-50-24](https://user-images.githubusercontent.com/17138347/98691290-2d668400-236e-11eb-831f-0e8e93e1102d.png)

(with filled in values for cpu and mem usage)

Next step is testing this on my physical node

**Comment by DylanVerstraete** [comment]
closed in https://github.com/threefoldtech/zos/pull/1052/files
