### ISSUE TITLE
vdc: specification of zos internal plumbing once IP is reserved 

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#1051]
The specification should describe the following:
- The internal wiring of the public IP for the traffic to reach a k8s node. Please check proposal [here](https://github.com/threefoldtech/home/issues/925#issuecomment-724640495)
- IPv6 support for VMs

**Comment by muhamadazmy** [comment]
Update workflow
- We move to CH and away from firecracker
- We modify the k8s image to have our custom script to configure IPs from our custom kernel cmdline arguments
- We boot the machine with the right ip configuration
- setup nft rules for the ip fitlering

**Comment by xmonader** [comment]
@muhamadazmy can you please update this to the latest state
