### ISSUE TITLE
kubernetes workloads failing on testnet

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/zos#1055]
error:
```
Workload 502530 failed to deploy due to error failed to install k3s: could not run vm: 2020-11-12T13:02:48.135265889 [502530-1:ERROR:src/firecracker/src/main.rs:268] Configuration for VMM from one single json failed: BootSource(InvalidKernelCommandLine("Command line string contains non-printable ASCII character"))
: failed to spawn vm machine process '502530-1'. For more details: https://explorer.testnet.grid.tf/api/v1/reservations/workloads/502530
```

https://explorer.testnet.grid.tf/api/v1/reservations/workloads/502530
https://explorer.testnet.grid.tf/api/v1/reservations/workloads/502538
https://explorer.testnet.grid.tf/api/v1/reservations/workloads/502552
https://explorer.testnet.grid.tf/api/v1/reservations/workloads/502568

**Comment by m-motawea** [comment]
seems the problem is caused by `\n` in the ssh key. when removed, deployment is ok

**Comment by muhamadazmy** [comment]
This was fixed in the sdk the explorer nor the node are not allowed to modify user input
