### ISSUE TITLE
failed to reserve filesystem for vm: not enough space available  for this disk size

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/zos#1059]
related to https://github.com/threefoldtech/zos/issues/1037
workloads that failed

```
Workload 504218 failed to deploy due to error failed to reserve filesystem for vm: not enough space available
 for this disk size. For more details: https://explorer.testnet.grid.tf/api/v1/reservations/workloads/504218 

Workload 504225 failed to deploy due to error failed to reserve filesystem for vm: not enough space available
 for this disk size. For more details: https://explorer.testnet.grid.tf/api/v1/reservations/workloads/504225 

Workload 504234 failed to deploy due to error failed to reserve filesystem for vm: not enough space available
 for this disk size. For more details: https://explorer.testnet.grid.tf/api/v1/reservations/workloads/504234

Workload 504245 failed to deploy due to error failed to reserve filesystem for vm: not enough space available
 for this disk size. For more details: https://explorer.testnet.grid.tf/api/v1/reservations/workloads/504245 

Workload 504258 failed to deploy due to error failed to reserve filesystem for vm: not enough space available 
for this disk size. For more details: https://explorer.testnet.grid.tf/api/v1/reservations/workloads/504258

Workload 504273 failed to deploy due to error failed to reserve filesystem for vm: not enough space available 
for this disk size. For more details: https://explorer.testnet.grid.tf/api/v1/reservations/workloads/504273
```

nodes should be reporting enough storage

![image](https://user-images.githubusercontent.com/32568986/99183156-89e8eb00-2742-11eb-98b4-94ddfb2299d9.png)

![image](https://user-images.githubusercontent.com/32568986/99183186-a8e77d00-2742-11eb-835b-409780167aaf.png)

![image](https://user-images.githubusercontent.com/32568986/99183235-f95eda80-2742-11eb-83bf-f5401a00a7d9.png)

![image](https://user-images.githubusercontent.com/32568986/99183254-14c9e580-2743-11eb-9d28-a97a297e1ab8.png)

![image](https://user-images.githubusercontent.com/32568986/99183287-31feb400-2743-11eb-97e8-d2aabc46d126.png)

**Comment by xmonader** [comment]
also related from zos chat https://explorer.testnet.grid.tf/api/v1/reservations/workloads/504343

**Comment by muhamadazmy** [comment]
Yes, as stated that is a known limitation that so far a zos node can only utilize one disk for vdisks allocation. A fix was planned but it seems that it needs to be done now.

Will be working on that today

**Comment by muhamadazmy** [comment]
Okay after some debugging it seems there are 2 possible causes:
- there is still discrepancy between what is reported, and what the node actually reserved, due to some calculation bug (already fixed on development branch, not available on testnet yet)
- that vdisks allocation can not utilize all disks on a node (work on progress)
