### ISSUE TITLE
Can't reach k8s VM 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/zos#1068]
I deployed k8s cluster on a network, then added access to that network and started wireguard and could reach the cluster without problems.

then suddenly wasn't able to reach the cluster

```
➜  js-sdk git:(development) sudo wg 
interface: mykube
  public key: Eez11+EHCOZd9VgYgBSwN4ign+CMU1bl01MSjYa8nmo=
  private key: (hidden)
  listening port: 49688

peer: k+JNg2NzCONOjmckckczeiMi/T48xH3UIutYk5W8rUY=
  endpoint: 185.69.166.59:7910
  allowed ips: 10.224.0.0/16, 100.64.224.0/32
  latest handshake: 1 day, 3 hours, 50 minutes, 20 seconds ago
  transfer: 2.72 MiB received, 8.89 MiB sent
  persistent keepalive: every 25 seconds

interface: vpn-work
```

## wids
http://explorer.testnet.grid.tf/api/v1/reservations/workloads/507585
http://explorer.testnet.grid.tf/api/v1/reservations/workloads/507586
http://explorer.testnet.grid.tf/api/v1/reservations/workloads/507587

and same for @dmahmouali

## wids 
- [506853](http://explorer.testnet.grid.tf/api/v1/reservations/workloads/506853)
- [506854](http://explorer.testnet.grid.tf/api/v1/reservations/workloads/506854)
- [506855](http://explorer.testnet.grid.tf/api/v1/reservations/workloads/506855)

Problem seems fixed after adding access

_Originally posted by @xmonader in https://github.com/threefoldtech/zos/issues/1042#issuecomment-731614022_

**Comment by waleedhammam** [comment]
for me can't reach the cluster, there's no handshake in the network. last access was last thrusday

wids

- 507217
- 507218
- 507219

```
➜  js-sdk git:(development_vdc_marketplace) sudo wg
interface: testnet_net
  public key: mrgw/owTqswFhmdUGNv3+MgyDZOwDIKGDqxOcl1uk1w=
  private key: (hidden)
  listening port: 44783

peer: kGWckFs+uZZWld5EvHLIkbpsAiqitoaMnb2QoeBIwEc=
  endpoint: 185.69.166.59:8883
  allowed ips: 172.23.0.0/16, 100.64.23.0/32
  transfer: 0 B received, 1.59 KiB sent
  persistent keepalive: every 25 seconds
```

**Comment by ashraffouda** [comment]
I got the same issue 
here is my workloads info 
```"wids": [505666,505667],
etwork": "management1|
"Master IP": "10.100.9.2"
"Slave IPs": ["10.100.10.2"]
"Slave Pools": [4837]
,"Master Pool": 4837
,
```

```
sudo wg                                                                                      ░▒▓ 1 ✘  at 11:51:29 AM   ▓▒░
interface: mana1
  public key: sinxkf/w+y2N6+Dd2It8a6RniC9WSsUnPzvD4hACahI=
  private key: (hidden)
  listening port: 54653

peer: DRUZr/TeDWkxLPwa1Km7lwVuVqINsyLwlLr38v/lfGQ=
  endpoint: 185.69.166.59:7852
  allowed ips: 10.100.0.0/16, 100.64.100.0/32
  transfer: 0 B received, 2.46 KiB sent
  persistent keepalive: every 25 seconds

```

**Comment by AhmedHanafy725** [comment]
happens with me too
### wids
[495770](https://explorer.testnet.grid.tf/api/v1/reservations/workloads/495770)
[495771](https://explorer.testnet.grid.tf/api/v1/reservations/workloads/495771)
[495772](https://explorer.testnet.grid.tf/api/v1/reservations/workloads/495772)

**Comment by abom** [comment]
The same here, worked again after adding access, WIDs:

[505177](https://explorer.testnet.grid.tf/api/v1/reservations/workloads/505177)
[505178](https://explorer.testnet.grid.tf/api/v1/reservations/workloads/505178)
[505179](https://explorer.testnet.grid.tf/api/v1/reservations/workloads/505179)

**Comment by zaibon** [comment]
Do you guys do any action on your network at some point when you lost connection ?
Like adding new workloads which would trigger a modification of the network ?

I'm suspecting the way chat flows does try, retry, cleanup just delete network resources while it should not. Basically, if you delete any existing network resource, the network for this node is gone.

**Comment by abom** [comment]
Last thing I did on dashboard was deploying the cluster, did nothing after that.

**Comment by zaibon** [comment]
but the deployment of the cluster does this dry run where it could delete network resources I guess ?

**Comment by m-motawea** [comment]
> but the deployment of the cluster does this dry run where it could delete network resources I guess ?

dry run uses a different network create temporary before it actually updates the network. we don't delete any network workload except the dry run network

**Comment by muhamadazmy** [comment]
@m-motawea & @xmonader do you guys still need this dry-run hack? why do we have this in the first place ?

**Comment by muhamadazmy** [comment]
I suspect (with no solid evidence) that this is related to the issue we had on the access node on testnet that it didn't redeploy all the reservations after the reboot. And adding an access basically created a new reservation that got deployed with the correct network resource setup.

**Comment by muhamadazmy** [comment]
btw: during some debugging on the node (to fix the lost network resources issues) some network resources has been destroyed permanently (next action set to "deleted") on the explorer due to a bug in networkd that is now fixed. it means some networks has been affected on testnet. so please if u still have an issue with your network make sure that all reservations in this network are in the correct state.

**Comment by DylanVerstraete** [comment]
Try adding access to your existing network again through the threebot. This fixed it for me.
