### ISSUE TITLE
k8s VM is not deleted after workload failure and after decommission on devnet

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/zos#1069]
trying public ips on devnet on node `2anfZwrzskXiUHPLTqH1veJAia8G6rW2eFLy5YFMa1MP`,
I created a VM https://explorer.devnet.grid.tf/api/v1/reservations/workloads/2083 and it failed with error `failed to start k3s VM in 5 minutes` then shortly after that tried to deploy a new VM https://explorer.devnet.grid.tf/api/v1/reservations/workloads/2084 on the same node it failed with error `kubernetes VM with the same name exists on network pub`

seems the first VM https://explorer.devnet.grid.tf/api/v1/reservations/workloads/2083 is still running although next action is 6.
even after decomission it is still not deleted and I can ssh into the VM.

related to https://github.com/threefoldtech/home/issues/925

**Comment by zaibon** [comment]
I think this specific case should be handled better now: https://github.com/threefoldtech/zos/commit/6ac1bdad030918f8e041ce454903df3c592bd68e
@LeeSmet right ?

Once this branch is merged this kind of error should not happen anymore.

**Comment by LeeSmet** [comment]
Indeed, at least some early testing shows that such cases should now be caught properly

**Comment by muhamadazmy** [comment]
It's fixed by the public ip branch

**Comment by waleedhammam** [comment]
happened again in:
`"message": "failed to install k3s: failed to install vm in 5 minutes"`

 https://explorer.devnet.grid.tf/api/v1/reservations/workloads/4229

**Comment by waleedhammam** [comment]
also with: https://explorer.devnet.grid.tf/api/v1/reservations/workloads/4496
again: https://explorer.devnet.grid.tf/api/v1/reservations/workloads/4508

**Comment by muhamadazmy** [comment]
> also with: https://explorer.devnet.grid.tf/api/v1/reservations/workloads/4496
> again: https://explorer.devnet.grid.tf/api/v1/reservations/workloads/4508

I checked the dev nodes and there are NO vms with those IDs running. So at least they get cleaned up cleanly. We still looking into the reason why sometimes they fail atm.
