### ISSUE TITLE
kubernetes vm with same network already exist

### ISSUE THREAD

**Issue by majjihari** [threefoldtech/zos#1076]
### Description

kubernetes vm with same network already exist

### Version information

Ubuntu 18.04

### Installation method

js-sdk-development (default)

### Steps to reproduce

While creating the k8s cluster on new network. I think the issue is created because of existing old workloads with state ERROR and nextAction set to DELETE. The expected behavior of these workloads is State=DELETED.

JS-NG> for workload in j.sals.zos.get().workloads.list(1500,NextAction.DELETE): 
     2     print("id=",workload.id,", state=",workload.info.result.state, ", nextAction=", workload.info.next_action)   
id= 489109 , state= State.Error , nextAction= NextAction.DELETE
id= 500611 , state= State.Error , nextAction= NextAction.DELETE
id= 504092 , state= State.Error , nextAction= NextAction.DELETE
id= 504105 , state= State.Error , nextAction= NextAction.DELETE
id= 504106 , state= State.Error , nextAction= NextAction.DELETE
id= 504129 , state= State.Error , nextAction= NextAction.DELETE
id= 504150 , state= State.Error , nextAction= NextAction.DELETE
id= 504151 , state= State.Error , nextAction= NextAction.DELETE
id= 504153 , state= State.Error , nextAction= NextAction.DELETE
id= 504174 , state= State.Error , nextAction= NextAction.DELETE
id= 504176 , state= State.Error , nextAction= NextAction.DELETE
id= 504208 , state= State.Error , nextAction= NextAction.DELETE
id= 504209 , state= State.Error , nextAction= NextAction.DELETE
id= 504283 , state= State.Error , nextAction= NextAction.DELETE
id= 504296 , state= State.Error , nextAction= NextAction.DELETE
id= 504343 , state= State.Error , nextAction= NextAction.DELETE
id= 504344 , state= State.Error , nextAction= NextAction.DELETE
id= 504510 , state= State.Error , nextAction= NextAction.DELETE
id= 504512 , state= State.Error , nextAction= NextAction.DELETE
id= 504513 , state= State.Error , nextAction= NextAction.DELETE

### Traceback/Logs/Alerts

https://explorer.testnet.grid.tf/api/v1/reservations/workloads/509017

**Comment by zaibon** [comment]
I'm reopening, This is not normal that these workloads are not deleted.

**Comment by muhamadazmy** [comment]
The cleaner (janitor) in provision engine should also make sure to check vm reservations that are not in the "deployed" state on the explorer and deprovision those as well.

**Comment by DylanVerstraete** [comment]
Waiting until new provisiond code is merged so we can tackle this easier
