### ISSUE TITLE
K8S VM becomes suddenly read-only

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#1086]
I've notice one of my VM has some struggle. After checking dmesg I found:

VM dmesg: https://gist.github.com/zaibon/4bc9ce87a45f1954b16ae7576da14755

VM logs (machine.log): https://gist.github.com/zaibon/85b8178e08cb7e1870807ed552dea7a5

Workload:https://explorer.grid.tf/api/v1/reservations/workloads/81140

**Comment by LeeSmet** [comment]
Is this a vm on devnet or testnet?

**Comment by zaibon** [comment]
I edite the comment with the link to the workload. It's mainnet...

**Comment by muhamadazmy** [comment]
The logs from machin.log seems like the host is running out of disk space. it seems firecracker does not propagate this properly.

**Comment by delandtj** [comment]
closing as it's not applicable any more... You know... cloud-hypervisor and all...
