### ISSUE TITLE
kubernetes workers do not join the cluster on devnet

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/zos#1091]
whenever I deploy a kubernetes cluster on devnet, the workers do not join the cluster.
workloads:
https://explorer.devnet.grid.tf/api/v1/reservations/workloads/2448
https://explorer.devnet.grid.tf/api/v1/reservations/workloads/2455

**Comment by LeeSmet** [comment]
Should be fixed in #1092

**Comment by muhamadazmy** [comment]
We have a potential fix on devnet now, could you please try again.

**Comment by DylanVerstraete** [comment]
Still does not work, worker does not join cluster

**Comment by DylanVerstraete** [comment]
Verified that it works
