### ISSUE TITLE
Node down notification

### ISSUE THREAD

**Issue by joefoxton** [threefoldtech/zos#1112]
As a farmer, I want to receive an email notification that my node is down from the grid perspective, so I can fix the problem

We are implementing monitoring and alerting on our Green Edge grid. However, there may be conditions under which our hardware looks completely healthy, but the grid is marking the node as "Down". As such we'd like to be notified about such events via email.

I understand that there is a plan to integrate Prometheus & Grafana, which should give us the above. Let us know the prescribed way for solving the above problem.

**Comment by muhamadazmy** [comment]
Related to #1101

**Comment by DylanVerstraete** [comment]
We can integrate this into 3.0. Should be moved to digital twin? @muhamadazmy

**Comment by xmonader** [comment]
should be addressed by a 3rd party solution
