### ISSUE TITLE
Since 0.4.7-rc8 no DHCPv6 on virtualized Zos

### ISSUE THREAD

**Issue by archit3kt** [threefoldtech/zos#1113]
Hi, I'm actually trying to test 3F on testnet (I post on the forum as NatureCrypto)

I've got 4 VM with Zos inside (KVM virtualization with 1 NIC linux bridging), they booted and got IPv6 OK from my ISP router. It does not work anymore since 0.4.7-rc8, they only get IPv4. Other test VM (debian or manjaro) got their IPv6 IP without problem, IPv6 connectivity on the net is OK.

It seems you made a lot of networking changes on this release, to be 100% sure it worked OK with rc7, is it possible to grab this previous version to test it ?

Thanks

**Comment by delandtj** [comment]
we did a lot of changes on the L2 level, that shouldn't be a problem.
Either way, we don't run an dhcpv6 client, only do SLAAC and accept RA's from a router. no dhcpv6

**Comment by muhamadazmy** [comment]
We will make a new release RC9 during the day that has more fixes to the zos network. This might have a fix for the issue you are having.

**Comment by muhamadazmy** [comment]
Okay, rc9 is ready could you let me know if you still have this problem. Thanks

**Comment by archit3kt** [comment]
Hi,

that's good to know you're not using DHCPv6, I turned it off !

Sadly, the new build did not resolve my issue. I still don't take an IPv6
address with rc9.

Is there a way to test an old build rc7 o rc6 to be sure the issue isn't on
my side ? Pretty sure it's not because other VMs get their v6 IP, but
well...

Thank you for your help


Le lun. 7 déc. 2020 à 12:51, Muhamad Azmy <notifications@github.com> a
écrit :

**Comment by archit3kt** [comment]
Still same problem today with the latest zos version.

Would it be possible to test the 0.4.7-rc7 to verify my theory ? Or could you verify that you encounter the bug on a standard KVM libvirt VM ?
