### ISSUE TITLE
boot: node need to proof it's part of a farm

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#1129]
Currently anyone can boot a node with any farm id. Once the node is booted the node will appear as part of this farm on the explorer. We need to come up with a mechanism to proof that the node is indeed part of that farm and that the owner of the farm booted it.

## Points to consider
- This proof should not affect current nodes. so if a node is already registered it should still appear as part of that farm
- New nodes need to provide a proof
  - A proof can be a token that is added to the node boot arguments that proofs that the owner owns the farmer identity (may be generated by the farmer management 3bot)
- explorer needs to validate node token.

**Comment by DylanVerstraete** [comment]
Can be added in 3.0 through the digital twin farmerbot
