### ISSUE TITLE
Zero-OS on ARM architechture

### ISSUE THREAD

**Issue by maxux** [threefoldtech/zos#1130]
This gonna be the entrypoint on roadmap to get Zero-OS running on ARM devices.

- We will need to defines what we need to support, there are multiple target (armv6, armv7, armv8, ...)
- We need to get a working kernel (https://github.com/threefoldtech/0-initramfs)
- We need a working zinit process manager (https://github.com/threefoldtech/zinit)
- Then we need zos runtime binaries (https://github.com/threefoldtech/zos)

We need to know that running on ARM will disable runtime features, like `KVM` support, obviously. We will need to see how to handle that.

Some code will need some refactor (like https://github.com/threefoldtech/0-db) because it requires some CPU specific feature like SSE 4.2

All projects will need to support easy target selection (update Makefile, etc.) without hacking build methods.

We need to see if running the full system in RAM is still doable with less RAM available aswell (depend on target).

Probably more to come. I would suggest to first target `armv8` since this is used by `Raspberry Pi 4` and will be easy to test.
This runs on `ARM Cortex A5x` and same will be used on production later, from what I heard :)

**Comment by muhamadazmy** [comment]
We keep carrying this issue from milestone to a milestone while i don't believe there is no real requirements (yet) may be it should be closed for now until there is an actual momentum to do this
