### ISSUE TITLE
Kubernetes phase2

### ISSUE THREAD

**Issue by zgorizzo69** [threefoldtech/zos#1134]
- [x] Deploy in a breeze kubernetes with VM and network provisioning
- [ ] Deploy Kubernetes in HA mode
  - [ ] investigate HA Proxy
  - [ ] investigate ETCD cluster
  - [ ] Update provisioning to launch with Dqlite
  - [ ] Update provisioning script to setup fixed IP (ha proxy or others ..)
  - [ ] Update startup script to include HA mode
  - [ ] Setup Inlet and metalLB to be able to have a public IP available for TLS termination in our cluster

**Comment by DylanVerstraete** [comment]
Closing because we don't have any current plans for this in grid 3.0
