### ISSUE TITLE
Failed to deploy network on node on mainnet

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/zos#1141]
Node: `74DKSsLfnkUX6Qy9FQPQSrNZvAvBt8L76EFJcucQ2GDZ`

`Workload 83144 failed to deploy in time`

workload: https://explorer.grid.tf/api/v1/reservations/workloads/83144

**Comment by muhamadazmy** [comment]
The logs i have here says this reservation has already been decomissioned

![image](https://user-images.githubusercontent.com/10920323/104609680-f5d8c880-568b-11eb-868b-39ae8e42b4e5.png)
