### ISSUE TITLE
nodes come online at boot and go offline right afterwards

### ISSUE THREAD

**Issue by andhartl** [threefoldtech/zos#1142]
farmer shave problems with their nodes staying online.
<img width="426" alt="image" src="https://user-images.githubusercontent.com/18591016/104000009-ef36e680-519d-11eb-91bc-19dd6ef41b23.png">

**Comment by andhartl** [comment]
Weynand tested with his node and has the same issue. node does not get IP

**Comment by LeeSmet** [comment]
Issue is reproducible on  a local vm. It seems the veth pair used to connect br-pub and the zos bridge is not set up. Manually doing this unblocks networkd
