### ISSUE TITLE
Failed to deploy network

### ISSUE THREAD

**Issue by MohamedEssamAdawy** [threefoldtech/zos#1145]
I try to deploy VDC on devnet and failed due to this error

![image_2021-01-10_10-41-43](https://user-images.githubusercontent.com/11272864/104119260-e4638980-5336-11eb-9a84-1024a3f909bf.png)

**Comment by waleedhammam** [comment]
No nodes with IPv4 available on devnet

**Comment by muhamadazmy** [comment]
@MElborolossy and @waleedhammam wrong repo ? I think this should be moved to js-sdk

**Comment by waleedhammam** [comment]
@muhamadazmy after the data center migration there's no access nodes with ipv4 on devnet so we can't create ipv4 networks, there was one before but didn't come up, also the created networks before gone down

**Comment by muhamadazmy** [comment]
We have access node with ipv4 now, hence I will close the issue
