### ISSUE TITLE
Workload failed to deploy in time on node on mainnet

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/zos#1146]
Reservation ID: https://explorer.grid.tf/api/v1/reservations/workloads/83696
node: `FhfuPwcPhjZNg7cp6H9uZc142eS2fHDWXzxdAz6XNCxT`

**Comment by muhamadazmy** [comment]
I can't find problem in the logs, and unfortunately this is a hidden node, so we can't get access to it to check the state on the machine. This is a "can't investigate" issue.

**Comment by sasha-astiadi** [comment]
removed from 2.4 backlog

**Comment by muhamadazmy** [comment]
There are lots of improvement regarding stability of the node services in release 0.5.0. We will close this issue now and to be reopen if issue persists on main-net after the release
