### ISSUE TITLE
getting Bad file descriptor error on deploying 3bot on mainnet

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/zos#1147]
Redis logs
```
3) "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/packages/tfgrid_solutions/scripts/threebot/entrypoint.sh: /sandbox/code/github/threefoldtech/js-sdk/jumpscale/packages/tfgrid_solutions/scripts/threebot/entrypoint.sh: Bad file descriptor\n"
```

Workload
https://explorer.grid.tf/api/v1/reservations/workloads/83913

**Comment by muhamadazmy** [comment]
Does this same flist works on other nodes ? does it work on testnet ?
This error "seems" to be a 0-fs issue, can be caused by a corrupt cache or bad disk. Unfortunately the node is hidden so I can really check what is going on.

I also can't see any alarming issues from the node logs.

**Comment by waleedhammam** [comment]
@muhamadazmy yeah only got this on that node
