### ISSUE TITLE
workloads' next action are delete and they are still active on the pool

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/zos#1148]
**pool:** https://explorer.devnet.grid.tf/api/v1/reservations/pools/2726
**workloads:**
https://explorer.devnet.grid.tf/api/v1/reservations/workloads/17004
https://explorer.devnet.grid.tf/api/v1/reservations/workloads/16995
https://explorer.devnet.grid.tf/api/v1/reservations/workloads/16982
https://explorer.devnet.grid.tf/api/v1/reservations/workloads/16981
https://explorer.devnet.grid.tf/api/v1/reservations/workloads/17008
https://explorer.devnet.grid.tf/api/v1/reservations/workloads/16992
https://explorer.devnet.grid.tf/api/v1/reservations/workloads/16988

**Comment by muhamadazmy** [comment]
A 'next_action' of Delete does not mean the workload is actually deleted. It's an instruction to the node to delete this workload, but as long as it's not actually deleted they still gonna be part of the pool.

I will take a look why this is not actually become deleted.

**Comment by muhamadazmy** [comment]
It seem that all **stuck** reservation are on node `qzuTJJVd5boi6Uyoco1WWnSgzTb7q8uN79AjBT9x9N3`which seems to be down. 

As long as the node is not processing the `to-delete` reservations this should be part of the pool. A better approach is of course if the node is down for long time that reservations on this node should be "paused". but that can be for the future.

**Comment by muhamadazmy** [comment]
Okay, the node was down. starting the node fixed the issue with the "active" reservations
