### ISSUE TITLE
VDC: silver size is not enough to deploy solution from marketplace, worker is <not ready>

### ISSUE THREAD

**Issue by hossnys** [threefoldtech/zos#1160]
- just deployed a silver size vdc name : qatest1  on testnet 

**workloads** : 
![image](https://user-images.githubusercontent.com/26298009/105366009-87ee4d00-5c07-11eb-9a0a-66358e42c5e2.png)

when listing nodes i got that the worker is not ready :
```
root@samir:~/.kube# kubectl get nodes
NAME        STATUS     ROLES    AGE   VERSION
k3os-5262   NotReady   <none>   75m   v1.19.4+k3s1
k3os-1499   Ready      master   77m   v1.19.4+k3s1
```

**Comment by waleedhammam** [comment]
node was killed
