### ISSUE TITLE
Kubernetes solution backup & restore 

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/zos#1161]
According to https://rancher.com/docs/k3s/latest/en/backup-restore/

```
Snapshots are enabled by default.

The snapshot directory defaults to /server/db/snapshots
```

we should be able to make backup/restore by default in `v1.19.1+k3s1` but `/server` directory not found on the cluster

```
k3os-1499 [~]$ ls /
bin  boot  dev	etc  home  k3os  lib  media  opt  proc	root  run  sbin  sys  tmp  usr	var
```

**Comment by muhamadazmy** [comment]
Why this can't be created before running the backup? what should be under /server ?

**Comment by m-motawea** [comment]
started local k3s cluster with single node 
```bash
sudo k3s server --etcd-snapshot-dir /server --etcd-snapshot-schedule-cron * * * * *
```

and created a pod & a namespace to check backup but nothing was backed up

**Comment by muhamadazmy** [comment]
Are you sure this directory exists on a rancher image by default, or need to be created somehow ? Note that we just use rancher image with just some custom scripts to setup networking, but with no changes to underlying image structure.

**Comment by m-motawea** [comment]
currently using velero to backup & restore the resources but below are some points to discuss:
- backup all deployments or the marketplace solutions only (requires a selector on each) 
- should we backup the volumes or not? (NOTE: hostPath volumes are not supported but local volumes can be restored) 
- for the backup storage should  the user get an external S3 or we should deploy one for them. (NOTE: velero shares the S3 creds with the VDC) so it we can't have a global s3 for all of them, and  the user can also with some experience abuse it and where to host the S3?

**Comment by xmonader** [comment]
I'll move that to next, as the team is already overloaded to look into it and we kinda have two other flows working (velero/etcd)
