### ISSUE TITLE
access nodes with unreachable ip on testnet

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/zos#1166]
there is a problem with the access node. I can't reach its public ip `185.69.166.59` and I'm getting the same with ip  `62.150.68.29` for node EBKTQA1A4gXVjvcJf5GE94DfA7DDE4rEGyKkfam8V1Wk : ogfarm
workload: 3105

@weynandkuijpers please add your relevant network workload ids

_Originally posted by @m-motawea in https://github.com/threefoldtech/js-sdk/issues/2317#issuecomment-766829194_

**Comment by delandtj** [comment]
that is a node in kuwait... Can't ping the public ip, can you tell me hos it's set-up ?
Either way, 185.69.166.59 would not be reachable there at all, as that is an IP from the network in Lochristi
