### ISSUE TITLE
Support vlans tagging of traffic

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/zos#1174]
Right now all traffic is just send out of the nics. We need the ability to optionally add vlan tags. There are 2 types of traffic: mgmt, and public traffic. We can simply modify br-pub and zos bridges to be vlan aware, and tag the incoming traffic from those. (care should be taken when br-pub is attached to zos)

**Comment by muhamadazmy** [comment]
Sounds good to me

**Comment by coesensbert** [comment]
Would be nice to have this to support https://github.com/threefoldtech/tf_operations/issues/1871

@delandtj had the idea to set dmz/public untagged/tagged via two optional kernel parameters, to be chosen by the farmer (which one untagged/tagged)

**Comment by muhamadazmy** [comment]
Sound good to me, i will include this in next milestone
