### ISSUE TITLE
Volume provisioning give btrfs subvolume of size 0

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#118]
I did a provisioning of volume of 5GiB, then when I wanted to write some file into my volume I immediately got an `quota exceeded error`

**Comment by zaibon** [comment]
@LeeSmet can you point where this is handled in the code ?

**Comment by muhamadazmy** [comment]
It's a bad size conversion, the Provision module expects module in GiB while storage expects a size in Bytes.
