### ISSUE TITLE
failed to ensure zdb container running

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/zos#1184]
**explorer:** devnet

while trying to deploy zdb on node `3NAkUYqm5iPRmNAnmLfjwdreqDssvsebj4uPUt9BxFPm`

```
failed to ensure zdb containe running: failed to dial \"/run/containerd/containerd.sock\": context deadline exceeded
```

**workloads:**
https://explorer.devnet.grid.tf/api/v1/reservations/workloads/26712
https://explorer.devnet.grid.tf/api/v1/reservations/workloads/26711

also, typo in the error message: `failed to ensure zdb containe running` => `failed to ensure zdb container running`

**Comment by muhamadazmy** [comment]
Fixed by https://github.com/threefoldtech/zos/pull/1245
