### ISSUE TITLE
ZOS: Setup zstor and 0-db-fs in k3os image

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/zos#1186]
In order to use https://github.com/threefoldtech/js-sdk/issues/2262 some binaries and dependencies are needed for that

Binaries required:

- hiredis
- libfuse3
- zstor
- zdb-fs
- zdb
- etcd

**Comment by xmonader** [comment]
zstor has static binary available, i guess the problem would be for the rest only @maxux ?

**Comment by maxux** [comment]
If you have `libhiredis` and `libfuse`, just compile zdbfs against them (use `make release`).
Or I need to provide a static binary with fuse and hiredis shipped and you don't need them.
But I won't provide a compiled binary with shared libraries needed, this will lead to issue with `hiredis` 0.13, 0.14 and 1.0.0

**Comment by maxux** [comment]
Don't forget `etcd` if you want `zstor` to works (without external etcd setup)
