### ISSUE TITLE
Provisioning module has no notion of reservation expiration

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#121]
Currently in the provisioning module, the reservation have no notion of time. We lack the information about for how long does the reservation needs to be live.

We need to add a duration to the Reservation struct, so we can know if a reservation is still valid or if it should be deleted from the system

**Comment by delandtj** [comment]
#### Duration or expiry date ? 
if a user adds coin to his reservation, what happens ?
- duration is a number, where newduration = oldduration - []list of elapsed + (coin * duration)
- expiry is a date where newdate = olddate + (coin * duration)

So : 
- expiry is indivisible and 
- in duration we could have a more granular approach of a list of durations where the reservation was active, but it seems to me we don't have a definition for that

and:
- expiry is simpler to reason and code around
- duration is more elastic

**Comment by zaibon** [comment]
Very good point. I think as long as we don't know how a user is supposed to extend a reservation we cannot really make a decision here. I would lean more toward duration cause I think this will make extension of a reservation easier. 
With fix expiration date, we'll need some logic somewhere that looks what was the previous expiration date, then add some time to it etc... Makes things a bit more complex I think

While if we just have duration, the node can perfectly gather all the reservation for a specific workload and just add all the duration to get the full duration time.

@despiegk any comment on that ?
