### ISSUE TITLE
CPU Core resource allocation is off

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/zos#1212]
Did a test with a number of different sized container as we are working with a partner who would like to test the performance of a container with low memory. All containers are provisioned with the "Ubuntu" solution in the online 3bot on testnet.

1. container with 1 core and 1GB of RAM
2. container with 2 cores and 1GB of RAM
3. container with 4 cores and 1GB of RAM

the results are things that are off:
- when I provision a single core I can max out all 24 cores (100% utilisation) (all 24 corews)
- when I provision multiple cores I can max out all 24 cores to (1/number_of_cores). 2cores -> max out all @ 50%. 4 cores -> max out all cores @ 25%
- when I provision more cores I can still use all cores, but I get a lower maximum percentage of all cores 

I guess desired behavior is:
- when provisioned a single core - you get 100% of a single core
- when you provision multiple cores you get access to multiple cores @ 100 % or get access to multiple of the provisioned cores at less than 100% max usage totaling to number of provisioned cores * 100%.

Partner is going to test (for a blockchain solution, proof of work type) how much performance they get renting cores.

- In order to test I have installed sysbench (parallel thread stress testing tools).
- Each container is installed on a physically different server
- pushing to launch 24 threads on each of these containers.

Result single core provisioning when the command is ```sysbench cpu --threads=24 run```
![screenshot_20210309_081216](https://user-images.githubusercontent.com/13766992/110417526-34e53200-80af-11eb-9407-55744b126274.png)

24 cores * 100% utlilisation = 24 times what I paid for.

Result double core provisioning when the command is ```sysbench cpu --threads=24 run```
![screenshot_20210309_081342](https://user-images.githubusercontent.com/13766992/110417649-665dfd80-80af-11eb-8c82-de51aa1fd4e0.png)
24 cores * 50%  / 2 cores = 1200 / 2 = 6 times what I paid for

Result four  core provisioning when the command is ```sysbench cpu --threads=24 run```
![screenshot_20210309_081501](https://user-images.githubusercontent.com/13766992/110417782-91485180-80af-11eb-9727-32dcb40810ed.png)

24 cores * 25% utilization / 4  = 600% / 4 = 1.5 time what I paid for

**Comment by weynandkuijpers** [comment]
![screenshot_20210309_082758](https://user-images.githubusercontent.com/13766992/110418642-63fca300-80b1-11eb-81a1-e2105a3946d1.png)

**Comment by DylanVerstraete** [comment]
Thanks for reporting @weynandkuijpers !

**Comment by weynandkuijpers** [comment]
Can I use my existing 3bot to check (by redeploying) or do I need to restart my 3bot? Next level test is to reserve a larger core container (16/32/64) on the largest machine we have (32 physical cores) and do the same.  The original (external) complaint was that it was super slow (while it should be super fast).  Will you check or you want me to check?

**Comment by weynandkuijpers** [comment]
While verifying:
- booked a 4 core ubuntu container 
![screenshot_20210310_105100](https://user-images.githubusercontent.com/13766992/110589147-6e8d6a00-818f-11eb-87a7-10d0ae5205b2.png)
- used sysbench to launch 1,2,3,4 core test.  All good (100% od 1, 2 3, or 4 cores)
``` sysbench cpu --cpu-max-prime=20000 --threads=4 --time=20 run```
![screenshot_20210310_105950](https://user-images.githubusercontent.com/13766992/110589406-ce841080-818f-11eb-933e-765263f7b6ca.png)
- when asking for more core sin sysbench it uses a maximum of 6 cores @ 100%

``` sysbench cpu --cpu-max-prime=20000 --threads=6 --time=20 run```
![screenshot_20210310_110212](https://user-images.githubusercontent.com/13766992/110589584-14d96f80-8190-11eb-87a0-da90c9409837.png)

``` sysbench cpu --cpu-max-prime=20000 --threads=24 --time=20 run```
In this case 24 * 0.25 cores (25%) = 6 cores.
![screenshot_20210310_110257](https://user-images.githubusercontent.com/13766992/110589666-320e3e00-8190-11eb-9063-4678981cfa75.png)

Shouldn't this max out at 4x100% = 4 cores in total?

**Comment by DylanVerstraete** [comment]
@weynandkuijpers we did not deploy yet on devnet. Will do it asap and let you know so you can try again.

**Comment by DylanVerstraete** [comment]
![Screenshot from 2021-03-09 15-03-51](https://user-images.githubusercontent.com/17138347/110597534-f8820680-8180-11eb-874c-2f15e8e4fdf4.png)

This is an example of a machine with 1 core running the cpu benchmark.

**Comment by weynandkuijpers** [comment]
okay - I was testing on testnet, not devnet.  Let me know when - I will then redo.

**Comment by DylanVerstraete** [comment]
reopening for verification

**Comment by DylanVerstraete** [comment]
@weynandkuijpers you can try now on devnet

**Comment by weynandkuijpers** [comment]
![screenshot_20210311_082230](https://user-images.githubusercontent.com/13766992/110735309-fda78a00-8242-11eb-999d-8f9ca87224ad.png)

Could not deploy a 3bot on devnet

**Comment by DylanVerstraete** [comment]
@xmonader Can you check what is wrong with the devnet 3bot deployer please?

**Comment by xmonader** [comment]
I just deployed a new one right now works ok, probably zerossl took too long to respond to generate the certificate for the 3bot

**Comment by DylanVerstraete** [comment]
@weynandkuijpers can you try again please?

**Comment by weynandkuijpers** [comment]
tested 1 - 2  and 4 cores ubuntu with 1, 2, and 4 threads.  Used 100% of the allowed cores.

![screenshot_20210312_125314](https://user-images.githubusercontent.com/13766992/110916288-12168000-8332-11eb-895a-d6c432759f07.png)

**Comment by weynandkuijpers** [comment]
and the same ubunto deployments with 6 times the number of threads (6, 12 and 24) it looks good too:
![screenshot_20210312_125637](https://user-images.githubusercontent.com/13766992/110916684-7f2a1580-8332-11eb-8764-34172904b928.png)

**Comment by DylanVerstraete** [comment]
We can include this in next release to be deployed on testnet.

**Comment by weynandkuijpers** [comment]
Is that the 2.6 release?  I would like to send / expose these VM's to a potential future partner earlier then end of next week.  Can we define and do a 2.5.1 release at the start of next week?
