### ISSUE TITLE
iSCSID service fails to start on K3OS

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/zos#1233]
Was trying to run iSCSI daemon to try out longhorn but it fails to start.
When executing `sudo /etc/init.d/iscsid -v start` It fails with the following error:
```
 * Executing: /lib/rc/sh/openrc-run.sh /lib/rc/sh/openrc-run.sh /etc/init.d/iscsid start
 * Checking Open-iSCSI configuration ...                                                                                                        [ ok ]
 * Starting iscsid ...
 * Detaching to start `/sbin/iscsid' ...
 *   start-stop-daemon: /sbin/iscsid died
 * Failed to start iscsid                                                                                                                       [ !! ]
 * ERROR: iscsid failed to start
```
and in `/var/log/messages`:
```
Apr  6 08:10:19 k3os-20359 daemon.warn iscsid: iSCSI logger with pid=23238 started!
Apr  6 08:10:19 k3os-20359 daemon.info iscsid: iSCSI daemon with pid=23239 started!
Apr  6 08:10:19 k3os-20359 daemon.err iscsid: can not create NETLINK_ISCSI socket [Protocol not supported]
Apr  6 08:10:19 k3os-20359 daemon.err /etc/init.d/iscsid[23215]: start-stop-daemon: /sbin/iscsid died
```

**Comment by muhamadazmy** [comment]
Can we provide more information like:
- `dmesg` 
- `lspci`

**Comment by OmarElawady** [comment]
lspci:
```
00:01.0 Class ffff: 1af4:1043
00:04.0 Class 0200: 1af4:1041
00:00.0 Class 0600: 8086:0d57
00:03.0 Class 0200: 1af4:1041
00:02.0 Class 0180: 1af4:1042
00:05.0 Class ffff: 1af4:1044
```
dmesg (last command was `sudo /etc/init.d/iscsid -v start`):
https://gist.github.com/OmarElawady/71b8fc27025ab61e4a02bb31ab6ac3a2

**Comment by muhamadazmy** [comment]
My guess is that the current k3os kernel is missing a module or something. because this is directly protocol not supported error returned by the kernel when trying to establish a netlink connection.

That's so far my finding, so it still might be wrong. 
![image](https://user-images.githubusercontent.com/10920323/113710657-476d7e00-96e4-11eb-8b4d-320d6a9b5f90.png)

Also deserve mentioning that the iscsi netlink protocol is supported since kernel 2.6 !

**Comment by muhamadazmy** [comment]
@OmarElawady  Seems the kernel for this k3os image was built without support for iscsi ! we will probably have to provide a new image with updated kernel

**Comment by LeeSmet** [comment]
To my knowledge we don't support direct k3s deployments in zos anymore
