### ISSUE TITLE
Log forwarding sometimes hangs the container's service

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/zos#1236]
workload id: https://explorer.testnet.grid.tf/api/v1/reservations/workloads/30324

when enabling log forwarding, the service stuck (it went in the spawned state)
![image](https://user-images.githubusercontent.com/41957921/114401694-7469d700-9ba3-11eb-811b-a7597b7f5fbe.png)

And when checking the process's status
![image](https://user-images.githubusercontent.com/41957921/114401917-a418df00-9ba3-11eb-97b3-990f01905613.png)

**Comment by muhamadazmy** [comment]
So I checked the node and here are the findings i found so far:
- logs from the container are not read anymore (checking logs from the /var/cache/modules/contd/logs/ns1830/30324-1.log) it seems "trimmed".
- the shim-logs is stuck on epoll_wait syscall
- stdout and stderr of the shim is both redirected to /dev/null so i can't tell if it logged an error before it get stuck
- the redis endpoint where the logs are forwarded is reachable from the node.

I suspect that somehow the shim stops reading from the pipe, hence the process (zinit) stdout/err buffer gets full and then no more writing is possible

**Comment by muhamadazmy** [comment]
may be fixed by https://github.com/threefoldtech/shim-logs/pull/5

**Comment by muhamadazmy** [comment]
the new shim-logs was release to devnet. can you please try again with "logs" and let us know if this solves it for you
