### ISSUE TITLE
kernel panic: attempt to kill init

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/zos#1247]
using qemu for dev environment and cloud hypervisor raised kernel panic, probably won't be a problem for physical nodes, but for development environment probably adding these flags would help https://github.com/cloud-hypervisor/cloud-hypervisor/issues/456#issuecomment-659091773 let's update the development document with the required info

**Comment by LeeSmet** [comment]
Closed by befac03f43d02e6c492c08b7e80310127eeb91dd
