### ISSUE TITLE
OPS: kubernetes VM suddenly becomes unreachable through the public ip

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/zos#1249]
workload: https://explorer.testnet.grid.tf/api/v1/reservations/workloads/33170
public IP: https://explorer.testnet.grid.tf/api/v1/reservations/workloads/33169

**Comment by muhamadazmy** [comment]
I check the machine logs and we have this error
```
cloud-hypervisor: 430168.751545616s: <_net2_qp0> ERROR:net_util/src/queue_pair.rs:70 -- net: tx: failed writing to tap: Resource temporarily unavailable (os error 11)
cloud-hypervisor: 430168.751928225s: <_net2_qp0> ERROR:virtio-devices/src/net.rs:181 -- Error processing TX queue: NetQueuePair(WriteTap(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }))
```
in cloud-hypervisor logs, so this sounds like a CH bug. I will report it it CH team

**Comment by muhamadazmy** [comment]
Discussion started here https://github.com/cloud-hypervisor/cloud-hypervisor/discussions/2517

**Comment by muhamadazmy** [comment]
I installed a patch from CH team. I already rebooted the affected VM. please check if it works now, and if you get the same issue with other vms.

**Comment by AhmedHanafy725** [comment]
worked and could access through the public IP 
![image](https://user-images.githubusercontent.com/41957921/115898345-be817100-a45d-11eb-92ea-e647229082d7.png)

**Comment by AhmedHanafy725** [comment]
Now getting this on testnet, the vm is reachable through the private network, but can't reach it through the public one
public ip: 185.69.166.140
VM workload: https://explorer.testnet.grid.tf/api/v1/reservations/workloads/36068
public ip wid: https://explorer.testnet.grid.tf/api/v1/reservations/workloads/36067

**Comment by muhamadazmy** [comment]
CH has been updated on both testnet and devnet
