### ISSUE TITLE
Check if we can run k3os flannel in host-gw mode

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/zos#1251]
Currently the flannel instance in k3os runs in the default `vxlan`. However the private network of the vms is already inside the private network of the user, which is essentially a wireguard based overlay network. Although the official requirements for `host-gw` mention that direct L2 connectivity is required, the overlay should be able to support this based on a quick look through the code. If we enable this (and it works), we would reduce the networking overhead (both in bytes and in cpu cycles), as we currently have essentially double encapsulation.

**Comment by xmonader** [comment]
k3s isn't a zos primitive anymore
