### ISSUE TITLE
Power Supply Switch Froze Nodes

### ISSUE THREAD

**Issue by ColinOnTheMove** [threefoldtech/zos#1280]
"Our main power supply switched from its A -> B feed and all of the zero O/S nodes froze. One of them had a message on the screen, noting that it had received a power signal that it didnt understand, but would 'try to continue' (screen shot attached). 
Other non-zero O/S  devices didn't have an issue with the power switch so we're happy that the power switch over was successful at hte hardware level at least. ![image](https://user-images.githubusercontent.com/56056976/118962848-66745680-b998-11eb-8a8b-632807d721cc.jpeg)

**Comment by muhamadazmy** [comment]
I have 2 questions:
- From the screenshot I seed the node doesn't have IP address
- How do you know the node is frozen?

Also:
- the node shows that it's offline on the explorer. was it ever marked as online ?
- I can see other node in the same farm (6 of them) that are marked as online.

**Comment by ColinOnTheMove** [comment]
Answers to your questions above:

Q. From the screenshot I seed the node doesn't have IP address
A. It did, up until the freeze - all the switches and the routers had 100% uptime during the power switch

Q. How do you know the node is frozen?
A. The node is unresponsive - not on the TF explorer and they keyboard num lock light doesn't trigger

Q. The node shows that it's offline on the explorer. was it ever marked as online?
A. Yes

Q. I can see other node in the same farm (6 of them) that are marked as online.
A. This is after restarting all nodes (all were unresponsive in a similar way)

**Comment by xmonader** [comment]
closing as too old
