### ISSUE TITLE
k8s VMs to support NFS and iscsi driver

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/zos#1283]
- iscsi https://github.com/threefoldtech/zos/issues/1233
- nfs https://github.com/threefoldtech/zeroCI/issues/61#issuecomment-654993915

**Comment by muhamadazmy** [comment]
@xmonader why this is needed?

**Comment by xmonader** [comment]
Typical user of kubernetes would expect being able to have nfs volumes or iscsi specially to use other rancher projects like longhorn

**Comment by sasha-astiadi** [comment]
we're removing it for 2.8, reason:
