### ISSUE TITLE
research: ZMACHINE primitive, run containers as VMs

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#1284]
To abstract and unify the concept of ZMACHINE we should research the possibility to run everything in ZOS environment as a VM. the benefit of this is:
- much more secure since it's way better isolation
- unify all the services that is provided to the user workload (network, disks, virtiofs), so it's cleaner and easier to implement

Already some projects does that like https://katacontainers.io/ we can investigate the usability of this. But i personally suggest we use cloud-hypervisor since we already use this for VMs. using our own custom build kernel+initramfs and an init script that setup the environment and then handover the init to the container entry-point. 

The container flist then will still only container exactly what a container image contains, and is served to the VM over virtiofs

**Comment by muhamadazmy** [comment]
@despiegk Do you think we should carry on with this one?

**Comment by xmonader** [comment]
I agree in general with the idea, but also I've a question how are we going to handle features like env and secret env as well? through kernel params? what would be the limit there?

**Comment by muhamadazmy** [comment]
So I managed to do the following:
- mount container rootfs from 0-fs 
- boot a cloud-hypervisor virtual machine with a custom built kernel+initramfs (they have everything needed to fully boot the container in a VM) although I think this can be improved a little bit to drop parts that not needed.
- pass environment variables to the container entrypoint 
- setup network interfaces (currently static IPs, but once this is approved we improve the setup to support dynamic config of IPs as we do on VMs)

## Performance
- after starting virtiofsd (to serve rootfs) the machine takes less than a second to boot fully
- I created a container with a 300M memory, that uses (https://hub.grid.tf/tf-official-apps/base:latest.flist.md) as a rootfs. This image only include (zinit, busybox and dropbear) 
- once booted, ssh to the container was possible, I logged in and we can see the following:

![image](https://user-images.githubusercontent.com/10920323/121504567-6806cc80-c9e2-11eb-8591-8869a473c6be.png)

*Total*: 263M (what the kernel reports out of the assigned 300M)
*Available*: 241M

The CH process on host has only **110M** RSS in memory, that's probably because the VM is not fully using it's memory. So I ran a tool (thanks @maxux) to allocate memory incrementally inside the container. and I can see that the CH process memory consumption grow up to **301M** on the host 

> Note before starting fine tuning the kernel there was only 105M available for apps inside the container from the assigned 300M

Next: I am going to run multiple container next to each other see how they behave

**Comment by delandtj** [comment]
hero

**Comment by muhamadazmy** [comment]
# Running multiple vms on a host:
The test is running on a zos node with 24 cores and `193477M` memory (around 188G)

## Setup
I used the following scripts to start multiple VMs on one zos node:
- `start.sh` to start a single container instance 
```sh
#!/bin/sh

root=$1
index=$2
init=$3

bridge="test"
tap="cont-${index}"

if ! ip l show $tap > /dev/null; then
    ip tuntap add dev "$tap" mode tap
    ip l set "$tap" master $bridge
    ip l set "$tap" up
fi

socket="/tmp/rootfs.${index}.socket"

./virtiofsd-rs --shared-dir ${root} --socket ${socket}  &

if [ -z "${init}" ]; then
    init='init=/sbin/zinit "init"'
fi

exec cloud-hypervisor \
    --kernel output/bzImage \
    --initramfs output/initramfs-linux.img \
    --cpus boot=2 \
    --memory size=300M,shared=on \
    --fs tag=/dev/root,socket=${socket}  \
    --net tap=$tap \
    --cmdline "console=ttyS0 rootfstype=virtiofs root=/dev/root rw ip=192.168.123.${index}/24 gw=192.168.123.1 ${init}" \
    --rng \
    --log-file ch-${index}.log
```

- `patch.sh` to start multiple containers
```sh
#!/bin/sh

for index in $(seq 2 254); do
    ./start.sh rootfs ${index} &
done
```

Running `patch.sh` will start 253 machines with 2 cores and 300M each. They will get IPs from 192.168.123.2 to 192.168.123.254

Each container has zinit+busybox+dropbear. The container will auto start ssh. After booting it was possible to ssh to each container.

## Statistics 
Before running the vms the node gives this on running `free`:
![image](https://user-images.githubusercontent.com/10920323/121650892-55e86500-ca9a-11eb-9d18-8b31b869b9fc.png)

Running path will start 244 VM each with it's own `virtionfsd` to serve the root. they all use the same host directory as rootfs.
Running `free` again shows this.
![image](https://user-images.githubusercontent.com/10920323/121652273-c3e15c00-ca9b-11eb-99bb-fc1bac9b0d2b.png)

Output from `top`
![image](https://user-images.githubusercontent.com/10920323/121652222-b88e3080-ca9b-11eb-9041-9914a8225957.png)

## With busy containers:
I restarted all the VMs but this time I included a process that keeps allocating memory in increments of 10M. Once it reached the max possible allocated memory the process is killed by oom, then zinit (inside the container) takes care of respawning it. So the machine is now busy allocating the memory to full capacity forever.

Output from free:
![image](https://user-images.githubusercontent.com/10920323/121664646-fa24d880-caa7-11eb-8c51-d86ac215b75f.png)

Output from top:
![image](https://user-images.githubusercontent.com/10920323/121664718-0dd03f00-caa8-11eb-9c8e-28d3c00670a3.png)

- Each VM now on the host allocated ~302M on the host (full assigned memory capacity to the container plus some overhead for the CH process)
- Fully *theoretical* max memory used by the containers = 300*253 = 75900M ~= 75G
- Computed used memory after spawning all VMs = 191031 - 109335 = 81696 ~= 79G this also include CH overhead **plus** 254 `virtiofsd` processes for the rootfs.
