### ISSUE TITLE
zos3: how are IP reservations going to work?

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/zos#1289]
based on https://github.com/threefoldtech/home/issues/1061 how are the ips going to be reserved? how would the know what is available and what is not? how would we validate? how would we make sure we avoid race conditions provisioning the same IP?

Azmy's suggestion was that we don't specify specific IP, but ask for any IP

**Comment by muhamadazmy** [comment]
As discussed with you before I suggest the following:
- Farmer still need to run the farmer twin bot. The twin knows about the available public IPs in a pool
- The user should not care what IP he gets, instead he send his ip workload request to the node.
- The node take care to ask the farmer bot. this will allow the farmer bot to confirm the identity of the node making sure it's one of his (different nodes groups can be assigned different IP pools based on the network setup)
- The farmer twin locks an IP and send it back to the node. the node processes the IP and update the reservation.
- The user now can read the deployment config, and see the IP he got assigned.
- On deprovision, the node will make sure the twin releases the IP from the locked pool

**Comment by muhamadazmy** [comment]
@despiegk agree ?

**Comment by muhamadazmy** [comment]
https://github.com/threefoldtech/zos/blob/master-3/specs/grid3/grid3.md#public-ips
