### ISSUE TITLE
zos3: NetworkInterface model 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/zos#1290]
according to https://github.com/threefoldtech/home/issues/1061 and the https://github.com/threefoldtech/vgrid/tree/development_zos3prims 

![image](https://user-images.githubusercontent.com/64129/120662356-59bc2c00-c489-11eb-9ff6-2c714669158b.png)

are there any technical issues to migrate the current model to this?

**Comment by muhamadazmy** [comment]
Didn't we discuss this and agreed this won't work this way?!

**Comment by muhamadazmy** [comment]
PR to suggested model changes: https://github.com/threefoldtech/vgrid/pull/3

Note: zos already (right now on a development branch) implements the proposed structure (without the support for multiple private networks)
