### ISSUE TITLE
zos3: remove kubernetes primitive

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/zos#1291]
zos should be working with the lowest primitives as possible and kubernetes doesn't seem to be one (it's almost like the VM primitive)

if we go with that path, what would it take to provision kubernetes on the threefold grid? does it work for normal VMs? do we need to support restarting and passing kernel params from the outside? in case of k3os I believe we do a restart after the installation and change  of kernel params

**Comment by muhamadazmy** [comment]
The problem with K8s is that there is an installation step that need to be done first before the machine is ready. the machine after the installation is booted with different set of kernel params. 

Giving the user the power to do this himself will make installing a k8s is gonna be more complex from both sides to implement. We will see if there is a possibility to run k8s with no installation step

**Comment by ashraffouda** [comment]
pr for k3s image
https://github.com/threefoldtech/tf-images/pull/46
