### ISSUE TITLE
Node ID: Not unique per node

### ISSUE THREAD

**Issue by andhartl** [threefoldtech/zos#1294]
If a farmer starts the same node that has been on the grid once before the node gets a different node id. this happens every time a farmer does this. this leaves a lot of ghost nodes (old node ids) in the system and causes problems with reservations. 

it would be ideal to link the node id to a non changeable attribute of the node so the node comes up with the same node id

**Comment by muhamadazmy** [comment]
This is only possible if the node doesn't have disks hence it can't persist it's ID. This can happen if the node also can not use the disks (disks were not cleaned properly before the node is started the first time)

I assume if you check the node information on the grid u will see no Storage capacity. In that case the node is running in a limited storage mode and there is not much it can do.

**Comment by sasha-astiadi** [comment]
what can we do for this? anny suggestion? @muhamadazmy @andhartl @weynandkuijpers @delandtj

**Comment by weynandkuijpers** [comment]
Should we allow for nodes to exist on the grid that have no disks (eg. that end up running in limited disk mode?).  The "limited disk" mode was invested at some point in time to support a use case, is that use case still a valid use case.  For capacity farming the CPR is calculated as CPR = 1.5*CU + SU.  And every CU comes with 50GB of free disk space (https://wiki.threefold.io/#/threefold__cloudunits) therefore SU cannot be 0.

So a rule to accept the system to be part of the grid as a 3node can be that:
 - CU's and SU's are calculated from CRU, MRU, HRU and  SRU
 - a 3node cannot have 0 CRU and 0 MRU
 - a 3node cannot have 0 HRU and 0 SRU
 
Proposed minimum values:
- 2 CRU and 2 MRU (= 0.5 CU)
- 0.1 SRU (50GB for the root volume + overhead to store the node ID) and 0.25 HRU

**Comment by zaibon** [comment]
A bit of history here 👋. 
The reason the "limited storage" mode was introduced was only so the node can finish its network bootstrap and be able to report that its storage is not working properly.

On this mode, the node is not able to process reservation and the farmer is expected to fix the problem, not let the node run as is.
