### ISSUE TITLE
ZOS integration with rmb (reliable message bus)

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#1298]
# Background story / requirements 

https://github.com/threefoldtech/home/issues/1061

# tickets

- [x] Adapter for ZOS provision engine to interface with RMB #1287
- [x] Create Flist https://github.com/threefoldtech/zos/issues/1295

**Comment by DylanVerstraete** [comment]
Blocked on:

- https://github.com/threefoldtech/rmb/issues/12
- https://github.com/threefoldtech/rmb/issues/13
