### ISSUE TITLE
storaged: HDD should use ext4 instead of btrfs, a single HDD can only be used with on ZDB instance and nothing else

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#1306]

**Comment by LeeSmet** [comment]
What is the underlying reason for this? And if we would go ext3, why not ext4?

**Comment by muhamadazmy** [comment]
> What is the underlying reason for this? And if we would go ext3, why not ext4?

The main reason to move away btrfs for HDD is that we already not using fancy btrfs features like snapshots or subvolumes. Why it should be ext3 or ext4 i have no argument for except we need the lightest possible version of a stable filesystem. I already changed this to ext4

**Comment by muhamadazmy** [comment]
Already @delandtj have concerns regarding moving to ext4 we probably should leave this in backlog for now until it's decided

**Comment by muhamadazmy** [comment]
we still use btrfs for zdb but assign a single zdb to one disk
