### ISSUE TITLE
storaged: hdd should only be used by a single ZDB instance

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#1311]
the end goal of this issue is the following:
- [ ] Only support creating subvolumes and VMs disk on SSD so storaged should not even accept DiskType as an argument
- [ ] Allocation of HDD for zdb need another special call (add a new method) this method should do the following:
  - [ ] Find the first un-allocated HDD, format it (create a filesystem, we now use btrfs until we find out which is better for zdb)
  - [ ] After formatting , the disk is mounted normally. The path is returned to the caller
  - [ ] A zdb container will be started on that returned path (that is already implemented but probably need revision) (what ID u gonna use for both the disk and zdb container? do we instead start zdbs on all HDD on boot, if so which modes? etc ...?)
  - [ ] after a machine reboot, starting a ZDB should reuse the same disk, otherwise we lose user data.
- [ ] Clean up storaged interface 
- [ ] Clean up storaged boot process

**Comment by DylanVerstraete** [comment]
Current storaged boot process:

- migrate v1 filesystems
- check for existing volumes
   - mount existing ones
- list devices (hdd, sdd)
  - seperate free/used devices 
- create new filesystems on free devices
   - mount new filesystems
- create or restore cache
- shut down disks that have no volumes + periodic check

Current interface:

- UpdateFilesystem(name, size)
- CreateFilesystem(name, size, disktype)
- ReleaseFilesystem(name)
- ListFilesystems()
- Path(name)
- GetCacheFS()
