### ISSUE TITLE
Zero-OS booting "edac amd64 dram ecc disabled" error

### ISSUE THREAD

**Issue by rfcd17** [threefoldtech/zos#1321]
Hi, i am having the error "edac amd64 dram ecc disabled" when trying to boot zero-os from my home desktop. is there any way to bypass this error or am i required to install ecc dram sticks to proceed ?

**Comment by qlxucn** [comment]
I encountered the same issue and can not boot the system. @rfcd17 Are you able to boot it?

**Comment by ricardodias17** [comment]
> I encountered the same issue and can not boot the system. @rfcd17 Are you able to boot it?

@qlxucn I had to purchase some ecc rams. Can’t remember if also changed something in BIOS

**Comment by muhamadazmy** [comment]
I can't recognize the error, and it's not clear exactly where does this appear. If you still and issue please reopen with more context
