### ISSUE TITLE
Is zeroing out disks actually necessary?

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#1326]
The node setup documentation recommends running ` dd if=/dev/zero of=$i bs=1M` in order to prep disks for use with Zos. This can take a very long time. Is it actually necessary?

**Comment by LeeSmet** [comment]
No, zos only cares that the disk is "not actively used". Meaning, there should be no partition table, no filesystem directly on the disk and no label (in might have missed something).

In practice, deleting the first few sectors / MiB should be sufficient.

**Comment by scottyeager** [comment]
Thanks @LeeSmet. The document I'm referring to is here: https://wiki.threefold.io/#/threefold__3node_prepare

And the full command given is:
```
for i in /dev/sd*; do parted -s $i mklabel msdos; dd if=/dev/zero of=$i bs=1M ; done
````

Could this be safely updated to:
```
for i in /dev/sd*; do parted -s $i mklabel msdos; dd if=/dev/zero of=$i bs=1M count=4; done
```
Or even:
```
for i in /dev/sd*; do dd if=/dev/zero of=$i bs=1M count=4; done
```

**Comment by muhamadazmy** [comment]
your simplification (doing only 4x1MB blocks is correct and should work). 

I personally prefer to use the `wipefs` command instead. 
so this should be sufficient:
```bash
for i in /dev/sd*; do wipefs -a $i; done
```
