### ISSUE TITLE
Zos boots and obtains network, no resources detected

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#1340]
A farmer reports that their system has booted Zos but is not showing resources available to the Grid. Is connected to network but shows nothing for CPU/Memory usage:

![image](https://user-images.githubusercontent.com/17682591/126492649-a1dfe1bb-0cbc-4b0b-8b6f-decf6bc49ca1.png)

Hardware:
Gigabyte Model No.- R181-Z93

![image](https://user-images.githubusercontent.com/17682591/126495359-64e3e1dd-072f-4045-a299-e47e1d634b68.png)

**Comment by scottyeager** [comment]
Currently node is online (was "up", now "likely down") with id (FioTmYozsuGxo1pk1PsMw6REL7Q2qPUfZ4UdkePKs3aQ), but explorer shows no resources:

![image](https://user-images.githubusercontent.com/17682591/126497544-a4130a4f-da1a-4342-af69-8151928e11da.png)

**Comment by muhamadazmy** [comment]
Have the disks been cleaned out before booting? Zos will not use any disk that already have a filesystem it partition table

**Comment by muhamadazmy** [comment]
I checked the node information on the explorer [here](https://explorer.grid.tf/api/v1/nodes/FioTmYozsuGxo1pk1PsMw6REL7Q2qPUfZ4UdkePKs3aQ?proofs=true) and it shows that the proofs (basically hardware information of the node) are not there 

![image](https://user-images.githubusercontent.com/10920323/126748077-ade6fa36-f547-4aa4-a331-7d1b80361350.png)

So i assume the hardware detection of this node failed somehow. it's pretty hard to know exactly what went wrong. We will try to provide debugging tools to help us debugging.

**Comment by xmonader** [comment]
closing as too old
