### ISSUE TITLE
Workload failed to deploy due to error network is not installed on this node

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#1350]
While attempting to deploy an Ubuntu, I get an error that the network is not installed on the node:

```
Workload 98022 failed to deploy due to error network net is not installed on this node. For more details: 
```
https://explorer.grid.tf/api/v1/reservations/workloads/98022

However, network is and always has been installed on the node:

https://explorer.grid.tf/api/v1/reservations/workloads/84363

Attempting to deploy a generic VM to the same network produces this error:

```
Workload 98020 failed to deploy due to error could not set up tap device: couldn't load network with id (C4meyGgAUtUec): open /var/run/cache/networkd/networks/C4meyGgAUtUec: no such file or directory. For more details: 
```
https://explorer.grid.tf/api/v1/reservations/workloads/98020

**Comment by muhamadazmy** [comment]
I have no access to the node, but i checked the node logs from grafana and I came to the same conclusion that the network setup on the node is gone for some reason! It will be hard to figure out why the network is deleted

**Comment by scottyeager** [comment]
Oh ya, forgot to mention that this is *my* node :slightly_smiling_face:

Anything to do other than try rebooting it?
