### ISSUE TITLE
Failed to spawn vm machine process

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#1351]
Attempting to deploy generic VM solutions fails with:

```
Workload 98021 failed to deploy due to error no logs available: failed to spawn vm machine process '98021-1'. For more details:
```
https://explorer.grid.tf/api/v1/reservations/workloads/98021

**Comment by scottyeager** [comment]
This is same node as #1350, so may ultimately be due to the failed network.

**Comment by xmonader** [comment]
I'll close as too old, and there're many successful deployments of VMs already
