### ISSUE TITLE
Grid 3: Fetch correct country / city ID based on the location of the node

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/zos#1357]
Query graphql instance for countries and cities to extract the ID's

```
{
  countries(where:{ code_contains:"EG"}) { name, id, code }
}
```

should be done over rest to: https://explorer.devnet.grid.tf/graphql/

**Comment by muhamadazmy** [comment]
ZOS should not use the graphql api. ZOS should only deal with substrate (the grid db) but not other services. otherwise we will end up with spaghetti design
