### ISSUE TITLE
Add all event types for substrate runtime modules

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/zos#1359]
Currently decoding events from a block can fail if it contains events which are not typed yet. For our custom `tfgridModule` and `smartContractModule` modules we need every event typed. 

- smartContractModule: https://github.com/threefoldtech/tfchain_pallets/blob/98648a40d9135a5475adc9621abb9c80497bfac1/pallet-smart-contract/src/lib.rs#L40
- tfgridModule: https://github.com/threefoldtech/tfchain_pallets/blob/98648a40d9135a5475adc9621abb9c80497bfac1/pallet-tfgrid/src/lib.rs#L128

Example of typing in Golang: https://github.com/threefoldtech/zos/blob/49e6b236940bcab1246c35fbc516bc745bdacd53/pkg/substrate/utils.go#L58-L63

**Comment by xmonader** [comment]
What is the status here?
