### ISSUE TITLE
ZOS3: network is shareable across deployments, but must be edited by the deployment that created it

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#1365]
Right now, the network workload load is the only workload that can be referenced from other deployments. so a deployment can create the network, but then another deployment can then create a vm that hooks to this network. This so far a requirement that is giving us lots of headache. because of the following:
- On decommission of the network, we can't reverse look up if it's still used by other deployments 
- Any (new) deployment can change the config of the network. And on cancellation of the old contract (deployment) the network will get decomissioned.

For now as a fix, the network should be only editable (or re-created, or re-configured) by the contract that created it.

A better fix, is that a network resource should only be used from a single deployment, this will also fix the issue with broken dependency (if a network is deleted while used from another deployment)

**Comment by delandtj** [comment]
Huh... don't under stand the 'better fix'

**Comment by xmonader** [comment]
CC @OmarElawady @AhmedHanafy725
