### ISSUE TITLE
UpdateContract doesn't support changing the number of public ips

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/zos#1366]
Adding a vm with another public ip to a deployment requires incrementing the number of public ips in the contract which is not currently supported
`func (s *Substrate) UpdateContract(identity *Identity, contract uint64, body []byte, hash string) `

**Comment by muhamadazmy** [comment]
Yes, that was intentional. It's problematic to do this, and we left it for later.

**Comment by muhamadazmy** [comment]
by design.
