### ISSUE TITLE
Kubernetes cluster nodes not ready after update

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/zos#1371]
Reproducing steps:
1. Make a deployment with one master on node 2 and one worker on node 4 (all good)
2. Change anything in the master (e.g. increase its cpus by 1), and change the worker node from 4 to 2 and add a new worker on node 4.
3. The master and the old worker is NotReady, the new worker is ready. (from `kubectl get nodes` on the master)

The workers have the correct `K3S_URL` env variable pointing to the master, and all of them can reach each other (pingable).

Old deployments: [link](https://gist.github.com/OmarElawady/055981d9e69cff326a7bb2331c38e892)
New deployments: [link](https://gist.github.com/OmarElawady/bca098d582e669299132e61ec1a1bf66)

**Comment by muhamadazmy** [comment]
After changing the deployment, did the deployment reflect in reality correctly. for example:
- do u have all vms running 
- are all vms reachable over wireguard 
- can the vms reach each other as expected
- are all vms env correct ?

If not what went wrong? does the wrong "configuration" is correct in the deployment or not ?

**Comment by OmarElawady** [comment]
All yeses. What went wrong is that the master and the worker became `NotReady` (the only ones that got affected by the update). I inspected the config by eye and checked the `K3S_URL` env and reachability after the update and all seemed to be correct.
