### ISSUE TITLE
QSFS as primitive in zos

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/zos#1375]
# QSFS primitive spec

Qsfs needs to be added as a primitive in 0-os. The goal is to enable everyone to create a filesystem, which is then mounted in a VM (plain VM or kubernetes), using virtio-fs.

## Qsfs components

Qsfs is build up from 3 local components:

- [0-db-fs]: The fuse filesystem which is the actual interface a user interacts with (in this case though the use of virtio-fs)
- [0-db]: Used by [0-db-fs] to store all the data. Also used as a local cache
- [zstor]: The storage daemon, which takes data files from [0-db], compresses, encrypts, and chunks them for uploading. Invoked through hook scripts in [0-db]

Next to these, there are also remote [0-db]'s running, which are used for the storage of the encoded data. Data stored is redundant according to a chosen profile.

## Requirements

In order to run qsfs, the following is needed:

- Some local storage, preferably on SSD storage. This is needed for the 0-db data files. It also acts as a local cache for recently used data.
- An IPv6 enabled interface. Since [0-db] uses IPv6 on the grid, it makes sense to also require IPv6 connectivity to start Qsfs. The only network connectivity needed is to upload/download data chunks. Optionally, there is a prometheus endpoint serving stats from [zstor], but we should probably not expose this. This means that the solution should not be externally reachable.
- The ability to start FUSE, as [0-db-fs] is a FUSE filesystem.

## Implementation

Since we are deploying a container, the same steps are followed as with a regular container deployment. There are, however, a few differences to accommodate for the requirements outlined above.

First, aside from the rootfs, another empty directory will be created somewhere by `storaged`. This directory is also mounted in the container. This will be the mountpoint where [0-db-fs] is started. This way the actual filesystem we expose to the user is isolated.

Second, the config file for [zstor] needs to be written. The idea is to write it in the root of the rootfs. Some parameters can be hardcoded (or otherwise implementation dependant), while others will need to be user specified as part of the reservation. See [reservation details](#Reservation-details) below.

Third, there a couple of options for the network interface. We (currently) don't need/want the IP to be reachable from the outside. We also don't include it in a private network. This leaves 2 options:

- Connect a macvlan directly to `br-pub`. The IP will be accessible from the outside, so firewall rules need to be put in place. This means we need some extra code to manage the firewall, but we can easily open ports in the future, if we decide to make the metrics user accessible. We also need to verify here that no data actually goes on the interface from the outside, as that would complicate billing, see (the resource requirements section)[#Resource-requirements)
- Connect a macvlan to `br-ndmz`. We can then set a private IP on the NIC. This means the workload will never be accessible from the outside. There is no extra work w.r.t. firewalling, but if we need to make the metrics accessible later there will need to be additional work as we essentially need to switch to the other approach.

Next, in order to be able to mount the fuse filesystem, the container must be run in privileged mode.

Finally, the mount namespace of the host must be used, so the host can actually see the filesystem.

With the above, the processes can be started. Ideally, [zstor] is started first. This allows us to recover the files in the `zdbfs-meta` namespace. This is important, since metadata files are all that is needed to fully recover a [0-db-fs]. With those present, a qsfs instance could technically be moved between nodes (as long as shutdowns are clean). There is currently no component which implements this recovery, although it is not hard to do. If [zstor] is running, something like a bash script could be used to fetch all files in the `zdbfs-meta` namespace (both index and data files) (file names are currently a [0-db] implementation detail). Then we start [0-db] and finally [0-db-fs]. With the above, the system is fully running and the FUSE filesystem is available on the host, where it can then be mounted in VM reservations through virtiofs.

Ideally, we will make use of `zinit` config files to automate this, and to make sure a crashed process gets restarted.

## Reservation details

Aside from the regular generic info, the reservation will need to have
the following workload specific information:

- Size of the root fs. This doubles as the cache size for [0-db]. Note that space used by data files can temporarily exceed the configured limit, until excess files are deleted. Also, zdbfs-metadata files are never deleted, and neither are index files. As a result, we need to account for overhead here (maybe only use half as actual cache size?).
- A prefix. This is used by [zstor] to generate the hashes for files, and is stripped from the path. This means the mountpoint itself is also important for the hashes, though this should be static inside the container, and properly documented. It is then up to the user to create a path locally so he can access the files locally, should this be desired (or to prepare a filesystem, which is also possible if we recover the metadata files).
- A redundancy config. These are 4 values, described on the [zstor] readme.
- The [0-db] namespaces to use for data storage. These should be provided in a 2 dimensional array, as there is the concept of groups. Again see the [zstor] readme for an explanation of this concept if interested, though we should be able to write this as provided in the config file.
- Exactly 4 [0-db] namespaces to use for metadata. These must be running in User-key mode. They also require an encryption algorithm and key (currently only AES with a 32 byte key is supported).
- An encryption key for the data (currently only AES with a 32 byte key is supported)
- An encryption algorithm (currently only snappy is supported)

## Resource requirements

- Cru: [0-db] is single threaded, and so is [0-db-fs]. [zstor] uses a single thread for its compute heavy workload (i.e. compression and encryption), and another thread for everything else. If the encryption is later found to be a bottleneck, this can be configured to run on multiple threads (user defined) in parallel. For now this is not the case however, and 4 logical CPU's cover the needs.
- Mru: currently accurate figures are not present, and some testing needs to be done here. [0-db-fs] is unknown, [zstor] mainly consumes memory when processing files. Currently file processing is sequential, and the data used at peak for this is `$file_size * (data_shards + parity_shards) / (data_shards)`. File size here is the size of the [0-db] data files. As an example, if [0-db] uses data files of 100MiB, and the config is 5 data_shards, 20 parity_shards, then data encoding will use 500MiB at its peak. There is also some runtime data being kept, but this should be negligible compared to the file processing memory usage. The big unknown here is [0-db-fs].
- Sru: The size of the root fs, as it will be mounted on an SSD.
- Hru: None
- Nru: Considering we run a container with a dedicated interface, and the only traffic will come from [zstor], we have a perfect read on the consumed network, and can bill accordingly.

## Caveats and known issues

- There is currently [a memory issue](https://github.com/threefoldtech/0-db-fs/issues/26) in the latest version of [0-db-fs].
- ~[zstor] has a feature to automatically reserve new capacity on the grid. Considering we will know run it as a primitive, and this feature requires a wallet setup, we should not use this. The feature and its associated config is currently required. Fake values can be used if needed, and there is [an issue open to fix this](https://github.com/threefoldtech/0-stor_v2/issues/69)~.

[0-db-fs]: https://github.com/threefoldtech/0-db-fs
[0-db]: https://github.com/threefoldtech/0-db
[zstor]: https://github.com/threefoldtech/0-stor_v2

**Comment by muhamadazmy** [comment]
# Implementation tasks:
- [x] Add the new workload type in the zos types. Plus data structure for this new type. 
  - [x] The workload data should include
    - All config required for the fs operation (zstor_v2 config) 
- [x] Build flist for the zdb-fs container, this include
   - [x] 0-db binary 
   - [x] zstor binary
   - [x] 0-db-fs binary
   - [x] zinit binary
   - [x] config files for zinit to auto start required services properly
- [x] provision handler for the new type, this will do input verification then do required calls to the zdbfs-daemon
- [x] build the zdbfs-daemon this one does:
  - [x] For each instance of the qsfs a call to the network daemon is needed to create proper network namespace.  [deatils TODO]
  - [x] Start the container with the 0-db-fs and make sure to pass the write config (via file or env vars)
  - [x] the container need to use the already configured namespace.
  - [x] once mount is complete, workload is considered successful, the ID of the workload is the id of the filesystem
  - [x] later a VM can use this mount by consult the manaager for the full path.
- [x] Support mounting a QSFS in a vm/container
