### ISSUE TITLE
zos3: gateway dynamically expose workloads running on the grid 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/zos#1380]
we used to have https://github.com/threefoldtech/tcprouter client that worked like ngrok sort of, because you weren't able to know the IP the backend service that you will forward the traffic to, so you needed some process to initiate the communication channel and the gateway would forward the traffic to it based on the SNI

the current suggest implementation is:
- the user creates a name contract against substrate with a prefix to reserve pointing to the gateway IP
- the user deploys/ starts the container (at this point the entrypoint needs to wait for gateway reservation workload to happen) -the next two steps-
- the user get the IP (public or ygg)
- the user updates the deployment with a gateway reservation workload 
- the entrypoint of the container continues 

on the grid 2 version, it was 
- the user reserves a subdomain pointing to the gateway ip
- the user start the container with trc process that communicates with the gateway telling it which domain it's  claiming to handle

(this grid2 version couldn't work across multiple gateways because the IPs/sessions where added in the runtime)

**Comment by muhamadazmy** [comment]
as per our call
- The grid is a generic platform for generic workloads (like gateways) so you basically can proxy traffic to an ygg ip that lives on your laptop
- ZOS can't and will not accept connections from users, other than the exposed messages on msgbug to create/delete deployments and other information query methods. so modifying a workload or reconfigure it outside of the normal flow is not gonna happen.
