### ISSUE TITLE
Zos3: document how to be a gateway farmer

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/zos#1383]
This should cover all the pieces needed 

This should cover, the following:
- Setting up dns to point the right domain (and other names) to the zos node yet to be a gateway
- Make the right rmb call to setup node public config (this must include public ipv4, optionally ipv6 and domain name)
- Validation of node configuration on substrate (optional step)

**Comment by xmonader** [comment]
docs to be added in https://github.com/threefoldfoundation/info_threefold_pub/blob/main/wiki/manual_tfgrid3/farming/gateway_farmer.md

**Comment by muhamadazmy** [comment]
This section is not enough ? https://github.com/threefoldfoundation/info_threefold_pub/blob/main/wiki/manual_tfgrid3/farming/booting_node.md#setting-up-public-configuration-pub
