### ISSUE TITLE
zos3 FR: support wildcard name workloads in gateways

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/zos#1413]
Currently if the gateway has a domain `gatewaydomain.com`, a user can create a name workload reserving `name.gatewaydomain.com`. In caprover, a wildcard domain must point to the caprover ip, so something like `*.name.gatewaydomain.com`.

**Comment by xmonader** [comment]
How hard is to implement? it's needed for caprover to work over the gateways

**Comment by xmonader** [comment]
For now ppl will configure their domains over name.com or so instead of the gateway

**Comment by despiegk** [comment]
its not really needed I think
