### ISSUE TITLE
zos3: zdbs are not working on nodes 4 and 5 and 6

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/zos#1418]
```
node 4:
ip: 10.9.0.101 
contractID:243
problem: the deployment is created but stuck in created state
```
```
node 5:
ip: 10.9.0.102
contractID:246
problem: the ygg ip returned is not reachable
```
```
node 6:
ip: 10.6.0.14
contractID:247
problem: the ygg ip returned is not reachable
```

**Comment by muhamadazmy** [comment]
@OmarElawady can you send me the Ygg Ip of deplolyment of node 5 and 6 ?

**Comment by muhamadazmy** [comment]
I think it's the same no-carrier issue with the bridge!
@delandtj do you have a proposed fix for this issue ?

**Comment by RafyAmgadBenjamin** [comment]
I was deploying on Node 4 and I keep getting this error message
![image](https://user-images.githubusercontent.com/46320202/137155202-33ad1287-c3ca-4598-b03f-41643a06c9cd.png)

This is my contract id
```
CreateNodeContract returned id: 536
```

**Comment by muhamadazmy** [comment]
It's not clear which stage has timed out. The error says, 'error waiting deployment' but waiting for what exactly is not clear. 
Also i see that the deployment is already in 'deleted' state.

A good practice is to leave the deployment active so we can investigate the issue.

**Comment by OmarElawady** [comment]
It's the same problem in the issue (the deployment is created but stuck in created state). It's deleted because the terraform plugin removes the contract and the deployment if it failed. But it's reproducible on node 4, all zdbs on it fail.

**Comment by muhamadazmy** [comment]
Will close this for now, and if this happens again a new issue need to be created
