### ISSUE TITLE
zos3: gateways not working

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/zos#1420]
stuck at initialization because of traefik service checks. Probably will be fixed by https://github.com/threefoldtech/zos/pull/1406/files#diff-f7ead8c7d00304fae98565a655608e64559eeeebd0620d6e1edafcbbb5641d80R66

**Comment by muhamadazmy** [comment]
Is this still an issue after the merge?

**Comment by OmarElawady** [comment]
not anymore, deployed a working name workload
