### ISSUE TITLE
VM is suddenly not reachable and can't reach the website was running on it 

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/zos#1426]
I have deployed a VM using terraform plugin, it was working well then suddenly, the website is no longer running and can't access the VM, I have checked my polka account and I have still money there 

![image](https://user-images.githubusercontent.com/46320202/136941646-c3bdde8b-4a5b-4a22-b697-386fa9f2da45.png)

contract details
```
{
  version: 1,
  state: Created,
  contract_id: 341,
  twin_id: 27,
  contract_type: {
    NodeContract: {
      node_id: 4,
      deployment_data: ,
      deployment_hash: 2e2f4f8b89baa494dc5374c7c4f78748,
      public_ips: 1,
      public_ips_list: [
        {
          ip: 185.206.122.40/24,
          gateway: 185.206.122.1,
          contract_id: 341
        }
      ]
    }
  }
}
```
![image](https://user-images.githubusercontent.com/46320202/136940720-d47770f3-2a1c-4927-a721-364aa9dc1a5c.png)

This is the billing information
![image](https://user-images.githubusercontent.com/46320202/136941853-ebeaf076-fd8c-4170-9278-9120842ffc25.png)

**Comment by muhamadazmy** [comment]
The current contract state is "deleted" so it's impossible to check what went wrong. if this happens again please leave the contract in created state and ping me directly so i can take a look. 

I see from the error it says 'No route to host' not 'destination host not reachable`. so this might actually be a wireguard issue not vm issue. a no route to host means basically your computer doesn't know how to reach this network you are trying to reach.

**Comment by muhamadazmy** [comment]
I will close the issue now, but please reopen once it's re-produced
