### ISSUE TITLE
Entry-point defined in the TerraForm conf file should take precedence.

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/zos#1429]
if you have an entry point defined in the docker file then convert it to flist and want to boot a VM with that flist. Then the entry point in TERRAFORM conf file won’t be used. It will always use the one from the docker file, and ignore the one in terraform conf file. To make the one from the tf file works you have to remove the entry point defined in the docker file entirely and rebuild the list.

I was expected that I can override the one defined in the image, by redefining it in the tf file, but this did not work. Is that intended or the expected behavior?

**Comment by muhamadazmy** [comment]
the entry point is handled like this 
- Load entrypoint definition from the flist (if defined)
- Check if Vm.config has a custom entrypoint defined
  - if vm workload config has entrypoint defined, use this one
  - if Not, use the one from the flist

This is defined here: https://github.com/threefoldtech/zos/blob/zos3/update-order/pkg/primitives/vm_utils.go#L280

So can you check the actual deployment (do a get call to the node) that containes the VM and check if the entrypoint value is set on the vm workload?

**Comment by muhamadazmy** [comment]
Can you also send me the link to the flist used to inspect as well

**Comment by OmarElawady** [comment]
Couldn't reproduce. Started the following zmachine with `/start.sh` as the entrypoint and found `/sstart`.

Dockerfile:
```
FROM ubuntu:20.04

RUN apt update
RUN apt install -y openssh-server dnsutils iproute2 vim
COPY init.sh /
COPY start.sh /
RUN chmod +x /init.sh
RUN chmod +x /start.sh
ENTRYPOINT ["/init.sh"]
```
init.sh:
```
#!/bin/bash

touch /sinit

mkdir -p ~/.ssh /var/run/sshd
echo $SSH_KEY >> ~/.ssh/authorized_keys
chmod 600 ~/.ssh/authorized_keys
chmod 600 /etc/ssh/*
/usr/sbin/sshd -D
```
start.sh:
```
#!/bin/bash

touch /sstrart

mkdir -p ~/.ssh /var/run/sshd
echo $SSH_KEY >> ~/.ssh/authorized_keys
chmod 600 ~/.ssh/authorized_keys
chmod 600 /etc/ssh/*
/usr/sbin/sshd -D
```
