### ISSUE TITLE
handle chain events for contact deletion and decomission the deployment

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#1437]
Currently the contracts status on chain are checked only during capacity reporting. so the node will basically report capacity to an active contract, and if the contract status was seen as "deleted" the node will then decomission the contract. 

This was fine when reporting was done every 5 minutes, so a node can keep a canceled contract active for only 5 min maximum before taking an action.

But now, since reports are one done every an hour, having a canceled contract deployed for an hour is not acceptable, hence the node needs to always listen to the chain events and process all contract canceled events for that node.

We need to grantee that no events are missed so:
- We still keep the mechanism that decomission contracts on capacity reporting this is a fail safe in case an event was missed
- The node need to listen to runtime events by scanning the chain, and keep tracking of the last event received (block hash or block id) 
- the last even block must be persisted on the node, on service restart, the node must then make sure to scan all blocks to the top to make sure no events were missed while the service was down.

**Comment by LeeSmet** [comment]
Substrate allows you to define custom events (which is what we already do), which are emitted when a certain extrinsic is called. Also, the main idea is that the runtime storage on substrate represents the active state of the chain. So for reservations, we would basically have a map, where the node ID is the key, and the list is a Vec of reservation ID's, which are active. If a reservation is decomissioned, a ContractDeleted (or similar) event is emitted, containing both the NodeID and ContractID (and optional other data such as who cancelled the contract, not important for the node). It then suffices for a node to subscribe to these events, and filter out the ones with it's own NodeID.

When a node boots, it can subscribe to these events, and then do a single get call for the "ActiveContracts" (or however it is called) map in the runtime storage, using it's own NodeID is as key. This will return a list of active contracts. The node then deletes the workloads which are not present in the list based on the ID (those have been deleted/expired). After this, the node starts processing the events as normal. This order is needed to prevent a potential race condition, where the node reads the storage key, filters its active contracts, then someone deletes a contract, before the node subscribes to events. The deleted contract would stay active.

This flow is applicable to all data. Essentially, the _CURRENT_ situation needs to be represented in the blockchain runtime storage, and changes to this need emit an event from the chain. This allows all services to sync the current state at boot, and get real time updates of changes to the state, without polling

**Comment by muhamadazmy** [comment]
We already have a map for the active contracts per node, and is already used like this. It's the subscribing to the events that is missing.

**Comment by LeeSmet** [comment]
Alrighty, my point is also that you don't need an (expensive) scan of chain history, or to keep track of the last seen block :)

**Comment by muhamadazmy** [comment]
It's code complete on branch  `node_events` but unfortunately, devent was blocked and couldn't finish testing.
