### ISSUE TITLE
cant write more than .25GB on the qsfs dir

### ISSUE THREAD

**Issue by mhost39** [threefoldtech/zos#1443]
using devnet and node 12
using terraform provider: i deployed a QSFS with zdb 10G and cache 1G
QSFS main.tf: https://gist.github.com/mhost39/145dba4041a5e2a6add2540e791ce35d

after deployed i tried to download 354M on /qsfs: 
```
wget https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img
```
and got this error 
```
get: write error: I/O error
ssl_client: write: Connection reset by peer
```
![image](https://user-images.githubusercontent.com/31102305/138701784-742e6ed4-02d3-48fc-8c51-3e0600b40de4.png)

**Comment by mhost39** [comment]
then i tried again with cache 10G and worked fine

**Comment by muhamadazmy** [comment]
This error message sounds like a network error not a filesystem error. What do u get if 
1) You tried to download the same file again ?
2) Write something that doesn't need network, for example
`dd if=/dev/urandom of=/path/to/qsfs/test.file bs=5M count=100`

**Comment by mhost39** [comment]
same error with ``` dd ``` command 

![image](https://user-images.githubusercontent.com/31102305/139839244-3bb8fe0b-4236-4a14-b460-34dab287a5ce.png)

**Comment by muhamadazmy** [comment]
Is this verified ? can it be closed?

**Comment by mhost39** [comment]
Verified
