### ISSUE TITLE
QSFS config related errors are not reported (fails with generic error message)

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/zos#1446]
If the user supplied a wrong zdb ip or namespace, or messed up almost anything. The QSFS container is started and fails when it validates the config. It doesn't mount the zdbfs and zos reports after a timeout that the mounting timed out. Validating the config thoroughly looks like a tedious task to do in ZOS. Should the container logs be provided in the error message in case of zdbfs mount failure?

**Comment by muhamadazmy** [comment]
We can attach a "tail" of the logs like last 100 lines of logs to the error message.

**Comment by ashraffouda** [comment]
https://github.com/threefoldtech/zos/pull/1473
