### ISSUE TITLE
found a malformed ip address in contract object '185.206.122.34'

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/zos#1447]
devnet: deployments that required public IP's gives that error message
```
error waiting deployment: workload 0 failed within deployment 127 with error found a mullformed ip address in contract object '185.206.122.33'
```

tried different times on different nodes 2, 3, 4 same results.

**Comment by coesensbert** [comment]
on it

**Comment by coesensbert** [comment]
My bad, ip's not in CIDR notation. Removed and re-added them.

Only 185.206.122.33 has a contract id to it, so can't remove. Can you cancel this contract? ->

```
  public_ips: [
    {
      ip: 185.206.122.33
      gateway: 185.206.122.1
      contract_id: 133
    }
    {
      ip: 185.206.122.33/24
      gateway: 185.206.122.1
      contract_id: 0
    }
```

**Comment by sameh-farouk** [comment]
thanks, @coesensbert.
the issue is resolved now. and the contract deleted you can try now to remove the old entry.

**Comment by coesensbert** [comment]
Old entry deleted
