### ISSUE TITLE
upgraded is not able to upgrade itself

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#145]
Since upgraded is running while an upgraded is happening (obviously) we get the `text file busy` error when trying to copy the new version of upgraded.

**Comment by maxux** [comment]
1. Move original (running) file to another name
2. Upload new file to original name
3. Restart process
4. Remove original file

**Comment by delandtj** [comment]
os.Rename

**Comment by zaibon** [comment]
ok that make sense. But then we have another issue. Since we just run the full root of the filesystem from tmpfs, we will run out of space when doing the copy.

**Comment by maxux** [comment]
Do it one by one and remove one by one

**Comment by zaibon** [comment]
already tried that, but still, I get out of space even for the first one.

**Comment by maxux** [comment]
Use another additional tmpfs ?
You don't even need to remove binaries then, just umount it when it's done and voilà

**Comment by zaibon** [comment]
> Use another additional tmpfs ? 

that won't work cause I cannot do a rename cross devices. Which means I would have to copy it to the new tmps, delete the current binary which would fail with the same 'test file busy' error.

**Comment by delandtj** [comment]
```go
package main

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"syscall"
)

func main() {
	dir, _ := filepath.Abs(filepath.Dir(os.Args[0]))
	fname := filepath.Base(os.Args[0])
	fmt.Println(dir, fname)
	full := filepath.Join(dir, fname)
	err := os.Rename(full, full+".old")
	if err != nil {
		fmt.Println(err.Error())
	}
	fmt.Println("I renamed myself to: %s", full+".old")
	source, err := os.Open("/usr/bin/ls")
	destination, err := os.Create(full)
	nBytes, err := io.Copy(destination, source)
	if err != nil {
		fmt.Println(err.Error())
	}
	// don't use defer here, as files need to be closed before 
	// syscall.Exec
	source.Close()
	destination.Close()
	fmt.Printf("Copied %d bytes into %s\n", nBytes, full)
	err = os.Remove(full + ".old")
	if err != nil {
		fmt.Println(err.Error())
	}
	err = os.Chmod(full, 0755)
	if err != nil {
		fmt.Println(err.Error())
	}
	err = syscall.Exec(full, []string{full, "-l"}, []string{""})
	if err != nil {
		fmt.Println(err.Error())
	}
}
```

**Comment by zaibon** [comment]
@delandtj :
> ok that make sense. But then we have another issue. Since we just run the full root of the filesystem from tmpfs, we will run out of space when doing the copy.
