### ISSUE TITLE
Whenever canceling its contract, the VM is still accessible and open to use

### ISSUE THREAD

**Issue by dmahmouali** [threefoldtech/zos#1451]
I deployed a VM on node 4, and after deleting the contract I still can access and use it for a couple of hours

this is the deployment get a response: https://rmbproxy1.devnet.grid.tf/twin/28/523e6063-f2b1-4ff8-a6bf-4db0fd05c308

**Comment by xmonader** [comment]
@muhamadazmy does this mean that provisiond was hangning?

**Comment by muhamadazmy** [comment]
Right now, the node only check the "validaty" of contracts on "capacity reporting" which happens every 1hour. so in worst case the VM can still be alive for 1 hour before cancelling the contract.

There is already an issue open for this so we also listen to grid events on cancellation. and decomission immediately.

**Comment by muhamadazmy** [comment]
related to #1437
