### ISSUE TITLE
failed to setup fqdn proxy

### ISSUE THREAD

**Issue by mhost39** [threefoldtech/zos#1454]
got this error when try to deploy gateway_fqdn example with terraform 
``` Error: error waiting deployment: workload 0 failed within deployment 77 with error failed to setup fqdn proxy: gateway is not supported on this node: no public configuration ```

with testnet and devnet

terraform logs: https://gist.github.com/mhost39/6bcbd94463e0c02d2823b54429a4893e
main.tf file: https://gist.github.com/mhost39/902047bc3d2b86c647ef8678ba9372c5

**Comment by muhamadazmy** [comment]
The error message is clear. This node does not have `public_config` hence it can't handle gateway workloads. The node that can deploy workload MUST have public config.
