### ISSUE TITLE
zos can't get node twin

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/zos#1464]
I followed the farming guide here in our wiki (testnet):
https://library.threefold.me/info/threefold#/manual_tfgrid3/farming/threefold__create_farm_testnet
and 
https://library.threefold.me/info/threefold#/manual_tfgrid3/farming/threefold__booting_node
I picked the ISO image which can use directly on a virtual Machine as mentioned on https://dev.bootstrap.grid.tf/generate
booted with VirtualBox I got this error.

I also followed the development guide here https://github.com/threefoldtech/zos/blob/main/qemu/README.md to boot zos in qemu, and ended with the same result
![photo_٢٠٢١-١١-٠٢_١٠-٣٤-٣٥](https://user-images.githubusercontent.com/42457449/140038900-185ab52d-61d6-4036-b2b2-d87f724631cf.jpg)

**Comment by muhamadazmy** [comment]
Can you switch to logs view (Alt+F2) (also try F1, F2, and F3) and report screenshots with any errors

**Comment by sameh-farouk** [comment]
![Screenshot from 2021-11-03 12-10-09](https://user-images.githubusercontent.com/42457449/140043516-b243fe8d-f991-4cb7-ba63-7f697423b98a.png)
![Screenshot from 2021-11-03 12-10-52](https://user-images.githubusercontent.com/42457449/140043576-a841dc3b-abac-42c3-84a9-6cd62bef3c0c.png)

**Comment by sameh-farouk** [comment]
also, in qemu, the issue was solved by ssh-ing and adding `zinit` service, nodded. thanks to @OmarElawady. he probably could add more relevant info to the issue.

**Comment by muhamadazmy** [comment]
The node will keep trying to register, but it's not clear why it can not register this can be duo to many issues (that should be visible in the logs)
- Account not funded for any reason (activation service)
- no disks attached (or detected) by the node

In the logs, provisiond already spitting out `failed cache reservations` which means the node does not have any disks detected.

**Comment by muhamadazmy** [comment]
> also, in qemu, the issue was solved by ssh-ing and adding `zinit` service, nodded. thanks to @OmarElawady. he probably could add more relevant info to the issue.

You started the node from `zos/qemu` with overlay enabled if the image was used, this won't be a problem

**Comment by sameh-farouk** [comment]
it works now.
setting the network to use NAT in Virtualbox, solve the `TCP i/o timeout` errors.
for `failed cache reservations` it was solved by setting the disk controller to AHCI. both IDE and SCSI controllers in VirtualBox didn't work well.
hope this would serve as a reference if anyone experimenting with zos in VirtualBox and has the same issue.
thanks, @OmarElawady, and @muhamadazmy for your time.
