### ISSUE TITLE
Configure a health check to remove unhealthy servers from the load-balancing rotation

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/zos#1468]
I deployed a gateway with 2 backends (2 VMS) and found that the gateway proxy forwards traffic to both backends (round-robin load balancing) even if the backend service went down.

Can we improve this from the `traefik` side? 
Better to **Configure a health check** to remove unhealthy servers from the load-balancing rotation in such a way that if the load balancer can’t communicate with the server it **failover** to the other server instead of returning a bad gateway.

currently, when one of the two backends goes offline half the requests fail.

### how to reproduce:
- I used an HCL file similar to this one, 

```
terraform {
  required_providers {
    grid = {
      source = "threefoldtech/grid"
    }
  }
}

provider "grid" {
}

resource "grid_fqdn_proxy" "p1" {
  node = 12
  name = "mytest"
  fqdn = "samehabouelsaad.grid.tf"
  backends = [format("http://%s", grid_deployment.d1.vms[0].computedip), format("http://%s", grid_deployment.d1.vms[1].computedip)]
  tls_passthrough = false
}

resource "grid_network" "net1" {
    nodes = [12]
    ip_range = "10.1.0.0/16"
    name = "network"
    description = "newer network"
}
resource "grid_deployment" "d1" {
  node = 12
  network_name = grid_network.net1.name
  ip_range = grid_network.net1.nodes_ip_range["12"]
  vms {
    name = "vm0"
    flist = "https://hub.grid.tf/tf-official-apps/base-ubuntu:latest.flist"
    entrypoint = "/sbin/zinit init"
    cpu = 1 
    memory = 1024
    publicip = true
    env_vars {
      key = "SSH_KEY"
      value = ""
    }
  }
vms {
    name = "vm1"
    flist = "https://hub.grid.tf/tf-official-apps/base-ubuntu:latest.flist"
    entrypoint = "/sbin/zinit init"
    cpu = 1 
    memory = 1024
    publicip = true
    env_vars {
      key = "SSH_KEY"
      value = ""
    }
  }
}

output "public_ip_0" {
    value = grid_deployment.d1.vms[0].computedip
}

output "public_ip_1" {
   value = grid_deployment.d1.vms[1].computedip
}
```

- then started a test server on both the VMS, you can use `netcat`

```
while true; do echo -e "HTTP/1.1 200 OK\r\nContent-Type: text/html\r\n\r\nI think the date is $(date), Have a good day!" | nc -l -p 80; done
```

- access the domain name from the browser couple of times to make sure both servers running well.
- interrupt `netcat` ctrl+c on one of the instances.
- repeatedly access the domain name from the browser, half the requests will return a bad gateway response.

**Comment by muhamadazmy** [comment]
To be honest, i don't believe it's up to zos to decide to remove this by itself. This configuration for the backend is part of a deployment that is stored in a contract created by the user, if one of the services is down, the client need to make sure to remove the config, and re-add it or change it if the backend was restored.

Imagine if zos decided to remove this backend, then the user managed to restore his failed backend. what should zos do? it will never know how/when to re-add this backend by itself and this make the system unnecessary complex.

**Comment by sameh-farouk** [comment]
> To be honest, i don't believe it's up to zos to decide to remove this by itself. This configuration for the backend is part of a deployment that is stored in a contract created by the user, if one of the services is down, the client need to make sure to remove the config, and re-add it or change it if the backend was restored.

@muhamadazmy i believe one of the main responsibility of loadbalancer is ensures high availability and reliability by sending requests only to servers that are online and most cloud-balancing services give the user someway to create or select a health check when configure a loadbalancer. one example is [google](https://cloud.google.com/load-balancing/docs/health-checks)

> Imagine if zos decided to remove this backend, then the user managed to restore his failed backend. what should zos do? it will never know how/when to re-add this backend by itself and this make the system unnecessary complex.

FYI, Traefik keeps monitoring the health of unhealthy servers. If a server has recovered (returning 2xx -> 3xx responses again), it will be added back to the load balancer rotation pool. check Traefik [docs](https://doc.traefik.io/traefik/routing/services/#health-check)
