### ISSUE TITLE
corex support

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/zos#1471]
corex is a custom `init` process that has a web ui where u can start jobs/procsses inside a container. The point is that we can inject this in any zmachine (vm) image, and then start it instead. once the machine is up the corex UI can be reached over the UI and a know port. then the user can then use the Ui to start processes or terminal.

What need to be done:
- Add corex flag to ZMachine workload
- If `corex is true` the provisioner need to do 2 things
  - copy the corex binary to the vm `<root>/bin/corex`
  - override entrypoint to `/bin/corex`

**Comment by LeeSmet** [comment]
I wonder if we want to keep the old flow. I feel like we might want to have corex connect to the console output instead (or a new tool to do this), running outside the VM. This allows us to provide a web based console (in the private network), similar to how standard cloud providers have it. We can then also add some basic commands such as restart/start/stop/... (useful if you manage to brick your VM).

**Comment by muhamadazmy** [comment]
What you suggest goes under a `new tool` for sure. corex was running as PID in containers, which allows web console and way to start processes (or debug) your image. This issue is about exactly that.

**Comment by ashraffouda** [comment]
https://github.com/threefoldtech/zos/pull/1562
