### ISSUE TITLE
Invalid certificate for returned domain of deployed gateway using typescript client

### ISSUE THREAD

**Issue by asamirr** [threefoldtech/zos#1477]
When I deploy a VM and then a gateway all using the typescript client, when I need to access the backend I specified for the gateway from the browser, the certificate is invalid.

**Comment by OmarElawady** [comment]
The NS record at the end of this [page](https://github.com/threefoldfoundation/info_threefold_pub/blob/main/wiki/manual_tfgrid3/farming/booting_node.md#setting-up-public-configuration-pub) was missing. Added it and it should be working now.
