### ISSUE TITLE
Data coming from the graphql is inconsistent 

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/zos#1487]
Examples:
`Belgium`  and "BE"

we suggest using the full name all the time and making it consistent 
![image](https://user-images.githubusercontent.com/46320202/141967999-9b70b93e-6ae4-452e-8e0b-555d5d9baf08.png)

**Comment by muhamadazmy** [comment]
Fixed with aeb99c03c9dbd629f5ec281d2f2129ea71f1e902

**Comment by muhamadazmy** [comment]
Actually do you prefer country name, or country code ?
