### ISSUE TITLE
Node testnet3.0 stop updating

### ISSUE THREAD

**Issue by luisanadal** [threefoldtech/zos#1489]
The sever shows a normal screen, no errors, all looks normal, but i found out that the node has not been uploading information for last 10 days (according to grahlql, which i think is right), other nodes in the same Datacenter woks normally but we other nodes that i suspect have the same issue.

Node 105,
Farm: 4, 
Testnet3.0
IP 10.2.2.13
Location: Toron
![Screenshot from 2021-11-26 17-33-11](https://user-images.githubusercontent.com/58570148/143614328-2710be04-75a6-418a-a1e1-f7c9fc95436b.png)
![Screenshot from 2021-11-26 17-32-47](https://user-images.githubusercontent.com/58570148/143614330-4e66e6a6-020d-4e30-80b4-9a23892f9127.png)
![Screenshot from 2021-11-26 17-32-34](https://user-images.githubusercontent.com/58570148/143614332-5c179eec-4767-4d8f-be57-b1ee0ef26047.png)
to

**Comment by muhamadazmy** [comment]
So this looked like a very weird error, at first. I was suspecting that something is wrong with the node storage. So i checked the info reported by the node on the chain and I got this

![image](https://user-images.githubusercontent.com/10920323/143835785-cb166de3-28fb-4560-ad90-281c7672fa7f.png)

The node is not reporting ANY storage units so this can be duo to:
- There are no disks attached to the node
- The node disks were not empty when it was first booted, so ZOS did not use them

Can you please confirm this, or rewipe the disks with `wipefs` and reboot the node. The node will unfortunately re appear with a totally new identity.
