### ISSUE TITLE
Zero-OS downloaded, but got stucked on starting up ....

### ISSUE THREAD

**Issue by mvrabec** [threefoldtech/zos#1498]
Hi guys,
anyone saw this issue ?
I was able to boot Zero-OS generated bootstrap. Downloading Zero-OS worked fine after booting. Now it's writing Zero-OS downloaded and ready, starting up ... 
But nothing is happening, just lower_slash is still blinking.
Any ideas ?
![263618372_4668870426527102_3309857432974965484_n](https://user-images.githubusercontent.com/71263506/144751843-7af3c2eb-d125-422d-bc8f-a48aefd1e677.jpg)
??

**Comment by muhamadazmy** [comment]
@maxux any idea what this can be ?

**Comment by maxux** [comment]
Can you give more information about the hardware ? Did you generated an EFI image or USB/ISO ?
For some reason the kernel freeze during unpacking. This can happen on low memory machine or not using EFI bootlloader.

**Comment by xmonader** [comment]
closing as too old
