### ISSUE TITLE
Check yggdrasil periodically

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/zos#1499]
Add a goroutine (in the YggServer?) to perform periodic checks on the peers in the config and performs a restart whenever all of them (or 1?) are dead.

Caused https://github.com/threefoldtech/tf_operations/issues/466

**Comment by muhamadazmy** [comment]
as far as I remember, networkd gets the list of peers, and test them before building yggdrasil config. May be idd we need to redo this more often

**Comment by muhamadazmy** [comment]
I think networkd, can be scheduled to re-test the peerlist of yggdrasil every few hours, and then compare it with what have been configured in yggdrasil, then restart if needed.

**Comment by muhamadazmy** [comment]
All nodes always use freefarm public nodes as peers
