### ISSUE TITLE
Failed to extend pools in testnet

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/zos#1500]
pool: https://explorer.testnet.grid.tf/api/v1/reservations/pools/37760
reservation: https://explorer.testnet.grid.tf/api/v1/reservations/pools/payment/44217

![image](https://user-images.githubusercontent.com/10658229/144843858-e14f7c94-0031-4b5d-93d2-1b5ecd3c5742.png)

**Comment by muhamadazmy** [comment]
Fixed temporary, we can't work on this atm
