### ISSUE TITLE
Used resource more than total in gridproxy

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/zos#1501]
As shown in image the `total ipv4u: 0` however `used ipv4u: 1`
![image](https://user-images.githubusercontent.com/31689104/144992378-b48f61a1-5ed7-4b87-87f8-ac1239871177.png)
This issue can be found in multiple nodes for example
https://gridproxy.dev.grid.tf/nodes/15
https://gridproxy.dev.grid.tf/nodes/14
https://gridproxy.dev.grid.tf/nodes/7

**Comment by muhamadazmy** [comment]
The node total IPV4 will  be always 0. the node can't tell how many ips are available in this farm. The node can also server unlimited number of IPs. Hence the total will be always 0. It can tell how many ips are used on this node.
