### ISSUE TITLE
persist all data on the VM fs in such a way it can survive a restart

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/zos#1511]
ATM it's hard to **persist all data on the VM fs in such a way it can survive a restart**. although a restart operation is disabled in zos, if the init process **crashed**, you lost your data.

also, it is hard to mount every directory to a disk, eg if you deployed VM with a disk mounted to rootfs, it won't be booted.

**Comment by muhamadazmy** [comment]
- You can't mount a disk to the rootfs `/` of a VM. that will never work. I will add a validation on the mount points to not allow `/`
- A VM restart on the other hand (on init crash) should not wipe up the data on rootfs, a node restart would (I will see if we can avoid that) 
- A delete of the vm should always wipe up the rootfs data.

In general a node booting should always automatically set up the VM to a working state. A vm flist should already have all the applications pre installed, and sanely configured. So changes to rootfs of the VM should be minimum (update some variables form ENV vars, write down some ssh keys, etc) and start up services.

**Comment by sameh-farouk** [comment]
Verified.
files preserved on VM restart. on Ubuntu VM

![Screenshot from 2021-12-21 20-09-37](https://user-images.githubusercontent.com/42457449/146978096-f52b2039-c709-4d12-adda-2eab89e5affb.png)

another approach on Apline VM
![Screenshot from 2021-12-21 20-21-05](https://user-images.githubusercontent.com/42457449/146980000-00dc6f98-d7fe-4578-9a8f-708d4803d4ab.png)

also, the validation on the mount points works as expected 
![Screenshot from 2021-12-21 20-31-28](https://user-images.githubusercontent.com/42457449/146980818-74b146b7-4816-49b1-9f66-5ee47a56e875.png)
