### ISSUE TITLE
zdbs are dead

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/zos#1517]
Deploying on node 7, 4, and 8 on devnet gives: `dial unix <zdb-socket> connect: connection refused`. Checking zdb on node 7, it looks like there's nothing running inside the container.

So probably zdb crashed. And it wasn't restarted by contd. This shouldn't happen with the normal flow since the containers are restarted if the root task exited up to 4 times, if the interval between successive failures is less than a minute. Which isn't the case as one of the last lines of the zdb container is `[  615557.870231][+] client: closing (fd: 31)`. The last part of the log of the zdb is truncated so the reason for zdb exiting is not clear.

When deploying a new zdb, the zdb containers are checked and found so they are not started again. But there are no tasks inside these zdb containers so namespace creation fails.

**Comment by muhamadazmy** [comment]
I think a good fix would to make sure contd always make sure all configured containers are "running" when it boots
