### ISSUE TITLE
Node without disk not available over Yggdrasil, shows offline on explorer

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#1523]
A farmer reported that their node came online and is pingable on public ipv6 but shows offline on the explorer. Upon checking TF Chain, I see that this node is not utilizing its disks.

```
Node id: 129
Public ipv6: 2a00:dc0:efff:1:e85d:8ff:fe37:7c42
Node twin id: 213
Yggdrasil IP: 302:357:faa3:ea0d::1
```

Since the explorer relies on RMB queries via the proxy server to determine if a node is up, I guessed that the lack of disk cache interferes with RMB operation. The node also doesn't reply to pings over Yggdrasil.

This results in a kind of in between state where the node is connected to the internet but is only reachable if it has a public ip not provided by Yggdrasil. The node is "online" in a general sense, but "offline" in that it cannot provide any capacity to the Grid.

I wonder then, is a node without any disks actually a supported configuration? Such nodes should probably not farm tokens (if they ever did on Grid 2), so the existing behavior is fine in that regard. Farmers may want to check that a node can boot successfully before installing disks in it, which can still be achieved by attaching a screen or checking TF Chain.

A simple improvement would be to add a more obvious message to the Zos status screen that the lack of disks will interfere with operation. Currently a node in this state displays `LIMITED CACHE` on the `cache disk` line. Perhaps something like "No disks detected, this node will not farm tokens or appear online for deploying workloads."

**Comment by muhamadazmy** [comment]
Yeah, you are right, we need a better error message and also stop the node completely from registering

**Comment by muhamadazmy** [comment]
I think storaged need to act differently when there is no available cash disk (SSD storage) instead of mounting a tmpfs cache. it instead need to block the system, other services need to act accordingly.
The UI need to still work and show the proper error messages
