### ISSUE TITLE
Harden the fact that a node cannot bootstrap itself if there is no farm id configured

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#153]

**Comment by muhamadazmy** [comment]
It's not hard to stop the booting of the node if farm-id is not set, the question is what do we need to do to notify the farmer that this node is missing some required configuration.

**Comment by zaibon** [comment]
well since we don't have a farm_id on the node itself, we cannot notify anyone since we don't know who to notify, so I guess the only solution is to print something on the console. 
So we should do that as part of https://github.com/threefoldtech/zosv2/issues/197

Now maybe we could still somehow write something special into the BCDB directory so we can list all the node booted without farm_id.

**Comment by maxux** [comment]
We could simply create a farm called `Unconfigured` or something like that and set this farmid as default farm if it's not set. At least we can query the bcdb and fetch stuff or provision that node to fetch logs, etc.

**Comment by delandtj** [comment]
that is a friggin good idea!

**Comment by zaibon** [comment]
@maxux super nice idea ! You're taking over to implement it ?

**Comment by zaibon** [comment]
fixed in https://github.com/threefoldtech/zosv2/pull/297
