### ISSUE TITLE
Workload not decommissioned after wallet drained

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#1530]
My workload 1422 on Grid 3 testnet drained the associated twin's wallet. When I topped up the wallet, I was billed for the elapsed duration. See analysis from @DylanVerstraete in https://github.com/threefoldtech/tfchain/issues/164#issuecomment-1003009223:

> I think I figured out what happened. Your contract got moved to `Delete` state and an event was emitted to signal ZOS to decomission the contract. ZOS most likely did not catch this event and kept the workload alive and kept sending capacity reports, the unbilled amounts acrued on chain and when you funded your wallet. When the next billing cycle triggered, the amount left due was withdrawn from your account. This is actually not a bug on Tfchain, rather on ZOS.

**Comment by muhamadazmy** [comment]
This should be fixed now, there was some issues in the grid events types. Please re-open if this happened again. Also I am working on some changes that would improve reporting as well
