### ISSUE TITLE
V2 to V3 upgrade crashing

### ISSUE THREAD

**Issue by Nelson361** [threefoldtech/zos#1544]
I was able to upgrade several nodes using the v3 usb drive, but two crash and shutdown.  Hardware is the same. To rule some things out I did a complete wipe and removed the 2nd SSD.  Still cannot get past the attached image
![IMG_20220105_195755](https://user-images.githubusercontent.com/38706735/148313405-61bcef46-f078-49f9-948b-fde06e74ce7d.jpg)
.

**Comment by muhamadazmy** [comment]
Can you try to switch to the other log views (Alt+f1, f2 and f3 ( see if u have more logs)

**Comment by Nelson361** [comment]
Running i7-6700 with 64gb of RAM with V2 was fine.  Upgrading to V3 caused it to crash. Updating the BIOS solved the issue
