### ISSUE TITLE
Zos reports incorrect cores/ram/ssd

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#1545]
Farmer reports that their node has registered the wrong CRU/MRU/SRU. On mainnet, node ID: 14.

Hardware reported by farmer, which is all successfully recognized by bios and a booted Linux:

```
Mobo = MSI MAG B460 TOMAHAWK
Cpu = Intel core i7 10700K (8 cores / 16 threads)
Ddram = 2 x 8 2666mhz
Disk = 4tb ssd
```
GraphQL shows:

```
    {
      "nodeId": 14,
      "twinId": 29,
      "cru": "6",
      "sru": "2048408248320",
      "mru": "12562669568"
    }
```

This node is also reporting resources utilized, according to the explorer, but GraphQL reports no contracts for the node.

![image](https://user-images.githubusercontent.com/17682591/148315474-ffe87ef3-6568-417a-ace3-74bd0c04d060.png)

**Comment by OmarElawady** [comment]
The dmi info of the node 14 can be viewed from here: https://gridproxy.grid.tf/nodes/14
It shows that there are 6 cores (and it's AMD not intel) detected and a 2 4GB memories and 2 2GB memories which matches the info in the issue. 

And the usage seems to be correctly shown in the explorer:
![image](https://user-images.githubusercontent.com/13040543/148676568-6642ec39-4a55-4f39-847b-a68763f3b723.png)

**Comment by scottyeager** [comment]
Thanks @OmarElawady. I think the farmer had farm id and node id mixed up :/
