### ISSUE TITLE
Failed to get node twin

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#1546]
A couple of farmers have reported that their nodes are showing the "failed to get twin" message shown below when attempting to boot Grid 3 mainnet nodes.

Rebooting several times does not resolve the issue. Outbound firewalling at the router level also doesn't seem to be the culprit.

 I don't see any nodes registered to the farm shown below, so I guess that node registration is failing.

![image](https://user-images.githubusercontent.com/17682591/148448468-577266ae-9621-49e1-97b4-d6b1fe150614.png)

Farmer with farm 24 on has a single node which appears to have successfully registered, but is now displaying the same error.

```
 "nodes": [
   {
     "farmId": 24,
     "twinId": 60,
     "publicConfig": null,
     "nodeId": 32
   }
 ],
```
![image](https://user-images.githubusercontent.com/17682591/148508331-6627cd68-f594-4149-ac9d-772b7793bc95.png)

**Comment by muhamadazmy** [comment]
Can you ask them to leave it running for a while and not reboot immediately.

**Comment by DylanVerstraete** [comment]
User reported that his node booted.

**Comment by scottyeager** [comment]
Another farmer reported this error was resolved after enabling IPv6 in their network.

**Comment by sasha-astiadi** [comment]
@scottyeager hope this get documented so they know they need to enable their ipv6

**Comment by scottyeager** [comment]
Hi @sasha-astiadi, I've added a note about this to my list of known issues in the forum. Since that was a one off which could have had a different root cause, I'll continue to monitor before reaching any conclusions here.

**Comment by muhamadazmy** [comment]
This should be fixed in later releases. Can u confirm they have the same issue still
