### ISSUE TITLE
Provide clearer messaging during twin registration

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#1557]
Currently, when a node is registering its twin, a message is displayed in red on the screen: "failed to get node twin...". This looks like an error and prompts farmers to seek support, when usually they just need to wait for their node to finish registering its twin.

_Propose:_ During initial registration of twin, show a different message, perhaps in yellow, stating that the node is "Registering twin on TF Chain, please wait".

**Comment by muhamadazmy** [comment]
Node now show registration status, and success or error status on screen.
