### ISSUE TITLE
Zos 3 bootstrap halts at initializing network devices

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#1559]
A farmer is attempting to migrate Grid 2 nodes to Grid 3. The new bootstrap file doesn't proceed beyond `Initializing network devices...`. Node continues to boot fine with v2 bootstrap.

Machine is a Dell poweredge 720d. I've asked the farmer to check for and perform a BIOS update if available.

**Comment by scottyeager** [comment]
Any ideas on this one, @maxux?

**Comment by maxux** [comment]
It get stuck on initializing device, nothing more after ?

**Comment by scottyeager** [comment]
Yes, this is what is shown on screen:

![image](https://user-images.githubusercontent.com/17682591/150467968-69db9d8a-8301-41f3-ae95-b81d0bdea586.png)

**Comment by maxux** [comment]
It's not the first time we see issue with Dell Powerdge, there are some BIOS settings to tweak to get it working, but not always the same. We need the user to show PXE settings from BIOS.

**Comment by scottyeager** [comment]
Thanks. Will inquire and return with the image.

**Comment by scottyeager** [comment]
This farmer is getting some direct help from @delandtj.

**Comment by maxux** [comment]
Yep we found a way with USB/BIOS mode :)
