### ISSUE TITLE
use public zos nodes as yggdrasil public peers

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#1560]
- All zos nodes must peer with  zos public nodes from all networks (closest) but it has to include a subset of the yggdrasil public nodes also.
- Public nodes from all networks are usable
- Avoid connecting to nodes on the same segment (for example if you are a public node yourself, do not connect to another public node in the same subnet as yourself

**Comment by despiegk** [comment]
please lets review some specs here

**Comment by coesensbert** [comment]
Mainnet currently has 4 public zos nodes

https://docs.grid.tf/threefold/itenv_threefold_main/src/branch/master/Kubernetes-clusters/hagrid-prod2/applications/tfchainmainnet/Public-config.md
