### ISSUE TITLE
Nodes without SSD should not be able to go online in V3

### ISSUE THREAD

**Issue by andhartl** [threefoldtech/zos#1569]
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/18591016/150508408-505eda61-9ec1-45e5-91b1-6de87ea21dd2.png">
given the new definition of CU which includes SSD capacity nodes without SSD should not be able to go online on grid 3

**Comment by scottyeager** [comment]
This was already addressed in #1523 and #1550.
