### ISSUE TITLE
Display quota size rather than node's disk size

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#1579]
Currently, users who run `df` within a VM will see the full size of the node's disk which their rootfs is allocated from. I'm not sure if this is the same behavior for attached disks. This makes it difficult to monitor available disk space and causes confusion for users who run out of quota.

There are some tools and methods for checking quota in cases like this, such as `quota` command, but I wasn't able to find any that work with the rootfs implementation.

**Comment by muhamadazmy** [comment]
No, for disks it's only the allocated size that shows up. it's different from rootfs because it uses virtiofs to access basically a shared directory on the host (zos) this directory (subvolume) has a quota limit.

I am trying to find out a solution for this issue. It's indeed confusing.

**Comment by despiegk** [comment]
suggest to delay
