### ISSUE TITLE
Node registration fails after "submit extrinsic: Transaction is temporarily banned"

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#1581]
We're seeing cases lately where node registration is failing and wiping disks seems to be the fix. I can't confirm whether wiping the disks, simply waiting, or the additional boot cycle is resolving the issue. See example output [here](https://forum.threefold.io/t/how-to-set-up-your-own-3node/833/91).

My hunch is that after `submit extrinsic: Transaction is temporarily banned` the node does not properly retry for some reason or TF Chain does not accept future attempts from that node to create its identity.

**Comment by muhamadazmy** [comment]
I think the wiping of the disks made the node to activate a new account on the chain. Why the transaction can be banned might be not clear. It can be the node somehow ran out of funds but this should not be possible anymore. Was it a new node?

**Comment by scottyeager** [comment]
Yes, always seeing this with new nodes. I'll see if I'm able to get a complete account address from a farmer for further investigation on whether insufficient funds is the cause.

Maybe @DylanVerstraete has some insight on why an extrinsic might show temporarily banned?

**Comment by scottyeager** [comment]
We are still seeing some instances of this, with new nodes. One farmer (farm id 1336) reports seeing this with a subset of their nodes, and same behavior after wiping the disks. I checked the accounts for two nodes, as shown below. Both have balances less than 1 mTFT, and both are on nonce 97. I will check if funding the accounts clears the issue.

5CWLoR2ZiQEPKYZiR3z4rhMgHs5RDWf8rpYAfuSPD6z1a7E7
```
{
  nonce: 97
  consumers: 0
  providers: 1
  data: {
    free: 731.2000 µTFT
    reserved: 0
    miscFrozen: 0
    feeFrozen: 0
  }
}
```

5GeKwf4T6kujeAnBi7v6jJz7NVDiZtuPjN1pTnWwuoXyGmrK
```
{
  nonce: 97
  consumers: 0
  providers: 1
  data: {
    free: 636.1000 µTFT
    reserved: 0
    miscFrozen: 0
    feeFrozen: 0
  }
}
```

**Comment by scottyeager** [comment]
Indeed, funding the wallets for these nodes cleared the issue and they were able to register successfully. I have not seen this issue occurring anymore.
