### ISSUE TITLE
Error while trying to build an image in our VM 

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/zos#1586]
I was trying to build an image on our VM, then I got this error 
![image](https://user-images.githubusercontent.com/46320202/153358966-12644138-238a-46bf-b26f-0c1a1632dd97.png)

while it builds successfully on a digital ocean machine 
![image](https://user-images.githubusercontent.com/46320202/153359044-46e11283-9345-45d9-b917-1a4e5d853aeb.png)

**Comment by xmonader** [comment]
@muhamadazmy any idea?

**Comment by muhamadazmy** [comment]
First of all, i think this is a warning not an error. It seems it continued building afterwards (please correct me if I am wrong). Also it looks like a build environment issue (complaining about a dependency that is unmet). Is it possible there is a missing update or something?

**Comment by RafyAmgadBenjamin** [comment]
Actually, it stopped building and didn't continue then I tried it again on a digital ocean machine, it worked well and all the dependencies were met and the image built and tagged successfully, not sure why this dependency was not met on our VM but was met on digital ocean.
