### ISSUE TITLE
For invalid public config, noded leaks redis connections

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/zos#1589]
I modified my node to have empty values in hope that it would unset the public config (it doesn't). Turns out that after some time, noded stops responding to rmb calls. The public method takes an event stream from zbus, and it doesn't get closed so eventually the redis pool runs out of connections.

https://github.com/threefoldtech/zos/blob/main/cmds/modules/noded/main.go#L187

**Comment by muhamadazmy** [comment]
Update the link to point to a `perminant` line because this points to nothing :) Then we should add protection against setting public config to empty so the node will just ignore it until it has been rebooted ?

Un-Setting public config is not supported, and will never be without a node reboot.

**Comment by OmarElawady** [comment]
Nice tip :) The issue is mainly about leaked redis connections. The goroutines starts a stream each time setting the public config fails (this can be for a lot of reasons, one of which is invalid data), the stream takes a redis connection from the pool. After a few failures the pool gets completely consumed and the rmb bus can't reply to incoming requests anymore (it shares the pool).

zbus stub: https://github.com/threefoldtech/zos/blob/715846cfc6d12446bfd3ffa4a62e19f2a2b82d04/pkg/stubs/events_stub.go#L52
pool get: https://github.com/threefoldtech/zbus/blob/9abf31fcba54eb37fb315fb5a487acb2e2fd325e/redis.go#L364
