### ISSUE TITLE
containerd: limit the amount of storage user can write on root

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#159]
Currently, if a user creates a container without any volume mounted. He can abuse the root of is container and store pretty much unlimited amount of data in there.
This data ends up in the cache of the node itself.

We need to limit this as much as possible. I don't think we can make root fully read-only, but the usage of volume in container should be really encouraged.

**Comment by zaibon** [comment]
One solution to this would be to implement this in flistd itself. 0-fs already allow to choose where to set the Read-Write layer.
So if flistd does creates a small sub-volume before starting the 0-fs process, he can point the RW layer to the sub-volume. Like this the user will get a nice `no more space on device` error if he tries to abuse it's root.

**Comment by delandtj** [comment]
also, from experience, people just don't use volumes, and expect `/` to not be ephemeral. Nasty surprises ensued, as well as dirty hacks using backups and restores for restarts. you'd be amazed at the imagination and inventivity
