### ISSUE TITLE
Gateway domain doesn't resolve with ingress in K8s cluster

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/zos#1591]
I have deployed a k8s cluster then tried to reach this cluster with a domain generated from our gateway, but Ingress failed to handle this domain (the domain didn't reach the ingress controller) then tried to generate domain from `name.com` and used it in my helm chart it works well. 

`contract ID`: 7724
`domain`: hamadabasha.gent01.dev.grid.tf
`env`: devnet

**Comment by muhamadazmy** [comment]
The gateway has been decommissioned so it's hard to debug the problem. But i see no errors in the logs regarding this. are u sure u had the correct backend IP address used ?

**Comment by RafyAmgadBenjamin** [comment]
> The gateway has been decommissioned so it's hard to debug the problem. But i see no errors in the logs regarding this. are u sure u had the correct backend IP address used ?

yes, I am sure of the IP address even @AhmedHanafy725  has checked this with me

**Comment by xmonader** [comment]
https://github.com/threefoldtech/zos/issues/1794
