### ISSUE TITLE
Nodes not recognizing RAID/HBA connected SSD

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#1601]
Some farmers are reporting that SSD connected via RAID controllers or HBA adapters is not being recognized by Grid 3 Zos. In some cases, it shows up as HDD. In other cases, the node is not able to fully boot because it sees no SSD. These nodes were working properly on Grid 3 previously. One farmer reports that booting the node back to Grid 2 resolves the issue and SSD is detected.

**Known affected nodes on Grid 3 mainnet:** 
421, 613, 570, 614

**Known affected hardware:**
HBA - LSI SAS9211-8i
HP Smart Array P410i Controller
FUJITSU SAS RAID KONTROLER D2616-A22
Dell H310

**Comment by muhamadazmy** [comment]
@maxux can this be because of a missing kernel support for raid controllers ?

**Comment by maxux** [comment]
Which image were used for the working v2 ? Was it the 5.10.55 kernel or the old one 5.4 ?
Can we have remote access theses node in v2 and v3 to see what's missing ?

**Comment by scottyeager** [comment]
Farmer who booted back to v2 has node id HfP2mtA8eJkqCrX3ez3T8oxNHWchtebTh9Ewbj2YixwK

This node will not boot on Grid 3 anymore because all SSD is connected via RAID/HBA. Grid 3 node ids listed above also have SSD connected directly to mainboard.

**Comment by scottyeager** [comment]
I've added a couple more hardware models with this problem in the original issue. Would be nice to resolve this with some urgency, since farmers will be complaining about missed farming rewards :scream:

Additional data point here, the farmer with the Dell H310 reports that by changing the boot device option within controller settings from "None" to "Factory default" one of their drives is properly recognized as ssd, while two others show as hdd.

**Comment by maxux** [comment]
I'll try to investigate that today

**Comment by maxux** [comment]
https://explorer.grid.tf/api/v1/nodes/HfP2mtA8eJkqCrX3ez3T8oxNHWchtebTh9Ewbj2YixwK
This node doesn't have ipv6 ?

**Comment by scottyeager** [comment]
I see ipv6 config on that node, but it looks like they took it offline. Let me see if I can get them to bring it back.

**Comment by scottyeager** [comment]
Probably that node is offline because auto migration has been activated and it won't stay on Grid 2 now.

I checked and this started occurring around 10 days ago, corresponding about with the 3.10 release. Checking the release notes, I found [this PR](https://github.com/threefoldtech/zos/pull/1592) to change the way that drive type detection is handled. I'm asking farmers with this issue to send their output of `lsblk` to see if the ROTA flag is set.

**Comment by maxux** [comment]
`ROTA` should never be trusted, if there is something wrong with `seektime`, we need to fix it.

**Comment by OmarElawady** [comment]
There was an [issue](https://github.com/threefoldtech/zos/issues/1539) with seektime taking time to get the seektime of hdds. It happened on multiple nodes on devnet (7 and 11). It wasn't a big issue, since seektime worked quickly the second try. So `storaged` failed to start multiple times for each HDD present, then worked normally after.

It was fixed by assuming the device is HDD if took more than 5 seconds here https://github.com/threefoldtech/zos/pull/1540

Then it was done like in this pr: https://github.com/threefoldtech/zos/pull/1592,

**Comment by maxux** [comment]
That should have been reported on seektime repo first: https://github.com/threefoldtech/seektime
Better to find out what happen than trying to workaround :)

**Comment by scottyeager** [comment]
I've confirmed with one farmer that ROTA is set for all drives demonstrating this issue.

**Comment by scottyeager** [comment]
Thoughts on this @muhamadazmy?

**Comment by maxux** [comment]
Like I said, ROTA needs to be ignored, this flag is not valid, with mostly any RAID controller.
Can I get access to a node which have the latency issue of seektime ? Stop looking for workaround, we just need to fix that.

**Comment by OmarElawady** [comment]
Node 7 on devnet, its ip is `10.9.0.101`.
![image](https://user-images.githubusercontent.com/13040543/157438600-97632f91-2749-4969-a646-96e4fddba075.png)

**Comment by maxux** [comment]
Thanks, I'm on it :)

**Comment by maxux** [comment]
This happen because the disk is in standby, of course the system needs to wait for the disk to be up before being able to compute seektime.

```
# hdparm -C /dev/sdc

/dev/sdc:
 drive state is:  standby
```

```
# strace -C -tt /usr/bin/seektime /dev/sdc
[...]
13:05:59.740376 lseek(3, 506570680, SEEK_SET) = 506570680
13:05:59.740427 read(3, "\26\256\232~\353\266\220\205\0P\374\353x\361\367+\2271\364\240^\353Yd\345\267\255H\323\24j\221"..., 512) = 512
13:06:13.030986 lseek(3, 864998928, SEEK_SET) = 864998928
```
The read syscall took 13 seconds.

```
# hdparm -C /dev/sdc

/dev/sdc:
 drive state is:  active/idle
```
State of the disk right after the test.

**Comment by scottyeager** [comment]
Thanks @maxux. Can we move forward with a fix based on your findings?

**Comment by raetser** [comment]
If you need access to my server remotely, I can offer that if you need to test/debug. Any idea when this will be fixed? When I moved to V3 a few weeks ago, everything was working fine...
