### ISSUE TITLE
Deployed VM on mainnet -> and when wallet is empty the VM disappeared.

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/zos#1606]
Deploying through the play.grid.tf portal a VM.  Wallet had about 100TFT's and a few days in the wallet was empty and the VM gone. 

Proposal: we should think about a mechanism to make the VM in-accessible bu not delete.  I also heard from Peter van VCC the same - Owncloud deployment and (low wallet to start with) after the wallet depleted the deployment was done.

**Comment by weynandkuijpers** [comment]
Can you please leave a link here to where you transferred the issue?

**Comment by hossnys** [comment]
Transfered here threefoldtech/zos#1606

**Comment by xmonader** [comment]
this should be in zos repo, as this its the one responsible for deleting workloasd

**Comment by muhamadazmy** [comment]
This behavior was in the original requirements for ZOS. Defining the policy to decomisison a contract that ran out of fund is not that straight forward or easy. The following points need to be taken into account.
- On the grid, the grid decide if the contract need to be cancelled immediately or not. Implementing this feature can be done easily on the grid by not cancelling the contract immediately, but wait instead when wallet runs out of fund.
- The idea was always that a 3rd entity should keep an eye on the wallet and top it up when needed.
- The node reacts to a cancel contract is immediate, this makes implementation simple in zos and not to complicate things. Hence I think the wait before decomission is better implemented on the grid.
- Who defined how long the deployment should be kept running when wallet runs out of funds.

**Comment by xmonader** [comment]
there's a grace period implemented now
