### ISSUE TITLE
Testnet: public ip not canceled on zos node ID 10

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/zos#1607]
With ops we have a deployment reservation on testnet where one vm with public ipv4 has an ip conflict on the network.
After some investigation it looks like a previous deployment, with public ip, was not removed propperly.

Currently, there is a vm running on zos **node 2 with contract id 3164**. It has **public ipv4 185.206.122.142**
Connectivity, over ipv4, to this vm goes on and off: ARP doing its things so sometimes you can reach the vm, sometimes not.

```
# grid_deployment.d2:
resource "grid_deployment" "d2" {
    id           = "3164"
    ip_range     = "10.30.4.0/24"
    network_name = "tfopstestnetwork"
    node         = 2
    vms {
        computedip  = "185.206.122.142/24"
        computedip6 = "2a10:b600:1:0:7c99:afff:fe7e:d471/64"
        cpu         = 4
        description = "Threefold TFchain Testnet public node 03"
        entrypoint  = "/init.sh"
        env_vars    = {
            "SSH_KEY" = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDYNeJXJV2FNEwuQz6e0jkKeqRbKWwftBKq+sjSTqa2x"
        }
        flist       = "https://hub.grid.tf/tf-official-apps/threefoldtech-ubuntu-20.04.flist"
        ip          = "10.30.4.2"
        memory      = 8192
        name        = "tfchaintestpub03"
        planetary   = true
        publicip    = true
        publicip6   = true
        rootfs_size = 100000
        ygg_ip      = "300:c282:7f31:4aa4:2280:af95:c595:3896"
    }
}
```

After some investigation it looks like there is **still a reservation running on zos node 10**. It has the same public IP configured in one of it's namespaces which should have been removed in the past. I'm not able to login on the zos node with ID 10 but @delandtj can provide more information.

Current deployment: zos node with ID 2: 10.9.0.131
Previous deployment / conflict node with ID 10: 10.9.0.139

**Comment by muhamadazmy** [comment]
I tried to investigate this issue and noticed that the VM that was hording the IP was gone already according to the logs it was decomissioned already by an OutOfFund contract. I noticed also that the dates when the contract was cancelled (according to graphana) didn't match the date when the Vm was actually deleted. There might be an issue there but was not possible to reproduce. 

I will close this now and see if this happen again in the future and hopefully check the conflicting VM before its gone to see why it wasn't deleted immediately
