### ISSUE TITLE
There is no way to get logs from a container

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/zos#1608]
Currently, running a container, especially a single binary one, does not give any option to check logs of the process.

**Comment by muhamadazmy** [comment]
The node stores logs locally from all running vms/containers. There are some issues regarding this:
- Fetching a log file can cause a big amount of data to be transferred, hence I think the best is you can ask for chunks of 4k each, so to read the entire file you need multiple calls, if chunk index is -1 then the last 4k chunk of the log file is returned.
- log-rotation is not supported so for a spammy containers there is no protection against generating a large amount of files. Will check if logrotate can be a solution for this problem or simply truncating the file. There is no built in way to rotate logs from CH itself, specially that we use a redirection of stdou/stderr to the log file this way we can have both console and CH errors in one file.

What we need to do:
- Add method to fetch log chunks
- Log rotation
