### ISSUE TITLE
Farms show zos version 0.0.0 when node attached to monitor

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/zos#1609]

**Comment by sabrinasadik** [comment]
![56A891AF-8F5B-4315-89A9-651C182FEC93](https://user-images.githubusercontent.com/31733464/156435598-df736fe4-44fc-46b7-a1e4-3bc2621bb546.jpeg)

**Comment by scottyeager** [comment]
There are also a number of nodes reporting version 0.0.0 via the explorer:

![image](https://user-images.githubusercontent.com/17682591/156839534-97cc8fc9-f90f-4e1a-8211-f5a9aa1fe1ea.png)
