### ISSUE TITLE
Node's wallet depleted

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#1628]
Farmer reported that their node 95 on testnet did not mint any tokens despite being powered on and even hosting a workload that remained accessible. Checking GraphQL, I noticed that uptime reports for the node stopped being logged on TF Chain around January 11. Checking the node's console and log screens, we saw this:

![image](https://user-images.githubusercontent.com/17682591/158911285-b8794595-3a68-4445-973e-5e049240a4cb.png)

![image](https://user-images.githubusercontent.com/17682591/158911337-8260149e-6bc0-4666-8f06-e95736d49286.png)

![image](https://user-images.githubusercontent.com/17682591/158911349-dd8e6979-c989-4ee6-9057-3d7941f5365b.png)

I then checked the wallet associated with the node's twin `5HfEiceBtjJ7skLRp3ose2XgVaWbw7D5w7TtkqNTvGVmoDBC` and noticed it had only a tiny amount of TFT. After funding the wallet with 1 TFT, errors cleared and the node began operating normally again.

Referencing #1581, I wonder if some issue with nodes depleting their wallets has already been resolved, but will log findings here anyway.

This node was created in late November and appears to have been initially funded with 1 TFT. The wallet was depleting at a steady pace until just before it stopped reporting uptime on January 11 and had about .2 TFT. Then the remaining TFT were quickly depleted somewhere between block 1220000 and 1250000. I'm not sure what extrinsics it executed in this period or why.

**Comment by muhamadazmy** [comment]
Thanks @scottyeager for the great debugging of the issue. The nodes should not deplete their wallets anymore for sure, I assume the node wallet was already depleted before the fix. I will verify with @DylanVerstraete when exactly was the fix available on testnet.

**Comment by muhamadazmy** [comment]
@DylanVerstraete can we tell when the fix for free node extrinsics was available on testnet ?

**Comment by DylanVerstraete** [comment]
We deployed a fix https://github.com/threefoldtech/tfchain/commit/ee56ce51f64a5c8664c9abeca9156fa1ab02538b on the 13th of January to fix this issue. All nodes that still have balance after this date should not have this issue anymore. Thanks for reporting @scottyeager

**Comment by scottyeager** [comment]
Thanks @muhamadazmy and @DylanVerstraete. Good to have this info going forward :+1:
