### ISSUE TITLE
all gateways deployed on node 8 doesn't work

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/zos#1630]
all solutions deployed from weblets which has a domain name `gent02.dev.grid.tf` gives `404 page not found`

![Screenshot from 2022-03-22 17-09-20](https://user-images.githubusercontent.com/32527347/159514527-d70ee502-d479-46cd-950c-2aef7c6e641d.png)

However the solution accessible with planetary IP
![Screenshot from 2022-03-22 17-11-11](https://user-images.githubusercontent.com/32527347/159514810-707ecc8b-a820-425e-9a9a-f9182796a655.png)

**Comment by muhamadazmy** [comment]
Yes, node 8 has issues i just checked and i think it's related to disk speed detection which caused cash to be deleted.I am rebooting the node but it will come up as a different node.
