### ISSUE TITLE
Failed to get node twin id

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#1631]
Farmer has three Titans. One successfully migrated to Grid 3, while the other two are stuck on "node is not registered" on Zos console and show the errors below:

![image](https://storage.crisp.chat/users/upload/visitor/bff6226bff09c000/f1b56bbab471b210d352aa46f669f4ec59d4f986.jpeg)
![image](https://user-images.githubusercontent.com/17682591/159627060-c5dca5a5-db7b-4e1a-a714-e556fe29094e.png)

I guess that wiping the ssd might probably help in this case, but would like to avoid that because these are plug and farm nodes and the farmer is not highly technical.

For troubleshooting, the farmer has rebooted both the nodes and their router. Failure also of the geoip lookup suggested maybe a networking error, but these nodes also worked fine on Grid 2.

Any ideas?

**Comment by muhamadazmy** [comment]
The node seems can't resolve https://geoip.grid.tf for some reason. Looks like a dns failure to me If the node can't detect the location it will keep trying but will not register. Other services are just failing because it's not fully registered yet.

As per the log message from 'noded' the service that is responsible for registration looking up failed dio to i/o timeout reading response from your dns server at 192.168.1.1.

**Comment by scottyeager** [comment]
We've tried the following troubleshooting:

1. Contact geoip service from web browser on another device in the farmers network. No problem here.
2. Switch cabling and router port from the one Titan that registered successfully to one of the others. This did not clear the issue

All three nodes were working fine on v2. Also, they must have working dns to get this far in the boot process and pass the initial internet connectivity test. So question is, why are they only failing at this step?

**Comment by muhamadazmy** [comment]
Sorry about this. But is this still an issue ?

**Comment by scottyeager** [comment]
Thanks for circling back, @muhamadazmy. If I remember correctly, the issue was resolved by booting the node once at a different location so it could register.
