### ISSUE TITLE
Error while sending twin report - context deadline exceeded

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#1633]
A couple farmers are seeing this error.

Node 467 on mainnet, no change after reboot:
![image](https://user-images.githubusercontent.com/17682591/160200435-e61d0ef9-bd2a-4bcc-a9e0-4e8bef575e4e.png)

This node doesn't seem to make it to the node console to display a node id. Has been rebooted several times:
![image](https://user-images.githubusercontent.com/17682591/160201175-5a362d3b-0d7d-47ec-b0b6-d91c02f0c811.png)

**Comment by gazgits** [comment]
Can anyone help with this issue please?

**Comment by muhamadazmy** [comment]
Yes, it's fixed in a new code, but it's not released yet. Eventually this will reach main-net
