### ISSUE TITLE
HTTP2 does not seem to work on Gateways by design

### ISSUE THREAD

**Issue by dumblob** [threefoldtech/zos#1638]
After skimming the architecture of ThreeFold Gateways I immediately asked myself the following question.

How does it handle HTTP2 (aka QUIC)?

The doc https://library.threefold.me/info/manual/#/technology/threefold__network_wall describes only HTTP(S) which is **request-based** but HTTP2 is **session-based** which totally shuffles the cards. But of course, maybe I'm missing something.

Any insights and/or plans how to support HTTP2?

**Comment by muhamadazmy** [comment]
Under the hood, we we `traefik` for the actual proxying of data. Hence theoretically can support whatever traefik can support.

We will do some research on the support of QUIC in traefik and see if we need to change anything to support it.

**Comment by xmonader** [comment]
At the moment, we only support two modes
- HTTP1.1 proxying: using traefik which serves lots of use cases when activated on the gateway (tlspassthrough=false), however you can find cases where specific custom headers are required which we don't do by default
- TCP Proxying: this is the most flexible option (TLSpassthrough=true mode), there you have full control of your setup. 
 
In case of QUIC, it requires further research from our side incase of the provided options aren't enough , for that limitation you can also just depend directly on IPs and discard the usage of gateways

**Comment by dumblob** [comment]
Ok, thanks for clarification. I will leave this open so that you can document the progress on your "further research".

**Comment by dumblob** [comment]
@muhamadazmy what did you find out?
