### ISSUE TITLE
Testnet: testnet3-11 has full disks

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/zos#1651]
testnet3-11 = Node ID: 11 = 10.9.0.140

![image](https://user-images.githubusercontent.com/88312671/162697965-dee16239-ff08-4bf5-9153-d64f7524a961.png)

**Comment by muhamadazmy** [comment]
It's not the machine disks that are full it's the root `/` which is full for some reason. I will try to increase the / size as a temp fix

**Comment by muhamadazmy** [comment]
This node is also ran ou of funds, and also running a very old zinit version 0.2.1, i will reboot it
