### ISSUE TITLE
Devnet: VM became unreachable after rebooting

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/zos#1654]
deployed test VM using ubuntu 22.04 using the image from [here](https://hub.grid.tf/tf-official-vms) with date Apr 08 2022
trying to reboot using `shutdown -r` then the machine didn't back online.

deployment is done via https://play.dev.grid.tf/ v:<47ca1cd>, on devnet.

things I remember doing before rebooting, 
`apt update`, `apt upgrade`, installing Docker, and pulling a few images.

```sameh@sameh-inspiron-3576:~$ ssh root@302:9e63:7d43:b742:b10a:dfc5:5dc0:bba4
ssh: connect to host 302:9e63:7d43:b742:b10a:dfc5:5dc0:bba4 port 22: No route to host```

**Comment by muhamadazmy** [comment]
This might be a hypervisor firmware bug [here](https://github.com/cloud-hypervisor/rust-hypervisor-firmware/issues/140). The only known work around at the moment is to always power off the machine instead of rebooting.

**Comment by sameh-farouk** [comment]
I can confirm that the `shutdown` command works, while by using `shutdown -r` the VM won't back online.

Is there any proper fix yet? there is no guarantee that a user won't try to reboot his VM for any reason. then it will end up with an unreachable machine.

can you check this suggestion https://github.com/cloud-hypervisor/rust-hypervisor-firmware/issues/140#issuecomment-1102716891

**Comment by sameh-farouk** [comment]
Verified on ef480d329f8f268d9e6ee148bb3e7a2d6aaf292f
```
root@VMe5f041a3:~# shutdown -r
Shutdown scheduled for Mon 2022-05-16 13:19:01 UTC, use 'shutdown -c' to cancel.
root@VMe5f041a3:~# Shared connection to 185.206.122.45 closed.
sameh@sameh-inspiron-3576:~$ ssh root@185.206.122.45
ssh: connect to host 185.206.122.45 port 22: Connection refused
sameh@sameh-inspiron-3576:~$ ssh root@185.206.122.45
Welcome to Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-110-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Mon May 16 13:19:39 UTC 2022

  System load:           0.3
  Usage of /:            4.0% of 48.29GB
  Memory usage:          2%
  Swap usage:            0%
  Processes:             138
  Users logged in:       0
  IPv4 address for ens3: 10.20.2.2
  IPv6 address for ens3: fd46:3954:454a:2::2
  IPv4 address for ens4: 185.206.122.45
  IPv6 address for ens4: 2a10:b600:1:0:8c55:9bff:fe02:ed2f
  IPv6 address for ens5: 302:9e63:7d43:b742:9964:d0a8:462b:4eca


33 updates can be applied immediately.
To see these additional updates run: apt list --upgradable


Last login: Mon May 16 13:17:42 2022 from 196.154.204.196
```
