### ISSUE TITLE
Cannot mount /dev/vdd : mount(2) system call failed: File exists.

### ISSUE THREAD

**Issue by archit3kt** [threefoldtech/zos#1657]
Hi,

typical terraform deployment (plugin version 0.1.27) with 6 disks, which should all be mounted inside the VM

Mounting disks from vdd to vdf fails with the error mount(2) system call failed: File exists.

There is also a seventh disk vdg which can be mounted read only and contains metadata and config info for the VM. Not a bug but I wonder what it is used for

**Comment by muhamadazmy** [comment]
Can you please show me how the terraform deployment for the VM looks like (you can hide keys and such) I only need to know, flist, and mount points as defined in the vm resource.

**Comment by archit3kt** [comment]
Sorry @muhamadazmy it was indeed a pebkac, forgot to change some disk names in the deployment mounts ! I should stop working when I'm too tired :D
