### ISSUE TITLE
Virtual Machine does not reboot and systemctl not properly 

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/zos#1658]
Deployed a VM on mainnet and needed to install webmin.

So after install starting the service does not work through `systemctl` and has to be done the manual way `/etc/webmin/start`

![reboot](https://user-images.githubusercontent.com/13766992/154042168-7845154c-51af-4864-ad09-b7f64517ea3e.jpg)

Also - not being able to reboot and have the additional installed software to boot there needs to be integration with `systemctl`.

**Comment by coesensbert** [comment]
The lack of systemd in any of our flists is a known issue. We also need this for ops. We did some investigation into making an full blown VM ubuntu flist with systemd (and not minimized) but it will take more time then expected.

Rebooting a node without systemd can be done via: echo b > /proc/sysrq-trigger

**Comment by LeeSmet** [comment]
This image is running as a container, meaning you should have control over the process which runs as PID 1. So it should be possible to start it with `init=/sbin/init`, as /sbin/init is usually a symlink to systemd

**Comment by muhamadazmy** [comment]
As @LeeSmet said, this is not a "VM" per se. This is running in a `container` mode which hence the entrypoint defined in your deployment becomes PID 1. If PID is systemd this will behave as you are expecting. 

It's not clear which flist you are using so I assume it's the base image which uses zinit as PID 1. That is completely different (and primitive/lightweight) compared to systemd and is used to run light weight containers which has minimal config and setup.

For a Full Ubuntu image you will have to wait for the next release where we support fully bootable cloud images. This is now available on testnet, in case you want to try it out.

On the other hand I don't think the weblets actually has support for those kind of VMs yet. 
@rkhamis do we have new weblets to install official supported VM images on the grid yet?
