### ISSUE TITLE
Mainnet: failing deployments on node 1470: file resize error

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/zos#1659]
Deploying on node 1470 always results in the following error. Both via play.grid.tf as via terraform:
![image](https://user-images.githubusercontent.com/88312671/156194013-591043f2-c700-409e-bc71-4c17153cf08f.png)
![image](https://user-images.githubusercontent.com/88312671/156194055-c88ab326-479f-4499-a3b4-2b93019a3162.png)

Play:
![image](https://user-images.githubusercontent.com/88312671/156194129-990c9fcf-7a60-473f-b496-cc28a7016dac.png)

Terraform:
```
terraform {
  required_providers {
    grid = {
      source = "threefoldtech/grid"
    }
  }
}

provider "grid" {
}

resource "grid_network" "net1" {
    nodes = [1470]
    ip_range = "10.20.0.0/16"
    name = "tfopstestnetwork01"
    description = "threefold test Ops network 01"
    add_wg_access = false
}
resource "grid_deployment" "d1" {
  node = 1470
  network_name = grid_network.net1.name
  ip_range = lookup(grid_network.net1.nodes_ip_range, 3, "10.20.3.0/24")
    vms {
    name = "opstestvm"
    description ="Threefold ops testing"
    flist = "https://hub.grid.tf/tf-official-apps/threefoldtech-ubuntu-20.04.flist"
    cpu = 2
    publicip = false
    publicip6 = false
    memory = 2048
    rootfs_size = 25000
    entrypoint = "/init.sh"
    planetary = true
    env_vars = {
      SSH_KEY ="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDYNeJXJV2FNEwuQz6e0jkKeqRbKWwftBKq+sjSTqa2x"
    }
  }
}
```

**Comment by LeeSmet** [comment]
Checked loki and there aren't any logs for this node for some reason. However judging by the error I assume the filesystem containing the cache is dead, which prevents writes in the cache, causing all workload deploys to fail.

**Comment by LeeSmet** [comment]
cc @delandtj

**Comment by muhamadazmy** [comment]
This `read-only` file system is alarming because it means cache disk somehow was set to read-only by the kernel which might indicate a disk failure or filesystem corruption 

luckily this node has a public IP and was able to login 
I see those errors from dmesg about the disk

![image](https://user-images.githubusercontent.com/10920323/165694471-dea5e626-e10c-4827-9993-9c0f591d6b96.png)

trying to remount the disk into rw mode again gives this error 
```
[5259427.044744] BTRFS error (device sdb): Remounting read-write after error is not allowed
```

I am not sure a reboot can fix it, but I will try

**Comment by muhamadazmy** [comment]
Rebooting fixed the issue BUT. I noticed that the cache disk 'name' has changed after the reboot from `sdb` to `sda` (but it still same disk, same guid and same node id). Is it possible that the farmer switched the disks while the node is running? without proper power cycling the node ?

**Comment by muhamadazmy** [comment]
Side note: It's a waste of public IPs to have this node assigned a public ip over dhcp like that. Would be better if the node instead gets a private IP and then use this public ip in public config, then this node can act as a gateway.
