### ISSUE TITLE
PCIe Bus Error on Titan

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#1677]
Titan node (am not sure which model but have inquired to find out) is displaying the following errors on boot:

![image](https://user-images.githubusercontent.com/17682591/166848704-aa4ff4f4-bde6-475e-858d-b39fadb6edf1.png)

**Comment by delandtj** [comment]
That error is a real hardware error. I hope rebooting would solve the issue, but I fear there is something wrong on the motherboard itself

**Comment by scottyeager** [comment]
Thanks @delandtj. Problem cleared after some reboots, and we'll replace the hardware if it persists.
