### ISSUE TITLE
New Yggdrasil peer list for ZOS

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/zos#1680]
Related to: https://github.com/threefoldtech/tf_operations/issues/852

To consolidate Yggdrasil communication, ZOS should also use this new peer list

```
  Peers:
  [
    # Threefold Lochrist
    tcp://gent01.grid.tf:9943
    tcp://gent02.grid.tf:9943
    tcp://gent03.grid.tf:9943
    tcp://gent04.grid.tf:9943
    tcp://gent01.test.grid.tf:9943
    tcp://gent02.test.grid.tf:9943
    tcp://gent01.dev.grid.tf:9943
    tcp://gent02.dev.grid.tf:9943
    # GreenEdge
    tcp://gw291.vienna1.greenedgecloud.com:9943
    tcp://gw293.vienna1.greenedgecloud.com:9943
    tcp://gw294.vienna1.greenedgecloud.com:9943
    tcp://gw297.vienna1.greenedgecloud.com:9943
    tcp://gw298.vienna1.greenedgecloud.com:9943
    tcp://gw299.vienna2.greenedgecloud.com:9943
    tcp://gw300.vienna2.greenedgecloud.com:9943
    tcp://gw304.vienna2.greenedgecloud.com:9943
    tcp://gw306.vienna2.greenedgecloud.com:9943
    tcp://gw307.vienna2.greenedgecloud.com:9943
    tcp://gw309.vienna2.greenedgecloud.com:9943
    tcp://gw313.vienna2.greenedgecloud.com:9943
    tcp://gw324.salzburg1.greenedgecloud.com:9943
    tcp://gw326.salzburg1.greenedgecloud.com:9943
    tcp://gw327.salzburg1.greenedgecloud.com:9943
    tcp://gw328.salzburg1.greenedgecloud.com:9943
    tcp://gw330.salzburg1.greenedgecloud.com:9943
    tcp://gw331.salzburg1.greenedgecloud.com:9943
    tcp://gw333.salzburg1.greenedgecloud.com:9943
    tcp://gw422.vienna2.greenedgecloud.com:9943
    tcp://gw423.vienna2.greenedgecloud.com:9943
    tcp://gw424.vienna2.greenedgecloud.com:9943
    tcp://gw425.vienna2.greenedgecloud.com:9943
  ]
```

**Comment by Parkers145** [comment]
I think it would be beneficial to peer the us nodes with my peers 

3nodes 
2914, 3049, and 3081

I also have a core node on the net, 

it’s info is
TCP://108.242.38.187:1337 or 9943

Can you tell me what domain records I need to see to make these addressable by domain?

**Comment by coesensbert** [comment]
Hi @Parkers145 

Thanks for your post. We had 2 of your nodes in the first version of this list, ran some tests for a few days and the US ones dropped out at several points so we removed them. Not sure why this was but for us it's important these are reliable peers, preferably also knowing the situation they run in (data center or not, WAN connection latency/bandwidth, ..). These must be as reliable as possible as they will form a sub-backbone of the Grid communications (both internal and client communication).
This list is also not permanent. Since Yggdrasil is still alpha-stage this is also a test for us if Yggdrasil communication would improve if we isolate ourselves a bit on the Yggdrasil network. If so we want to implement some kind of auto list generation and the ability to update it to all clients

Could you elaborate a bit more on how and where you are running your public gateway nodes?

**Comment by Parkers145** [comment]
I can explain that, I didn’t plan to dive as deep as I have and I had some trouble with my Yggdrasil public node not playing nicely. 

i also had some down time to add 100gb of Ram to one, some drives to another. 

Lastly I migrated from a 1gig to to 2.5 gig over the last 24 hours and had to drop some new cables. 

All that to say, they are up for good now. 

Only been aware of threefold and Yggdrasil for about a week, mistakes were made.

**Comment by Parkers145** [comment]
My structuring is I have a primary gateway with a 2.5 gigabit connection, 3 nodes and a ygg public node have primary drops to the gateway sharing the 2.5. Everything is wide open on that side of my net. I can expand this to 5 gigabit reasonably cheap if it works well. 

2 of my nodes have 10gigabit nics but they won’t pull more the a gig

I’ve made a bunch of post about what I’m doing with my public ygg node, on the forums 
https://forum.threefold.io/t/yggdrasil-nodes/2795/14

**Comment by Parkers145** [comment]
As for where I’m running my gateways, I’m just getting started and I’m a paramedic so it’s no data center but it’s reliable, now that I’m done messing with it. 

I have a fiber to the home drop with the neighborhood head conveniently in my backyard, 99% of my drop is protected coiled in my attic. It is overhead for about 12 feet. 

The primary gateway is bgw-320 serving a public subnet of 5 addresses, the nodes and a home router, though I mostly use cellular for personal. 

22~ feet of cat 6 in wall the office, about 5’ wall to node, 6 drops 2 from the home router, 4 from the gateway. 

There’s a helium miner on the net, striped honeysuckle trout,

I’m down to harden it as much as needed. I could bring in a cellular gateway, or a second gigabit line on cable. I plan to build it out definitely an opportunity 
![9D2B43B0-B505-4986-899E-C6C119E22D98](https://user-images.githubusercontent.com/44621168/167819796-2928037f-9eb4-4725-a6cd-09a193d14d2b.jpeg)
![6CFCD8E9-C86E-40D9-9E83-E151CE35174E](https://user-images.githubusercontent.com/44621168/167819807-a06008e5-1043-47db-8e8e-547cb096a11a.jpeg)
![01DF4F51-E160-4604-992E-6CCBE43E69FA](https://user-images.githubusercontent.com/44621168/167819816-5e764c5f-3056-4825-bf69-c69a44a41f6a.jpeg)
![4A2F48E3-B9EE-4B1E-B222-797E4556BAA8](https://user-images.githubusercontent.com/44621168/167819819-abb1dea2-a0eb-43b3-88a4-01644914505b.jpeg)
![46624764-D950-44A8-B185-683546DA886D](https://user-images.githubusercontent.com/44621168/167819829-ecc0f978-238f-4dc3-9701-d80191ca43db.jpeg)
![0EC36A2B-F3CA-45CB-8AFD-221C233C363A](https://user-images.githubusercontent.com/44621168/167819831-52489e21-4787-48f3-91b1-ec16263957fc.jpeg)
![4D6E227D-EA5C-4A71-9DB4-8D2D0BB792DD](https://user-images.githubusercontent.com/44621168/167819837-bed0ac3d-61a7-4ad0-9c97-847a2352ca52.jpeg)

the network stuff looks a little different now but that’s the idea :)

**Comment by Parkers145** [comment]
Last post, sorry the adhd is in full force, that top 1u, i purpose built to function in a “router” capacity. It’s running a e3-1225, 32 gb of ram and an intel qat card, it’s been a side project of mine for awhile it has 6x 10gb nics and the boards are cheap.  The quick assist card is supposed to be able to do vpn offloading at 20 gb/s and I can swap it for a 100gb card, I think it could be used in this this role aswell, no idea how to make it work though. Hence why it’s node now

i would be open to discussing ways to better this setup. I have a great site, I’m the property owner, there’s Atleast 6300 down/5300 up bandwidth potential. Power is 8 cents per hour. Wanting to put in Solar if I can afford it easy net zero.

**Comment by Parkers145** [comment]
its late i hope this is right. 

![image](https://user-images.githubusercontent.com/44621168/167990151-3f6a4fea-2d64-4a79-9ecf-c8a948ee0d2f.png)

also I’m 12 hops from vienna1 at 134ms and 19 hops from lochrist at 154ms

**Comment by coesensbert** [comment]
Hi @Parkers145 , thanks for your extensive reply.
For now we would prefer to go with data center operated nodes due to reliability. We added your peers to our monitoring and if they appear stable over time we will add them to the list. Thanks for you enthusiasm and effort!

**Comment by Parkers145** [comment]
Copy that sir, now it’s a mission 😂
