### ISSUE TITLE
Present hardware details on the ZOS-console

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/zos#1682]
Can we use a small portion of the ZOS console to represent the installed resources?
![image](https://user-images.githubusercontent.com/13766992/167240939-c879a89f-3c8a-4a8f-809e-1be7b8d01caf.png)

I guess this is simple as we do represent percentages of usage of these resources, why not add the quantity asl well 

CPU [available/reserved] : 8/1 etc...

**Comment by muhamadazmy** [comment]
Can you be more specific about the `installed` resources? The idea is that a farmer shouldn't care or worry about what kind of capacity is used by users. But he can still know how many and what contracts are active on his node by checking the block-chain. (get active contracts on a specific node id). But this won't expose the actual workloads (vms, disks, zdbs, etc...) that are actually being used by those contracts.

Hence we think showing utilization of the node is actually better for the farmer (he can tell how heavily his node is used)
