### ISSUE TITLE
support signing strategy of polka extension

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/zos#1683]
I suggest we support [`<Bytes>$data</Bytes>`](https://github.com/polkadot-js/extension/pull/743) for ease of use. I was suggesting we do it implicitly trying to verify against data expecting the polka extension wrapped data and we fail back to the current verification mechanism, @muhamadazmy is suggesting storing that with a flag in the deployment.

**Comment by muhamadazmy** [comment]
I like things to be more explicit. `trying` to do something then `trying` to do something else is imho not explicit enough. We instead can add a flag `signature-type` on the the deployment (which also should be included in the signature hash) that then instruct zos to which format of the $data is hashed. if it's just `$data` or `<Bytes>$data</Bytes>`

Can you be explicit also what the `$data` here refer to? is it the `Challenge` or the `ChallengeHash`

**Comment by sameh-farouk** [comment]
> I was suggesting we do it implicitly trying to verify against data expecting the polka extension wrapped data and we fail back to the current verification mechanism.

+1

verify in Polkadot done by
- first, detect whether the message is wrapped or not, then try to verify the signature, if it didn't match then
- wrap the message if it wasn't wrapped, or
- unwrap the message if it is already wrapped
- then it tries one more time to verify.

https://github.com/polkadot-js/common/blob/3597a4eb4e0cf9985104568058c5cd23701bbaed/packages/util-crypto/src/signature/verify.ts#L97-L107

**Comment by sameh-farouk** [comment]
> Can you be explicit also what the `$data` here refer to? is it the `Challenge` or the `ChallengeHash`

it is the ChallengeHash

I can see this happens here:
https://github.com/threefoldtech/grid3_client_ts/blob/49f54b36a4267d7dc42fbfbe49084b41dbd13a2e/src/zos/deployment.ts#L94-L99

**Comment by muhamadazmy** [comment]
This is already available on devent (by #1685) can you let me know if this works now as expected. Note that you need to set a new flag on the signing requirements as here https://github.com/threefoldtech/zos/pull/1685/files#diff-0a4e4eed3135a62c73cdb0bbf6f8992bf8d797ee12e4c2c9992177e4f5b458d1R245

**Comment by AhmedHanafy725** [comment]
I was trying to verify this issue, but I got `failed to verify signature` when signing with polkadot extension

challenge hash: `dc15904c5f84d7b0f7b03732ac65bad2`
address: `5DVBMsUfxwFm36ykq6s6zTQa3Mf1HcpkK3i2zAhystvdbCXR`
keypairType: `ed25519`
signature: 
```
fb425cf41c94771d6a5000afc8666bd70f784c9b006c52ff4d9b511f59da777ed809460ad8af3d2030f461de12ffce6f4fac9fe4ff5de9dc8fbb5ae9798c5f0b
```
payload: 
```
{"version":0,"twin_id":83,"expiration":0,"metadata":"{'testVMs': true}","description":"test deploying VMs via ts grid3 client","workloads":[{"version":0,"name":"wedDisk","type":"zmount","data":{"size":8589934592},"metadata":"{'testVMs': true}","description":"test deploying VMs via ts grid3 client"},{"version":0,"name":"wedtest","type":"network","data":{"subnet":"10.249.2.0/24","ip_range":"10.249.0.0/16","wireguard_private_key":"SdF7nq9zOxJlwYP+QRuytY78LDUxYVkgUHvAd0mRinA=","wireguard_listen_port":3254,"peers":[]},"metadata":"{'testVMs': true}","description":"test deploying VMs via ts grid3 client"},{"version":0,"name":"testvm","type":"zmachine","data":{"flist":"https://hub.grid.tf/tf-official-apps/base:latest.flist","network":{"public_ip":"","interfaces":[{"network":"wedtest","ip":"10.249.2.2"}],"planetary":true},"size":0,"compute_capacity":{"cpu":1,"memory":2147483648},"mounts":[{"name":"wedDisk","mountpoint":"/testdisk"}],"entrypoint":"/sbin/zinit init","env":{"SSH_KEY":"ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMUv2EQUnLL/Ei2+JRR/8EFIOrMxmlVLIc7psOZau6FE engm5081@gmail.com"},"corex":false},"metadata":"{'testVMs': true}","description":"test deploying VMs via ts grid3 client"}],"signature_requirement":{"requests":[{"twin_id":83,"required":false,"weight":1}],"signatures":[{"twin_id":83,"signature":"fb425cf41c94771d6a5000afc8666bd70f784c9b006c52ff4d9b511f59da777ed809460ad8af3d2030f461de12ffce6f4fac9fe4ff5de9dc8fbb5ae9798c5f0b","signature_type":"ed25519"}],"signature_style":"polka-wallet","weight_required":1}}
```

**Comment by muhamadazmy** [comment]
Okay, I think the problem is that you didn't include the `signature_style` in the challenge before signing. 
Please fix this in the type script code and try again.

For reference
https://github.com/threefoldtech/zos/blob/main/pkg/gridtypes/deployment.go#L260

**Comment by AhmedHanafy725** [comment]
**Verified**
Polkadot extension works with hex-encoded hash only, so after this PR #1703, it worked well.

![extension](https://user-images.githubusercontent.com/41957921/168776885-f1280345-a9a7-4d34-9b75-4bc7b7c3e3b5.gif)
