### ISSUE TITLE
Deployment Failure with error no space left on device

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/zos#1688]
After i approved a deployment request from the owncloud requests page the status changed to `deploying` and after a while it changed to `Apply_Failure` producing this error.

![image](https://user-images.githubusercontent.com/101194226/167608428-ca5a2741-1016-4f33-82f1-4516813e82e0.png)

![image](https://user-images.githubusercontent.com/101194226/167608371-b7233298-32de-4861-9bd7-558c50800c95.png)

```
Error: error waiting deployment: workload 0 failed within deployment 4439 with error no space left on device
```

**Comment by sameh-farouk** [comment]
@OmarElawady can you give us a hint about the cause of this error, it was returned by the new version 0.1.29 of Terraform's grid plugin. from the logs, the deployer tries 10 times until now with the same error.
```
Error: error waiting deployment: workload 0 failed within deployment 4428 with error no space left on device

Error: error waiting deployment: workload 0 failed within deployment 4429 with error no space left on device

Error: error waiting deployment: workload 0 failed within deployment 4430 with error no space left on device

Error: error waiting deployment: workload 0 failed within deployment 4431 with error no space left on device

Error: error waiting deployment: workload 0 failed within deployment 4432 with error no space left on device

Error: error waiting deployment: workload 0 failed within deployment 4436 with error no space left on device

Error: error waiting deployment: workload 0 failed within deployment 4437 with error no space left on device

Error: error waiting deployment: workload 0 failed within deployment 4438 with error no space left on device

Error: error waiting deployment: workload 0 failed within deployment 4439 with error no space left on device
```

**Comment by sameh-farouk** [comment]
still debugging this. can reproduce also in the play.dev (weblets). it is not directly related to the Owncloud-Deployer. @muhamadazmy debugging this from the node side. will update the issue when I have more input.

**Comment by sameh-farouk** [comment]
Turn out to be a  ZOS bug. so I'm transferring this issue to the ZOS repo, for tracking and verification. from the Owncloud-Deployer side, the issue will be resolved by itself eventually as soon as the zos fix is pushed to testent.
