### ISSUE TITLE
Multiple public nodes causes inconsistent chain state which causes the deployments to regularly fail

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/zos#1696]
terraform interacts with only one public node. But when the deployment arrives to zos, sometimes it doesn't find the deployment and fails with the error `workload 0 failed within deployment 1414 with error failed to get deployment contract: contract not found: object not found`. This may be caused by the zos node querying a different node which is not in sync with the latest in the node the terraform interacts with. Should zos query all the nodes or is there a time bound after which it's guaranteed that all nodes have a block recorded that terraform should wait before submitting the deployment?

**Comment by muhamadazmy** [comment]
Which environment is this. On production we found a node that was lagging behind (many days) and caused all kind of problems when zos lands on it by accident.

I am wondering if other public nodes might have the same issue on other networks.

Anyway, there was a fix (13th May) that will make zos only accept nodes that can be max of 2 blocks behind. Can you verify if this is still an issue after this fix?

**Comment by OmarElawady** [comment]
It's mainnet, this is the main [issue](https://github.com/threefoldtech/terraform-provider-grid/issues/235) in terraform. Will make a go script to test this.
