### ISSUE TITLE
ro mount of flist failed: exit status 1

### ISSUE THREAD

**Issue by archit3kt** [threefoldtech/zos#1697]
Hi,

I tried three times a typical 1 vCPU 2 GB RAM terraform deployment of the flist tf-official-vms/ubuntu-20.04-lts.flist on my testnet node 95

It is failing with this error

> Error: error waiting deployment: workload 0 failed within deployment 4794 with error failed to mount flist: 489-4794-tfnode1_test: ro mount of flist failed: exit status 1

Was working great two days before :(

main.tf file 

```
terraform {
  required_providers {
    grid = {
      source = "threefoldtech/grid"
    }
  }
}

provider "grid" {
    mnemonics = "" 
    network = "test"
}

resource "grid_network" "netk8s1" {
    nodes = [95]
    ip_range = "10.13.0.0/16"
    name = "netk8s1"
    description = "selfHosting k8s VM network"
    add_wg_access = true
}

resource "grid_deployment" "t3k8s" {
  node = 95
  network_name = grid_network.netk8s1.name
  ip_range = grid_network.netk8s1.nodes_ip_range["95"]
  disks {
    name = "rootFS"
    size = 40
  }
  vms {
    name = "tfnode1_test"
    flist = "https://hub.grid.tf/tf-official-vms/ubuntu-20.04-lts.flist"
    cpu = 1
    publicip6 = false
    planetary = false
    memory = 1024
    entrypoint = "/init.sh"
    rootfs_size = 0
    mounts {
      disk_name = "rootFS"
      mount_point = "/mnt/nonUsedMountToCopyRootFileSystemTo"
    }
    env_vars = {
      SSH_KEY = "ssh-rsa myKey"
    }
  }
}
```

**Comment by muhamadazmy** [comment]
Can u provide a screenshot of logs view `Alt+f2`

**Comment by archit3kt** [comment]
I launched a new deployment to get fresh logs

![Capture](https://user-images.githubusercontent.com/32200831/168155950-d9cb04ef-f54c-4136-936b-1958f71b72a1.PNG)

![Capture2](https://user-images.githubusercontent.com/32200831/168155994-6cd3ba8b-69af-4296-ae16-f020af72bced.PNG)

**Comment by sameh-farouk** [comment]
+1 I started to see this error for the first time on May 12, when deploying Owncloud using terraform.
deployment will succeed eventually after a couple of retries.

[main.tf file](https://github.com/threefoldtech/owncloud_deployer/blob/main/docker/tf_source_module/main.tf)

**Comment by muhamadazmy** [comment]
@sameh-farouk can you provide a node id where this fails on one of our farms so I can investigate deeper ?

**Comment by muhamadazmy** [comment]
Also @archit3kt i see from your node public logs the node can not use of of the node disks /dev/sdc because it already has a filesystem
![image](https://user-images.githubusercontent.com/10920323/168536823-91e7a167-b4ad-4deb-9495-29077625266d.png)

**Comment by muhamadazmy** [comment]
@sameh-farouk the only change I see around this time in storage is regarding virtual-disks allocation. But i can't see how this might affect flist functionality. Anyway, can you tell me when node id has the issue. Better a node on our farms so I can actually lock inside.
