### ISSUE TITLE
Upgrade and lifetime procedures for zosv2 binaries

### ISSUE THREAD

**Issue by delandtj** [threefoldtech/zos#170]
We need to come up with a proper lifetime definition and accordance with the web-served image for booting the nodes.
Basically, even when live-upgrading binaries in zos, there needs to be :
  - a global state for all binaries, with one version (or a list of compatible versions)
  - the served 0-OS (uefi) image needs to follow that versioning, checking necessary migrations along the way until all migrations are done before getting to a 'ready' state.
  - also figure out __where__ we 'install' (or overwrite) binaries, with their migration scripts? tools?

- [x] Specifications
- [x] Data migration support in daemons
- [x] Bootstrap

**Comment by zaibon** [comment]
Current status is:
- We have a single 0-OS image that is updated manually by triggering a new build whenever we feel like it
- The live-upgrading is done using upgraded ([see doc](https://github.com/threefoldtech/zosv2/tree/master/docs/upgrade)) and we have a development version of the "upgrade server" at https://versions.dev.grid.tf. This server list all the available version and detail of the flist to use to apply the upgrade

Now with what we have at the moment there is already multiple issues:
1. there is no synchronization between the version publish for upgraded and the 0-OS images
2. If there are some migration steps to be done, only the live-upgrade currently support it. There is nothing in place in the 0-OS images that allow to do any migration.
3. As new version are published and if we don't creates more recent images, the time to apply all update at boot will become more and more long. 
4. If we always starts from an old 0-OS image and redo the full incremental update, we will try to redo the same data migration multiple time, which will eventually create a disaster...

**Comment by muhamadazmy** [comment]
## How about we do this

- 0-OS official image should has no binary, only the absolute necessary plus the `upgraded` daemon (or some sort of other bootstrap daemon), may be also `networkd` so machine can connect to the internet.
- On boot, the upgraded will always have to download latest binaries from the official releases (in sort of a manifest file) it has to always get the latest. binaries, and only store them in the tmpfs (in memory) no persistence.
- The image (and upgraded) should not care about the data migration, it's up to the  daemons themselves to be support older versions of their own data. if an older version format is found on disk, it can update the data to newer version. It means that daemons must keep track of an object schema version in the data itself.
- The upgrade server `versions.dev.grid.tf` should have a manifest of the latest binaries to download, hashes, links to binaries, etc... so `zos` on boot can download the manifest, followed by the needed binaries (all binaries), zinit config files and then validate them before starting the services.
- This will make it easy to have local mirrors to `versions.dev.grid.tf` and even local mirrors in the data center so we don't have to go over the main mirror everytime. 
- An automated mirror update can be scheduled to make sure the local mirror is uptodate with the source.

**Comment by zaibon** [comment]
This is a nice idea. But at the end we have the same problem as we have now for both the networkd and upgraded. So if there is an upgrade of the networkd for example, the image won't have the proper version, we are in the same situation as now, no ?

**Comment by muhamadazmy** [comment]
Well, true, but I also said this can be another bootstrap daemon/script to take care of initial boot, later on once the system is fully booted, updgraded can take care of the system make sure it's always up to date. But the bootstrap util can be very simple because it will just pull, and verify the latest manifest and make sure services are monitored by zinit.

**Comment by zaibon** [comment]
fixed in #208
