### ISSUE TITLE
Uptime reporting violation created by node

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#1713]
Farmer did not mint tokens for node 2634 on mainnet for the April period. @LeeSmet checked and noted an uptime violation for this node. The farmer has several other nodes with the same hardware config which minted normally. Opening this issue to track any investigation and discussion of why Zos might produce this behavior.

**Comment by muhamadazmy** [comment]
@LeeSmet can you explain what kind of uptime violation was detected ?

**Comment by scottyeager** [comment]
The minting code compares the timestamp delta to the uptime delta to detect violations. So, if the node reports more accumulated uptime than the elapsed time since the last uptime report, that's a violation.

**Comment by scottyeager** [comment]
Farmer reports that this node did not mint again for May. @LeeSmet can you check if it was an uptime violation again?

**Comment by LeeSmet** [comment]
Yeah another violation. To give an example, for the one detected now:

In block 1,817,281, the node reports an uptime of 1,094,689 seconds at block timestamp 1,651,690,050.
In block 1,817,282, the node reports an uptime of 1,094,688 seconds at block timestamp 1,817,282,056.

As you can see, even though the chain advanced 6 seconds, the uptime of the node supposedly decreased by 1 second. This is then assumed to indicate a node rebooted in the minting code (after all, that is the only valid way a node uptime can decrease). Then, it is checked that the reported uptime is less than the difference in time between the report and the previous (6 seconds here). As the node HAS to have rebooted after the previous ping, and therefore can't have an uptime greater than the time delta.

**Comment by scottyeager** [comment]
Nodes should only report uptime every two hours, or maybe sooner if they did reboot. But never twice in two subsequent blocks. Assuming that `/proc/uptime` is behaving properly (i.e. returning monotonically increasing values), I suspect something like this is happening:

1. Zos begins writing uptime X to TF Chain
2. For some reason, a second attempt to write uptime is initiated, now with uptime X + 1
3. The second attempt is successful and uptime X + 1 is recorded at block height Y
4. The first attempt is also successful and now uptime X is recorded at block height Y + 1

We have two reports of this behavior on one system, but no known reports on any other systems. The cause then could be some quirk (partial failure?) on that specific hardware.

**Comment by scottyeager** [comment]
Seems resolved, since no violations were reported for any nodes in June. Closing this issue, discussion continued in #1754.
