### ISSUE TITLE
Adding more Terraform gateways

### ISSUE THREAD

**Issue by Zurga** [threefoldtech/zos#1718]
Often, the gateway will timeout while deploying. 

We (GreenEdge) have recently added more IPv4 addresses to the Grid, so it should be possible to add more gateways.

**Comment by Zurga** [comment]
We added more gateways, but I am still getting these time-outs: 
```
│ Error: error waiting deployment: couldn't get twin public key: dial tcp 185.206.122.74:443: i/o timeout
```

**Comment by muhamadazmy** [comment]
This IP is actually the IP for tfchain.grid.tf. That is the blockchain itself. and seems for some reason the node can not reach it while this is mandatory for healthy ZOS operation.

This can also be duo some grid failure at the time, I would say try again see if you still have the same issue

**Comment by LeeSmet** [comment]
Public nodes show no drop in connections since the last 7 days according to the monitoring

**Comment by ramezsaeed** [comment]
@OmarElawady @muhamadazmy 
please check if we can close this.
