### ISSUE TITLE
node 74 on test net failed to mount flist

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/zos#1732]
tried several times to deploy discourse flist https://hub.grid.tf/rafybenjamin.3bot/threefolddev-discourse-v4.0.flist on node 74 on test net and got this error 
![Screenshot from 2022-06-08 13-24-29](https://user-images.githubusercontent.com/32527347/172643910-90f98e8e-cc2c-4fcd-bd00-513e48e45184.png)

the same flist deployed and worked successfully on node 1 at the test net. also, another flist deployed on node 74 and worked

**Comment by coesensbert** [comment]
https://github.com/threefoldtech/grid_weblets/issues/753#issuecomment-1154933218

**Comment by muhamadazmy** [comment]
@coesensbert what was the state of the node? is this still an issue ?

**Comment by muhamadazmy** [comment]
Seems it's working fine now!

**Comment by coesensbert** [comment]
> 

all resolved, thanks!
