### ISSUE TITLE
Nodes stop reporting uptime after an error

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/zos#1745]
Example: node 415 on production

The node had a failure to report uptime on Tuesday 14th of june, 3:50 AM  CEST. After this, no more uptime reports were send to the chain. There are multiple nodes with active workloads ( so we know the node is up ), which are reported to be down as they don't send uptime events anymore. Note that this node still sends capacity reports.

Since the minting checks for uptime events, these nodes will be considered down if they don't send a new report before the minting period ends.

**Comment by muhamadazmy** [comment]
The node seems to be pushing uptime now. I will close this issue but please reopen if it happens again.
