### ISSUE TITLE
Zos should not complete boot without virtualization enabled

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#1751]
Farmers have reported seeing the following errors when attempting to make deployments on their own nodes:

![image](https://user-images.githubusercontent.com/17682591/174691197-2bf59900-f47f-4617-b684-d55961656d57.png)

![image](https://user-images.githubusercontent.com/17682591/174691281-0b4df16c-9648-4f4e-921e-8d80a23f62a8.png)

In both cases, the issue was resolved by changing mainboard settings to enable virtualization.

Since nodes in this state can effectively not perform any useful work, I think they should not complete booting and start farming tokens. Better to throw an error during the boot process so farmer can resolve from the start.

**Comment by Nelson361** [comment]
This issue probably is present is a very large percentage of the online 3nodes.  It would appear that by default virtualization or SVM is only on by default in commercial servers and Intel NUCs. In my farm none of the Lenovo mini PC's or my towers can deploy a VM.  If this patch is done abruptly, I would guess a third of the network will go offline.
