### ISSUE TITLE
SSD sometimes changes to HDD while node is running

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#1769]
Farmers occasionally [report](https://forum.threefold.io/t/ssd-miraculously-moves-from-sru-to-hru/3099) that SSD which was properly detected at boot is later labeled as HDD by Zos. Usually rebooting corrects the issue, but farmers then receive incorrect rewards for the entire period.

I would think this should not be possible due to https://github.com/threefoldtech/zos/issues/1644, but I can't verify that the change to persist seektime was implemented and deployed to mainnet.

**Comment by muhamadazmy** [comment]
The persisted seektime is already available on mainnet. Can I have the node ids that had this issues? How do the farmer find out that the ssds are detected as hdd?

**Comment by scottyeager** [comment]
That was on node 2098. Farmer noticed coincidentally while checking public ip config in the explorer. Possibly the change happened a while ago before seek time persistence was implemented.
