### ISSUE TITLE
The node got stuck after rebooting.

### ISSUE THREAD

**Issue by shng4you** [threefoldtech/zos#1772]
The node is running well(node id 1477), but unfortunately, after rebooting, the node got stuck here.
![image](https://user-images.githubusercontent.com/95933607/179982608-2b446d27-d369-4a2e-801a-04afd21573cb.png)

**Comment by muhamadazmy** [comment]
Wow, that's a panic. It's not stuck! It's dead! 
- How much memory does this node has?
- Was there any changes to the node hardware? (attached new device or replaced something?
- What is the boot method to zos?
- Have you tried restarting the node?

**Comment by teis-e** [comment]
Hello @muhamadazmy,

The processor was the issue for this node, but i got another problem.
![download](https://user-images.githubusercontent.com/89307927/180777668-43760421-e2e3-48d2-adf2-1b8726171d3b.png)


This node has 0 error in the manegament log, the other one did (CPU error).
