### ISSUE TITLE
ZOS detected one of the disks as hdd instead of ssd

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/zos#1780]
Node 4127, see https://github.com/threefoldtech/tf_support/issues/356

**Comment by muhamadazmy** [comment]
Was the node updated? by the time of writing this comment the node still has ~4T of SSD and ~1T of HDD. Note that zos only detect disk speed on boot onetime. It doesn't rely on what the disk report as a type instead it does speed tests. It's possible that the disk is too slow or of bad quality even if it's an SSD that it will be considered as HDD

**Comment by sabrinasadik** [comment]
2nd user with similar issue.

Farm ID 138 - Clubbing bear

Node 2293 had 0HDD and 2.48TB SSD. After reboot he suddenly got a different node id (4296) with 2TB HDD and 480.07 GB SSD.

**Comment by sabrinasadik** [comment]
We asked the user of farm 138 to reboot which he did. Now Node 2293 is back online, with the right amount of HDD and SSD. Very strange behavior. Please investigate.

**Comment by muhamadazmy** [comment]
@sabrinasadik i will.

What i think might have happened is that 
- nodes was running already before the storage fix (to only detect disks on boot)
- then at some point the bad detection happened
- then the node got the fix, and now it stuck was latest speed tests values.
- after rebooting, the node re-detected the speed correctly, and now it's persisted and should remain.

I will still investigate what might have went wrong

**Comment by sabrinasadik** [comment]
Any updates?

**Comment by scottyeager** [comment]
Anecdotally, I see reports of this from time to time. They always clear with a reboot and don't seem to recur. I'll document further cases here if I see them.

**Comment by scottyeager** [comment]
Here's a new case, node id 3755 on mainnet. This one is not clearing with reboot. We can see the the farmer minted for last month with the properly detected specs:

![image](https://user-images.githubusercontent.com/17682591/195939193-83ba4407-bbc9-4c07-b1cc-4a7b1cc2c932.png)

But now part of the SSD is showing as HDD in the explorer (verified this against grid proxy too):

![image](https://user-images.githubusercontent.com/17682591/195939410-0276d492-3def-41bb-95f9-5d0efd1e98a1.png)

It sounds like this happened while the node was online. Double checking that with the farmer and will update here.

**Comment by TullysInc** [comment]
Yes @scottyeager  - it appears to have occurred while the node was online.
 
Quoting the user:
"Yes it happened when it was powered on because that's when I restarted it thinking that would fix the issue, I hope it's not because of the 2.5 SSDs because all my other node have m.2 NVMe and those don't have any issue"
