### ISSUE TITLE
substrate-client integration tests

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#1783]
Changes on the grid types always break the code of the client (specially the get operations) so we need some integration tests that we can run against any environment to do "get" on all types.

**Comment by xmonader** [comment]
can this be a good issue for interns to workon?

**Comment by muhamadazmy** [comment]
I was rethinking this one actually. The main problem is that sometimes types changes on the grid but because the changes don't reflect in the data structures in this repo it keeps building but fails to decode the structures. So we actually need 2 things here:
- Generation of types from the grid metadata 
- Basic integration tests for all the getters functions to make sure Get operations won't fail. This won't be easy also because u won't grantee that an object with specific id exists on the grid (deleted by owner, etc...) and we shouldn't mock the grid (won't be easy anyway) 
  - what about extrinsics ?

IMHO. what the interns can do is basically generating Go types from substrate metadata. I actually don't know if something like that already exists (it exists for rust) so may be researching should be part of the job.

**Comment by muhamadazmy** [comment]
The actual issue is here https://github.com/threefoldtech/substrate-client/issues/35

**Comment by muhamadazmy** [comment]
@xmonader can u assign to Eslam please, i don't know her github user.
