### ISSUE TITLE
Nodes don’t recover from network outage

### ISSUE THREAD

**Issue by Parkers145** [threefoldtech/zos#1791]
Had an isp failure that caused my network to be down nearly 20 hours.

of my 6 nodes 4 of them were unable to recover on their own once connection was restored 

nodes that didn’t recover 

dev 
45&49

test
219

main
3049 

the non recovered nodes showed this 
![EECA5945-C41C-420F-951A-5DDDED9FA14A](https://user-images.githubusercontent.com/44621168/187704025-88e794b4-3160-4797-8442-877d6c6cdcde.jpeg)

the nodes that did  recover
222, 2914

showed this 
![7A86B66B-FA98-4904-9C17-B670FBAACCA0](https://user-images.githubusercontent.com/44621168/187704209-f0ca35a9-500c-4289-815c-d528f61c0731.jpeg)

notably both 2914&222 are my most modern nodes. And the nodes that didn’t recover were my older nodes generations wise. 2914/222 are uefi, the others are bios. 

Rebooting resolved the issue.

**Comment by muhamadazmy** [comment]
Thank you for reporting this. I will see what i can do.

**Comment by muhamadazmy** [comment]
@Parkers145 one question. When the network was back How long did you leave the nodes running before deciding to reboot? I can see that the nodes renew their dhcp lease every 1 hour anyway.

**Comment by Parkers145** [comment]
About 30 minutes, the one that recovered renewed its. Dhcp lease be
Normally that ones that Did just kept panicking
