### ISSUE TITLE
Node stopped sending uptime reports, "has panicked"

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#1803]
My node 3995 on mainnet stopped sending uptime reports a few days ago. Everything looks normal on the main console screen, but I see the errors below on the log screen:

![image](https://user-images.githubusercontent.com/17682591/191401146-8b6d7472-35f1-4fcd-81a6-038b5512c78b.png)

**Comment by scottyeager** [comment]
Another report here: https://github.com/threefoldtech/test_feedback/issues/296

**Comment by muhamadazmy** [comment]
This error actually means that uptime reported failed to collect some data from other internal services on time. So the problem actually resides somewhere else. (mostly identityd) 
I will see if i can find any useful logs to figure out why this is happening

**Comment by muhamadazmy** [comment]
I am just wondering if you tried restarting the node.

**Comment by muhamadazmy** [comment]
Should be fixed in release `v3.2.1`
