### ISSUE TITLE
storaged fails test with iLO virtual media attached

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#1809]
I have an HPE server with iLO 4, on which I tried booting Zos via a "virtual media" network attached USB image. It gets stuck at the storaged/test step:

![image](https://user-images.githubusercontent.com/17682591/194624916-99b56c3c-5118-4971-985c-3e3b7302c1ff.png)

As soon as I eject the virtual drive, the node continues booting normally. No problem, of course, there are other ways to boot a node. Just documenting the behavior in case it does warrant further investigation.

**Comment by delandtj** [comment]
hum... we wouldneed to see in the logs.. can you tell what node that is ?

**Comment by scottyeager** [comment]
Node id is 3995 on mainnet.
