### ISSUE TITLE
workload fails on node reboot 

### ISSUE THREAD

**Issue by Parkers145** [threefoldtech/zos#1823]
![image](https://user-images.githubusercontent.com/44621168/196057993-f40a4a6f-72d9-4c57-973d-036013b5f370.png)
![image](https://user-images.githubusercontent.com/44621168/196058019-f3f63c51-c007-4f08-aef9-e7fd1d2db1c0.png)

was on node 219, cockpit rc2 image with the switch to network manager preformed whitch is why suspect this happened. its still up but this appears to be unrecoverable. really just reporting for documentation sake, this is definitely a issue with my image not necessarily zos.

**Comment by xmonader** [comment]
can you please let us know which env this is running on?

**Comment by Parkers145** [comment]
> can you please let us know which env this is running on?

 The deployment was on 22.1 kinetic kudu, with notable changes of an nginx install and migration from networkd-> network manager. And cockpit. 
 
https://forum.threefold.io/t/cockpit-managed-vm-flist-release/3398

**Comment by muhamadazmy** [comment]
May I ask why do you need to switch to NetworkManager on this workload ? ZOS passes static network config to the node over cloud-init hence switching to NetworkManager is not supported from our side. There is nothing we can do for this. I suggest we close the issue. 

If you have the same issue with a standard VM image you can reopen

**Comment by Parkers145** [comment]
> May I ask why do you need to switch to NetworkManager on this workload ? ZOS passes static network config to the node over cloud-init hence switching to NetworkManager is not supported from our side. There is nothing we can do for this. I suggest we close the issue. 
> 
> 
> 
> If you have the same issue with a standard VM image you can reopen

It's nessecary to make the cockpit image work, that means the entire cockpit project has been pointless from the start if there's no way for that to be compatible. Would of been nice to shut that too have been mentioned somewhere in any of the posts I've made about this on the forums.

**Comment by scottyeager** [comment]
Reopening this, since I couldn't reproduce simply by switching a deployment to use Network Manager. To clarify, all VMs in question were booted successfully with networkd the first time, then the configuration was migrated to Network Manager. Such VMs survived reboots of the VM and the node in my tests, with fully functional networks.

The issue that remains here is why these VMs ended up in a state where the (testnet) playground finds no IP addresses for them and they can no longer be reached, after the node rebooted.

**Comment by muhamadazmy** [comment]
I think this was related to https://github.com/threefoldtech/zos/issues/1874 but now since this one is closed, we can close this one again
