### ISSUE TITLE
network: see how we are going to manage the listen port of the wireguard interface for exit points

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#183]

**Comment by zaibon** [comment]
Lacking other better ideas I'll add a list of used port in the information the node publish to the BCDB.
So user/tool creating TNo can check that information and try to pick a unused port. 
This will still eventually lead to conflict if 2 user/tool pick the same port, but I don't see a way out at the moment

**Comment by delandtj** [comment]
either way, the in use ports for wireguard will need to be registered somehow, be it in a normally connected node or one with a public namespace:

```sh
~ # ip netns exec public ash
~ # ss -ulpn 
State     Recv-Q      Send-Q            Local Address:Port           Peer Address:Port     
UNCONN    0           0                       0.0.0.0:1600                0.0.0.0:*        
UNCONN    0           0                          [::]:1600                   [::]:*        

```
and 

```
~ # ss -ulpn
State     Recv-Q     Send-Q            Local Address:Port            Peer Address:Port     
UNCONN    0          0                       0.0.0.0:58273                0.0.0.0:*        
UNCONN    0          0                          [::]:58273                   [::]:*        
```

**Comment by delandtj** [comment]
come to think of it :
same old , same old, use uint6 with prefix nibbles of NR 
et hop !

**Comment by zaibon** [comment]
That solves all our problem, wonderful !
