### ISSUE TITLE
Full nodes (reserved) - real node disk capacity displays as not available do deploy (testnet)

### ISSUE THREAD

**Issue by s-areal** [threefoldtech/zos#1836]
Unfortunately I could not create a VM with all the resources. I tried to add a disk (please confirm that when you add a disk on the disks tab it will utilize HDD space instead of SSD) but every time i chose a disk of 500GB or even 200GB out of 2TB available, the system wouldn’t let me do it “saying” that the resources were not available.

**Comment by AhmedHanafy725** [comment]
The disk added from disks tab is SSD disk, so if the node doesn't have enough SSD storage, it won't deploy the vm on this node.

**Comment by s-areal** [comment]
Thanks for your reply but I am not sure if I was clear enough.
It is not possible to add the available HDD resource from the disk tab (now that you confirm it). When you try to add the disk, (any capacity) I get the error message that "Node(191) might be down or doesn't have enough resources."
After adding HDD capacity, its impossible to deploy anymore the VM.
Several other issues as you will see, I'm on testnet

https://user-images.githubusercontent.com/49781569/201473574-cbe191b6-f697-4d22-9d95-91cdf10b9743.mp4

**Comment by xmonader** [comment]
- Only SSD is allowed as Disks
- For HDD is only utilized through ZDBs
- If you replaced the disk storage, the node comes back with a new identity
- If you added a new physical disk, that doesn't mean you can have a disk spanning multiple physical disks https://github.com/threefoldtech/zos/issues/1830
- keep in mind the zos reserves 100GB ssd as well

**Comment by s-areal** [comment]
Would be good that this kind of info would be included in the interface as info notes so UX would be improved.
Still don't know how to use the disk space. Not the right place for support (I am aware of that) but don't have a clue what ZDBs is and could not find it in documentation.
![Captura de ecrã 2022-11-19, às 01 08 05](https://user-images.githubusercontent.com/49781569/202826588-3a0ec46f-0231-45d6-9798-14efc53e5651.png)

**Comment by Parkers145** [comment]
> Would be good that this kind of info would be included in the interface as info notes so UX would be improved.
> 
> Still don't know how to use the disk space. Not the right place for support (I am aware of that) but don't have a clue what ZDBs is and could not find it in documentation.
> 
> ![Captura de ecrã 2022-11-19, às 01 08 05](https://user-images.githubusercontent.com/49781569/202826588-3a0ec46f-0231-45d6-9798-14efc53e5651.png)
> 
> 
> 
> 

Hey Simao, 

Here's the info that you need, 

As of right now there isn't any solutions that allow for deployment of hdd space on the testnet playground (though I did notice an update I haven't explored). Zdbs and qsfs file systems are seperate deployments from your vm in the eyes of the grid and these are currently only deployable one terraform. 

So the trouble your running into, that the disks deployed through the playground all represent ssd storage only, your node has a 500gb ssd, and 100gb belongs to zos, so you have just under 400gb of deployable space via the playground. 

That probably sounds disappointing but this is where architecture becomes really important, you will want to use the ssd storage for the os storage of your deployment, and attach disks to it utilizing the hdd space. 

This is doable today, but you'll have to get into deploying with terraform, here is the documentation you will need for that, 

[Terraform Tutorial](https://forum.threefold.io/t/terraform-guide-for-grid-deployments/3525/7)

[Terraform Wiki](https://library.threefold.me/info/manual/#/manual3_iac/grid3_terraform/manual__terraform_readme)

There is also documentation available on the individual storage protocols it's just a bit deeper right now. 

[zero file system](https://github.com/threefoldtech/0-fs)

[zero database](https://github.com/threefoldtech/0-db)

[zero database file system](https://github.com/threefoldtech/0-db-fs)

[zero stor](https://github.com/threefoldtech/0-stor_v2)

[quantum safe file system](https://github.com/threefoldtech/quantum-storage)
