### ISSUE TITLE
Node reported an impossible timestamp

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/zos#1841]
User didn't receive any TFT for his node minting last month

Node id: 2992
Farm id: 33
Wallet address: GCCREPBLPLYQNKWTP4KIXYNUXU7KJMBSNDMR7Q6TE22LCFWTTXLBBDXG

According to Lee, there might be a bug in zos which reflects an impossible timestamp.

See issue https://github.com/threefoldtech/tf_support/issues/398

**Comment by muhamadazmy** [comment]
Check progress on the original tf_support issue https://github.com/threefoldtech/tf_support/issues/398

**Comment by muhamadazmy** [comment]
Not zos issue. the farmer backed up his node so at some point there were 2 nodes running with the same identity
