### ISSUE TITLE
Coupling  the `tls_passthrough` option with the type of the service protocol.

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/zos#1842]
In the current implementation of our gird gateways, I noticed that we are configuring a TCP service in Traefik routes in case of `tls_passthrough` is enabled (this allows you to proxy any TCP-based service, not just HTTP), otherwise, we configure an HTTP service.

This (inconsistency) raises a few questions:
- Why do we support TCP proxy only when tls_passthourgh is enabled?
https://github.com/threefoldtech/zos/blob/11516d751fe9cd69b46a3b548361452dda555982/pkg/gateway/gateway.go#L605-L609
- Why we are hiding the fact that by enabling `tcp_passthrough` we are proxy to any TCP service, by forcing the user to include `https` as a schema although **the schema has no effects** (aside from the (unnecessary) validation in zos, the schema is not used anywhere else, we use only the host part)?
https://github.com/threefoldtech/zos/blob/11516d751fe9cd69b46a3b548361452dda555982/pkg/gateway/gateway.go#L574-L576
https://github.com/threefoldtech/zos/blob/a5793cb13d6d9aa51f13b2872544212de795f727/pkg/gateway/gateway.go#L577-L579

IMHO, there is no reason for **coupling** the `tls_passthrough` option with the type of service protocol (TCP, HTTP). instead, we could have an extra flag, say `tcp_prxoy`, to enable Using TCP as the service protocol independently from the way encrypted traffic is handled (by passthrough, or offloading). regarding the validation, in case `tcp_proxy` is enabled the schema must be empty, otherwise, it should be one of HTTP, or HTTPS.

We need to support these scenarios:
  - I  have an HTTP service running in my backend
    - `tcp_prxoy` = false

  - I  have something like an FTP service (non-HTTP service) running in my backend
    - `tcp_prxoy` = true

  - For any of the services above I can do TLS passthrough and handle the encrypted traffic on my server, or opt-in to decrypt the data with a gateway. 
    - `tls_passthrough` could be `true` or `false` regardless of the service protocol set by the `tcp_proxy`  flag. 

In this way, the behavior of the gateway is more defined and easier to reason about.

**Comment by muhamadazmy** [comment]
We agreed not to do this atm. the changes in the PR are enough for now
