### ISSUE TITLE
Upgrade Yggdrasil client in ZOS to 0.4.7

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/zos#1846]
Some improvements have been made that might improve [the current Yggdrasil issues](https://github.com/threefoldtech/test_feedback/issues/367):

https://github.com/yggdrasil-network/yggdrasil-go/releases/tag/v0.4.7

> Buffers are now reused in the router for DHT and path traffic, which improves overall routing throughput and reduces memory allocations

**Comment by xmonader** [comment]
comments from azmy:
- needs to then test it still work fine when he uses this version with zos
- so he must first run zos in his vm
- then replace the binary
- restart ygg
- then test all connectivity over ygg still working fine
