### ISSUE TITLE
Uptime reporting occasionally lags

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/zos#1856]
Sometimes (rarely) a node will report an uptime which is lower than expected. After investigating such an example, it seems that the node actually reports the uptime as expected (+7200) but almost 10 minutes too late. The node in question has node id 79

| block | block timestamp | uptime|
| --- | --- | --- |
| 3,531,317 | 1661988198 | 20020668 |
| 3,532,613 | 1661995974 | 20027874 |
| 3,533,814 | 1662003180 | 20035650 |

Notice that the difference in timestamp between the first 2 blocks is 7776, whereas the difference in uptime is 7206. The uptime difference is expected (back in august/september uptime was reported every 2 hours, + 6 second block time which can happen), yet for some reason the extrinsic only arrived 9 and a half minutes after the uptime was retrieved. Between block 2 and 3 we see the expected difference in block timestamp (7206, again 2 hours between reports + some allowed difference because blockchain), yet this time uptime is advanced by 7776 (to account for the earlier delay). The minting did allow this because the specific checks for this drift were disabled, but these will be enabled again, which would mean the node would not have gotten tokens.

Additionally, here was no extraordinary activity on the chain around this time, so its not a case of blocks being full. Also blocks have been created properly every 6 seconds during this timeframe.

**Comment by LeeSmet** [comment]
Other node with this problem: 4200. graphql query to get 3 uptime events which are not in line:

```graphql
query MyQuery {
  uptimeEvents(where: {nodeID_eq: 4200, timestamp_gte: "1666599918", timestamp_lte: "1666844640"}, orderBy: timestamp_DESC) {
    uptime
    timestamp
  }
}
```

The 2nd data point reports considerably less uptime compared to increase in timestamp (-1999 seconds), the third (newest) compared to the second reports a bit more uptime compared to timestamp difference (+303 seconds).

Additionally, this node seems to have other instances of this occurring more recently. Of particular instance is this event:

```graphql
query MyQuery {
  uptimeEvents(where: {nodeID_eq: 4200, timestamp_gte: "1669545036", timestamp_lte: "1669553322"}, orderBy: timestamp_DESC) {
    uptime
    timestamp
  }
}
```

where the third (newest) event actually has a positive drift (uptime increases more than timestamp) of 367 seconds, without a significant prior negative drift.

**Comment by muhamadazmy** [comment]
@LeeSmet is this still an issue?

**Comment by LeeSmet** [comment]
Last month there was a node which reported the same uptime twice a couple of seconds apart (this node had similar issues in january):

```
{
  "data": {
    "uptimeEvents": [
      {
        "nodeID": 3237,
        "timestamp": "1673847018",
        "uptime": "2775"
      },
      {
        "nodeID": 3237,
        "timestamp": "1673844612",
        "uptime": "360"
      },
      {
        "nodeID": 3237,
        "timestamp": "1673844606",
        "uptime": "360"
      },
      {
        "nodeID": 3237,
        "timestamp": "1673830500",
        "uptime": "7532"
      }
    ]
  }
}
```

There was a similar issue for a node in january:

```
{
  "data": {
    "uptimeEvents": [
      {
        "nodeID": 303,
        "timestamp": "1673639388",
        "uptime": "14784567"
      },
      {
        "nodeID": 303,
        "timestamp": "1673636982",
        "uptime": "14782155"
      },
      {
        "nodeID": 303,
        "timestamp": "1673636976",
        "uptime": "14782155"
      }
    ]
  }
}
```

Similar issue in January for node 1474

**Comment by muhamadazmy** [comment]
Since there was some work around uptime (regarding to power mgmt) we can may be move this to next release and see if it's still reproducable. 

Because from the code I can only image that this is possible if:
- There are 2 instances of the `noded` daemon running on the same node. This was possible in a very old version of zinit hence a solution might be to restart the node
- There are 2 nodes running with the same ID. (Can happen if a farmer missed a backup and ended up running 2 nodes with the same backup)

**Comment by muhamadazmy** [comment]
zos only report UPTIME it doesn't send the timestamp. The timestamp is inserted by the chain itself. If he node failed to report uptime, it does not try again with the same uptime value, instead it fetches a new value for uptime before it tries again.

So it does not make sense that 2 uptime reports are reported by the node at 2 separate timestamps which means that the node  "retried" with the same value for the uptime.

The low level client (substarte-client) can retry on its own if (and only if) an error `ErrIsUsurped` is returned by the chain. can this cause this ?

**Comment by LeeSmet** [comment]
FWIW, in march, nodes 322,409,451,461 had uptime issues (the one reported in the original post, with lagging uptime). Only checked until 600

**Comment by LeeSmet** [comment]
After checking there are a couple of nodes which still exhibit this problem. One where it is very clear is `4667`, uptime events from graphql for the last incident (22nd of april):

```
{
        "nodeID": 4667,
        "timestamp": "1682130306",
        "uptime": "9195932"
      },
      {
        "nodeID": 4667,
        "timestamp": "1682127900",
        "uptime": "9193526"
      },
      {
        "nodeID": 4667,
        "timestamp": "1682125494",
        "uptime": "9190155"
      },
      {
        "nodeID": 4667,
        "timestamp": "1682121378",
        "uptime": "9187004"
      },
      {
        "nodeID": 4667,
        "timestamp": "1682118972",
        "uptime": "9184598"
      },
```

which essentially means:

| timestamp | timestamp delta | uptime | uptime delta |
| --- | --- | --- | --- |
| 1682130306 | 2406 | 9195932 | 2406 |
| 1682127900 | 2406 | 9193526 | 3371 |
| 1682125494 | 4116 | 9190155 | 3151 |
| 1682121378 | 2406 | 9187004 | 2406 |
| 1682118972 | - | 9184598 | - |

The timestamp jumps forward by roughly 16 minutes more than uptime. then increases normally again (40min intervals)

Note that this node has a lot of incidents like this over the past moth. Also there are other nodes which exhibit similar though maybe not as extreme issues.

**Comment by muhamadazmy** [comment]
I think i finally found a potential cause for that issue

![image](https://user-images.githubusercontent.com/10920323/234556538-992bc431-be86-4411-969a-9336502d9522.png)


By investigating the log around the uptime anomaly I found that the `client` itself if can't manage to establish a connection to substrate retries multiple times until it give up. 

The problem is this retries to connect happens after the uptime is already fetched, hence the uptime reported with all the accomulated delays

There is also something weird in the logs, it looks like at some point it took 10min for the connection to return a timeout error

**Comment by muhamadazmy** [comment]
Hence the fix can be done by fetching the uptime only after a successful substrate  connection has been established

**Comment by muhamadazmy** [comment]
Potential fix https://github.com/threefoldtech/zos/pull/1956

**Comment by muhamadazmy** [comment]
after the deployment of the fix above, we can close this for now, and we can reopen if it happens again
