### ISSUE TITLE
detection of wol support on BIOS

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#1860]
Wake on lan has to be supported and enabled by the BIOS/motherboard for power management feature to work. The problem is this need to be enabled and supported by 2 parts 
- Network card (nic)
- Motherboard (BIOS)

From the system it's easy to check support of the NIC and enable/disable it when needed. But unfortunately it's not possible for the BIOS. Until the creation of this issue i didn't find a way to check bios support and if it's enabled. if no way this can be detected, the entire power management feature has to be an opt-in feature, meaning the farmer has to choose if he wants it enabled for his nodes or not.

**Comment by muhamadazmy** [comment]
## Support a `power.mgmt=1` flag to cmdline
This is the most solid and easier implementation, for the following reason:
- Farmer has to choose explicitly on the bootstrap.grid.tf that he wants to opt in.
- There is no runtime switching on/off of the flag (not straight forward to implement)
- To enable this farmer will be forced to download the most recent zos image which has latest zinit with shutdown support. Only farmers who know what they are doing AND want this feature will do so.

**Comment by muhamadazmy** [comment]
## Support `PowerMgmt: bool` flag on the Node object on the chain
- This one does not require reboot of the node. Although old nodes won't have latest `zinit` with `shutdown` (we instead can do sleep)
- Farmer will have to enable this for each node from the dashboard 
- If farmer enable this while his node has no support for WOL the node can power off with no way to bring it up again. This is of course is also possible with the cmdline flag as well but will be harder to enable this by mistake since it needs more work from the farmer to enable power management.

**Comment by muhamadazmy** [comment]
@despiegk @delandtj @xmonader 
Please i need input on this

**Comment by xmonader** [comment]
I think option 1 is more appropriate, farmers with just one node won't be needing the power management feature, those who have bigger farms & affected by the energy bills will be more experienced and I believe it's acceptable to do a little manual work in that case

**Comment by delandtj** [comment]
just commandline is more than enough for now

**Comment by maxux** [comment]
As far as I know, if `ethtool` reports `Wake-On` active, then it's enabled by BIOS, so if it's not, the farmer have to enable it, we can't do anything against that :/

**Comment by muhamadazmy** [comment]
Actually no, Wake-On reported by ehtool report and enable/disable this for the nic itself. And it can be suported by the nic but not the BIOS.
