### ISSUE TITLE
Extra namespaces in QSFS zdb, doesn't decommission on destroy

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#1861]
I've deployed the latest QSFS example with no changes to the default values, on testnet. I noticed when inspecting the created zdb that there are additional namespaces beyond those used in my deployment. After I destroyed the deployment, the zdb is still available. I've queried contracts associated with my twin and don't see any that could correspond to the zdb deployment. Is it possible that I'm somehow using a zdb deployed by another user?

Before destroying:
```
> redis-cli -h 300:9fab:2cda:749d:aa8e:43c:aeee:dfef -p 9900

> NSLIST
 1) "default"
 2) "647-10987-meta1"
 3) "647-10987-meta2"
 4) "647-10987-meta3"
 5) "647-10987-meta4"
 6) "647-10987-data1"
 7) "647-10987-data2"
 8) "647-10987-data3"
 9) "647-10987-data4"
10) "647-10987-data5"
11) "647-10987-data6"
12) "647-10987-data7"
13) "647-10987-data8"
14) "647-10987-data9"
15) "647-10987-data10"
16) "647-10987-data11"
17) "647-10987-data12"
18) "647-10987-data13"
19) "647-10987-data14"
20) "647-10987-data15"
21) "647-10987-data16"
22) "647-10987-data17"
23) "647-10987-data18"
24) "647-10987-data19"
25) "647-10987-data20"
26) "81-11081-meta1"
27) "81-11081-meta2"
28) "81-11081-meta3"
29) "81-11081-meta4"
30) "81-11081-data1"
31) "81-11081-data2"
32) "81-11081-data3"
33) "81-11081-data4"
```

After destroying:
```
> NSLIST

 1) "default"
 2) "647-10987-meta1"
 3) "647-10987-meta2"
 4) "647-10987-meta3"
 5) "647-10987-meta4"
 6) "647-10987-data1"
 7) "647-10987-data2"
 8) "647-10987-data3"
 9) "647-10987-data4"
10) "647-10987-data5"
11) "647-10987-data6"
12) "647-10987-data7"
13) "647-10987-data8"
14) "647-10987-data9"
15) "647-10987-data10"
16) "647-10987-data11"
17) "647-10987-data12"
18) "647-10987-data13"
19) "647-10987-data14"
20) "647-10987-data15"
21) "647-10987-data16"
22) "647-10987-data17"
23) "647-10987-data18"
24) "647-10987-data19"
25) "647-10987-data20"
```

**Comment by AhmedHanafy725** [comment]
every node has one zdb instance only and when you create a zdb workload, it will just add a namespace for you on this zdb instance, and deletion will remove this namespace

**Comment by scottyeager** [comment]
Thanks for the explanation @AhmedHanafy725. Feels to me like this should be more isolated, but that's an issue for Zos.

**Comment by muhamadazmy** [comment]
It's not a ZOS issue. ZOS hosts zdb instances, which by default allow you to do some read-only operations (like listing namespaces) but you can't read or write to those namespaces without authentication. 

In other words you can "list" the name spaces available on any zdb node so you only see their names, BUT you can't access them. this is how zdb works. Hence i close this as a non-issue.
