### ISSUE TITLE
Nodes have ips they shouldnt 

### ISSUE THREAD

**Issue by Parkers145** [threefoldtech/zos#1869]
opening at the request of jan he saw my picture and said that ZOS shouldnt have an ipv6 address, on all of my node it has a /128 and a /64
![IMG-6749](https://user-images.githubusercontent.com/44621168/208539431-f3861ca0-083f-495e-ba56-c574fe8a4275.jpg)
![IMG-6748](https://user-images.githubusercontent.com/44621168/208539433-a1d9995a-d2b8-4aee-ac4b-5f7d1797c29a.jpg)
![IMG-6747](https://user-images.githubusercontent.com/44621168/208539434-383048ae-59b8-49bb-82d0-5b63d42237e9.jpg)
![IMG-6746](https://user-images.githubusercontent.com/44621168/208539436-d7163d31-da93-45e3-99f4-fc0f591fcc43.jpg)
![IMG-6744](https://user-images.githubusercontent.com/44621168/208539437-894af5fc-ba39-4205-ba31-8ebffe60e591.jpg)
![IMG-6743](https://user-images.githubusercontent.com/44621168/208539438-a56e9d88-f102-4fbd-84e0-605e6f202372.jpg)

**Comment by delandtj** [comment]
can you elaborate on that a little?
That is ; a little napkin drawing of your physical network layout and eventual switch/router config

**Comment by Parkers145** [comment]
![image](https://user-images.githubusercontent.com/44621168/209847051-270b8fc0-cf1b-4734-9600-063d270f1198.png)






         IPV4 WAN CONFIG

  WAN IPV4 Address: 104.15.48.92
  WAN IPV4 Gateway 104.15.48.1
  Primary DNS Server 68.94.156.9
  Secondary DNS Server 68.94.157.9


          IPV6 WAN CONFIG

   Global Unicast IPv6 Address	2001:506:7c1e:11a::1
   Link Local Address	fe80::de8d:8aff:fec0:b8c1
   Default IPv6 Gateway Address	fe80::2d0:f6ff:fe17:9388

          DHCP COFIG

   Device IPv4 Address	192.168.1.254
   DHCPv4 Netmask	255.255.255.0
   DHCP Server	On
   DHCPv4 Start Address	192.168.1.64
   DHCPv4 End Address	192.168.1.253
   DHCP Leases Available	295
   DHCP Leases Allocated	20
   DHCP Primary Pool	Private
   Secondary Subnet	Enabled
   Public Subnet	162.205.240.128/25
   Public Subnet Gateway 162.205.240.254

         IPV6 LAN CONFIG

   Global Unicast IPv6 Address	2600:1700:c1e0:1150::1
   Link-local IPv6 Address	fe80::de8d:8aff:fec0:b8c2
   IPv6 Addressing Subnet (including length)	2600:1700:c1e0:1150::/64
   IPv6 Delegated Prefix Subnet (including length)	2600:1700:c1e0:115f::/64
   
		 Switch Config 
   Uplink- Port Type Access, Vlan 1 
   Nodes- Port Type Access, Vlan 1, Edged Port

**Comment by Parkers145** [comment]
I cannot change any configuration on the ISP Gateway, But I am able to use IP passthrough and Cascaded router with it.

**Comment by Parkers145** [comment]
I believe I have finally located the issue that I have THOUGHT was incompatibility between my switch and 5gbaset. but, after borrowing a cable tester from a local friend i found that my in wall cat 6a run had a single pair that was not functioning properly. 


Heres the behavior i had 

intermittent speed degradation, this is what really threw me off because sometimes i got the full speed. 

slow dhcp aquisition 

slow RA aquisition. 

Some equipment would only make 100 mbit links 

ultimate purchasing my mikrotik gear is what gave me enough info to finally find the issue as that gear absolutely refused to show more then 100mbit link when everything else was claiming to have full link speed. going to do more test to verify today, but hopefully this resolves the rest of my issues with my pub addresses.

**Comment by muhamadazmy** [comment]
@Parkers145 any updates on this? can we close it ?

**Comment by rkhamis** [comment]
@Parkers145 please reopen if you still have an issue
