### ISSUE TITLE
remove public uplink persistence

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#1872]
After a discussion with @delandtj we found that persisting what uplink is used by the public bridge `br-pub` on a node is not a good idea. Since a node can be booted first time with no ipv6 hence the node is assumed to be a `single` setup node.  But later once ipv6 is available, the node will always remember it's a single setup node even after a reboot. 

A fix for this issue is never persist, once Ipv6 is available for the node the node MUST be rebooted to come up with proper setup.

**Comment by A-Harby** [comment]
> A fix for this issue is never persist, once Ipv6 is available for the node the node MUST be rebooted to come up with proper setup.

Closing the issue
