### ISSUE TITLE
Node that was up now failing to boot 

### ISSUE THREAD

**Issue by Parkers145** [threefoldtech/zos#1874]
At approximate 1000am central time us today I noticed that node 219 on test net was running abnormally. It had ramped up to a full tilt fan speed beckoning my attention. 

When I hooked up a monitor I found it rebooting, knowing this shouldnt happen I interrupted the boot and went Ilo where it passed hardware diagnostics and all network connections tested fine. 

Now, I returned to so where it downloads the image and goes through the boot process normally. But once booted I get this 

![A035DCB3-D433-48A4-88C1-0A12657B7720](https://user-images.githubusercontent.com/44621168/210273909-fa031174-56d3-4f36-b642-5ca58aeaea73.jpeg)

it seems to be failing to download a file nessecary for the boot process, I am out of local troubleshooting steps can anyone here advise? 

This is node 219 on test net and until today it’s worked beautifully hosting all of the threefoldcloud sites like mastadon and peertube. Getting this back up would be amazing

**Comment by Parkers145** [comment]
Did a whole lot of trouble shooting here and identified the root cause(s) of the issue, But now im stuck as the node is up, but the workloads that were on the node have lost their public ip address. 

Eventual possible causes that i identifed 
- ram issue ( one time got a proc 1 dimm 1 error)
- SSD issue, The nvme drive was running hot. 
- nic issue, the network care was at times showing a pci bus failure. 

given the first symptom i replaced the nic 

and this got the node back to booting, but i suspect it was the long period spent off that caused this to happen. after a period of time the node would now have consistent pci related failures but this is also where it saw the memory error. 

so i replaced cpu 1 dimm 1. 

this had the same affect as the nic, short term return of performance, but pci bus errors still. 

So i monitored the ssd and came to the conclusion it was overheating. So i swapped it into a pci e enclosure with a better heatsink. 

this where i am now. the node now seems to have returned to full function but i have 3 workloads that have lost their public ips and their planetary network addresses. 

this is the console of the node 
![image](https://user-images.githubusercontent.com/44621168/210285035-ad6b86ff-793b-477a-877c-d32f9c33c3fe.png)

this is my playground
![image](https://user-images.githubusercontent.com/44621168/210285069-b22716cd-5a82-4214-af74-fd568387674b.png)

the json from a deployment 
```
{
    "version": 0,
    "contractId": 15314,
    "nodeId": 219,
    "name": "Music",
    "created": 1672696062,
    "status": "error",
    "message": "could not get public ip config: public ip workload is not okay",
    "flist": "https://hub.grid.tf/tf-official-vms/ubuntu-20.04-lts.flist",
    "publicIP": {
        "ip": "",
        "ip6": "",
        "gateway": ""
    },
    "planetary": "",
    "interfaces": [
        {
            "network": "NW3ea9ad82",
            "ip": "10.20.2.2"
        }
    ],
    "capacity": {
        "cpu": 4,
        "memory": 2048
    },
    "mounts": [
        {
            "name": "DISKdeedaa1f",
            "mountPoint": "/",
            "size": 107374182400,
            "state": "ok",
            "message": ""
        }
    ],
    "env": {
        "SSH_KEY": "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFqf0+CsLH41KOlxesTlTkZRghWm4nEkHL9448XDa1HW parker@smithtac"
    },
    "entrypoint": "/init.sh",
    "metadata": "{\"type\":\"vm\",\"name\":\"Music\",\"projectName\":\"Fullvm\"}",
    "description": "",
    "corex": false
}
```

**Comment by Parkers145** [comment]
cliff notes where im at, 

- node is up and stable after correcting overheat issue, replacing a stick of ram, reseating cpu, reapplying thermal paste to cpu, running diagnostics, passing said diagnostics 
- 3 workloads have lost their ips 
- the nodes ipv4 gateway address is pingable  
- the nodes ipv6 gateway address is pingable

**Comment by Parkers145** [comment]
# Timeline 

How the failure occured 
- 1000 AM node shuts down due to unkown cause, 
- node reboots i was home so i went into ILO and checked health says all is well 
- Console Check reveals traefik Error
	
First Solution
- Replaced Nic
	- node comes back up, but workloads are missing ips and node crashes after short time
	- node produces processor 1 Dimm 1 Memory Error 
	- node produces embedded pci device 2 error
		- Ambient temps were higher then normal upon inspection nvme temps high but stable in safe range
		
Second solution 
- reseat memory modules, put heat sink on nvme, 
	- No errors on boot, stable multiple hours. 
	- tcp handler upgrade errors begin 
![image](https://user-images.githubusercontent.com/44621168/210305250-bf3ad90d-05ac-4920-8ea7-f901d03faa45.png)

	- check node nic config, verify with a set of the set of the correct nic. 

![image](https://user-images.githubusercontent.com/44621168/210305076-bbfa43ec-06d4-4dd0-bdd6-ffdd2933a595.png)


```
root@SmithTac:/mnt/c/Users/ParkerS/documents/threefoldtools# ./admin network public-exit --node 219 get
{"level":"debug","url":"wss://tfchain.test.grid.tf/","time":"2023-01-02T22:48:15-06:00","message":"connecting"}
2023/01/02 22:48:15 Connecting to wss://tfchain.test.grid.tf/...
---
dual setup (enp3s0f1)
```

```
root@SmithTac:/mnt/c/Users/ParkerS/documents/threefoldtools# ./admin network public-exit --node 219 list
{"level":"debug","url":"wss://tfchain.test.grid.tf/","time":"2023-01-02T22:48:36-06:00","message":"connecting"}
2023/01/02 22:48:36 Connecting to wss://tfchain.test.grid.tf/...
---
- enp3s0f0: "14:58:d0:44:8d:48"
- enp3s0f1: "14:58:d0:44:8d:4c"
- zos: "14:58:d0:44:8d:48"
```
```
root@SmithTac:/mnt/c/Users/ParkerS/documents/threefoldtools# ./admin network public-exit --node 219 set enp3s0f1
{"level":"debug","url":"wss://tfchain.test.grid.tf/","time":"2023-01-02T22:49:29-06:00","message":"connecting"}
2023/01/02 22:49:29 Connecting to wss://tfchain.test.grid.tf/...

root@SmithTac:/mnt/c/Users/ParkerS/documents/threefoldtools# ./admin network public-exit --node 219 get
{"level":"debug","url":"wss://tfchain.test.grid.tf/","time":"2023-01-02T22:50:00-06:00","message":"connecting"}
2023/01/02 22:50:00 Connecting to wss://tfchain.test.grid.tf/...
---
dual setup (enp3s0f1)
```

	- Gateway ipv4 Address & domain deploys / ping able 
		
 ![image](https://user-images.githubusercontent.com/44621168/210303503-122b5082-2a5b-4baf-b549-55c80c947a12.png)

	- Gateway ipv6 address deploys / ping able 
	
![image](https://user-images.githubusercontent.com/44621168/210303547-28d84455-29b0-4970-9f8f-eb9de5c743eb.png)

	- workloads show this in json 

	- ```
		{
			"version": 0,
			"contractId": 15314,
			"nodeId": 219,
			"name": "Music",
			"created": 1672696062,
			"status": "error",
			"message": "could not get public ip config: public ip workload is not okay",
			"flist": "https://hub.grid.tf/tf-official-vms/ubuntu-20.04-lts.flist",
			"publicIP": {
				"ip": "",
				"ip6": "",
				"gateway": ""
			},
			"planetary": "",
			"interfaces": [
				{
					"network": "NW3ea9ad82",
					"ip": "10.20.2.2"
				}
			],
			"capacity": {
				"cpu": 4,
				"memory": 2048
			},
			"mounts": [
				{
					"name": "DISKdeedaa1f",
					"mountPoint": "/",
					"size": 107374182400,
					"state": "ok",
					"message": ""
				}
			],
			"env": {
				"SSH_KEY": "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFqf0+CsLH41KOlxesTlTkZRghWm4nEkHL9448XDa1HW parker@smithtac"
			},
			"entrypoint": "/init.sh",
			"metadata": "{\"type\":\"vm\",\"name\":\"Music\",\"projectName\":\"Fullvm\"}",
			"description": "",
			"corex": false
		}
		```

Clearly the node has access to the public subnet for the gateway addresses to be working. but something is preventing the workloads from getting their addresses, so i considered the persistent storage of the public config sitution and since i wasnt sure if the ssd or nic was the actual culprit, i put the first nic back in. 

this resulted in going back to failing to boot, with Traefik error in the first post. i think this confirms my suspicion it was the failed part. but, im curious is these workloads might somehow still be looking for the first nic that died? 

- I did also attempt removing the manually configured ipv6 gateway address as ive been informed its unessecary

**Comment by Parkers145** [comment]
This node is continuing to have issues and now more memory errors I think this may be a hardware problem that has caused corruption of the OS. 

Node 3049 on main net started behaving this way today aswell and after digging into that it also seems to be having memory errors and has suddenly lost a fan, I’m not sure I can’t readily chalk both of them up to luck, but for now the nodes are off until I can do further repairs

**Comment by xmonader** [comment]
@muhamadazmy can you please check

**Comment by Parkers145** [comment]
> @muhamadazmy can you please check

Some new info, ram memtest for 16 hours on the node with no errors, 

Rebooted zos, 
ilo reported errors on 4 sticks, 

rebooted and re ran memtest, same result of pass 

Rebooted zos again, memory errors back 

Replaced 4 sticks of ram, 

Booted zos, node is working now. 

Any idea why zos is having errors that memtest can't replicate? I spoke with Bert and he said this isn't a new phenomenon with older nodes. For now everything seems to be working and it's deploying workloads with pub ip and the gateway ip is up 

Even after making it back to the functional state the workloads above never recovered, but another user did report his workloads recovering

**Comment by muhamadazmy** [comment]
Hey, sorry I am late to reply to this one. You did a great job investigating this issue and the way you stated the facts.

The only thing I noticed from above is that the VM error message is `"message": "could not get public ip config: public ip workload is not okay"` which means the VM couldn't deploy again because the public ip workload failed to deploy. 

Hence if you also get the json from the Public IP workload you will be able to see details of the error why the IP failed to deploy, which can give us an idea what have might went wrong !

**Comment by Parkers145** [comment]
Ill do one better i now have a live specimen that occurred without any associated hardware failure. I ended up replacing 6 total sticks of ram, all of it passed memtest, but fails in zos, but the node was up for atleast the last 7 days with no hardware errors from ILO. with that said today i opened playground and found this

![startstate](https://user-images.githubusercontent.com/44621168/215298632-1f30c307-a5cb-4f0e-bfe5-cbfc4d597fda.png)
```
{
    "version": 0,
    "contractId": 17768,
    "nodeId": 219,
    "name": "VM56919c91",
    "created": 1673951202,
    "status": "error",
    "message": "could not get public ip config: public ip workload is not okay",
    "flist": "https://hub.grid.tf/tf-official-vms/ubuntu-18.04-lts.flist",
    "publicIP": {
        "ip": "",
        "ip6": "",
        "gateway": ""
    },
    "planetary": "",
    "interfaces": [
        {
            "network": "NW1fcf5c01",
            "ip": "10.20.2.2"
        }
    ],
    "capacity": {
        "cpu": 4,
        "memory": 8192
    },
    "mounts": [
        {
            "name": "DISKf9b21b4b",
            "mountPoint": "/",
            "size": 53687091200,
            "state": "ok",
            "message": ""
        }
    ],
    "env": {
        "SSH_KEY": "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFqf0+CsLH41KOlxesTlTkZRghWm4nEkHL9448XDa1HW parker@smithtac"
    },
    "entrypoint": "/init.sh",
    "metadata": "{\"type\":\"vm\",\"name\":\"VM56919c91\",\"projectName\":\"Fullvm\"}",
    "description": "",
    "corex": false
}
```
this is the json from the deployment. 

i created a second deployment with that one still up as shown in the picture to show the node is working here's that json 

```
{
    "version": 0,
    "contractId": 17906,
    "nodeId": 219,
    "name": "VMf8b693f5",
    "created": 1674953674,
    "status": "ok",
    "message": "",
    "flist": "https://hub.grid.tf/tf-official-vms/ubuntu-18.04-lts.flist",
    "publicIP": {
        "ip": "162.205.240.136/25",
        "ip6": "2600:1700:c1e0:1150:c813:35ff:fe6b:9c17/64",
        "gateway": "162.205.240.254"
    },
    "planetary": "301:9970:5ee:bbce:c5e2:cabe:7e94:9f50",
    "interfaces": [
        {
            "network": "NW7b984332",
            "ip": "10.20.2.2"
        }
    ],
    "capacity": {
        "cpu": 4,
        "memory": 8192
    },
    "mounts": [
        {
            "name": "DISK13e28b24",
            "mountPoint": "/",
            "size": 53687091200,
            "state": "ok",
            "message": ""
        }
    ],
    "env": {
        "SSH_KEY": "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFqf0+CsLH41KOlxesTlTkZRghWm4nEkHL9448XDa1HW parker@smithtac"
    },
    "entrypoint": "/init.sh",
    "metadata": "{\"type\":\"vm\",\"name\":\"VMf8b693f5\",\"projectName\":\"Fullvm\"}",
    "description": "",
    "corex": false
}
```

heres what the nodes showing 
![IMG-6858](https://user-images.githubusercontent.com/44621168/215299348-a28a6458-720a-481a-bc52-1889ad48e9ef.jpg)
![IMG-6859](https://user-images.githubusercontent.com/44621168/215299349-834e607e-9da6-42df-877a-76fa9e277611.jpg)


here is my theory, my networks RA and dhcp are slow, its something ive been working on for awhile, ive watched the node reboot with workloads deployed before and im not sure it waits properly for the node to reconnect fully before trying to deploy its workloads? 

ive actually taken most of my nodes down as ive been trying to chase these bugs out of the network as this would be a terrible user experience and its something im not seeing on other farms. i have 128 ip addresses and a symmetrical 5 gig link available though so id really like to get it working properly

i really cant explain how my nodes sometimes have a bad public config.

**Comment by Parkers145** [comment]
Some network info is probably relevant so i took a look at dashboard and i found i have two contracts for public ipv4 that are not actually in use 

![downips](https://user-images.githubusercontent.com/44621168/215300074-6dbdc5ee-e36d-4051-b08d-1d2a48321474.png)

to verify these weren't just unpingable workloads i took a look at the gateway witch confirmed these ips aren't in use

![downiprouter](https://user-images.githubusercontent.com/44621168/215300105-48237ec3-6351-4196-a1fe-7f93338a793c.png)

the info from the dashboard 

<html>
<body>


162.205.240.134/25 | 162.205.240.254 | 17768 | Delete IP
-- | -- | -- | --
162.205.240.135/25 | 162.205.240.254 | 17889


</body>
</html>

this is how my network is configured 

![network configuration](https://user-images.githubusercontent.com/44621168/215300222-a17d59b4-5b88-4f8c-9313-89c4bd859ca0.png)

**Comment by Parkers145** [comment]
my nodes have ipv6s they apparently shouldnt?, this could be related? 

https://github.com/threefoldtech/zos/issues/1869

looking back this happened before, at this point i thought the cause was the vm, but the most recent one was a default 18.04 vm i accidentally deployed and never interacted with 

https://github.com/threefoldtech/zos/issues/1823

lastly the network card in these nodes was changed, prior to that i had no reliability issues, even after going back to the original network card, i have had intermittent issues every since. this issue was a different node but it has affected all my nodes at this point. 

https://github.com/threefoldtech/zos/issues/1817

**Comment by muhamadazmy** [comment]
I was able to fetch the change log of all the workloads on this contract and this is what i see 

First, this part (already from your screenshots) shows the reason why this VM failed
```
"result": {
      "created": 1673951202,
      "state": "error",
      "message": "could not get public ip config: public ip workload is not okay",
      "data": {
        "id": "667-17768-VM56919c91",
        "ip": "10.20.2.2",
        "ygg_ip": ""
      }
    }
```

It basically says, I need the `ip` workload `VM56919c91_pubip` but this workload has failed, hence I can't continue. so what we needed to find out is why this workload has failed. 

So by looking into the change log  and checked the IP workload 
```json
  {
    "version": 0,
    "name": "VM56919c91_pubip",
    "type": "ip",
    "data": {
      "v4": true,
      "v6": true
    },
    "metadata": "{\"type\":\"vm\",\"name\":\"VM56919c91\",\"projectName\":\"Fullvm\"}",
    "description": "",
    "result": {
      "created": 1673951202,
      "state": "error",
      "message": "could not look up ipv6 prefix: no public ipv6 found",
      "data": {
        "ip": "",
        "ip6": "",
        "gateway": ""
      }
    }
  }
```

The public ip has both `ipv4` ad `ipv6` enabled (so the Vm will get both) but it seems it has failed to "get" an ipv6 from SLAAC.

Since this happens only after a reboot. it indeed might been exactly as you suggested, a slow DHCP or RA because from what I see the node "now" is fully configured (network wise) hence creating another VM with similar config should work:

I will discuss with @delandtj what is the best solution for this, we can put some delays to wait for RA (until the node has Ipv6)

**Comment by muhamadazmy** [comment]
@Parkers145 I have a question. do you use the `admin` tool to change the network public exit device after the node is already booted?

**Comment by muhamadazmy** [comment]
So seem the node already tried to wait for ipv6 on boot but never got IPv6. 
![image](https://user-images.githubusercontent.com/10920323/215442629-45752ead-4f17-49c3-b6b6-f6ded1175a17.png)

but it obviously get it later but when it's already too late. How slow is RA ?

**Comment by Parkers145** [comment]
> @Parkers145 I have a question. do you use the `admin` tool to change the network public exit device after the node is already booted?

i had used it while the node was already up is that incorrect?


as for the RA time, Im not sure what it is, it is not a configurable option in my current gateway, i recently bought some new hardware, and im going to update this  [ issue ](https://github.com/threefoldtech/zos/issues/1869) with all the details so maybe we can figure out a best practice on setup in these situations, I worry alot about others workloads suffering these problems on my nodes and it reflecting poorly on the grid. 

apologies for the long reply time, i seem to have missed the notification on this one

**Comment by muhamadazmy** [comment]
@Parkers145 any update on this issue from your side?

**Comment by Parkers145** [comment]
From the tech perspective the node has been working great, and I’ve determined the loss of a workload will only occur after a prolonged down, I assume long enough there Router discarded the record. 

On the upgrading the network to address the ra issue… I have everything in place and bought one of these

https://amzn.to/3ItqZPR

haven’t actually deployed any of the new stuff yet, learning it first, I think we cad go ahead and close this issue since we now know this is a my network problem so it’s not stuck on the board waiting for me

**Comment by muhamadazmy** [comment]
Thank you
