### ISSUE TITLE
Cannot Deploy Public Addresses on Testnet, Workloads Down 

### ISSUE THREAD

**Issue by Parkers145** [threefoldtech/zos#1875]
# Suddenly Cannot Deploy Public Ipv4 Addresses On Testnet 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Had what I thought was an isolate node failure today, but after trouble shooting that most of the day, I found the issue may not be isolated as i am now unable to deploy address on any node on testnet. on the play ground i recieve this error with no capacity filter requirements other then ipv4 
![image](https://user-images.githubusercontent.com/44621168/210305702-d016aa80-11d9-467e-9353-5c6d7467b078.png)

The Explorer is showing no available addresses on most nodes, node 203 in the green edge shows 5 but playground says resource unavailable. my node should be showing about 10. 

![image](https://user-images.githubusercontent.com/44621168/210305731-1396582d-18a9-4f2a-9569-ac5ee877d422.png)

For reference this documented in the other [issue](https://github.com/threefoldtech/zos/issues/1874) i opened on my node specifically further but I have three workloads that failed to redeploy when my node restarted 

![image](https://user-images.githubusercontent.com/44621168/210305938-f96d7cb9-543b-461c-b43b-e77b883f185d.png)

and the details of one of their jsons is 

```
{
    "version": 0,
    "contractId": 15319,
    "nodeId": 219,
    "name": "VM5752cedf",
    "created": 1672696063,
    "status": "error",
    "message": "could not get public ip config: public ip workload is not okay",
    "flist": "https://hub.grid.tf/tf-official-vms/ubuntu-20.04-lts.flist",
    "publicIP": {
        "ip": "",
        "ip6": "",
        "gateway": ""
    },
    "planetary": "",
    "interfaces": [
        {
            "network": "NW0c883658",
            "ip": "10.20.2.2"
        }
    ],
    "capacity": {
        "cpu": 4,
        "memory": 8192
    },
    "mounts": [
        {
            "name": "DISK2c1916c7",
            "mountPoint": "/",
            "size": 322122547200,
            "state": "ok",
            "message": ""
        }
    ],
    "env": {
        "SSH_KEY": "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFqf0+CsLH41KOlxesTlTkZRghWm4nEkHL9448XDa1HW parker@smithtac"
    },
    "entrypoint": "/init.sh",
    "metadata": "{\"type\":\"vm\",\"name\":\"VM5752cedf\",\"projectName\":\"Fullvm\"}",
    "description": "",
    "corex": false
}

```

**Comment by despiegk** [comment]
@xmonader what is status here? its now open for 2 weeks, is it an issue, does it need to be resolved?

**Comment by xmonader** [comment]
Just deployed on testnet with a public IP
![image](https://user-images.githubusercontent.com/64129/213678110-5ecf9deb-5cd4-43e8-8cd1-58e0551263d8.png)

please reopen if still an issue
