### ISSUE TITLE
Node registration failed - can't reach geoip

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#1884]
A couple of [farmers](https://github.com/threefoldtech/tf_support/issues/422) have reported that their nodes show a registration failed error due to not reaching the geoip service. It seems this can also stop the node from reporting uptime and thus the farmer doesn't get paid. I'm not sure why only a few nodes would fail to reach geoip when the service is up and they are able to download Zos successfully.

I think reaching geoip should not be a blocker for a node to fully boot, report uptime, and accept workloads, especially if it has already registered a location previously.

![image](https://user-images.githubusercontent.com/17682591/211952137-d39641ab-a57d-485f-b81f-606f44a1192a.png)

**Comment by muhamadazmy** [comment]
Reaching the geoip is needed because that's what gives the node it's coordinates in the grid hence locaiton. This is why reaching the geoip is necessary. 

The weird thing is I never had any issue to reach geoip service BUT it's not the first time i see farmers complain about this. Can it be dns or location error ? where geoip IP address is not routed correctly to our services ?

This service is maintained by @maxux and @coesensbert I hope they have a better answer

**Comment by maxux** [comment]
I don't think geoip have any issue.

The main issue is probably the dns server not responding/resolving anything or internet not working. The first call made is probably the call to geoip and that one is reporting an error but it's not because geoip is not reachable. More investigation should be made node side regarding this.

**Comment by scottyeager** [comment]
We see two users in Turkey both experiencing this issue, so it looks like it could be related to national internet restrictions. Asking the farmers to try opening geoip in another device and will report back.

Update: farmer reports that they *are* able to reach geoip in their phone's browser on the same network.

**Comment by coesensbert** [comment]
The farmers update is in line with some of the DNS propagation checks we used, altough these are not really reliable nor consistent in their results.
Wanted to try to deploy some vm's in Turkey on the Grid to test ourselves. Found 2 nodes there but none work due to Yggdrasil issues.

geoip.grid.tf is also in our monitoring and was not reported as down the last few months.

**Comment by scottyeager** [comment]
DNS as the root cause makes sense. That would explain why another device within the same network is able to reach geoip—perhaps it is providing its own DNS configuration rather than relying on what the router provides. I'll see if the farmer I'm in contact with can provide some details about the DNS config on his router.

I see only one node online in Turkey right now. It took a deployment and I was able to `wget geoip.grid.tf` successfully. I guess that's no surprise though, since any node showing online is not experiencing this issue (maybe is using a different ISP).

**Comment by shng4you** [comment]
When the farmer is trying to access https://geoip.grid.tf/, he gets this error: {"address":"94.54.237.20","country_code":"TR","country_name":"Turkey","subdivision":"Istanbul","continent":"Asia","city_name":"Istanbul","latitude":41.0107,"longitude":28.9345,"source":"maxmind geolite2"}

**Comment by scottyeager** [comment]
That's actually not an error @shng4you. It's the data returned by the geoip service. So this is suggesting in another case that the farmer can reach geoip from another device inside their network.

As a troubleshooting exercise, I had one farmer affected by this issue try changing the DNS servers in their router. We only discovered as result that Google's public DNS servers are blocked in Turkey.

This farmer is able to reach geoip in his browser on his laptop which is taking its DNS servers from the router (we checked). I even ran `dig` on geoip from a VM in Turkey (these DNS servers don't respond to my home IP, and all of the DNS servers on the farmers router return a correct IP for geoip.

The node id for the one node I was able to deploy on in Turkey and test is 5168, if that's helpful for you @coesensbert.

**Comment by maxux** [comment]
It's not the first time Google DNS (or other well known) DNS server are blocked in some countries.
We were using a `ping 8.8.8.8` at some point to check when network were reachable and faces lot of issues with this solution. It's needed to use ISP DNS server :/

**Comment by coesensbert** [comment]
Thanks @scottyeager , that was the node indeed and was able to deploy on it a few hours later. Tried some dns and connectivity tests again, the node seems to be in Turkey indeed. I could not find anything that does not work related to this issue, even dnsperf showed no issues testing multiple known public dns servers. Also every response from geoip is fine and correct.

Reviewing one of the original tickets about this: https://github.com/threefoldtech/tf_support/issues/422#issuecomment-1400740377
Makes me suspect that the geoip failure is just a consequence of a local networking issue. In the screenshot there are lots of "reject NAK via .." errors which point to an issue with ip assignment for that client (zos). Seems related to dhcpd client-id, if true could explain why a mobile device does work with the same network/dhcp server (not dhcpd)

From dhpcpd.conf in ZOS:

```
# Use the hardware address of the interface for the Client ID.
#clientid
# or
# Use the same DUID + IAID as set in DHCPv6 for DHCPv4 ClientID as per RFC4361.
# Some non-RFC compliant DHCP servers do not reply with this set.
# In this case, comment out duid and enable clientid above.
duid
```

@mahendravarmayadala93 @TullysInc @sabrinasadik is communication still ongoing with farmer 423? Could we know what kind of dhcp/router he is running on that network? Maybe see his dhcp server config file? I saw online a few times that rebooting the router worked, but not always, has this been tested?

Found an older ticket that could create some better feedback in the ZOS cli dashboard, not only that geoip timed out: https://github.com/threefoldtech/zos/issues/1704

**Comment by TullysInc** [comment]
@coesensbert - we're currently in communication with the farmer, and from an overview of the on-going discussions we can't ascertain if rebooting the router has already been tested (but I assume at some point it should have been done). However, I will relay an attempt while we also gather additional intel on the dhcp/router and dhcp server config file.

Thanks for sharing your analysis.

**Comment by scottyeager** [comment]
Good catch @coesensbert. I also see this line on that image:

```
info ndmz default route missing, waking up dhcpcd
```

I wonder if Zos is trying to reach geoip over the ndmz interface. This could explain why Zos is able to boot (handled over Zos interface) then fails to reach geoip.

Farmer 423 has a modem/router combo from Netmaster like [this one](http://netmaster.com.tr/urun/9) (I am confirming the model number). DHCP config would just be a few options like client limit and lease time.

What's interesting to me is that another farmer in Turkey experiencing this issue sent a photo showing part of their router and it looks very similar. We didn't yet get a look at the full log screen in that case but I'll follow up. So the root cause might be something about the firmware running on these routers. That farmer also said they tried booting up their Titan nodes at three other locations with no success.

**Comment by coesensbert** [comment]
@TullysInc @scottyeager any updates on the modem/router combo from Netmaster ?

**Comment by scottyeager** [comment]
I checked in with farmer 423. He has a second router connected to the Netmaster, and the node boots fine when connected to the second router. Looks like there was no reply from the other farmer in Turkey who might have a Netmaster.

**Comment by coesensbert** [comment]
Ok thanks @scottyeager , so the conclusion can be it's a local issue with a specific router hardware brand/model?
We should still figure that out: https://github.com/threefoldtech/tf_support/issues/422

Ok to close this once? Since it's not an issue with the geoip or another backend service.

**Comment by scottyeager** [comment]
Summarizing what we know about this issue:

In early to mid January, two farmers in Turkey noticed that their nodes had been offline.

### Farmer 423
* Was using a modem/router combo from Netmaster and saw `dhcp reject NAK` errors in the logs
* Switching the node to a second router in the farmers network resolved the issue

### Farmer 1002
* Appeared to also be using the same Netmaster router (deduced just from a single photo based on the layout and coloring of ports and switches)
* Reported the Titan also didn't work at several other locations where they tested it
* This farmer has not responded, but I noticed that one of their nodes came back online so I've messaged them again to ask if they changed something

### Questions
1. Why can these nodes successfully `wget` Google or boot at all for that matter, but then fail to connect to GeoIP?
2. Why did this issue pop up for two farmers who appear to be using the same hardware at the same time, when the nodes were previously working on the same setup? Netmaster is a Turkish brand and we don't have too many farmers, so it seems likely that we heard from everyone farming with this model of router

This got me curious if something changed in Zos around this time that could have affected connectivity in these nodes. Indeed, there was a switch from `udhcpc` to `dhcpcd` in Zos [version 3.4](https://github.com/threefoldtech/zos/releases/tag/v3.4.0) in November. 

Thanks to @coesensbert's observation regarding the NAK errors and `dhcpcd.conf` above, I think the most likely root cause is that these routers don't work well with `dhcpcd` while they worked fine with `udhcpc`. This could also explain why the error only occurs after bootstrap is complete—the dhcp implementation in iPXE is also working with the router and failures begin after handing off to `dhcpcd`.

@muhamadazmy, do you agree with this assessment?

**Comment by maxux** [comment]
This is more likely a bad configuration in `dhcpcd.conf` than an incompatibility, dhcpcd is the most widely used dhcp client on Linux, udhcpc is really tiny but basic. Can we do some test on a specific node regarding this ?

**Comment by scottyeager** [comment]
@maxux, I am in contact with the owner of farm 423 and can arrange to do some tests. It's a certified node, so would need a signed bootloader.

**Comment by xmonader** [comment]
Closing as too old
