### ISSUE TITLE
validate a backend

### ISSUE THREAD

**Issue by rawdaGastan** [threefoldtech/zos#1886]
case: `ip:port` fails when validating a backend because it can't parse `ip:port` as a url 

![Screenshot from 2023-01-22 12-22-55](https://user-images.githubusercontent.com/47260239/213912339-6f88f60e-0ccb-4ad4-8b81-ae772b008f67.png)

example for `1.1.1.1:10`

![Screenshot from 2023-01-22 12-56-15](https://user-images.githubusercontent.com/47260239/213912375-c934915d-0291-4f1e-ba52-43a67c1ddb44.png)

**Comment by muhamadazmy** [comment]
When tls passthrough is enabled that backend must always be in the `ip:port` format. The `ip` must be a valid ip v4 or v6. it tls passthrough is must be a full url in the format `http://ip:port` also the ip part must be a valid ipv4 or v6.

**Comment by muhamadazmy** [comment]
Related to #1906

**Comment by xmonader** [comment]
@maayarosama please verify on devnet your issue no need to add `//` now to the url
