### ISSUE TITLE
use a list of geoip services in zos

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/zos#1887]
blocked on https://github.com/threefoldtech/tf_operations/issues/1374

related to https://github.com/threefoldtech/zos/issues/1884

**Comment by muhamadazmy** [comment]
https://github.com/threefoldtech/tf_support/issues/444#issuecomment-1493802378

**Comment by xmonader** [comment]
It's ongoing now to deploy more geoip instances https://github.com/threefoldtech/tf_operations/issues/1374#issuecomment-1604523903, will move back to accepted

**Comment by xmonader** [comment]
actually moving to 3.12 now

**Comment by muhamadazmy** [comment]
@rawdaGastan any update on this, the list of extra geoip services are available for a while now.

**Comment by coesensbert** [comment]
https://docs.grid.tf/threefold/itenv_threefold_main/src/branch/master/Grid-operations/geo-ip-service.md#current-deployments

- https://geoip.grid.tf/
- https://02.geoip.grid.tf/
- https://03.geoip.grid.tf/
