### ISSUE TITLE
Power management

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/zos#1889]
The chain will orchestrate the power management, there is one events that nodes should take actions upon:

## 1: PowerTargetChanged

Meaning the power target of the node has changed

- If the power target has changed to `Down`, the node should set it's power state to `Down` and gracefully shutdown afterwards.
- If the power target has changed to `Up`, nodes in the same farm should send a WOL packet to the node that needs to turn on. When this node turns on, it needs to check its power target on chain and act accordingly. If the power target is set to `Up`, the power state should also be set to `Up` by the node.

**Comment by DylanVerstraete** [comment]
Needs changes in substrate client first: https://github.com/threefoldtech/substrate-client/issues/77

**Comment by xmonader** [comment]
closed by https://github.com/threefoldtech/zos/pull/1891
