### ISSUE TITLE
Potential dependency inconsistency

### ISSUE THREAD

**Issue by Ben131-Go** [threefoldtech/zos#1890]
## Dependency line:
github.com/threefoldtech/zos --> [github.com/containerd/containerd](https://github.com/threefoldtech/zos/blob/main/go.mod#L18) --> [github.com/urfave/cli](https://github.com/threefoldtech/zos/blob/main/go.mod#L71) <br>
github.com/containerd/containerd v1.5.0-rc.2 --> github.com/urfave/cli v1.22.1<br>
<https://github.com/containerd/containerd/blob/v1.5.0-rc.2/go.mod#L74>

## Background
Repo `github.com/containerd/containerd` at version `v1.5.0-rc.2` uses replace directive to pin dependency`github.com/urfave/cli` to version `v1.22.1`.<br>
According to [Go Modules wikis](https://github.com/golang/go/wiki/Modules#when-should-i-use-the-replace-directive), `replace` directives in modules other than the `main module` are ignored when building the main module.
It means such replace usage in dependency's go.mod cannot be inherited when building main module. And it turns out that `threefoldtech/zos` indirectly relies on `urfave/cli@v1.22.5`, which is different from the pinned version `containerd/containerd` needed.<br>
><https://github.com/threefoldtech/zos/blob/main/go.mod>(Line 71)
```Go
github.com/urfave/cli v1.22.5 // indirect
```

><https://github.com/containerd/containerd/blob/v1.5.0-rc.2/go.mod>(line 52&74)
```Go
github.com/urfave/cli v1.22.2
github.com/urfave/cli => github.com/urfave/cli v1.22.1
```
So this is just a reminder in the hope that you can notice such an inconsistency.
### 1. Bump the version of dependency `github.com/containerd/containerd`
You can try upgrading dependency `github.com/containerd/containerd` to a newer version, which may have eliminated the use of this replace directive.

### 2. Add the same replace rule to your go.mod
```Go
replace github.com/urfave/cli => github.com/urfave/cli v1.22.1
```

**Comment by muhamadazmy** [comment]
Thank you. Yes we need to update the containerd dependency, i will take care of that and see what it gives.

**Comment by Ben131-Go** [comment]
Thanks for your feedback!
