### ISSUE TITLE
Define container profiles

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#19]
After the discussion from https://github.com/threefoldtech/0-OS_research/issues/5#issuecomment-475149757
We agreed we will provide different container "profiles". 
This issue is about choosing what kind of profile we want and write the config.json file for them.

**Comment by muhamadazmy** [comment]
Link to specs (which is still WIP by the time we added this link)
https://github.com/threefoldtech/zosv2/blob/flist-meta/specs/container/readme.md#oci-bundle

**Comment by zaibon** [comment]
closing this, nobody seems to care about that anyhow.
