### ISSUE TITLE
Factorise the network object into the minimal information required

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#192]
Since our network system is fully deterministic, we could actually reduce the amount of information we need to store for a network to just the bare minimum:
```go
type NodeID struct {
	ID string `json:"id"`
	FarmerID       string         `json:"farmer_id"`
	ReachabilityV4 ReachabilityV4 `json:"reachability_v4"`
	ReachabilityV6 ReachabilityV6 `json:"reachability_v6"`
}


type NetResource struct {
	NodeID *NodeID `json:"node_id"`
	Prefix *net.IPNet `json:"prefix"`
	ExitPoint int `json:"exit_point"`
	PrivateKey string `json:"private_key"`
}

type Network struct {
	NetID NetID `json:"network_id"`
	PrefixZero *net.IPNet
	Resources []*NetResource `json:"resources"`
	AllocationNR int8 `json:"allocation_nr"`
	Version uint32 `json:"version"`
}
```

So we get rid of 
- the `Peer` struct: All the wireguard configuration except the private key is determined by the prefix of the network resource.
- The ExitPoint struct: Everything is determined by the PrefixZero

**Comment by delandtj** [comment]
well... a part from the fact that it makes the code lean and mean, it will stop us from allowing users to do their own network config. Also, it could be a problem if our deterministic way of doing things somewhere along the line avers to be a bad idea after all, and that we have to reintroduce IPv4, IPv6 configs specifically.
Although note: less code is less code. But it is suddenly very opinionated and that may be very OK for us, but not for a user.

**Comment by zaibon** [comment]
This doesn't change anything regarding the freedom of the user. We already doesn't allow anything else then this configuration anyhow. And the code of networkd itself will still work against the full network definition. We only change what is carried over the network when doing a reservation.

This proposal also remove the different type of peer and assume only wireguard, which we know is not what we want to have for big farm with large number of node in the same lan.

So this is not all perfect, let's keep this open as idea if we ever need it.

**Comment by delandtj** [comment]
` And the code of networkd itself will still work against the full network definition` -> arf, to make things going over the wire smaller, then of course I don't have any objection

**Comment by zaibon** [comment]
BCDB implementation will use the small format for network provisioning. 
To make it compatible with us with less amount of work I think we can create a method that take the small version as input and expand it to the full Network object we currently use everywhere

**Comment by delandtj** [comment]
another part in that refactoring is that we __will__ need to add possible portforwards when a user buys IPv4, and account for IPv6 firewalling (opening up the diode firewall for every ExitPoint)

**Comment by delandtj** [comment]
hmm looking more into that :
1) An ExitPoint __can__ have a Public IPv4 address that is allocated to him, hence `ExitPoint.Ipv4Conf` needs to exist __Somewhere__ in that format, __with__ the full DNAT list, __if__ the ExitPoint has a Public IPv4.
2) Ipv6Allow **could** be generated, if the container/service is single_purpose (is listening on only one port)
For containers that are attached directly to the Network Resource, the Ipv6Allow struct needs to be filled in, allowing forwarding to the specific ports of that network resource that the attached container is listening on.
so you provision a service through the 3Bot, that would mean that the 3Bot needs to fill in that data, being part of the reservation.

**Comment by delandtj** [comment]
so in terms of networking, it is intricately married to the provisioned containers, so almost *every* container provision, will bump the version of the TNo, i think... we'll have to make sure the ExitPoints get their information in a timely manner.
If no new network resources are created , it seems to me that only the ExitPoints will have to do something, i.e. only update the nft, which leads me to wonder if we don't have to get the drawing board open again on the types of info we expose for the nodes(differentiate services from pure networking)
...
Which ultimately will lead us to some discussions about service announcement/discovery things that we'll have to maintain in the longer run, as container IPv6 addresses won't be that easily memorized.

**Comment by zaibon** [comment]
> An ExitPoint can have a Public IPv4 address that is allocated to him, hence ExitPoint.Ipv4Conf needs to exist Somewhere in that format, with the full DNAT list, if the ExitPoint has a Public IPv4.

This is something we will need to resolve indeed, but as now, we don't deal with IPv4 allocation for exit point just yet. Let's open an issue about it and plan it for future releases.

> Ipv6Allow could be generated, if the container/service is single_purpose (is listening on only one port)

This is not out intend to be single service, so we need to re-add at least the port forwarding rules to be able to expose ports from containers.

> For containers that are attached directly to the Network Resource, the Ipv6Allow struct needs to be filled in, allowing forwarding to the specific ports of that network resource that the attached container is listening on.
so you provision a service through the 3Bot, that would mean that the 3Bot needs to fill in that data, being part of the reservation.

This is indeed how things should work. When a user deploy a container that have a service listening on a port, it needs to also update the tno to reflect this open port.

**Comment by delandtj** [comment]
I still think service registration and firewalling are by definition not part of the network . The network should be ubiquitous, nothing more, nothing less. that is : 
- run the wireguard mesh
- handle inter-network resource routing
- for IPv6, just have the EP run a diode firewall, outgoing only stateful filtering
- for IPv4, NAT in the gateway container for all 10.0.0.0/8 and in the EP outgoing only stateful filtering. If/when a user gets a public IPv4, we then only have to change the default gateway, but the same fiirewall rules apply, just stateful filtering.

register a container in DNS, be it for just A/AAAA records or SRV records should be part of the provisioning scheme.
__the same__ rules for services should then have allowance entries or in case of IPv4 portforward entries, and only when necessary.

so again.. the firewall entries should not be part of the TNo, as I previously envisioned, but something that is part of the provisioning schemes. For instance, creating a service container actually doesn't update the TNo, if it weren't for just he firewall entries, so if these entries are not part of the TNo, nothing changes on network level, removing the need for distributing the TNo to all other participating nodes of that network

**Comment by zaibon** [comment]
replaced by https://github.com/threefoldtech/zosv2/pull/278
