### ISSUE TITLE
Booting stops at network bootstrap - no route with default gateway

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#1927]
A farmer is having trouble during Zos boot. The initial bootstrap is okay, but the network bootstrap fails:

![image](https://user-images.githubusercontent.com/17682591/226717458-f0a71dd5-c535-4cd3-8949-f4510aff84a8.png)

![image](https://user-images.githubusercontent.com/17682591/226713171-387a9c1d-a41e-4a18-b483-c81c82709923.png)

The farmer shared some images from the BIOS settings of this machine. I thought this might be of interest—there is IPv6 connectivity, but not default gateway shown at this stage:

![image](https://user-images.githubusercontent.com/17682591/226719631-940adf3c-f971-48ff-8cc9-ee93267ffdaa.png)

Is it possible that Zos is overlooking this interface because it has no IPv6 gateway specified?

Farmer provided this output from `ip route` on another machine in the network:
```
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.0.1     0.0.0.0         UG    600    0        0 wlp0s20f3
169.254.0.0     0.0.0.0         255.255.0.0     U     1000   0        0 virbr0
192.168.0.0     0.0.0.0         255.255.255.0   U     600    0        0 wlp0s20f3
192.168.122.0   0.0.0.0         255.255.255.0   U     0      0        0 virbr0
```

Output of `ip -6 route` from the same machine:

![image](https://user-images.githubusercontent.com/17682591/226726672-34008501-934c-419e-9854-ff4d82a48623.png)

Node is connected to a cable modem and router combo ([this model](https://drinia.tech/product/cbn-ch7465lg-lc/)). We weren't able to access the admin panel to check any settings on the router.

**Comment by muhamadazmy** [comment]
@scottyeager thank you for the detailed issue.
This error can only happen at a very early stage of the boot. (network bootstrap) the only job of this stage is to basically manage to get a connection to the internet. 

What it does is that it goes all available network interfaces of the node, then tries to DHCP them, the one that gets ipv4 with a valid default gateway (v4) is used as the main interface and is immediately hooked to the default zos bridge. From that point, the system can then download add necessary zos packages.

This means that ipv6 is not important at the moment, we are more interested in the IPv4 network.

I am suspicious that the router is only handing ipv6 addresses and gateways (not sure if that can be possible) can you provide me the output of 

- `ip a`
- `ip -4 r` 
- `ip -6 r` 

on that other machine on the same network (that is connected to the modem over an ethernet cable, not wifi)

**Comment by scottyeager** [comment]
Here are the outputs from the farmer's laptop:

```
ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp65s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 7c:8a:e1:37:8f:aa brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.205/24 brd 192.168.0.255 scope global dynamic noprefixroute enp65s0
       valid_lft 86345sec preferred_lft 86345sec
    inet6 2a02:1812:141e:5200:7b5d:1ee7:dad3:f57c/64 scope global temporary dynamic 
       valid_lft 242527sec preferred_lft 69727sec
    inet6 2a02:1812:141e:5200:4e5d:9265:415c:76c7/64 scope global dynamic mngtmpaddr noprefixroute 
       valid_lft 242527sec preferred_lft 69727sec
    inet6 fe80::c98c:6b9b:c6a:b297/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: wlp0s20f3: <BROADCAST,MULTICAST> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether c8:58:c0:92:b3:6e brd ff:ff:ff:ff:ff:ff
4: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 52:54:00:a5:63:14 brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.1/24 brd 192.168.122.255 scope global virbr0
       valid_lft forever preferred_lft forever
```

```
ip -4 r
default via 192.168.0.1 dev enp65s0 proto dhcp metric 100 
169.254.0.0/16 dev virbr0 scope link metric 1000 linkdown 
192.168.0.0/24 dev enp65s0 proto kernel scope link src 192.168.0.205 metric 100 
192.168.122.0/24 dev virbr0 proto kernel scope link src 192.168.122.1 linkdown
```

```
ip -6 r
::1 dev lo proto kernel metric 256 pref medium
2a02:1812:141e:5200::/64 via fe80::5667:51ff:fe10:8327 dev enp65s0 proto ra metric 100 pref medium
fe80::/64 dev enp65s0 proto kernel metric 1024 pref medium
default via fe80::5667:51ff:fe10:8327 dev enp65s0 proto ra metric 100 pref high
```

It occurred to me that the issue here could be due to how `dhcpcd`  is specifically responding in this case. I asked the farmer to boot a live Ubuntu disk on the same machine they are trying to boot Zos on, and run `dhcpcd`. Here's the output:

![image](https://user-images.githubusercontent.com/17682591/226995750-2c0cdce1-504b-4d2d-9519-2dd2248a3d3a.png)

This seems okay, as there's a correct default route over IPv4 being added. The mystery is why Zos does not see the same result.

*Edit: I checked the relevant code, and it seems that Zos is still using `udhcpc` for the initial probe and then switching to `dhcpcd` later. I'll see if the farmer can also test with `udhcpc`.*

**Comment by scottyeager** [comment]
Farmer ran the following test with `udhcpc` too:

![image](https://user-images.githubusercontent.com/17682591/227029806-82dbed76-23ff-4526-8f2e-8ba829aa5092.png)

**Comment by muhamadazmy** [comment]
I will try to improve the proping (may be switch also to dhcpcd) and add more logs. Changes to the `internet` service require rebuilding a new image since this update can't be shipped during runtime (since it's needed to actually have internet access)

**Comment by scottyeager** [comment]
Thanks @muhamadazmy. Let me know when something is ready and I'll ask the farmer to test it.

**Comment by muhamadazmy** [comment]
@scottyeager can you ask the farmer to try to reboot his node? let me know if it works or if the error message has changed.

**Comment by scottyeager** [comment]
Farmer booted up the node again. This is what they see now:

![image](https://user-images.githubusercontent.com/17682591/228443838-e96c34f2-5c02-485d-a8cc-e33d148570a9.png)

**Comment by muhamadazmy** [comment]
From this log sequence I realize that the node did not detect the Ethernet interface at all. Is it possible that the farmer tries to boot this machine with a different system (say an ubuntu live usb) to see if the interface is detected? 

If it does it might mean that the hardware is not known by the linux kernel version we are using

**Comment by muhamadazmy** [comment]
Can you also please include hardware information regarding NIC interface

**Comment by scottyeager** [comment]
The system is a mini PC, UM480 by Minisforum, with an Intel Ethernet Controller I225-V.

**Comment by scottyeager** [comment]
[Seems](https://forums.debian.net/viewtopic.php?t=151101) there's support in the kernel for this network device since Linux 5.7, but also a lot of complaints about this card in that thread and elsewhere. There's potentially a firmware update available, with the official install method being Windows only.

That said, the nic is definitely supported by Ubuntu on the farmers system. Outputs above where host name is `ubuntu-server` are from Ubuntu running on the same hardware.

**Comment by muhamadazmy** [comment]
So it can be then a missing `firmware` in zos. I will mention @maxux to take a look at this one.

@maxux Please check this issue regarding this nic that is not detectable under zos. Is it possible we get a firmware update for zos?

**Comment by maxux** [comment]
Only way to really know is with a `dmesg`, maybe we should think about a special kernel to debug

**Comment by maxux** [comment]
Can the user give an output of `dmesg` (full output) on working Ubuntu ?

**Comment by scottyeager** [comment]
@maxux, here's the `dmesg` output from the Proxmox installation the farmer has on the machine now:

![image](https://user-images.githubusercontent.com/17682591/230232380-c5afd44b-b543-464b-97b3-4d82ce0255d8.png)
![image](https://user-images.githubusercontent.com/17682591/230232394-07e1e72a-3df4-4daa-84b7-5407036b69ed.png)
![image](https://user-images.githubusercontent.com/17682591/230232405-5c84faa1-2463-48c7-8272-d360dd00c6b7.png)
![image](https://user-images.githubusercontent.com/17682591/230232420-18459951-4bc0-402d-939f-4513fc1302c8.png)
![image](https://user-images.githubusercontent.com/17682591/230232424-20ff4c15-3373-4b35-b7d4-fd341d9e1432.png)
![image](https://user-images.githubusercontent.com/17682591/230232441-25ba80b5-c16b-4457-a92f-433f84e28680.png)
![image](https://user-images.githubusercontent.com/17682591/230232465-849b7c01-5a42-4390-9377-7acfd2771bc0.png)
![image](https://user-images.githubusercontent.com/17682591/230232474-5d27a534-5300-45d2-b6e7-4e2e27d6545e.png)
![image](https://user-images.githubusercontent.com/17682591/230232490-f1fca1df-29cc-4d73-b454-8c8e01160421.png)
![image](https://user-images.githubusercontent.com/17682591/230232504-d0882bff-b81e-4e90-a156-c9b97805e1cb.png)
![image](https://user-images.githubusercontent.com/17682591/230232535-b8e609c4-aac0-4bdb-bdf7-93dc6617161c.png)
![image](https://user-images.githubusercontent.com/17682591/230232557-17a85835-169a-4f8f-a58e-bcf670884cf5.png)
![image](https://user-images.githubusercontent.com/17682591/230232567-ab6098ae-4cc9-4614-9065-ba3d40f3bdff.png)

**Comment by maxux** [comment]
Well, this is (again) an `Intel 2.5G Network Adapter` using driver `igc`.
That driver doesn't require firmware AFAIK. But our kernel is maybe too old to support that specific card.

In order to confirm that, `lspci` will give a better view about Network Adapter so we can confirm that.
Please ask the farmer to learn how to copy/paste text and not take photos of a console :pray: but for a `lspci` that can works...

I can check to provide a test release of initramfs running latest LTS kernel `6.1.x` which should contains latest drivers later :)

**Comment by scottyeager** [comment]
Yeah, we'll cover how to get the text output off the system without a desktop installed :)

I'll ask for the `lspci` output and can also ask the farmer to test a release with the new kernel when it's ready. Thanks!

**Comment by scottyeager** [comment]
Here's the output from `lscpi`:

```
00:00.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir Root Complex
00:00.2 IOMMU: Advanced Micro Devices, Inc. [AMD] Renoir IOMMU
00:01.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir PCIe Dummy Host Bridge
00:01.3 PCI bridge: Advanced Micro Devices, Inc. [AMD] Renoir PCIe GPP Bridge
00:02.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir PCIe Dummy Host Bridge
00:02.1 PCI bridge: Advanced Micro Devices, Inc. [AMD] Renoir PCIe GPP Bridge
00:02.2 PCI bridge: Advanced Micro Devices, Inc. [AMD] Renoir PCIe GPP Bridge
00:08.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir PCIe Dummy Host Bridge
00:08.1 PCI bridge: Advanced Micro Devices, Inc. [AMD] Renoir Internal PCIe GPP Bridge to Bus
00:08.2 PCI bridge: Advanced Micro Devices, Inc. [AMD] Renoir Internal PCIe GPP Bridge to Bus
00:14.0 SMBus: Advanced Micro Devices, Inc. [AMD] FCH SMBus Controller (rev 51)
00:14.3 ISA bridge: Advanced Micro Devices, Inc. [AMD] FCH LPC Bridge (rev 51)
00:18.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir Device 24: Function 0
00:18.1 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir Device 24: Function 1
00:18.2 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir Device 24: Function 2
00:18.3 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir Device 24: Function 3
00:18.4 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir Device 24: Function 4
00:18.5 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir Device 24: Function 5
00:18.6 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir Device 24: Function 6
00:18.7 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir Device 24: Function 7
01:00.0 Ethernet controller: Intel Corporation Ethernet Controller I225-V (rev 03)
02:00.0 Network controller: MEDIATEK Corp. Device 0608
03:00.0 Non-Volatile memory controller: Silicon Motion, Inc. SM2262/SM2262EN SSD Controller (rev 03)
04:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Renoir (rev c1)
04:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Device 1637
04:00.2 Encryption controller: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 10h-1fh) Platform Security Processor
04:00.3 USB controller: Advanced Micro Devices, Inc. [AMD] Renoir USB 3.1
04:00.4 USB controller: Advanced Micro Devices, Inc. [AMD] Renoir USB 3.1
04:00.5 Multimedia controller: Advanced Micro Devices, Inc. [AMD] Raven/Raven2/FireFlight/Renoir Audio Processor (rev 01)
04:00.6 Audio device: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 10h-1fh) HD Audio Controller
04:00.7 Signal processing controller: Advanced Micro Devices, Inc. [AMD] Raven/Raven2/Renoir Sensor Fusion Hub
05:00.0 SATA controller: Advanced Micro Devices, Inc. [AMD] FCH SATA Controller [AHCI mode] (rev 81)
05:00.1 SATA controller: Advanced Micro Devices, Inc. [AMD] FCH SATA Controller [AHCI mode] (rev 81)
```

**Comment by maxux** [comment]
Okay I was maybe too confident on the simple `lspci` output :x
Can you ask output of that exact command please:
```
lspci -vvvxnn | grep -A25 'Ethernet controller'
```

(Full output of `lspci -vvvxnn` also works)

In addition I see another Network controller MEDIATEK, no clue what this is.

**Comment by scottyeager** [comment]
I thought that looked a little sparse :P

Turns out the output for this device is quite long. Here's 35 lines of `vvv` output:

![image](https://user-images.githubusercontent.com/17682591/230464934-75d8b96f-dacb-46ce-bae3-23f29da3eacd.png)

And 80 lines of `vv` output:

![image](https://user-images.githubusercontent.com/17682591/230464681-7dd623c2-889c-44ac-afb6-1a9ffcca8163.png)

**Comment by maxux** [comment]
Well, that specific device is supposedly supported since kernel 4.20, we should support it correctly. I don't see what could be wrong.

Is it possible to get a vidéo (in slow-mo would be better) of the boot process of zos ? Maybe I can catch a line in the kernel logs to see what's wrong :)
Picture like you did for Ubuntu Kernel could works as well, but slow-mo video is easier to take and should not skip anything :)

**Comment by xmonader** [comment]
Will close as too old
