### ISSUE TITLE
Connecting to bootstrap.grid.tf (185.69.166.9:80 wget: download timed out

### ISSUE THREAD

**Issue by shng4you** [threefoldtech/zos#1945]
I have rebooted twice the modem twice, bypassed the switch, and tried both NIC ports on the server, but remain the same issue. Also, I have moved iDRAC to its dedicated port, so there weren't conflicting IP issues. Finally, I've changed to a new dedicated IP address for zOS on the router and switched up the cabling and ports but no changes.

![Zeros network issue](https://user-images.githubusercontent.com/95933607/229849376-0d67744c-700c-44ea-b178-c58e3dd98297.jpg)

**Comment by muhamadazmy** [comment]
The node is trying to test internet connectivity by trying to reach bootstrap.grid.tf which is a service needed to reach to this stage. It seems the system get `timeout` trying to connect which is weird.

It's not clear how it gets `download timed out` at this stage. 

Can you test if you can access `https://bootstrap.grid.tf` from the same network as this node?

**Comment by doubledizzle** [comment]
> The node is trying to test internet connectivity by trying to reach bootstrap.grid.tf which is a service needed to reach to this stage. It seems the system get `timeout` trying to connect which is weird.
> 
> It's not clear how it gets `download timed out` at this stage.
> 
> Can you test if you can access `https://bootstrap.grid.tf` from the same network as this node?

I launched a Windows USB on affected node and had no issues.

![image](https://user-images.githubusercontent.com/129960362/230083258-b079eea9-ddf7-4f0e-8bec-25695c5e9ac1.png)

**Comment by doubledizzle** [comment]
I uploaded a screen recording of the [boot process](https://youtu.be/qBjaBS4JUPo) for anyone looking for more information than what has already been provided.

**Comment by doubledizzle** [comment]
@shng4you  You can close this ticket, I finally figured out the issue. 

The problem was right in front of us the whole time, the DNS IP being pulled in at boot wasn't Cloudflare as I had configured in my router but was actually my router's gateway address. I found 'DNS relay performed by Gateway' was enabled for DNS 1 while 'DNS directly from WAN connection' was properly configured for DNS 2. After changing DNS 1 to match DNS 2 and rebooting the server, I am back online.

**Comment by shng4you** [comment]
Thanks for the update.

**Comment by muhamadazmy** [comment]
Glad that it's fixed. Meanwhile i was building a new zos base image that prints more logs during the boot process (regarding networking) 😆 

Anyway, it's good that we have it now would help with similar future issues

**Comment by doubledizzle** [comment]
That sounds like an incredible idea for logging! I was starting to wonder if there was some way to SSH into zOS to run some queries for more logs as well.
