### ISSUE TITLE
bootstrap: revisit bootstrap process

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#1947]
bootstrap is a tiny process that is built in zos image and what makes sure all latest binaries are installed on the system during boot. it needs to be revisited for improvements for example:

-  stop relying on rfs process to extract/download flists. rfs lib has tools to do that without mounting the filesystem
- detect if there is an available cache on the system, if yes use that during the download to speed up download next time the node reboots.

**Comment by AbdelrahmanElawady** [comment]
After discussions with Azmy we decided that it is not worth the hassle of rewriting it for now. RFS lib is mainly async and rewriting bootstrap will require some effort. For now it won't be done but could be revisited in later versions.
