### ISSUE TITLE
stress testing

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#195]
Now that we have the [decommission system in place](https://github.com/threefoldtech/zosv2/pull/182) we should start doing some stress testing on the nodes of the dev lab.

My idea is we write a small script that send different reservations at random time with different duration.
During this time we monitor the systems (memory, cpu, networks, errors rate, ...)

So we start building some knowledge about how everything works together.

**Comment by zaibon** [comment]
For the system monitoring we already have a node exporter in place on the node in the labs so that fine.
For the logs we don't have anything, so I proposer we quickly write a small tool that would read the logs from the zinit ring buffer and send them to a remote endpoint where we can aggregate/process them.

**Comment by maxux** [comment]
Idea is using `tfuser` to request provisioning:
- Lot of request with small duration
- Request with longer duration
- Request using multiple seeds
- Request with random delay between request
- Sending invalid schema
- Reserving the full capacity of one node
- Do random reservation with random data ?

**Comment by maxux** [comment]
Branch used: https://github.com/threefoldtech/zosv2/tree/stresstest

**Comment by zaibon** [comment]
fixed in https://github.com/threefoldtech/zosv2/pull/282
