### ISSUE TITLE
Node unreachable by RMB after 3.9 upgrade

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#1950]
Since the upgrade to 3.9 yesterday, my node with id 4550 is unreachable via RMB. It is powered on and submitting uptime events. Last timestamp is ~20 minutes ago:

![image](https://user-images.githubusercontent.com/17682591/231560390-d7b62c65-a05b-42b6-917e-fced1613c13e.png)

But it is shown as down when selecting it for deployment in the playground:

![image](https://user-images.githubusercontent.com/17682591/231561499-edff871f-727c-4060-9168-1d58ed07d571.png)

And manual RMB call via `rmb_sdk_ts` to the node's twin 7082 times out after 60 seconds (I let it go for five minutes too):

![image](https://user-images.githubusercontent.com/17682591/231564483-bbf130c3-1cc5-4550-8537-3201cef453da.png)

I have not tried resetting this node yet. It would be a bit of hassle to attach a screen to it, but I can do so if it would be helpful.

**Comment by muhamadazmy** [comment]
Thank you for reporting this. I found an issue with the rmb-peer (that lives on the node side) that it can get stuck on updating the twin information on the chain if the transaction was not finalized! 

I will have to fix this asap and create a patch, hence you don't need to reboot (at least now) to not lose uptime. and wait for the fix

**Comment by muhamadazmy** [comment]
@scottyeager after deploying the patch, I can now reach the node over rmb. Please verify it's resolved from your side before closing this issue

**Comment by scottyeager** [comment]
Looks good here. I also verified a couple other nodes reported to have this issue are now reachable. Thanks for the swift resolution!

**Comment by muhamadazmy** [comment]
No problem
