### ISSUE TITLE
Failed to register node: failed to update node data with id: 5469: failed to update node: failed to submit extrinsic: Priority is too low: (19998 vs 3059):registration failed

### ISSUE THREAD

**Issue by shng4you** [threefoldtech/zos#1958]
I just went to dc and rebooted 5469. It seems okay now, and I was able to deploy something just now. However, I did notice some strange behavior when it finished booting. Attached is the original error that appeared on top of the zos screen. Then the log, and eventually, it corrected itself. Jyst FYI. Unfortunately, the DC monitor is broken and doesn't show green.
![IMG_20230427_144729_hdr](https://user-images.githubusercontent.com/95933607/234953071-0e42d543-a8e2-4e28-9460-75231b782e19.jpg)
![IMG_20230427_144752_hdr](https://user-images.githubusercontent.com/95933607/234953080-43a42c52-c2cd-4953-87d8-7ea1ccbac084.jpg)

**Comment by shng4you** [comment]
The node 5469 is up on the dashboard and grid proxy (https://gridproxy.grid.tf/nodes/5469/status).

**Comment by muhamadazmy** [comment]
Hi @shng4you the "priority is too low" error shouldn't be a fatal error and should eventually fix itself "normally" so i have few questions:
- How long the node kept spitting this error before u notice (minutes, hours, days)
- What was the node uptime before rebooting -if you can remember- (in case it had an old base image that could have issues)
- The state after the reboot (i assume is good)


Note: i checked the logs and didn't manage to find this error, when was this happening?

**Comment by TullysInc** [comment]
Hi @muhamadazmy; from the report obtained from GQL (timestamps specific for yesterday), it appears to have occurred in between:
![image](https://user-images.githubusercontent.com/105203696/235113490-bab0aa77-eb68-4cb0-8323-648a62812df0.png)

The error screenshots were shared at 18:52pm.

**Comment by amandacaster** [comment]
The user says that with Node id 5469, he was able to deploy HestiaCP, and it worked fine also set it up through the browser via 185.10.157.198:8083, however, this IP now can not be pinged anymore even though the node is up and deployed still live. 

![afbeelding_1rj5619](https://user-images.githubusercontent.com/88147124/235641041-0a72f9b3-ca3f-4b8e-a93c-2c08698d150a.png)

**Comment by shng4you** [comment]
Per our instruction, he restarted both his nodes (5469) and (5453) are working fine after rebooting the nodes. Unfortunately, the farmer has a different issue with the terraform deployment after restarting the node (5469). He deployed a HestiaCP on node 5469 a few days ago, and it worked fine, and he was able to ssh into it and set it up through the browser via 185.10.157.198:8083. However, now the IP is unreachable.
**Re: Rj Lamers on crisp:** 
Guys, now that we have node 5469 up and runnign with your help, I'm still experiencing issues. I installed somehting through Terraform on ip 185.10.157.198. It worked fine sinnce I was able to login both usiging Putty as well as through the URL port 8083 to setup the software. Ever since we messed around with this node, that IP is unreachable, while it is still deployed. It shows up in the playground. I'm also able to deploy another vm. Somehow that IP became unreachable after we rebooted the node maybe? What happened?

**Comment by muhamadazmy** [comment]
@shng4you I really think this is not the same issue ? right ? this issue is about failed to register a node. but now you reopen with a totally different context regarding some workload not reachable.

Please re close this issue and open a new one with proper title and description

**Comment by shng4you** [comment]
Sure, I will close this ticket and create the new one. Thanks.
