### ISSUE TITLE
Intel SGX technology in Zero-OS

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/zos#1959]
Not my expertise, but is there any consideration or planning done around using / enabling the Inter SGX feature set in Zero-OS?  

It has clear benefits with regards to protection data processing and execution in the Intel chiptset where Zero-OS already brings a lot of security and benefits over and above a normal bare metal install.

**Comment by scottyeager** [comment]
It's [supported](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/631af8a4f7b72f56d2ba8425095344f99b2fd1c8/docs/intel_sgx.md#L1) in Cloud Hypervisor. An extra command line parameter is needed, so we'd have to build that into the entire deployment flow as a set of options and parameters.

Linux kernel version 5.13 or later is [needed](https://www.intel.com/content/www/us/en/developer/articles/technical/virtualizing-intel-software-guard-extensions-with-kvm-and-qemu.html). I'm not sure what we're running currently or where to check that—last reference I see in an issue was to 5.10.x in 2021. Farmers will need to enable it in their BIOS too. There is a "software enable" feature too, but Intel stopped maintaining the [code](https://github.com/intel/sgx-software-enable) to activate it earlier this year.

**Comment by xmonader** [comment]
@AbdelrahmanElawady can you please kickoff some research of the required changes? not part of 3.11 though.
