### ISSUE TITLE
Workload did not start after ZOS node power loss

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/zos#1960]
Two nodes who had an accidental power outage booted again but the workload on it did not. Workload public ip's are unresponsive.

Nodes (rented as dedicated):
- 3183 - 10.13.0.152
- 3182 - 10.13.0.150

**Comment by muhamadazmy** [comment]
This is fixed now on devnet, for main-net there is a patch ready to fix the issue, but not deployed yet. I am not sure if we should deploy it or wait until released.

The thing is the patch will fix the nodes that haven't lost power (rebooted) yet. to protect against this issue, nodes that has been rebooted and suffered from the bug (some VMs witch reserves almost ALL node memory) will not be restored by the patch
