### ISSUE TITLE
Improve interface giving information about available capacity

### ISSUE THREAD

**Issue by renauter** [threefoldtech/zos#1963]
On ZOS interface some information is provided on screen such as:
- General Info
- Network
- System Used Capacity

See here how it looks:
![photo_2023-05-05_16-10-02](https://user-images.githubusercontent.com/73958772/236549571-cb372724-b21e-4d7d-b711-e6372576936f.jpg)

It would be great to add another field with available capacity (CRU / MRU / SRU / HRU), maybe called `System Available Capacity` (that would fit between `Network` and `System Used Capacity`).

Indeed when a node is upgraded (ex: adding extra SSD) the only way, to my knowledge, to see if the capacity was effectively added is via dashboard / grid proxy / graphql.
Which is not the most convenient because not direct and with delay.

**Comment by muhamadazmy** [comment]
@renauter thanks for reporting this. The UI was mainly to show if there are issues with the node specially during registration but the node information should all be available via the dashboard. 

Anyway, it won't harm to add more information to it, we can do that later

**Comment by muhamadazmy** [comment]
![image](https://user-images.githubusercontent.com/10920323/236812385-e6a4ba27-0018-432b-9e3a-05d99e5ea472.png)

**Comment by renauter** [comment]
Great!

> the node information should all be available via the dashboard.

Indeed, I usually check on dashboard but I guess it is not immediate to get the updated information there.
Grid proxy is updated each 1h or 2 h, correct? I don't remember exactly...

**Comment by muhamadazmy** [comment]
There is no gridproxy anymore, it's all near real-time data

**Comment by xmonader** [comment]
Click on the node details in the dashboard, shows the data indeed without caching as it directly communicate with zos to get the resources and now on the node its shows them properly too 
![image](https://github.com/threefoldtech/zos/assets/64129/62e957c1-6f42-4dbc-b637-2576f873649e)
