### ISSUE TITLE
Nodes have uptime reports but no relay set

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#1969]
During the last minting period, a number of nodes successfully reported some amount of uptime but ended the period with no relay set on chain. This should not be possible, since Zos was clearly able to connect to a TF Chain node and submit transactions.

Here's a sample of affected node ids:

```
268
387
419
541
588
```

I also noticed that some farms had a higher rate of occurrence. For example, farm 2823 shows this issue for a majority of its nodes.

**Comment by muhamadazmy** [comment]
268: the node did not push any logs (is it running?) (last uptime was: 4/May)
387: same (last uptime was 3/April)
419: same (last uptime was 5/April)
541: last uptime 11/April
588: last uptime 3/April


The point is those nodes have actual violations. Of course we can't be one 100% sure that all the nodes on the list has issues or actual violations so if you provide a full list of node ids, I can run a script to check there status and uptime reports and may be filter them out

**Comment by scottyeager** [comment]
Thanks for checking these, @muhamadazmy. I didn't think to check when the 3.9 update happened in relation to the last minting cycle. Since it occurred April 11, any nodes that went offline before that would not have a relay set.

Here's the full list:

```
268
387
419
541
588
632
757
943
985
1069
1200
1203
1288
1365
1428
1446
1502
1691
1703
1721
1755
1783
1848
1850
1989
2060
2061
2120
2147
2152
2417
2420
2435
2436
2447
2495
2681
2686
2715
2823
2958
2959
2960
2961
2988
3165
3282
3319
3347
3493
3582
3814
3830
3831
3938
3988
4100
4130
4162
4369
4392
4535
4795
4877
4889
4914
4942
5084
5394
5457
5487
5518
5519
5523
5524
5525
5526
5529
5540
5541
5544
5548
5550
5559
5570
5571
5579
5587
5588
5590
5633
```

**Comment by muhamadazmy** [comment]
research shows that those nodes were not up, of fake nodes (bots)
