### ISSUE TITLE
Migrate boot screen from v1

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#197]
Even though the node is unreachable for anyone, we still want to print some useful information when a screen is connected to a node.

If no one as objection, we can just migrate the tool we use in the v1 to create this screen. Let's just define what we want to show.

**Comment by muhamadazmy** [comment]
I have some objects:
- The UI was built into core0 (pid 1) of v1
- We didn't any use any terminal libraries so it was kinda hard to setup the layout, add, or edit the layout or add new information. I built it from scratch by drawing directly in the terminal.
- The new version UI must run as a separate daemon (basically like how X11 runs) and then add different widgets that shows stats from separate parts, hence we need to know what to monitor, and how is it going to be monitored, what meterics is important to us, etc...
- we should definitely use this (https://github.com/gizak/termui)

**Comment by zaibon** [comment]
> and then add different widgets that shows stats from separate parts, hence we need to know what to monitor, and how is it going to be monitored, what meterics is important to us, etc...

I think we can be generic about that. We define an interface that any module that wants to show something on the boot screen needs to implement, and the UI daemon just loop over all modules and get the data
