### ISSUE TITLE
Dual configuration lost after node crashed

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#1975]
Farmer noted that their node 5469 came back up in single interface mode after a crash, when it previously had a DUL interface set via RMB. This should be persistent, correct?

**Comment by muhamadazmy** [comment]
the persistence of the `dual` setup has been rolled-back because it caused other issues and wasn't the right approach to fix the original issue.

Instead the farmer HAS to provide a valid and working IPv6 network environment. (ipv6 router advertisement must be available on the public interface)
