### ISSUE TITLE
 Display right disk size in micro vms

### ISSUE THREAD

**Issue by AbdelrahmanElawady** [threefoldtech/zos#2007]
Currently, displaying file system space usage with something like `df` outputs the host file system details not the VM. So, a VM with 10 GB of storage could show multiple Terabytes for example as available. While the VM can't utilize any thing more than this 10 GB, still it would be better to show data only relevant to the VM not the host system.

virtiofsd is being used to manage the filesystem of the VM. it is built on FUSE we can utilize that to report the right size with a `--size-hint` option and modify the right function call to show the right details.

**Comment by muhamadazmy** [comment]
@AbdelrahmanElawady any update on this one ?

**Comment by AbdelrahmanElawady** [comment]
Didn't work on this a lot, however last thing I tried is running Cloud-Hypervisor with virtiofsd according to [this](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/docs/fs.md). However, it did show like 2GBs for root dir not the whole system storage. So, there might be some different options sent to virtiofsd and CH in ZOS than what I used. So, will need to look for that.

**Comment by muhamadazmy** [comment]
where is that value of 2GB is coming from? a folder has no size, hence virtiofs has noway to report what size is available. is this the the size of the entire filesystem shared with CH?

**Comment by AbdelrahmanElawady** [comment]
not sure but I just needed to [mount it](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/docs/fs.md#mount-the-shared-directory). I added `size-hint` option and it does indeed report the right total size for --size-hint=100G:
```console
cloud@cloud:~$ df vtest/ -H
Filesystem      Size  Used Avail Use% Mounted on
myfs            100G   68G   20G  78% /home/cloud/vtest
```
what's remaining is to figure out how to get the available storage so it won't report available storage on the host system but the available for user.

**Comment by muhamadazmy** [comment]
As discussed today, we agreed to instead or providing a size-hint argument for the total size, that we instead rely on an external tool `--stat "cmdline"`  to return stats about the shared directory. This way we can run a script that returns the full size and the usage of the subvol as reported by btrfs qgroup without having to have this specific logic part of virtiofs itself

**Comment by AbdelrahmanElawady** [comment]
It turned out that ZOS runs virtiofsd with the default option for `--sandbox` flag which is `namespace`. which applies some restrictions among them changing the root of the running process to be the shared-dir. So, depending on any executable outside of share directory is not possible unless we removed this restriction (which is not recommended). Also, the daemon process applies a seccomp filter allowing only needed syscalls so a simple command like `echo` fails. So, any external tool we need to run from virtiofsd we will need to trace which syscalls it executes and add them to the [allowed list](https://gitlab.com/virtio-fs/virtiofsd/-/blob/main/src/seccomp.rs?ref_type=heads#L61).

What I can think of to overcome these restriction without removing them is:

- Providing the needed stats inside the chroot environment using a daemon that keeps updating some file periodically and virtiofsd reading it. However, not sure about performance overhead and how it can be manipulated by users inside the VM.
- Using [seccomp notify](https://man7.org/linux/man-pages/man2/seccomp_unotify.2.html) to intercept `statfs` syscalls and modify the response without the daemon itself being aware of any data change, just a new rule appended to the seccomp filter. An example implementation of intercepting container syscalls and modifying them can be found in [runc](https://github.com/opencontainers/runc/tree/main/contrib/cmd/seccompagent) but it applies generally to any process. The only issue here is that writing a seccomp agent is a bit tricky and prone to failures so it needs some effort.

**Comment by muhamadazmy** [comment]
IMHO this is getting way to complex now. This was intended to be cosmetics  issue to make `du` output looks decent. Even if the wrong total size is shown, the limit still applies. 

Right now i am not sure if we should continue with this one or not. I don't want to run (and maintain) yet another daemon, or interrupt syscalls. Also better than periodic updates is to have a pipe between virtiofsd and that daemon so they still can communicate similar to unix sockets. But again this is to complex for such a not important fix.

I would say to close it as won't fix for now and focus on more important stuff

**Comment by muhamadazmy** [comment]
Issue has been fixed using a patched version of virtiofs that can expose the correct values
