### ISSUE TITLE
Fatal Errors

### ISSUE THREAD

**Issue by shng4you** [threefoldtech/zos#2009]
Farmer stated, "I still have some problems with some of my nodes which don't react to the fb; although the power target is up, the node stays down during periodic wake-up. In farm 3099, nodes are 2101, 2102, 2309, and 5922; in farm 3098, nodes are 3416, 5912. In both farms, the FB. log says at the end that they are waking up, but they don't.
3098 Log file here:

[farm-3098_mu8xh4.log](https://github.com/threefoldtech/zos/files/12081371/farm-3098_mu8xh4.log)

3099 log file here:
[farm-3099_h3fbl4.log](https://github.com/threefoldtech/zos/files/12081388/farm-3099_h3fbl4.log)

When Brandon looked at the logs of the ZOS nodes, he saw some fatal errors:
![Fatal error](https://github.com/threefoldtech/zos/assets/95933607/76c8fc5e-e5e4-4953-a6e4-49a7a3408f2a)

Farm id: 3099 and 3098
Node id: 2101, 2102, 2309, 5922, 3416, and 5912
Timing: 02:52:45

**Comment by scottyeager** [comment]
Zos is not detecting the cache SSD and therefore will not complete booting. Does this happen on every boot, or intermittently?

**Comment by amandacaster** [comment]
The user has no option of restarting his node and is looking for further suggestions on what can be done. He wants to know if the problem is with the ZOS boot device or the SSD itself.

**Comment by scottyeager** [comment]
The problem isn't with the boot media, since the node has passed the first bootstrap phase. It could be the SSD, another issue with the node hardware, or something else. The next step in troubleshooting would be to try booting another OS and run some disk diagnostics if the SSD is recognized. If the problem seems isolated to Zos we could investigate further.

**Comment by amandacaster** [comment]
Will pass on the same to the user, thanks @scottyeager.

**Comment by brandonpille** [comment]
> The problem isn't with the boot media, since the node has passed the first bootstrap phase. It could be the SSD, another issue with the node hardware, or something else. The next step in troubleshooting would be to try booting another OS and run some disk diagnostics if the SSD is recognized. If the problem seems isolated to Zos we could investigate further.

Yes indeed that is the issue. Could he try rebooting manually? If the error still occurs indeed try another OS. If that still fails there might be a problem with the ssd.

**Comment by amandacaster** [comment]
No response from the user for several days, hence closing the chat will open it again if the user reverts.
