### ISSUE TITLE
Error: Fetching realtime node information... please wait

### ISSUE THREAD

**Issue by shng4you** [threefoldtech/zos#2010]
Farmer states: "I have a router of my ISP configured as a bridge, and behind that, a TP-Link Archer C6 is acting as my AP, where this machine is plugged in directly with UTP. I see it logged connected to my router. Every connection is going thru this configuration flawlessly. Unfortunately, after completing the Zos download, the process encountered an issue and did not proceed further."

![image](https://github.com/threefoldtech/zos/assets/95933607/e9e68f56-fc75-4ad7-93b8-6c847b2173c4)

 Log message Alt+F2 
![image](https://github.com/threefoldtech/zos/assets/95933607/f7f4e357-5bdd-4d8c-889e-bf4336c33c43)

Log message Alt + F1
![image](https://github.com/threefoldtech/zos/assets/95933607/5d9457b9-ece5-4dd7-bd0c-4f24b3dda787)

Tp link Network setting:
![image](https://github.com/threefoldtech/zos/assets/95933607/807ff634-3469-4fd1-8ce6-d5f20073b258)

**Comment by muhamadazmy** [comment]
ZOS needs 2 IPs on the mgmt (private) network to work. It seems it can't get the second IP from the dhcp. Is the farmer have some sort of limited pool on what MACs get IPs? or a static assignment of IPs/MACs pairs ? 

The error shows that the second (virtaul) device inside zos can't get an IP from dhcp.

**Comment by shng4you** [comment]
Farmer stated that he has disabled ARP and has a DHCP server on the Archer C6 running. And some reservations for specific MAC addresses. I suggest him to enable it and see how it works. I will update you once I get a reply from him.

**Comment by muhamadazmy** [comment]
@shng4you any update on this one ?

**Comment by shng4you** [comment]
The user still awaits an update. I just sent a reminder again.

**Comment by shng4you** [comment]
Due to the user’s unavailability, I will close this ticket temporarily. I will reopen the ticket and resume support when the user returns.

**Comment by shng4you** [comment]
Due to the user’s unavailability, I will close this ticket temporarily. I will reopen the ticket and resume support when the user returns.
