### ISSUE TITLE
Node sets power state to Down when power management is not enabled

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#2018]
While investigating a minting issue reported by a farmer, I noticed that the power target and power state for the affected nodes was repeatedly set to "Down" when the nodes did not actually shutdown because power management is not enabled. During the same period, the node was sending uptime reports.

Here is a sample of the logs:

```
2023-05-16 18:42:37 | [+] powerd: 2023-05-16T16:42:37Z info ignoring shutdown because power-management is not enabled
2023-05-16 18:42:24 | [-] powerd: 2023/05/16 16:42:24 Connecting to wss://02.tfchain.grid.tf/...
2023-05-16 18:42:24 | [+] noded: 2023-05-16T16:42:24Z info got power target change event node=4139
```

The reason for connecting to TF Chain is not shown, but it seems that this is to set the node's power state to "Down".

Reviewing the [code](https://github.com/threefoldtech/zos/blob/cf9e816109a9dc0baf3a445aa8c39146cbef92ea/pkg/power/power.go#L137) that handles this, it looks like the power state is set before calling the shutdown routine where the check is then executed for whether power management is enabled. The power state is not subsequently set to "Up".

What I don't understand is why the node was setting it's power state repeatedly to "Down", despite the [check](https://github.com/threefoldtech/zos/blob/cf9e816109a9dc0baf3a445aa8c39146cbef92ea/pkg/power/power.go#L140) to only execute this when the state is "Up". I wonder if there's an issue with how the power state is retrieved from TF Chain.

Here are the events I queried from TF Chain for this node (all power state and target events):

Time stamp | Date/Time | Event
-- | -- | --
1684341150 | 5/17/2023 16:32:30 | change_power_state to Down
1684341144 | 5/17/2023 16:32:24 | change_power_target to Down
1684337250 | 5/17/2023 15:27:30 | change_power_state to Down
1684337244 | 5/17/2023 15:27:24 | change_power_target to Down
1684333350 | 5/17/2023 14:22:30 | change_power_state to Down
1684333344 | 5/17/2023 14:22:24 | change_power_target to Down
1684329450 | 5/17/2023 13:17:30 | change_power_state to Down
1684329444 | 5/17/2023 13:17:24 | change_power_target to Down
1684325556 | 5/17/2023 12:12:36 | change_power_state to Down
1684325550 | 5/17/2023 12:12:30 | change_power_target to Down
1684321650 | 5/17/2023 11:07:30 | change_power_state to Down
1684321644 | 5/17/2023 11:07:24 | change_power_target to Down
1684317750 | 5/17/2023 10:02:30 | change_power_state to Down
1684317744 | 5/17/2023 10:02:24 | change_power_target to Down
1684313850 | 5/17/2023 8:57:30 | change_power_state to Down
1684313844 | 5/17/2023 8:57:24 | change_power_target to Down
1684309950 | 5/17/2023 7:52:30 | change_power_state to Down
1684309944 | 5/17/2023 7:52:24 | change_power_target to Down
1684306050 | 5/17/2023 6:47:30 | change_power_state to Down
1684306044 | 5/17/2023 6:47:24 | change_power_target to Down
1684302150 | 5/17/2023 5:42:30 | change_power_state to Down
1684302144 | 5/17/2023 5:42:24 | change_power_target to Down
1684298250 | 5/17/2023 4:37:30 | change_power_state to Down
1684298244 | 5/17/2023 4:37:24 | change_power_target to Down
1684294350 | 5/17/2023 3:32:30 | change_power_state to Down
1684294344 | 5/17/2023 3:32:24 | change_power_target to Down
1684290450 | 5/17/2023 2:27:30 | change_power_state to Down
1684290444 | 5/17/2023 2:27:24 | change_power_target to Down
1684286550 | 5/17/2023 1:22:30 | change_power_state to Down
1684286544 | 5/17/2023 1:22:24 | change_power_target to Down
1684282650 | 5/17/2023 0:17:30 | change_power_state to Down
1684282644 | 5/17/2023 0:17:24 | change_power_target to Down
1684278750 | 5/16/2023 23:12:30 | change_power_state to Down
1684278744 | 5/16/2023 23:12:24 | change_power_target to Down
1684274850 | 5/16/2023 22:07:30 | change_power_state to Down
1684274844 | 5/16/2023 22:07:24 | change_power_target to Down
1684270950 | 5/16/2023 21:02:30 | change_power_state to Down
1684270944 | 5/16/2023 21:02:24 | change_power_target to Down
1684267050 | 5/16/2023 19:57:30 | change_power_state to Down
1684267044 | 5/16/2023 19:57:24 | change_power_target to Down
1684263150 | 5/16/2023 18:52:30 | change_power_state to Down
1684263144 | 5/16/2023 18:52:24 | change_power_target to Down
1684259250 | 5/16/2023 17:47:30 | change_power_state to Down
1684259244 | 5/16/2023 17:47:24 | change_power_target to Down
1684255356 | 5/16/2023 16:42:36 | change_power_state to Down
1684255344 | 5/16/2023 16:42:24 | change_power_target to Down
1684213698 | 5/16/2023 5:08:18 | change_power_target to Up
1684211598 | 5/16/2023 4:33:18 | change_power_target to Up

**Comment by muhamadazmy** [comment]
Hi @scottyeager why do you say there is no power mgmt when there are events that sets power **target** to down. The node only respond to changes in the power target. the node can't change the power target this is only possible by a farmer bot (it requires the farmer credentials) the node only change it's state in response to the target change.

Are we sure there is No farmer bot running for this farm ?

**Comment by scottyeager** [comment]
Yes, there's a farmerbot running on the farm. I mean power management in the sense of what causes the node to log the message seen above: `ignoring shutdown because power-management is not enabled`. If I understand correctly that means Zos has detected WoL is not enabled on the node.

**Comment by muhamadazmy** [comment]
Ah that one! sorry i did not notice you refer to this. This one is a protection mechanism from the node in case the the NIC does not support wake on lan (exactly as you said).  If the node detects that the NIC does not support this feature the node will prevent itself from shutting down because otherwise it won't be possible to bring it up again.

**Comment by muhamadazmy** [comment]
So what is the issue ? 😅

**Comment by muhamadazmy** [comment]
I am just back from vacation and my brain is not working 100% yet haha

**Comment by scottyeager** [comment]
All good 🙂 The issue is that the node sets its power state to down *before* checking that WoL is enabled or not.

**Comment by muhamadazmy** [comment]
Ah i get what u mean now, thanks for clarification. It's indeed a bug, i will fix that one no problem.
