### ISSUE TITLE
the update that almost broke the internet

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#2024]
Please more details on what happened here

https://forum.threefold.io/t/some-nodes-went-down-because-of-an-upgrade-bug/4046

The fix should be simple to not delete the packages that are gone from the hub, but this fix need to be part of the next release, any release that goes to mainnet without this will definitely break it

**Comment by xmonader** [comment]
can we mark this as resolved in 3.11?

**Comment by muhamadazmy** [comment]
yes
