### ISSUE TITLE
[perf] research cpu performance tools

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#2036]
The tool need to do some shallow tests that does not affect the performance of running workloads but give an estimation of CPU pefroamnce.

During building of the peformance report (after running the perf tool) the reporter must also include the amount of workloads that was hosted on the node during test running

**Comment by AbdelrahmanElawady** [comment]
decided not to go with `perf` binary instead just stress test some of the available CPUs and report load with the number of running workloads.
waiting on #2046

**Comment by muhamadazmy** [comment]
You already can start by creating the required binary package
