### ISSUE TITLE
Some nodes have no cache

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#2043]
While surveying all active nodes on mainnet by sending them `zos.statistics.get` via RMB, I found that some nodes responded with the error: `subvolume 'zos-cache' not found: file does not exist`.

Since the initial query, I've retried all of these nodes, and found that some have since been rebooted and are now functioning normally.

Here is the list of nodes currently presenting the error:

```
5616
5324
5607
5623
5617
1418
5618
5671
1873
5339
5438
4203
5496
5414
5386
1987
2538
4975
5287
5298
5389
5158
5323
5336
5286
5288
2611
5321
5445
1664
1517
5232
5415
5297
4525
5291
1952
1466
2609
1668
5447
5234
2245
5157
5289
2348
5403
5319
5410
5448
5388
5624
5894
4233
3547
3011
5285
5295
4918
2711
4386
1610
1609
5244
1289
5411
1872
5338
4708
5283
5387
5383
5290
5337
```

And here's the list of recovered nodes:

```
757
1783
730
773
632
744
1784
1850
1848
```

I've started checking for useful information in the logs of these nodes. Of interest is node 5671, which appears to be the always on node for a farm managed by farmerbot. Its [logs](https://mon.grid.tf/explore?orgId=1&left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnode%3D%5C%225Gtyri5zoKcSz8a8XAdGD26m1XMd9gaGwjEezHA456cPn6Le%5C%22%7D%22%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D) show that it is responding to power target changes and attempting to wake up other nodes in the farm. 

Scanning back through the logs, we can see the cache error started on August 22 ([link to relevant log range for 5671](5Gtyri5zoKcSz8a8XAdGD26m1XMd9gaGwjEezHA456cPn6Le)). Just prior to that are a large number of log messages that look like an update. For node 2611, the timing and previous log messages are very similar. See the log range [here](https://mon.grid.tf/explore?orgId=1&left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnode%3D%5C%225CRzLSzqWQkEhxzhTouK2PodaXDfvvbsgqTm6oCEYEHLPJD6%5C%22%7D%22,%22maxLines%22:3000%7D%5D,%22range%22:%7B%22from%22:%221692568800000%22,%22to%22:%221692741599000%22%7D%7D)

**Comment by xmonader** [comment]
@scottyeager please leave issues unassigned

**Comment by scottyeager** [comment]
Hi @xmonader, I had already discussed this issue with Azmy, who requested more information, thus the assignment.

**Comment by muhamadazmy** [comment]
I checked the code, and noticed the following:
- statistics.get tries to find the cache size reserved by the system, because the cache size reserved is elastic hence can change during runtime
- the call is then forwarded to the `storaged` to get the current status of the cache volume
- storaged tries to look up the cache subvolume and it cannot find it! 

That's where it gets weird, why the storaged can't find the cache volume and how come it's gone? The node is obviously still operational which means the cache should be mounted (what happens if it reboot)

I will try to check possible update bugs that might caused the cache volume to get deleted (why other nodes are not affected).

**Comment by muhamadazmy** [comment]
Whey you say list of `recovered` nodes! does this mean they had this same error and was recovered after a reboot? or how do u mean recover?

**Comment by muhamadazmy** [comment]
I see from the logs that nodes that recovered were actually booted, but they kept their identity. Hence the cache volume was actually safe and was not lost! so the error might be something else

**Comment by scottyeager** [comment]
Yeah, "recovered" nodes were showing the error but don't anymore. I retested all the nodes after a couple days. All recovered nodes appear to have been rebooted, based on their uptime reports.
