### ISSUE TITLE
Some nodes missing librt after Zos update

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#2044]
A farmer reported that their nodes weren't reporting uptime, even though they were posting metrics to the metrics server. Investigation showed that the uptime reporting stopped on August 22nd, the same day as the last Zos update. Affected nodes are 5470, 5471, and 5506.

I pulled the [logs](https://mon.grid.tf/explore?orgId=1&left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnode%3D%5C%225G5Za3ZcKAxgHHd2UJBoFQS5HCsRDAScP7nzq389kzXYnsgS%5C%22%7D%22,%22maxLines%22:3000%7D%5D,%22range%22:%7B%22from%22:%22now-2d%22,%22to%22:%22now%22%7D%7D) for node 5470 and see the following error repeatedly:

```
storaged: 2023-08-31T10:53:58Z fatal exiting error="failed to initialize storage module: failed to scan devices: stderr: lsblk: error while loading shared libraries: librt.so.1: cannot open shared object file: No such file or directory\n: exit status 127"
```

Rebooting the nodes solved the issue. Reporting here in case there's something to learn that can help ensure smoother updates in the future.

**Comment by muhamadazmy** [comment]
That is exactly what the bad bug in the update do. That's one of the nodes that were affected by this bad update. The bug was fixed but as you already know the affected nodes need to be rebooted.

**Comment by scottyeager** [comment]
Got it, thanks for clarifying @muhamadazmy. I didn't know which errors were specifically associated with the known bug, so will make a note of this.
