### ISSUE TITLE
Debug mode for the node

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#205]
I had an idea regarding debugging for the node once they will be in the field.

When node will be in production we won't have any way to reads the logs. My idea is to create a new type of reservation. This reservation would need to be signed by the farmer and contains an endpoint where the logs needs to be forwarded.
So when we want to debug a node we send this reservation schema to the farmer he signs it then send it to BCDB. The nodes will pick it up and start forwarding the logs to the endpoint. This could also enable debug level for the logs.

This is not really a backdoor since we don't open an access on the node itself and it is still fully up to the farmer to agree

**Comment by muhamadazmy** [comment]
It's a good idea, except it assumes that the node `provisioning` is actually working. may be a node should by default forward the logs to log aggregation endpoint defined in the boot params. Then a farmer elasticsearch node can receive this and used for debugging when needed? just an idea.

**Comment by delandtj** [comment]
Either way, we already hav a state of a node where we have no clue for why it doesn't boot.
Previously we knew, as everything was sent to the kernel ringbuffer, so we could tell.
So yeah... sometimes the kernel ringbuffer might be of help.
is there a way to (with a `debug` kernel parameter for instance) to pipe to both ? (zinit ringbuffer __and__ kernel ringbuffer) ?
