### ISSUE TITLE
Some nodes don't display Zui

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#2055]
After the recent update to Zos 3.8.4, some farmers have reported that their nodes no longer display the Zui after booting up, just a blank screen.

So far I've checked one example, node id 6039. This node is generating uptime reports and [logs in Loki](https://mon.grid.tf/explore?orgId=1&left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnode%3D%5C%225EH1DhLrENwkR2tsPeLWtS6hnZ8hW59yBS6G6NFUX982hu19%5C%22%7D%22,%22maxLines%22:5000%7D%5D,%22range%22:%7B%22from%22:%22now-24h%22,%22to%22:%22now%22%7D%7D), as well as responding to RMB pings.

**Comment by scottyeager** [comment]
After some further investigation, this appears to be due to the GPU being grabbed for use by workloads.

Seems some farmers would prefer the GPU be used to display Zui, especially in the case of nodes with integrated graphics where it's unlikely the node would be rented for its GPU.

Not sure if there's anything to do here, but I'll leave this open for comments from the dev side.

**Comment by scottyeager** [comment]
There is one case of special concern here. When a node is booted and not yet registered, it can end up in a state where it has a blank screen and also writes no logs to Loki. This makes it difficult to troubleshoot what is blocking the node from reaching a fully up state.

Regarding integrated graphics chips, this is affecting AMD systems, since Zos is filtering all Nvidia/AMD GPUs to make accessible to workloads. While it's probably the case that users are unlikely to rent an integrated GPU, I'm not sure that we want to exclude these entirely as a rule.

Maybe allowing the farmer to set a flag to disable GPU capture during bootstrap generation would be the best approach here.

**Comment by muhamadazmy** [comment]
Yes, your finding is again correct. We can see if we can filter out integrated GPUs and only capture the "discrete" ones.

**Comment by scottyeager** [comment]
After working some more with farmers on GPU capture related issues, I think the most important feature is a flag to disable the capturing altogether. Not every mainboard has integrated graphics, so we still need to be able to disable capture of a *dedicated* GPU for troubleshooting, as in #2061.

On the other hand, we might find a circumstance where someone wants to offer their integrated AMD graphics chip for rent, even for testing purposes.

So maybe the best approach is to have a bootstrap parameter with three possible options:

1. Automatic (default, meant to capture any dedicated Nvidia/AMD GPU)
2. None (disable capture entirely)
3. All (capture any, including integrated)
