### ISSUE TITLE
limit number of cpus reserved in VM to max number of CPUs on host

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#2056]
Since VMs uses vCPUs which are not mapped to actual cores. it's totally okay to reserve more vCPUs that number of cores that the node physically has. 
While this works fine, it might be better to avoid doing this and limit the number of CPUs to physical number of cpus on the host. 

Note: that this limitation is done per VM so a node with 8 cores can still has 2 VMs each with 8 VCPUs.

**Comment by A-Harby** [comment]
Verified, 

Testes on TS client and Playground by deploying a VM with a number of CPU exceeding the node cores.

![image](https://github.com/threefoldtech/zos/assets/109473873/db666d63-2ddf-46f6-bf10-3c67253d88ec)
![image](https://github.com/threefoldtech/zos/assets/109473873/ae88888b-1c09-491c-a34f-f0674ae723b0)


Created test on TS Client suite with full steps:
https://app.testlodge.com/a/26076/projects/40893/suites/194096?expand_section=306578#case_4099871

**Comment by A-Harby** [comment]
Verified, 

Testes on TS client and Playground by deploying a VM with a number of CPU exceeding the node cores.

![image](https://github.com/threefoldtech/zos/assets/109473873/db666d63-2ddf-46f6-bf10-3c67253d88ec)
![image](https://github.com/threefoldtech/zos/assets/109473873/ae88888b-1c09-491c-a34f-f0674ae723b0)


Created test on TS Client suite with full steps:
https://app.testlodge.com/a/26076/projects/40893/suites/194096?expand_section=306578#case_4099871
