### ISSUE TITLE
Freezing after GPU detection

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#2061]
Farmer reported that node 404 on mainnet which was previously working stopped coming fully online after the `3.8.4` Zos update. 

Checking the [logs](https://mon.grid.tf/explore?orgId=1&left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnetwork%3D%5C%22production%5C%22,node%3D%5C%225EChBtgeeKM75DjufJfvNenkW8x6UjfZD67NkrNbnKUPDKWR%5C%22%7D%22%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D), I see that Zos reports finding a GPU, attempts to contact geoip with some failures, and then no further logs are produced (node never begins reporting uptime either). The problem doesn't seem to be about connection to the geoip server, since the farmer's other nodes (176 for example) do come fully online after displaying the same errors initially on trying to contact geoip. The only difference in the logs is the presence of the GPU detection message.

**Comment by muhamadazmy** [comment]
I think this also relate to the GPU capture issue. I think we can do 2 things:
- See if we can filter out integrated chips 
- Add a boot flag to force disable GPU support on the node for similar situations.

**Comment by muhamadazmy** [comment]
Related to #2055

**Comment by shng4you** [comment]
The farmer reported:  "I did remove the GPU and booted, it says down still, I also tried putting a different GPU in and had the same issue."

**Comment by scottyeager** [comment]
I've been talking with this farmer some more. It seems that the machine actually doesn't boot with no graphics card installed.

In this case, it's actually a dedicated Nvidia GPU and there's no integrated graphics. Thus the best thing here would be a flag to disable GPU capture. Then we can see if that resolves the issue and take it from there.

**Comment by muhamadazmy** [comment]
@ashraffouda we need to add a boot flag to zos that disable GPU feature on the node entirely so no GPU capture is done on the node and hence GPUs won't be available to the workloads

**Comment by muhamadazmy** [comment]
ZOS should accept `disable-gpu` flag that disable gpu capture for the entire node
