### ISSUE TITLE
node validation of farm public ips

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#2069]
We have a big issues with public ips available on the farm is that until this moment there is no way we can validate if those IPs are routable from/to the internet to that farm or not.

A miminaml `<syntax>` validation is done on the IPs to make sure the values provided by the farmer are valid public ips and gateway config is "sane" but we can't grantee if the IPs are topologically valid or are owned by this farm. 

Hence we agreed that a `single` node in each farm (can be the node with lowest ID and online inside the farm) to run a scheduled tests of all "usable" IPs in that farm say every 6 hours.

- Test is run on a single node to avoid conflicts in case multiple nodes decided to test all IPs at the same time (since we probably use internal cron)
- The tests need to only test `free` IPs that are not assigned to any contract to avoid disturbing active workloads
- The test need to be fast enough to not hog the IP for long time, since the IP will still show up as free on the chain and hence can be used.

## The test goes like this:
- On start of the test suite, a `Public` tap will be created by asking networkd to prepare one, this can be used via the stub. The tap name can have a unique hardcoded name like `testtap` or something similar 
- once the tap is created the tap is moved to a special namespace to make it isolated from the rest of the system. This setup can stay as is for the entire life of the system, hence the code need to create it only once and assure it exists only on the service restart.
- by default the tap should not assigned ANY ip (again because IPs can get used) and only IPs are assigned when tests are running.
- when test starts, the node gets the farm object with all its IPs.
- for each IP a test result is generated this can be
  - IP allocated (so we don't run test, but is mentioned in the report)
  - IP free, we run the test, and store the result
- If an IP is free, the IP is assigned to the tab (inside the namespace) and the gw is set correctly (also inside the namespace) then a ping test is done against some known external IPs (guess what, the ping runs inside the namespace)
- The update of the ping test is stored on the report for that IP.

Once all IPs are tested, the current tap ip is remove and the tap is set to `down` but not removed so it's ready to test next time.

This can integrate well in the current `perf` framework that we have, because this expose a way to fetch the tests from the node directly, and integrates well in the node cron.

**Comment by muhamadazmy** [comment]
Actually the `tap` might not work! since it can't be used as a virtual device (unlike veth). A tap is instead need to be used via software but not given IPs on its own (tbh I am not 100% sure) 

If that can't work we will have to then use a `veth` pair where one end is plugged in the br-pub bridge, and the other one can then be used instead of the tap above. This will definitely work but will then require changes to networkd to support this functionality.

**Comment by muhamadazmy** [comment]
An even better thing to use is a macvlan from the br-pub bridge but that's again require changes to networkd to support creating this on the br-pub bridge

**Comment by muhamadazmy** [comment]
Instead of the `ping` (because u still can be natted and u won't know about it) we instead can test against one of `what is my ip` websites. If this return the same IP that we have then we are truly a public ip

If you received a different public IP then it's considered fake (make sure you force using of  IPv4)

**Comment by AbdelrahmanElawady** [comment]
So, the new validation task has been deployed on devnet after #2100 and noticed the following on Freefarm:

- The validation task only runs on node 11 (the node with the smallest ID and up state) and skipped for the rest of the nodes.
- For the 35 IP on Freefarm: 9 valid, 25 skipped (because they are used in deployments) and 1 invalid.
- The invalid one is 185.206.122.34/24 and keeps failing the check (it ran multiple times in the past days).
- Calling `zos.perf.get` for the node client with the task name `PublicIPValidation` returns the result for the test or nothing if it was skipped (a node with less ID and up exists).
- On node start it reported all invalid or skipped but later the result seems to be accurate so that needs some verification.
