### ISSUE TITLE
install and support rfs v2 with backward compatibility support

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#2071]
Right now zos uses rfs with v1 (named g8ufs on the zos) we need to also have (and support) v2 on the node. So we ALWAYS need to maintain the 2 binary versions 
- v1 (already named g8ufs)
- v2 (we can stick with rfs name)

The flistd daemon need to be able to decide which one of the 2 binaries to use based on the `flist` name. Right now the best way to do so is by just checking the `flist` extension of the flist to be mounted.
- v1 flist extension is always (.flist) as done by the hub.
- v2 flist is a completely new format (named fungistore) hence the extension used is `.fl` 

flistd then can detect the type, and based on that either use the old binary, or the new one. Note that they both has different argument lists.

**Comment by khaledyoussef24** [comment]
where can i verify or check the images of v2 `.fl` ?

**Comment by khaledyoussef24** [comment]
- verified 
- followed and read the docs of https://github.com/threefoldtech/rfs

- it was clear and followed them and `ran rfs pack -m output.fl -s 00-80=dir:///tmp/store0 -s 81-ff=dir:///tmp/store1 ~/Documents`
![image](https://github.com/threefoldtech/zos/assets/110984055/b93d8f8f-faa9-490b-9acd-cf9ed1a08f09)

- and the output file created successfully 
![image](https://github.com/threefoldtech/zos/assets/110984055/2b215483-9ecf-43e0-b2a3-08d229f2b435)

- then mounting the `.fl` file to another directory
![image](https://github.com/threefoldtech/zos/assets/110984055/022c6919-5181-4985-b342-fcf6a0239085)

- then checking the directory from another terminal to check the mounted docs
![image](https://github.com/threefoldtech/zos/assets/110984055/9170914e-265c-40b8-878f-b0e060aa4a4e)


- the mounted docs copied successfully 
![image](https://github.com/threefoldtech/zos/assets/110984055/6f7127c2-546c-460c-a553-73bf8de06e47)


- the data found successfully

**Comment by khaledyoussef24** [comment]
verified deployed a vm using terraform using v2 '.fl'
and it worked fine and was reachable
it is not supported on playground yet
the example used:
![image](https://github.com/threefoldtech/zos/assets/110984055/8462ab28-caae-45f7-9c47-fb7d45088160)
deployed 
![image](https://github.com/threefoldtech/zos/assets/110984055/342c8bd4-6145-427f-9fe7-f331096550aa)
![image](https://github.com/threefoldtech/zos/assets/110984055/6a9d4260-49d1-4f76-8443-f940f2e10594)
the VM worked fine

**Comment by ramezsaeed** [comment]
Note:
- not supported in playground.
- only supported grid client, GO client and terraform
