### ISSUE TITLE
 Network configuration succeed but zero-os kernel could not be downloaded.

### ISSUE THREAD

**Issue by shng4you** [threefoldtech/zos#2087]
The user has restarted the router, and changing the LAN cable does not help.

![img9138_h8is9d](https://github.com/threefoldtech/zos/assets/95933607/6a639c45-76a0-4584-b432-fbb773803a07)

**Comment by muhamadazmy** [comment]
This is not `zos` issue since the system is not even downloaded yet as this stage. The ipxe error provider https://ipxe.org/err/1d0c65 says that it gets http 5xx error when download the image.

**Comment by shng4you** [comment]
Thanks, Azmy, for the update. I will close this ticket for now, and I will reopen this ticket incase this issue is related to zos.
