### ISSUE TITLE
update `zos-update-worker` to use new style of zos release

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#2099]
This requires first the documentations from this issue below to be done first

Depends on #2098

**Comment by muhamadazmy** [comment]
Please check out the documentation issue docs are already available. After you read and understand how the release is done, then what we need to do here is to update the worker so it create the new style links as follows:

- the link is still created under `tf-zos` but it will have the name of the network (so qa, testing, production).
- the link will then point to `tf-autobuilder/.tag-<version>`

**Comment by Eslam-Nawara** [comment]
WIP:
- [x] read the release docs
- [x] investigate how the update worker works
- [x] change the links to the new style

**Comment by xmonader** [comment]
aman
