### ISSUE TITLE
 Clean up VM host key before first boot

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#2109]
Related to https://github.com/threefoldtech/tf-images/issues/165

Many flists has the host key built in the image, this causes a problem because now all instances created from that the same flist will end up having the same hostkey which is not secure!

According to @scottyeager it would be better if zos takes care on cleaning up the host keys from the VM rootfs before it boots for the **first time** 

After booting, when the image generate a new key the key should not be touched. The image scripts should also take care to generate the keys when they don't exist

Of course  a good image should not include the host key in the base image, but it seems it's a common mistake that people leave that in there by accident

**Comment by scottyeager** [comment]
Hi @muhamadazmy, thanks for the issue.

To be clear, my suggestion is to handle both the deletion of host keys and the generation of fresh ones automatically on first boot. This is to mirror the functionality provided by `clout-init` in our full VMs.

If we only delete the host keys then we'll break SSH in many existing images and force all maintainers (including ourselves) to update. I'd rather not take this halfway step unless we can agree on the full approach.

Let's pause this for further discussion.

**Comment by muhamadazmy** [comment]
I will definitely not do generation of host keys @scottyeager ! Again, already i am not fully convinced that deletion of the key is the right thing to do.

ZOS should be completely transparent to workload types, deletion (or generation) means that zos assumes something regarding the workload and/or operation of the workload which is wrong in the firsplace.

**Comment by scottyeager** [comment]
Let's go ahead with the deletion feature here, and I'll coordinate with our image maintainers to make sure the images generate host keys as needed.

That said, I don't agree with the assessments about what is "wrong" behavior for Zos. It exists to serve users, not philosophical ideals!

My suggestion, again, is simply that we align behavior for our micro VMs with the industry standards for full VMs, where the possibility of host keys sometimes getting shipped in public images is just a fact of life, not a "mistake", and the erasure and regeneration of such keys is considered sane default behavior.

But even though we don't agree on that, doing the part we agree on here can at least help protect all grid users without requiring compliance from third party image authors, so I don't want to hold that up any further.

**Comment by Eslam-Nawara** [comment]
Investigation and Solution:

- currently, I'm investigating where to add the update and trying to create a zos node to test the updates but it gets stuck for some reason with no reported error

**Comment by Eslam-Nawara** [comment]
Work in Progress (WIP): 
- created a local node to test the update against 
- started updating zos to delete vm host keys on first boot

**Comment by Eslam-Nawara** [comment]
The update is tested using [peertube-v3.1.1](https://hub.grid.tf/tf-official-apps/peertube-v3.1.1.flist.md) which has the host keys built in and doesn't make sure that the host keys are regenerated if they were deleted on first boot.

Now all hostkeys from the flist are removed and cloud-container makes sure that the newly created vm contains new host keys

![image](https://github.com/threefoldtech/zos/assets/67752395/65f3d594-de71-4d03-87c0-0798c0bef28c)
