### ISSUE TITLE
perf testplan

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/zos#2122]
Reference Docs:
- https://github.com/threefoldtech/zos/tree/main/docs/tasks

Testlodge coverage:
- ToDo

verify basic perf  test and node performance in ZOS

- https://github.com/threefoldtech/home/issues/1454
- https://github.com/threefoldtech/zos/issues/2033

Need to be tested
- [x] #2111 
- [x] #2106 
- [x] #2113 
- [x] #2112
- [x] #2114 
- [x] https://github.com/freeflowuniverse/crystallib/issues/296

**Comment by ramezsaeed** [comment]
All info moved to https://github.com/threefoldtech/home/issues/1470
