### ISSUE TITLE
PerfTest: why the result overrides old ones, we lose history logs.

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/zos#2127]
we can keep old results not for long time.
just in order to track if failure occur when it had started.
We can save results max for 1 week, so we can compare old with new results if needed.

**Comment by muhamadazmy** [comment]
imho, i don't believe it's up to the node itself to store this information. Like promethium it would make more sense that the node only expose the current values, and whoever wanna want the node can then keep track of the history. (say pull the data once per day and store them forever somewhere)

While i prefer the approach above, it's not impossible to keep track of last runs in redis if there is no other way 

@xmonader what do you think?

**Comment by xmonader** [comment]
- the overall status of the node is supposedly is the concern for minting 
- usability (network upload, download and utilization) is a concern for the user for the most recent - periods (last couple of hours)
- usability of the node in terms of getting money for the utilization is a concern of the farmer (they can provide whatever *opinionated solutions* they want to track/alert, .. etc based on these test primitives) 

All in all, I don't think that's a concern that node needs to worry about.
