### ISSUE TITLE
Development quick start guide refer to not found script 

### ISSUE THREAD

**Issue by Eslam-Nawara** [threefoldtech/zos#2135]
## Describe the bug

the [script](https://github.com/threefoldtech/zos/blob/fc3562af40a57fccbcee08692c91624ba8ef7717/docs/development/quickstart.md?plain=1#L15) used to setup the network to run zos node locally is not found

**Comment by khaledyoussef24** [comment]
some links are fixed but this link is still broken
![image](https://github.com/threefoldtech/zos/assets/110984055/7baae953-3914-47e8-9767-d66340e56212)
![image](https://github.com/threefoldtech/zos/assets/110984055/c92642db-6db0-405a-9d9e-dd20d1bede2b)

**Comment by Eslam-Nawara** [comment]
The link in the issue is from an old commit, you can find the fix in the main branch with the latest commit [here](https://github.com/threefoldtech/zos/blob/fc3562af40a57fccbcee08692c91624ba8ef7717/docs/development/quickstart.md?plain=1#L15)

> updated the link in the issue as well

**Comment by khaledyoussef24** [comment]
checked for the net.sh file in the new commit and the file is working fine
![image](https://github.com/threefoldtech/zos/assets/110984055/1b329c92-0e46-4026-a39e-b8b5ca2b3992)

**Comment by ramezsaeed** [comment]
verified
