### ISSUE TITLE
Change Create Farm link in quickstart docs

### ISSUE THREAD

**Issue by Eslam-Nawara** [threefoldtech/zos#2136]
[Create Farm](https://github.com/threefoldtech/zos/blob/53c2107fe0cae239a4010991353ba92977d43f2a/docs/development/quickstart.md?plain=1#L12) refers to docs that refers to outdated docs that refers to another docs, I think it would be much better if it refers to the actual docs directly https://manual.grid.tf/farmers/3node_building/1_create_farm.html

**Comment by khaledyoussef24** [comment]
links for create farms in `docs/development/quickstart.md` are fixed
![Screenshot from 2023-12-18 08-18-41](https://github.com/threefoldtech/zos/assets/110984055/9867dc18-5ce8-47f3-9a66-f2344200abe0)
![Screenshot from 2023-12-18 08-18-28](https://github.com/threefoldtech/zos/assets/110984055/fcbdc73c-69db-4c57-8ce7-58e016e0b59e)
