### ISSUE TITLE
iperf test download speed giving 0

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/zos#2139]
## Describe the bug

after running the iperf test on different nodes, it is always giving me 0 download speed
```
  "download_speed": 0,
  "error": "the server is busy running a test. try again later",`## To Reproduce

```

**Comment by muhamadazmy** [comment]
I think the problem might be that using cron, all tests end up running at exactly the same time. I thought this might affect the test results but not that.

The solution might be that we introduce some jitter in the scheduler.

**Comment by muhamadazmy** [comment]
I think the best way to do this is for the Task interface to provide a Jitter function that returns Seconds which is the max number of seconds the job will sleep before actual execution 

The code execution will then `sleep rand(0, task.Jitter())` before actually running the task.
A Jitter value of 0 should not introduce any sleep

**Comment by A-Harby** [comment]
I just ran it again, and it gave the same error: `The server is busy running a test. try again later`.

Devnet, Node TwinID is 21.
![image](https://github.com/threefoldtech/zos/assets/109473873/e82843ae-966e-4c94-886f-be4937a180ca)

**Comment by muhamadazmy** [comment]
Okay, seems the jitter did not have the right effect (although i am sure it helped) but seems we have 2 issues here that need to be worked on:

- Iperf server that we host on public node need to support multiple (but still limited) number of concurrent tests. I think this should supported by the server arguments (please check manual and let's modify options)
- The second thing is that for each test of these if we get this exact error, the client need to retry (with some exponential waits and jitter) for maximum of may be 10 retires before it give up and move to the next public node)

**Comment by Omarabdul3ziz** [comment]
the mentioned pr does some retries with backoffs in case the server is busy.

exploring the possibility of enabling the iperf3 server to handle multiple connections found the following:
- Iperf3 is designed as a single-threaded application. 
  there were suggestions on the repository to enable the server to accept multiple requests per connection but weren't approved by the dev team.
- one of the proposals suggested the following approach:
  the server would handle the initial request. subsequent requests would fork the iperf server process on different ports.
  we can do something similar by running multiple instances of the server on different ports and randomly selecting one until an available port can handle the request?
- also there were some comments that the single-threaded design is specific to iperf3, while iperf2 is multi-threaded. I will try to validate this first before we consider using iperf2 instead. is there any specific need to use iperf3?

**Comment by Omarabdul3ziz** [comment]
- verified that `iperf2` can handle multiple clients (running both servers on the same machine)
  ![image](https://github.com/threefoldtech/zos/assets/32527347/3509c831-bc62-4ed8-aaa2-7c86ef18d4e7)

- docs here refers to the changes from `iperf2` to `iperf3` 
  https://iperf.fr/iperf-doc.php#3change

- the difference between the outputs of the two versions
  ![image](https://github.com/threefoldtech/zos/assets/32527347/3c5e0d49-a4ce-4761-a595-db92c2f06a1d)

**Comment by muhamadazmy** [comment]
- There is not specific reason we used iperf3 instead of 2 except that it was "latest" 
- Running multiple test server on the same node sounds like a waste, specially that we have to hog a set or ports only for that.

Do they explain why they insisted on using the single threaded approach (other than it might give wrong test results?)

**Comment by Omarabdul3ziz** [comment]
No, couldn't find any other reason mentioned in the discussions other than having multiple, unrelated connections interfere with each other.

**Comment by Omarabdul3ziz** [comment]
should we go with `iperf2` instead or wait for verification to ensure retrying with backoff fixes the problem?

**Comment by xmonader** [comment]
is that still reproducible @khaledyoussef24 and what to do ? @muhamadazmy @Omarabdul3ziz

**Comment by Omarabdul3ziz** [comment]
to verify i randomly called about 7 nodes on dev net and the error is not happening anymore, looks like the retry with the backoff did the trick
