### ISSUE TITLE
hdparam: checksum mismatch

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/zos#2148]
https://github.com/threefoldtech/zos/actions/runs/7016437026/job/19087665102?pr=2140

**Comment by muhamadazmy** [comment]
Too me this looks like a random failure from github, there are following tests where this passes [this one](https://github.com/threefoldtech/zos/actions/runs/7047165018) 

There is already an issue with the build that is tracked here https://github.com/threefoldtech/0-hub/issues/72

So i will close this one for now
