### ISSUE TITLE
feature: bootstrap daemon to boot a fresh node

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#215]
The bootstrap daemon requirements:
- A bootstrap daemon (as the name suggests) runs only on booting a new node. It's considered an error to re-run bootstrap after the node it booted, and measures should be taken to prevent it from re-running otherwise it can interfere with the node runtime.
- The bootstrap daemon should have NO dependency on node daemons (0-OS daemons) but of course is allowed to use the embedded tools in the image.
- bootstrap needs to make sure node can reach the internet (or nearby hub) to download flist of latest binaries).
- a tmpfs is created and used as a cache backend for the boot flist
- after mounting the flist ALL files are copied to the `rootfs` of the node 
- all new yaml files under `/etc/zinit/` are monitored 
- bootstrap unmount the boot flist, and remove the tmpfs mount

**Comment by muhamadazmy** [comment]
The first issue we need to discuss is networking. 0-initramfs used to have a simple unit file that boots dhcpcd on the available network card(s). But it was removed in fever of `networkd`.

I think we can bring this back (with some improvements) and we make it responsibility of `networkd` to stop this service before taking over the machine networking stack.

Later on, `bootstrap` can only then depend on this `internet` service, and we grantee a smooth boot and running of the service

**Comment by zaibon** [comment]
> I think we can bring this back (with some improvements) and we make it responsibility of networkd to stop this service before taking over the machine networking stack.

I don't have a problem with this. Seems logical enough. @delandtj ?

**Comment by delandtj** [comment]
for networking https://github.com/threefoldtech/zosv2/pull/236 addresses the bootstrap part of the network, as I think some simple dhcp runs on interfaces will not cope with some more complex setups.
It will never be as simple, and now in bootstrap we can set a krnl cmdline  to include or exclude interfaces, as that __will__ come up in the future.
also commented in the meeting notes [20190909](https://github.com/threefoldtech/zosv2/blob/master/meetings/notes_20190909.md)
