### ISSUE TITLE
introduce diagnostics call

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/zos#2153]
Introducing the `zos.system.diagnostics` Command

## Motivation

Currently, we depend on a centralized mechanism to gather detailed logs/monitoring the system and present the health status of system components. which probably not ideal to query or to develop toolings for while we could just get the information from the node  in a brief way 

## Proposed Solution

Introduce the `zos.system.diagnostics` command to provide a consolidated view of system component health. This command should retrieve and display the status of each component, including:
```
{
  systemok: true/false,
  components: 
    {
    	 name: {name, status, error}, .. 
    
    }
}
```

- **SystemOK:** A global boolean flag indicating whether the whole system is considered healthy or not. (if the system is unhealthy no uptime reports should be sent)
- **Component Name:** The identifier for the system component.
- **Status:** The current operational state of the component, such as "OK", "NO"
- **Error:** A string containing the error message that should be communicated

> Note: feel free to remove the repetition of the component name in the value record

This information would enable clients to quickly assess the overall system health, make decisions to include/exclude that node from their planning, notifying the user in the dashboard or even adding more visualization to the node details

- **Proactive Issue Detection:** Early identification of potential system issues, facilitating timely intervention and preventing system outages.
- **Enhanced Troubleshooting:** Simplified troubleshooting process by providing a centralized source of system component status information.
- **Improved System Stability:** Reduced downtime and improved system reliability due to proactive issue detection and resolution (when probably monitored)
- **Uptime Reports:** It shouldn't send uptime in cases where SystemOK is false

**Comment by muhamadazmy** [comment]
Many don't know that for each zbus server there is a built in "Status" call that can:
- Get indication if service is running (if it answers or not)
- Returns number of workers 
- Return state of the worker (free, busy, etc...)

zos already has a built in command line tool `zbusdebug` that prints the status of all services and their helath. 

it should be failry easy to implement an rmb handler that can basically run the same code and return diangoses of the services.

It can also may be expanded later to include other checks as well

**Comment by Omarabdul3ziz** [comment]
update: https://github.com/threefoldtech/zos/pull/2160 in review
