### ISSUE TITLE
Add network health check

### ISSUE THREAD

**Issue by AbdelrahmanElawady** [threefoldtech/zos#2163]
## Description

Add a network check as part of our health check task to make sure internet connectivity to our services is working fine and set some flag in case something failed.

**Comment by AbdelrahmanElawady** [comment]
Related: #2157

**Comment by Omarabdul3ziz** [comment]
this should also be exposed through `zos.system.diagnostics` endpoint on this [pr](https://github.com/threefoldtech/zos/pull/2160)

**Comment by Omarabdul3ziz** [comment]
update: https://github.com/threefoldtech/zos/pull/2160 in review
