### ISSUE TITLE
Improve flist cleanup

### ISSUE THREAD

**Issue by AbdelrahmanElawady** [threefoldtech/zos#2166]
## Description

Some mountpoints of old VMs are kept around in the node cache. For example:

![image](https://github.com/threefoldtech/zos/assets/60783742/941d8eba-da9c-4ccf-8ddf-c33a6a9202e6)

It would be better if we can cleanup this mountpoints instead of cluttering the cache dir

**Comment by Eslam-Nawara** [comment]
WIP:
- added a lock on creating the mount point to prevent the cleaner from removing the mount point before the file system is created

**Comment by Eslam-Nawara** [comment]
## Work Completed: 
- removed the `MountsCleaner` and changed the `cleanUnusedMounts` to be able to remove any folder that is not a mount point
