### ISSUE TITLE
research: zos disk snapshotting and restoration

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/zos#2168]
the idea is to enable ZOS to take disk snapshots into a user's S3 bucket or a Restic repository (considering alternative options if more suitable). The proposed approach is to implement this as a workload configuration tied to deployment identification and virtual machine name (if going to be done in its own deployment). It can potentially occur post a successful deployment or may involve `updating the deployment` , debatble given the evolving nature of ZOS4 APIs.

As user, I should be able to set my credentials, such as the Restic repository key and secret. Additionally, I expect to define the expiration and retention parameters according to my specific requirements.

**Comment by xmonader** [comment]
Also it could be really useful to allow the farmer to configure a global backup credentials and policies, so this can happen smoothly (with a cost for sure)

**Comment by muhamadazmy** [comment]
We need to check first what support cloud-hypervisor provide for that (to backeup the disk) although i think it's none. The only way i can think of to do this correctly is by pausing the VM and then backup the full vdisk. 

This doesn't mean no data will be lost because the kernel in the guest will probably using paging of some files. 

We can investigate that, and see how others are doing it, although i am sure it is probably relying of some sort of hypervisor/guest support

**Comment by ashraffouda** [comment]
WIP: cloud-hypervisor is doing snapshotting using the api, started implementing it in zos,as Azmy said this will require the machine to be paused first then take snapshot, the start it again as soon as this is done will start in backing it up to s3 or whatever we will agree on

**Comment by xmonader** [comment]
maybe it won't be a problem if it was with pauses, how about btrfs snapshots too? also it seems that ZFS allowing live snapshotting with LXC

**Comment by ashraffouda** [comment]
tried snapshoting and restoring from snapshot using cloud-hyvervisor it was very fast  but tried it with small disks, need to try it with larger disks to see what will happen
it exports 2 files on is the `vm.json` about 300kb and one is `memory-region-0`  was around 1G which contains the actual snapshot will dig more on this

**Comment by ashraffouda** [comment]
tested a machine with a disk 50G full of data then pause the machine 
- created a disk with 
```
truncate -s 50G file.disk
```
- started the machine and used fdisk to create a partition on it and wrote some data
```
dd if=/dev/urandom of=sample.txt bs=64M count=800 iflag=fullblock
```
- pause the machine
```
 sudo ./ch-remote --api-socket=/tmp/cloud-hypervisor5.sock pause
```
- take snapshot 
```
sudo ./ch-remote --api-socket=/tmp/cloud-hypervisor5.sock  snapshot file:///home/afouda/code/github/threefoldtech/cloud-hybervisor/snapshots
```
- stopped the machine and removed the disk, then created an empty disk with the same name
```
truncate -s 50G file.disk
```
- restored the machine again 
```
sudo ./ch-remote --api-socket=/tmp/cloud-hypervisor5.sock  snapshot file:///home/afouda/code/github/threefoldtech/cloud-hybervisor/snapshots
```
- resume the machine 
```
sudo ./ch-remote --api-socket=/tmp/cloud-hypervisor.sock resume            
```
did tail on the created file 
```
tail sample.txt
```
the file is there and has the data 
notes: 
1- the back in both scenarios without  disk  and with a disk of 50G was of size 1G in both cases
2- the restore took no time in both scenarios regardless the amount of data 
ps pause the original machine succeeded but resuming it fails while pausing and resuming the machine restored from snapshots always works with no problems

**Comment by xmonader** [comment]
Thank you!!
