### ISSUE TITLE
build is not working on ubuntu 22:04

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/zos#2176]
## Describe the bug

I build the binaries from ubuntu 22:04 but for some reason it is not working as expected and it gives this error when I do `zinit log `

## To Reproduce
go to `cmds` directory and do make then try to instantiate a vm
## Screenshots
![Screenshot from 2023-12-19 16-31-13](https://github.com/threefoldtech/zos/assets/1689456/96a9c8c7-68a8-45db-bbaa-0b0f9aacfacb)
the issue was saying 
```
db: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub"
```
as a work around I did the following 
created ubuntu docker and mounted zos inside it 
```
docker run -it   -v ~/code/github/threefoldtech/zos:/root/zos ubuntu:20.04 
```
then inside the docker install 
```
apt-get install -y wget make binutils build-essential
```
then  install golang and do make this the resulting bins should be correct in this case 
also not `build-essential` is required for sqlite issue to be solved

**Comment by muhamadazmy** [comment]
Weird that I tried to reproduce this by using `ubuntu:22.04` container 
```
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
```

I only had to install:
- build-essential 
- git
- go v1.21.5

I built the binaries in the container then started my zos vm. The boot went completely fine with no errors. Can you please try to rebuild on ubuntu 22.04 but inside a container. If that works we need to figure out what is different from your actual local setup

**Comment by ashraffouda** [comment]
https://github.com/threefoldtech/0-fs/pull/48
