### ISSUE TITLE
Some deployed VMs can't reach the public network

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/zos#2177]
env: qa
nodeId: 2

It doesn't always happen, but sometimes the deployed vm has `/etc/resolv.conf` empty.

**Comment by ramezsaeed** [comment]
we need to check node on qa net when started and the version of software running on it.
as a work around u can populate the /etc/resolve.conf manually and it should work.

**Comment by muhamadazmy** [comment]
can you provide information about the flist used to deploy this VM.

**Comment by AhmedHanafy725** [comment]
I was using Caprover flist
https://hub.grid.tf/tf-official-apps/tf-caprover-latest.flist

**Comment by AbdelrahmanElawady** [comment]
It's an issue with cloud-container not continuing network configuration if an error happens which leads to empty `/etc/resolv.conf` file (among maybe other things).
https://github.com/threefoldtech/cloud-container/issues/20

**Comment by muhamadazmy** [comment]
Reopened to be verified first
