### ISSUE TITLE
Update virt-what to fix Nutanix VM detection

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#2179]
Our [last version bump](https://github.com/threefoldtech/zos/issues/1712) of `virt-what` fixed one issue with VM detection affecting some farmers, but unfortunately it introduced [another](https://issues.redhat.com/browse/RHEL-7533). After my report upstream, the issue was resolved, but we still have some nodes sidelined from the grid.

While the newer version of `virt-what` with this fix is being shipped with the latest versions of Red Hat already, there hasn't been a new minor version release that includes the change (Zos is on `1.25` which is still the latest). Based on the history, these releases can sometimes take a year or more.

Unless there's any objection, I think we should update to the latest `virt-what` code that's made the cut for inclusion with Red Hat. There's no tarballs for these versions, but they are stored as branches in the [official git](http://git.annexia.org/?p=virt-what.git;a=summary).

The one I have in mind now is [rhel-9.3](http://git.annexia.org/?p=virt-what.git;a=shortlog;h=refs/heads/rhel-9.3):

![image](https://github.com/threefoldtech/zos/assets/17682591/ce25a4d7-29aa-488d-9fe9-3bb6f6439128)

**Comment by ramezsaeed** [comment]
@Eslam-Nawara please verify virt-what is the latest

**Comment by Eslam-Nawara** [comment]
WIP: 
- virt-what version is updated to rhel-9.3 and build is done successfully
![image](https://github.com/threefoldtech/zos/assets/67752395/d1a86a6e-f819-4173-8a86-ea111f2cabb3)

**Comment by scottyeager** [comment]
Farmer reports that nodes are no longer showing as virtualized. Thanks.
