### ISSUE TITLE
internet package should try also other urls than bootstrap.grid.tf

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/zos#2188]
because it might be down and we won't be sure if we got actual internet and can reach bootstrap.grid.tf or if we have it and the bootstrap website is down

**Comment by muhamadazmy** [comment]
we actually then need to test the `hub.grid.tf` because if that one is down we won't be able to continue the boot anyway

**Comment by muhamadazmy** [comment]
@Eslam-Nawara this is a very easy task. we have an `internet` binary (under cmds/internet) that tries to test connectivity to some public services. We need to make sure we also include the hub.grid.tf

**Comment by ashraffouda** [comment]
verified
