### ISSUE TITLE
Failed to Copy files error during Boot process

### ISSUE THREAD

**Issue by mahendravarmayadala93** [threefoldtech/zos#2189]
Two farmers named Pritesh Lakha & Denai Lewis reported that their Nodes (Not using WOL)are unable to complete the boot sequence due to the error **"Failed to copy files"**

Also, basic trouble shooting like rebooting the Node & router doesn't help.

Pictures Shared by Pritesh Lakha

![image_175x7rl](https://github.com/threefoldtech/zos/assets/89931135/0773a728-a466-4d30-be04-86c65cabc013)

Pictures shared by Denai Lewis

![image_1nnxj8c](https://github.com/threefoldtech/zos/assets/89931135/3bf125bd-99c8-4f84-bf05-74c83eb1fcfe)

A user on Telegram 

![photo1705522873](https://github.com/threefoldtech/zos/assets/89931135/881c8fe4-a93c-4175-bcf0-28199ed23a3b)

**Comment by scottyeager** [comment]
Looks like this was due to issue with the Hub that has since been resolved.
