### ISSUE TITLE
Return average speed in Iperf tests

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/zos#2207]
The current behavior from getting the Iperf test over zos returns the tests against all gateway nodes found. We aim to modify it to provide only the average of the test results across all detected nodes.

**Comment by Eslam-Nawara** [comment]
Discussed the issue with @AhmedHanafy725, and we agreed to leave the handling of the display of the output of the `iperf` tests to the client side and the test will still return the same output.

We also discussed checking if a public node testing the speed of itself would return a non-reasonable result

While investigation, I noticed that the pref test on `mainnet` nodes returns zero values for all fields with errors 
- node_id: 1
- twin_id: 7

- `error:unable to connect to server - server may have stopped running or use a different port, firewall issue, etc.: Operation timed out`
- `error:unable to connect to server - server may have stopped running or use a different port, firewall issue, etc.: Connection refused ` 

but running the test on `devnet` on nodes 11 and 14 the speeds sounds reasonable and no major differences between measuring the speed on different nodes

![untitled(3)](https://github.com/threefoldtech/zos/assets/67752395/3412b723-8f8f-4552-9408-fe545ca7a129)

**Comment by ashraffouda** [comment]
nothing will be done here
