### ISSUE TITLE
no docs available for health checks in perf tests

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/zos#2209]
## Describe the bug

found health checks task but no docs were mentioned in https://github.com/threefoldtech/zos/tree/main/docs/tasks
and also the results is unclear
```
    "name": "healthcheck",
    "result": {},
```

## To Reproduce

run get_all
![Screenshot 2024-02-29 at 9 55 42 AM](https://github.com/threefoldtech/zos/assets/110984055/e1c8afd6-9d8d-4084-9155-026de66253b9)

**Comment by ashraffouda** [comment]
verified
