### ISSUE TITLE
Failed deployment: error - Failed to send request to twinId 8374 with command: zos.storage.pools

### ISSUE THREAD

**Issue by TullysInc** [threefoldtech/zos#2211]
This issue was initially reported over the support chat:

![5376_failed deployment error](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/105203696/0bbc6d47-cb63-460d-8010-ae6e5db53dc2)

Replicated the issue at our end as well:

Node ID: 5376
network: https://next.dashboard.grid.tf/

Dashboard and grid proxy is indicating the node 5376 status is Up. 

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/105203696/d28afced-5064-4227-8c15-158c239b9396)

However, when clicking into the Node details it indicates this node is down.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/105203696/19d63c2f-93ee-4c98-add6-ac9a66317b52)

**Comment by AhmedHanafy725** [comment]
Tried to ping this node over RMB but it always times out. Also when I selected this farm, there were no nodes returned even this node. @sabrinasadik can we check the logs of this node? maybe the RMB service has an issue

**Comment by scottyeager** [comment]
Node logs indicate the node can't connect to RMB relay:

```console
2024-02-29 18:26:43	
[+] noded: 2024-02-29T17:26:43.743Z ERROR [rmb::peer::socket] failed to establish connection to Some("relay.grid.tf") : IO error: failed to lookup address information: Try again
2024-02-29 18:26:38	
[+] noded: 2024-02-29T17:26:38.738Z INFO  [rmb::peer::socket] connecting to relay Some("relay.grid.tf")
```

Messages like this are printing constantly, while the node is still submitting uptime reports. Transferring this issue to Zos repo for further investigation.

**Comment by muhamadazmy** [comment]
I think this issue was a temporary failure in name resolution. But whatever caused it, it's gone now! i can reach the node normally on rmb now with now issues.

I assume this was a network glitch in the farmer network! but once it was resolved, the node was reachable again.
