### ISSUE TITLE
Error:  Could not boot: Requested memory not available.  Image downloaded but Zos kernel could not be executed

### ISSUE THREAD

**Issue by shng4you** [threefoldtech/zos#2212]
The farmer reported: "tell me, please, I'm running the node, it's constantly rebooting, what needs to be done to make it fully functional."

![image](https://github.com/threefoldtech/zos/assets/95933607/e51584a4-2514-4eba-bbda-8acbf9ad4c1d)
![image](https://github.com/threefoldtech/zos/assets/95933607/c5f8d2be-b408-4a87-9602-34eb58bd0545)

The farmer changed the RAM and inserted it into a different slot, then rebooted the node. Unfortunately, the issue remains the same.

**Comment by muhamadazmy** [comment]
this IPXE error is described here https://ipxe.org/err/460381

It suggest that you update the BIOS firmware to latest version and try again. I don't believe it's actually a memory issue but just outdated BIOS firmware.
