### ISSUE TITLE
More robust NTP server name resolution

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#2219]
While investigating a [case](https://github.com/threefoldtech/zos/issues/2194) of farmer's nodes not working properly due to failure to reach NTP servers, I landed on an interesting [thread](https://bbs.archlinux.org/viewtopic.php?id=292688) discussing the root cause of the issue.

The summary is this:

* Zos resolves `[0-3].pool.ntp.org` to find the IP of an NTP server to use
* ntp.org is using geolocation on the source IP of these requests and mapping them to regional server pools
* The farmer with the issue is located in the Philippines, and the pool of servers provided to the farmer's nodes is polluted with faulty servers (this is a country specific pool that can be queried directly at `ph.pool.ntp.org`)
* Until the ntp.org pool is cleaned up, this farmer and potentially any others in the Philippines will be liable to have time sync issues with Zos

I think we can make some simple changes to improve the robustness of Zos in reaching a functional NTP server. Maybe a three tiered approach:

1. What we do now, query `[0-3].pool.ntp.org`
2. Assuming we have already completed geoip, query the appropriate [continent pool](https://www.ntppool.org/zone/@) based on the node's location. For example `[0-3].asia.pool.ntp.org`
3. Go round robin on the remaining continent pools, if the local one has failed

That said, I am just now reading this on the ntp.org [vendors page](https://www.ntppool.org/vendors.html):

>To allow you to use the pool as the default time service in your application, we will set you up with special hostnames, for example 0.vendor.pool.ntp.org, 1.vendor.pool.ntp.org, 2.vendor.pool.ntp.org and 3.vendor.pool.ntp.org.
>
> You **must absolutely not use the default pool.ntp.org zone names** as the default configuration in your application or appliance.

Pretty sure that's meant to include us, and it would explain why all the distros have their own subdomains (`arch.pool.ntp.org`, `ubuntu.pool.ntp.org`, etc). But I think it leaves us with the same issue, as these subdomains seem to resolve in the same way as the base domain.

I'm happy to pursue getting our own subdomain from ntp.org. I can also ask while I'm at it what their recommended approach regarding this issue would be.

**Comment by muhamadazmy** [comment]
Hi @scottyeager 
  That's an amazing research. In fact we relay on the ntp pool to provide the proper (and local) address for the ntp server to contact. The idea is that reduces the latency and hence improves time syncing accuracy. 

We actually don't even choose which pools to contact, we simply run the ntp binary with no arguments and it queries all the built in pool addresses which is then handled correctly by the local dns server.

The suggested solution will definitely work. It's a great solution. But i am wondering if it worse it. Since local ntp server should be fixed by the organization.
- If we tried to have a special handling for every little thing then that can go wrong we end up with a huge code base that most of it is redundant.
- ntp is one of the very basic services that starts almost before anything (since time is needed to be correct before the system moves on) means that we can't wait to sync time later. Ntp daemon is actually one of the base service in the zos image and not installed during boot

**Comment by scottyeager** [comment]
I appreciate the sentiment of wanting to keep Zos simple, and certainly I don't want to make any change that could make the situation worse.

However, I don't think the characterization is quite correct. We do ship an ntpd [config file](https://github.com/threefoldtech/0-initramfs/blob/development-zos-v3/config/etc/ntp.conf) and even if this is default behavior for ntpd, there are aspects of Zos that warrant special consideration here.

In a typical situation where a user has issues with their local pool of NTP servers, they have a few options:

1. Reconfigure their system to use a different URL pointing to a different pool or individual server
2. Intercept the DNS query locally and provide a different set of IPs
3. Manually set their hardware clock good enough and wait for the faulty servers to be removed from their pool

Let's remember now that we have a lot of nodes in the field that were sold as "plug and farm". Options 2 and 3 are out for such nodes.

Providing a way for the farmer to configure an (additional) NTP URL as a kernel parameter is maybe an okay solution. This requires though that we provide these signed in the case of secure booted nodes.

> ntp is one of the very basic services that starts almost before anything (since time is needed to be correct before the system moves on) means that we can't wait to sync time later. Ntp daemon is actually one of the base service in the zos image and not installed during boot

This is exactly why I think it's a candidate worthy of some special handling to improve robustness. We want to deploy Zos all around the world, and especially in more places where the local NTP pool is liable to become unreliable.

Of course the broken NTP servers should be fixed or withdrawn from the pool. But in my opinion simply telling farmers they must wait for this to happen is not a great solution.

## Idea 2

So all that said, after reviewing some information about ntpd configuration, I see a very simple way to implement a version of what I suggested above.

Within the ntpd config file, it's [possible](https://www.ntp.org/documentation/4.2.8-series/prefer/) to specify a `prefer` directive to one or more servers. So the solution becomes to keep the existing base set of pool URLs, mark them as preferred, and then add a set of fallback URLs without the preferred designation.

This should allow ntpd to continue functioning in case of a local outage while always returning to the local pool when it becomes available again. We can accomplish this without any extra code, just a few lines of config.

**Comment by Omarabdul3ziz** [comment]
I did some research and here are some of my findings:
- I read in a couple of places that using `prefer` option is not recommended and it doesn't affect much on the selection process. [here for example](https://kb.meinbergglobal.com/kb/time_sync/ntp/ntp_basics#classification_of_time_sources:~:text=Please%20note%20that%20the%20prefer%20keyword%20has%20only%20limited%20effect%20on%20the%20selection%20process.%20Usually%20the%20best%20approach%20is%20to%20simply%20let%20ntpd%20select%20the%20system%20peer) and it is better to stick with the global pool
- also as far as understand all the pool does is just recommend the local server to connect to so either a global pool `pool.ntp.org` or a zonal one `asia.pool.ntp.org` will end up giving the same local server `ph.pool.ntp.org`

**Comment by scottyeager** [comment]
> * I read in a couple of places that using `prefer` option is not recommended and it doesn't affect much on the selection process. [here for example](https://kb.meinbergglobal.com/kb/time_sync/ntp/ntp_basics#classification_of_time_sources:~:text=Please%20note%20that%20the%20prefer%20keyword%20has%20only%20limited%20effect%20on%20the%20selection%20process.%20Usually%20the%20best%20approach%20is%20to%20simply%20let%20ntpd%20select%20the%20system%20peer) and it is better to stick with the global pool

Seems indeed that `prefer` doesn't work the way I was expecting. The biggest issue is that it would influence the peer selection process in a potentially negative way for the majority of nodes that are served working peers from the global pool.

> * also as far as understand all the pool does is just recommend the local server to connect to so either a global pool `pool.ntp.org` or a zonal one `asia.pool.ntp.org` will end up giving the same local server `ph.pool.ntp.org`

*(Removed my original comment showing how these URLs resolve on my own machine, since it might not accurately reflect the view from inside the Philipines)*

In the [thread](https://bbs.archlinux.org/viewtopic.php?id=292688) from the Arch Linux forum I linked in my original post, the user reports precisely that they resolved their issue with the `ph` pool by switching from the global pool URLs to the Asia URLs.

After some more consideration, I think the best approach here is just to provide a kernel flag to allow the farmer to override the NTP servers. This is a rather rare situation, so requiring some manual intervention from the farmer while not touching anything for normally functioning nodes seems like a good tradeoff.

**Comment by muhamadazmy** [comment]
@Omarabdul3ziz can you please implement this feature as Scott asked. A kernel flag for specific ntp server sounds like a good solution for a very rare case
