### ISSUE TITLE
cloud-init cidata seed are not deleted when Vm is deleted

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#2234]
## Describe the bug

cloud-init cidata seed are not deleted when Vm is deleted

## To Reproduce
- create a vm 
- delete the vm
- cidata for this Vm under /var/cache/modules/vmd/cloud-init/<seed-disk>  is not deleted

**Comment by Eslam-Nawara** [comment]
I checked the issue and tried to reproduce but found that the cidata were removed with no issues
- I tried deploying 3 vms
- deleted two vms and checked the data path
- deleted the last vm and checked the path and every thing is looking fine to me 
``` console
~ # ls -al /var/cache/modules/vmd/cloud-init
total 120
drwxr-xr-x    1 root     root           114 Mar 19 10:10 .
drwxr-xr-x    1 root     root            28 Nov 28 14:11 ..
-rw-r--r--    1 root     root       2097152 Mar 19 10:04 4653-103178-vmkax35
-rw-r--r--    1 root     root       2097152 Mar 19 10:09 4653-103184-vmkax36
-rw-r--r--    1 root     root       2097152 Mar 19 10:10 4653-103186-vmkax37
~ # ls -al /var/cache/modules/vmd/cloud-init
total 40
drwxr-xr-x    1 root     root            38 Mar 19 10:13 .
drwxr-xr-x    1 root     root            28 Nov 28 14:11 ..
-rw-r--r--    1 root     root       2097152 Mar 19 10:04 4653-103178-vmkax35
~ # ls -al /var/cache/modules/vmd/cloud-init
total 0
drwxr-xr-x    1 root     root             0 Mar 19 10:15 .
drwxr-xr-x    1 root     root            28 Nov 28 14:11 ..
~ #
``` 

I've noticed that the deletion errors are ignored, maybe we should log the errors if there is any
