### ISSUE TITLE
automatic vmlinuz decompression for micro VMs

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#2236]
Right now, flists that provide their own kernel has to have it already uncompressed [as per docs here](https://github.com/threefoldtech/zos/blob/main/docs/manual/zmachine/zmachine.md#vm) 

The idea is that while users usually forget about this, it also problematic if the kernel was updated then the VM restarted. This can brick the VM.

Instead zos should detect the kernel if it's compressed, and then does the uncompression automatically if needed (check the method in the docs above)

**Comment by rawdaGastan** [comment]
WC:
- removed `lzo` pkg because it requires an extra lib to be installed
- 2 errors for `zstd` and `bzip` will be ignored
- other algorithms worked well
- uncompressed kernel will override the compressed one

WIP: 
- testing different kernels through deployments

**Comment by rawdaGastan** [comment]
This part is removed now
