### ISSUE TITLE
Unauthorized error: failed to establish connection to relay.grid.tf.

### ISSUE THREAD

**Issue by TullysInc** [threefoldtech/zos#2239]
Nodes are showing up in dashboard, however you click into the node details, it indicates the nodes are offline.

![image](https://github.com/threefoldtech/zos/assets/105203696/2c814429-2fa3-4a79-b919-6895dd4acea4)

![image](https://github.com/threefoldtech/zos/assets/105203696/6abadbe6-8477-4e51-af2c-882a7290d3b5)

Zos logs from the node show a successful boot up.
![Node ID 3784](https://github.com/threefoldtech/zos/assets/105203696/9d6539bd-83f3-480b-a841-beaac6553960)

Logs obtained by Azmy:
![image](https://github.com/threefoldtech/zos/assets/105203696/82c642b4-c269-4a72-9d3c-0a946a7c71c9)

**Comment by TullysInc** [comment]
@muhamadazmy 

ping relay.grid.tf - latency:

<img width="479" alt="relay grid tf_latency" src="https://github.com/threefoldtech/zos/assets/105203696/eaf383ee-2b92-431a-9b26-199c1408f7bc">

<img width="598" alt="relay grid tf_latency_1" src="https://github.com/threefoldtech/zos/assets/105203696/39219c51-ee87-420c-8113-1a55afcef397">

https://relay.grid.tf/metrics - He is unable to open this one.

**Comment by muhamadazmy** [comment]
Note: 
- The ping command need to be without the http part so `ping relay.grid.tf` but i see he managed to use the ip instead which is okay
- When u say unable to open this url https://relay.grid.tf/metrics what exactly happens, what error does he get?

**Comment by TullysInc** [comment]
Farmers' response: 
sh-3.2# ping https://relay.grid.tf/metrics
ping: cannot resolve https://relay.grid.tf/metrics: Unknown host
sh-3.2#

**Comment by muhamadazmy** [comment]
Are there any nodes in this farm that is working fine?

**Comment by TullysInc** [comment]
The following nodes are booting up Zos fine (as confirmed from the final boot screen):

- 905
- 1745
- 3032
- 3452
- 3596
- 3679
- 3702
- 3784
- 3785
- 4008

However, none of these nodes can ping the relay.grid.tf URL. and the node health states these are offline.

**Comment by muhamadazmy** [comment]
Okay, so after some investigation I finally found the problem:
For some reason (i really don't know why) the node takes over a minute to establish a connection with the relay by the time connection is established, the access token has already expired.

We already have a fix for this, by simply increase the token expiry time. But i will need to create a patch for mainnet to deploy that fix. So eventually this issue will be fixed

**Comment by TullysInc** [comment]
Thanks much for the detailed insight.

**Comment by muhamadazmy** [comment]
So the patch has been deployed, it can be couple of ours before the update reaches all nodes. So i suggest to verify the issue is resolved tonight or next morning. 

let me know if the issue is not resolved by then

**Comment by TullysInc** [comment]
Thanks for the quick resolution, Azmy.  Will keep you posted.

**Comment by TullysInc** [comment]
Checked dashboard this morning and all nodes in Up status are corresponding accordingly. This issue has been resolved.
