### ISSUE TITLE
implement gedis client to BCDB for identityd

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#224]
The implementation of the BCDB actor has started : https://github.com/threefoldtech/tf_cockpit/issues/7

As this effort is going we need to implement the gedis client in our side so we can gradually replace all the client we use to talk to our bcdb_mock with the real one.

We have multiple location in our code base where we have implemented a part of the BCDB interface:
- https://github.com/threefoldtech/zosv2/blob/master/modules/identity/store.go
- https://github.com/threefoldtech/zosv2/blob/master/modules/network/tnodb/store.go 

Could be I missed some place where we have other code talking to BCDB, so an audit of the full code is probably required.

Part of this task should be implemented some interoperability tests between our go client and the python BCDB actors

**Comment by zaibon** [comment]
to win time we can generate the type expected by the gedis actor using [schemac](https://github.com/threefoldtech/zosv2/tree/master/tools/schemac).
So internally in the gedis client these types are used, but they are then converted to the type 0-OS expect. This will allow us to have a layer in case something change in any of the sides.

JSX schema are located at: 
- https://github.com/threefoldtech/jumpscaleX_threebot/tree/development/ThreeBotPackages/threefold/tfgrid_workloads/models
- https://github.com/threefoldtech/jumpscaleX_threebot/tree/development/ThreeBotPackages/threefold/tfgrid_directory/models

**Comment by maxux** [comment]
Also use: 
- `modules/provision/remote_store.go`

I'm doing some test and playing with schemac right now

**Comment by maxux** [comment]
Does the `network/tnodb/store` needs to be ported to BCDB too ?

**Comment by maxux** [comment]
Status:
- set, get, list, update node resource implemented
- set, get, list, update farm implemented
- some tests written

But some issues:
- Conflict in model between farmid (integer or string), need to clarify
- Issue with redigo on return value for capacity stuff (update works well, response fails)

Will discuss tomorrow to see how fix theses stuff
