### ISSUE TITLE
managed ssh keys

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#2250]
Right now the zos imagine contains few authorized keys for some developers to allow remote debugging*. IMHO this shouldn't be hardcoded in the base image but instead, managed upon request as follows:

- On boot, identityd should take control over authorized keys. It can start it completely removing it from the root. This will make sure the base images keys are ineffective. 
- Based on the set of usernames that should be defined in `zos-config` repo (need to be added), the defined users keys are then retrieved fro github and updated into the authorized_keys files. ONLY this set of users are.
  - Normally this list then should be empty for mainnet.
  - Should this keys be fetched periodically ? or is it a one time thing!
- For all networks except mainnet, identityd should also respect an optional kernel cmdline argument (say `ssh-key`) that accepts a username, this user key is fetched from github and added to the list of pre-configured users from zos-config before updating the authorized keys files.
- Special case for mainnet freefarm since we always need access to this one for development and debugging purposes, the keys should use the list from testnet always.

> *remote debugging: this is only possible to networks that are actually reachable by developers so in real life this is probably only possible for freefarm and local development nodes

**Comment by Eslam-Nawara** [comment]
# Investigation and Solution:
- currently, I'm investigating the issue and have questions,
   - if we assumed that this is run only once, is there something indicating that `identityd` is running for the first time?
   - the other case if we run it periodically, are we sure that the user won't add another ssh key manually to the `authorized_keys` file, then the update will overwrite it?
- investigating `google/go-github` to use it to get a file content from GitHub.
