### ISSUE TITLE
supporting using HDD for virtual machines workloads

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#2258]
Right now, we leave HDD exclusively for zdb.  More requests are coming in that we need to support using HDD also for vm workloads, that includes
- rootfs volumes 
- virtual disks

The original proposal suggests we only allow this if a special boot flag is given to the node (say hdd-provision) but this will make it hard for clients to choose which node to use specially that HDD storage has to be requested specifically by the client duo to the performance impact.

Extra care has to be taken with "capacity reporting" to make sure correct storage grade is reported correctly

**Comment by ashraffouda** [comment]
https://github.com/threefoldtech/zos/pull/2265

**Comment by A-Harby** [comment]
Verified, After a few try and failing errors, we were able to deploy a real node with only HDD with the `missing-ssd` flag, Can read more here:https://github.com/threefoldtech/zos/issues/2367.

Also, I created an issue for the docs: https://github.com/threefoldtech/info_grid/issues/595.

Another issue is related: https://github.com/threefoldtech/zos/issues/2376
