### ISSUE TITLE
[zui] on boot, zui takes really long time before it shows anything.

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#2263]
## Description 
On boot, zui starts and you already can see screen has rendered black. But then it takes a lot of time before it shows anything. This is (i assume) duo to it trying to make zbus calls to other services to collect information but those services are not up yet.

What we need to do is:
- Make sure we should the ZUI interface. Show missing information as (loading) without blocking the entire interface.
- Show loading progress somehow ? maybe list of services and their status

**Comment by Eslam-Nawara** [comment]
Work Completed:
- updated `zui` start immediately and not block until services are up.
- updated the start screen to show the status of some services until the services are active, then show the Network conf and system resources as normal.

**Comment by ashraffouda** [comment]
verified
