### ISSUE TITLE
cloud-console on full vm wireguard dashboard link not working

### ISSUE THREAD

**Issue by mik-tf** [threefoldtech/zos#2267]
# Situation

- Deploy a full vm on the TF Dashboard (main or test nets)
- set wireguard
- can't access the cloud-console as written [here](https://github.com/threefoldtech/zos/blob/main/docs/manual/zmachine/cloud-console.md)
- `10.20.4.1:20002` in this case

# Solution

- Make sure cloud-console is set for all deployments with wireguard

**Comment by muhamadazmy** [comment]
Hi, there were an issue indeed with cloud-console that has been fixed here https://github.com/threefoldtech/zos/pull/2237

Unfortunately this is not on mainnet yet

**Comment by muhamadazmy** [comment]
@Mik-TF can you try the console on devnet see if u still have issues with it?

**Comment by mik-tf** [comment]
I confirm it works on devnet
