### ISSUE TITLE
404 link

### ISSUE THREAD

**Issue by Kaya-Sem** [threefoldtech/zos#2280]
## Describe the bug
In the github repo discription, there is a link to `threefold.io/grid`, which doesn't exist. Was that link supposed to link to some part of documentation, or to the grid dashboard?
![image](https://github.com/threefoldtech/zos/assets/73200952/bb28b47d-0a44-4427-9c08-0d5fc2efe04c)
![image](https://github.com/threefoldtech/zos/assets/73200952/19423c0b-4f7a-4102-9832-1afa2c31c822)

## To Reproduce

    1. Go to homepage of this repo
    2. Click on link in description.

**Comment by muhamadazmy** [comment]
Thank you for reporting this. I fixed the link :)
