### ISSUE TITLE
make image debug tool works for micro vms' images

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/zos#2290]
now image debug tool can only used for full vms images it depends that the image has a kernel which is not the case for micro images. this can be done if we provided the required params while starting cloud-hypervisor to provide the kernel and then can be used for those micro images

**Comment by muhamadazmy** [comment]
I think the best thing the script can do is to automatically download and use the cloud-container kernel+initramfs. Currently they are only available as flist. Which means the script will have to depend on rfs (v1) to be able to download and use that from the hub.
