### ISSUE TITLE
network speed tests are limited to 1mb

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/zos#2325]
![image](https://github.com/threefoldtech/zos/assets/64129/2b365f96-292d-4ea7-b871-31fb8a9450a6)
![image](https://github.com/threefoldtech/zos/assets/64129/b2a0164d-29ba-42c7-9465-0c510dca8533)

**Comment by muhamadazmy** [comment]
I think the entire iperf test suite need to be reviewed. right now an iperf server supports only one connection at a time. Not sure if that was best approach.

we can definitely build a "simpler" test suite for this sacrificing the accuracy a little bit for better management

**Comment by xmonader** [comment]
I believe the test should be maybe downloading a known file on zos node e.g the kernel.efi file or from a known link e.g ubuntu iso

**Comment by Omarabdul3ziz** [comment]
Verified

iperf3 works fine now, its bandwidth is unlimited. and nodes show reasonable results 
![image](https://github.com/user-attachments/assets/0020cb12-d338-4a14-b7b4-a5484e81ce14)

are we still considering finding an alternative option for testing speeds? or ok to close?

**Comment by xmonader** [comment]
@Omarabdul3ziz we can create more tickets for any suggested enhancements
