### ISSUE TITLE
provisiond: make 0-db container IP deterministic

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#233]
follow up issue from https://github.com/threefoldtech/zosv2/issues/218

Since a same reservation can be deployed multiple time (in case the node goes down for example) we need to make sure that the connection information stays the same between the two deployment. otherwise the client won't be able to connect to its workload after the node is back online.

We have deterministic IP allocation for normal container but not for 0-DB container.

0-db container get a public IP via SLAAC, so we don't control it at all. a 0-db can get different IP between 2 reboot of a same node.

**Comment by muhamadazmy** [comment]
I have no idea what SLAAC is, so if given more information I can work on this.

**Comment by delandtj** [comment]
https://tinyurl.com/yyuo556u
