### ISSUE TITLE
Add mycelium support to zos

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/zos#2338]
we need to run myceilum instance for zos to be able to download flists overy myceilum network

**Comment by Eslam-Nawara** [comment]
### WIP: 
- Integrated mycelium in zos host.
- Support serving flists over mycelium.
- Add mycelium support for zdbs with backward compatibility.
- Tested mycelium on the host, and connecting zdbs over mycelium.

> Need to test the update against node with public namespace.

**Comment by A-Harby** [comment]
Verified, devnet.

I was able to deploy ZDB using ts client and connect to mycelium ip.
![image](https://github.com/threefoldtech/zos/assets/109473873/6a3cb6ef-7bf7-4471-a99b-5bf5672be389)
![image](https://github.com/threefoldtech/zos/assets/109473873/3741c42d-a8ac-4551-b0c2-1a3a4ef92eb5)
