### ISSUE TITLE
Node 1479 doesn't pick up the last update of 3.10.6

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/zos#2347]
## Describe the bug

zos version is outdated. 

## To Reproduce

- Ping node 1479 using RMB
- Check zos version

## Expected behavior

the version should be 3.10.6

## Screenshots

![image](https://github.com/threefoldtech/zos/assets/40770501/72db3fbe-bb3d-401c-944e-457a25708a8c)

**Comment by xmonader** [comment]
Which network?

**Comment by zaelgohary** [comment]
> Which network?

main.

**Comment by ashraffouda** [comment]
all nodes?

**Comment by zaelgohary** [comment]
> all nodes?

It happens with some nodes only like 1479 in main.

**Comment by ashraffouda** [comment]
the node is behind for a couple of versions and it has a read only file system, so the only way is to ping the farmer to reboot his node to get the new version 
![image](https://github.com/threefoldtech/zos/assets/1689456/ddef89b1-e549-4f67-b6a2-8d010a96eb0f)
