### ISSUE TITLE
Vm deployment with GPU crashes

### ISSUE THREAD

**Issue by maayarosama** [threefoldtech/zos#2349]
## Describe the bug

I tried deploying a VM on node ```4771``` with a GPU after renting it, but I couldn't ssh to it, after some investigation and getting the changes of the contract, I noticed that the status of the contract is ```deleted```

```

[
  {
    version: 0,
    name: 'vmgpuDisk',
    type: 'zmount',
    data: { size: 107374182400 },
    metadata: '',
    description: 'test deploying VM with GPU via ts grid3 client',
    result: { created: 1717314878, state: 'init', message: '', data: null }
  },
  {
    version: 0,
    name: 'vmgpu',
    type: 'zmachine',
    data: {
      flist: 'https://hub.grid.tf/tf-official-vms/ubuntu-22.04.flist',
      network: [Object],
      size: 0,
      compute_capacity: [Object],
      mounts: [Array],
      entrypoint: '/',
      env: [Object],
      corex: false,
      gpu: [Array]
    },
    metadata: '',
    description: 'test deploying VM with GPU via ts grid3 client',
    result: { created: 1717314878, state: 'init', message: '', data: null }
  },
  {
    version: 0,
    name: 'vmgpuDisk',
    type: 'zmount',
    data: { size: 107374182400 },
    metadata: '',
    description: 'test deploying VM with GPU via ts grid3 client',
    result: { created: 1717314880, state: 'ok', message: '', data: [Object] }
  },
  {
    version: 0,
    name: 'vmgpu',
    type: 'zmachine',
    data: {
      flist: 'https://hub.grid.tf/tf-official-vms/ubuntu-22.04.flist',
      network: [Object],
      size: 0,
      compute_capacity: [Object],
      mounts: [Array],
      entrypoint: '/',
      env: [Object],
      corex: false,
      gpu: [Array]
    },
    metadata: '',
    description: 'test deploying VM with GPU via ts grid3 client',
    result: { created: 1717314887, state: 'ok', message: '', data: [Object] }
  },
  {
    version: 0,
    name: 'vmgpu',
    type: 'zmachine',
    data: {
      flist: 'https://hub.grid.tf/tf-official-vms/ubuntu-22.04.flist',
      network: [Object],
      size: 0,
      compute_capacity: [Object],
      mounts: [Array],
      entrypoint: '/',
      env: [Object],
      corex: false,
      gpu: [Array]
    },
    metadata: '',
    description: 'test deploying VM with GPU via ts grid3 client',
    result: {
      created: 1717314925,
      state: 'deleted',
      message: 'workload decommissioned by system, reason: deleting vm due to so many crashes',
      data: null
    }
  }
]
```

I also tried deploying a VM on the same node without GPU and  everything was fine

## To Reproduce

    1. Rent node ```4771```
    2. deploy a vm with gpu on it
    3. try to ssh

**Comment by ashraffouda** [comment]
which env?

**Comment by maayarosama** [comment]
> which env?
> 
> 

Mainnet

**Comment by ashraffouda** [comment]
seems there is an issue with this node since it worked on other nodes
here the contract is created 
![Screenshot from 2024-06-02 17-27-35](https://github.com/threefoldtech/zos/assets/1689456/46558d7b-869b-4fcd-ae7a-de24ca9ab438)
and here like after 1hour  the node received a cancel contract event 
![Screenshot from 2024-06-02 17-30-40](https://github.com/threefoldtech/zos/assets/1689456/46f84c2b-5fc0-48b1-b7a8-f60da93db73a)

**Comment by ashraffouda** [comment]
seems there is an issue with this specific node because cloud container is giving error `deleting vm due to so many crashes`
I verified the node has the correct zos version also the node is not in freefarm so we can not ssh to it to check on the node itself

**Comment by ashraffouda** [comment]
also for some reason grid proxy seems giving wrong info about this specific node because now it says the node has gpu but the node doesn't show up as a rentable node while it is not  rented  also doens't have network contracts 
![image](https://github.com/threefoldtech/zos/assets/1689456/e83541f6-cc01-4691-9b38-7798b04f85f6)

**Comment by ashraffouda** [comment]
let's follow up here for grid proxy first 
https://github.com/threefoldtech/tfgrid-sdk-go/issues/1061

**Comment by ashraffouda** [comment]
so this look like a node issue maybe network issue, I tried using grid-cli it sometimes fails and sometimes it succeed something like the following 
![Screenshot from 2024-06-05 16-59-49](https://github.com/threefoldtech/zos/assets/1689456/e66ca383-ae68-4ee6-9994-e167333479fa)


![Screenshot from 2024-06-05 17-00-15](https://github.com/threefoldtech/zos/assets/1689456/67529199-fa40-498b-a0f8-1f942f1f60d4)

**Comment by ashraffouda** [comment]
now it works all times maybe it was a network issue and it is fixed
