### ISSUE TITLE
node can't deploy a workload even if it covers the required capacity 

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/zos#2351]
for example. node 11 have `total_sru=512110190592` and `used_sru=480436551680` so it should have free `31673638912` around 29GB but it can't deploy a workload asking for sru more than 22GB.

if fails with this error:
```
failed to create vm rootfs: not enough space left in pools of this type ssd
```
it may be because the node splitting its SSD to pools and no pool can cover the requested SSD 
 https://github.com/threefoldtech/zos/blob/02480a938b32294cca7031866262a017c0bae7fb/pkg/storage/storage.go#L741

**Comment by Omarabdul3ziz** [comment]
after some debugging here what i found:
- both grid clients go/ts do ask for `zos.storage.pools` before it considers the node appropriate to host this workload.
- what will happen in the parent issue is, the script asks for sru with only the disk size which the node can cover its capacity. but will deploying the machine required extra sru for rootfs which the node couldn't afford.

reported to edit the script.

it is not an issue, safe to close

**Comment by Mahmoud-Emad** [comment]
What is the required extra sru for rootfs? 2GB?

**Comment by Omarabdul3ziz** [comment]
as far as i remember if the provided rootfs is zero, there is an equation that will calculate it from the CU (ram/cpu) or at least yes will be 2GB. @AhmedHanafy725 can clarify more on that
