### ISSUE TITLE
irregular distribution of grid endpoints over all nets

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/zos#2353]
## Is your feature request related to a problem? Please describe
irregular distribution of grid endpoints over all nets

https://github.com/threefoldtech/zos/blob/main/pkg/environment/environment.go#L107-L167

## Describe the solution you'd like

Ops maintains two full backend stacks for each net, so each net has a spare url for each service to stay operational. zos currently makes use of this but does not make use of all available endpoints. Following list lacks in the config:

# Devnet
### TFchain
- wss://tfchain.02.dev.grid.tf

### Activation service
- https://activation.02.dev.grid.tf/activation/activate

### Graphql
- https://graphql.02.dev.grid.tf/graphql

-- -- --

# QAnet
### Relay
- wss://relay.02.qa.grid.tf

### Activation service
- https://activation.02.qa.grid.tf/activation/activate

### Graphql
- https://graphql.02.qa.grid.tf/graphql

-- -- --

# Testnet
### TFchain
- wss://tfchain.02.test.grid.tf

### Activation service
- https://activation.02.test.grid.tf/activation/activate

### Graphql
- https://graphql.02.test.grid.tf/graphql

-- -- --

# Mainnet
### TFchain
- wss://tfchain.02.grid.tf

### Activation service
- https://activation.02.grid.tf/activation/activate

### Graphql
- https://graphql.02.grid.tf/graphql

**Comment by Omarabdul3ziz** [comment]
verified: found all mentioned endpoints on the code
