### ISSUE TITLE
support `<subdomain>.<name>` in gateway

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#2354]
Right now you can configure a gateway with a reserved `<name>` on the chain. Since we already own the `name`, then it's good idea to also allow configuring subdomains to my name, say `images.azmy` for example where azmy is the reserved name contract. and images is a subdomain (that doesn't require reservation).

Hence later i can do other gateway deployment with a 'name' that is actually subdomain+name as follows
- images.azmy
- about.azmy
- images.azmy

the gw, will verify that I own the name `azmy` and then allow configuring this subdomain to be served as
```
- images.azmy.<gw-root-domain>
- about.azmy.<gw-root-domain>
- images.azmy.<gw-root-domain>
```

**Comment by rawdaGastan** [comment]
Reverted because ssl certificates are not allowed for subdomains
