### ISSUE TITLE
Registration Failed while booting Zero-Os Node without SSD Disk

### ISSUE THREAD

**Issue by atefnazmy** [threefoldtech/zos#2367]
## Describe the bug

- While trying to boot Zero-Os Node without SSD disks then the registration failed, despite the same node working fine if the SSD disk was attached 

![photo](https://github.com/threefoldtech/zos/assets/32517137/63515816-7c9f-4baa-b8a3-05dd7652a56e)

[video_720p_25fps_10pts.webm](https://github.com/threefoldtech/zos/assets/32517137/9a0c040f-aadd-48a8-a584-1be9393007fc)

## Related Issue
https://github.com/threefoldtech/tfchain/issues/967

**Comment by A-Harby** [comment]
Still failing with the missing-ssd flag.

![image](https://github.com/threefoldtech/zos/assets/109473873/ca173390-9b7b-49fc-99f7-28db8eaf1481)

**Comment by ashraffouda** [comment]
so this works after @atefnazmy changed the sata config in bios to `AHCI`, nice catch ya Atef. we will add it to the docs because this may happen with other nodes too

**Comment by mik-tf** [comment]
@ashraffouda we have this in the manual: https://manual.grid.tf/documentation/farmers/farming_troubleshooting.html?highlight=ahci#disk-not-recognized-by-zero-os

EDIT: Will add a section on the farmers' manual on how to boot nodes with only HDD. will add the AHCI part.
