### ISSUE TITLE
Add validation on the workload name's length

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/zos#2368]
Currently, ts and go clients are using different validation for the workload names which broke the loading deployments in the dashboard. 

Related issues: https://github.com/threefoldtech/tfgrid-sdk-go/issues/1055, https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2364

### Suggestion

We can add the validations here so all clients can follow them.

The required extra validation is on the workload name's length, maybe 50 characters.

**Comment by Omarabdul3ziz** [comment]
https://github.com/threefoldtech/tfgrid-sdk-go/issues/1055#issuecomment-2419558915

**Comment by Omarabdul3ziz** [comment]
Verified

- passed the validation on the client by commenting
- tried to deploy a workload with long name and it failed
![image](https://github.com/user-attachments/assets/8ed61c38-9fd3-4d54-b495-3e212a4f6b01)
