### ISSUE TITLE
Zero-Os node main Screen doesn't display the HDD errors correctly.

### ISSUE THREAD

**Issue by atefnazmy** [threefoldtech/zos#2376]
## Describe the bug

After booting Zero-Os with only HDD disk, If the HDD has any errors or isn't wiped correctly, then the main screen doesn't show the HDD error and only displays that "no ssd disks detected"

![nossd](https://github.com/threefoldtech/zos/assets/32517137/d63f0931-aa18-4ce5-b0fb-2adb3854498e)
 

## Expected behavior
- It would be better to show a message that display the error of HDD more clearly.

**Comment by Eslam-Nawara** [comment]
## Work Completed: 
- update disks error message
- update powerd to log registration errors to zui erros
![image](https://github.com/user-attachments/assets/ac64db35-a99b-4167-a730-f363c4cab288)

**Comment by rawdaGastan** [comment]
### Verification

- Tried to remove disks before running the node

![image](https://github.com/user-attachments/assets/a90493f6-b7ee-4fcc-a96b-a2ef497df60d)

- Got `no disks` error

![image](https://github.com/user-attachments/assets/21accd5d-cd63-477d-bd43-5da4e2d5e39c)
