### ISSUE TITLE
zos to work on cloud providers 

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/zos#2378]
we need to support an new version of networkd where we have mycelium without ygg, public ip and wireguard more specs is here 
https://github.com/threefoldtech/zos/tree/fecd21a5f475e5c6680f00f800700dc4a64f4704/docs/internals/network-light

**Comment by AbdelrahmanElawady** [comment]
ZOS networking has been updated and the node is functioning. As for workloads, we currently have support for vms, networks and zdbs while qsfs and gateways still need some updates.

There are also some modifications for ZOS API that needs to be handled (features endpoint and network/admin endpoints).

**Comment by ashraffouda** [comment]
so far what is done 
- deploying a network
- deploying a vm 
- deploying zdb 
- changes in bootstrap  but not tested yet
- changes in identityd and upgrader but not tested yet

what still not done yet is 
- changes in  update_worker that runs on the hub 
- changes in initramfs to have bootstrap and internet they will become part of the base image
- need to try on a real machine
- creating a fork for the new zos light repo

**Comment by iwanbk** [comment]
> we need to support an new version of networkd where we have mycelium without ygg, public ip and wireguard more specs is here
https://github.com/threefoldtech/zos/tree/fecd21a5f475e5c6680f00f800700dc4a64f4704/docs/internals/network-light

I see that the specs is still a draft / in WIP.
Does the specs considered final now and we follow it all?

**Comment by ashraffouda** [comment]
https://github.com/user-attachments/assets/ae9ebcf4-0313-497b-9115-12676daccd3e
