### ISSUE TITLE
Outdated Quickstart docs for Zos

### ISSUE THREAD

**Issue by rowangamal** [threefoldtech/zos#2388]
## Outdated Quickstart for Zos

The [quickstart](https://github.com/threefoldtech/zos/blob/main/docs/development/quickstart.md) docs is outdated regarding many points:

1. Only Qemu is required now, dnsmasq actually made me some extra problems with ports and it isn't needed.
2.  The [Create a farm](https://manual.grid.tf/farmers/3node_building/1_create_farm.html) link is linking to an unfound page, I think the new link should be [Create a farm](https://manual.grid.tf/documentation/farmers/3node_building/1_create_farm.html#create-a-farm)
3.  `Setup the network using this script [this script](https://github.com/threefoldtech/zos/blob/main/qemu/net.sh)` isn't needed anymore --> substitute by running
```
cd qemu && make net
```
4.  The line `sudo ./vm.sh -n node-01 -c "farmer_id=<your farm id here> printk.devmsg=on runmode=dev"` also could be subbed by: (in qemu directory)
```
make run id=<farm id> user=<your github user>
```

**Comment by SalmaElsoly** [comment]
### 13-10-2024
5. add option to download image by using make prepare 
```bash
cd qemu && make prepare
```
