### ISSUE TITLE
Node screen stuck at "Registration is still in progress" While the Node is online on dashboard and offline after a while.

### ISSUE THREAD

**Issue by mahendravarmayadala93** [threefoldtech/zos#2389]
Farm ID : 881

Node ID : 1071 

The Node screen stuck at " Registration is still in progress" while the Node is online on dashboard and offline after a while.

![img20240731085702_d1a780](https://github.com/user-attachments/assets/827640bb-be7d-4672-8bdc-ee2d017f3afb)

Node Logs screen shots

![image_i0i9n4](https://github.com/user-attachments/assets/3d15115b-f1a1-4652-88c2-8877841c47b5)

![6147521437230021684](https://github.com/user-attachments/assets/81b0f91f-cc6e-447d-87ca-b0a0c7a6c451)

![6150204915616694470](https://github.com/user-attachments/assets/bec1f2a7-5841-4bac-8e33-532ba7afaf1e)

Recent changes to health checking and reporting on the node console, as noted by @scottyeager, may be causing this issue to function improperly.

**Comment by xmonader** [comment]
Looks like a broken disk?

**Comment by scottyeager** [comment]
Yes, looks indeed like a failed disk. The question is why doesn't the error appear on the console screen.

**Comment by mahendravarmayadala93** [comment]
> Yes, looks indeed like a failed disk.
Hi @scottyeager !Can you confirm if we can recommend RMA as the next step?

**Comment by Eslam-Nawara** [comment]
error not appearing on the console screen is fixed [here](https://github.com/threefoldtech/zos/issues/2409)
