### ISSUE TITLE
get repository ready for prime time

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#240]
Now that we are close to release the first version of 0-OS v2. We should make sure this repository looks the way it should.

- [x] set topics
- [x] add contributor guideline
- [x] review main README 
  - [x] quick introduction
  - [ ] links to docs, specification, other documentation about TF grid
- [x] Rename repository
- [ ] Have proper milestone for next versions

Regarding the renaming of this repo. When we created it I just called it zosv2 but this is not a valid name. I'm not sure what we should call it though. Some ideas:
- 0-OS (but this will be ugly in painfull in golang imports)
- zos, nice and clean but already used by https://github.com/threefoldtech/zos although this current zos repo can probable be renamed and archived
- ...

**Comment by muhamadazmy** [comment]
I vote for option 2

**Comment by zaibon** [comment]
I kinda like we could use zos too. this is short and easy to write and it works good in a go import path.
I'll open an issue on the current zos repo to rename/archive it then. so we can reclaim the name.

https://github.com/threefoldtech/zos/issues/102

**Comment by maxux** [comment]
Sounds the best idea for import yes

**Comment by delandtj** [comment]
zos.. but then all code imports must be touched ?

**Comment by zaibon** [comment]
> zos.. but then all code imports must be touched ?

yes, a search and replace of the imports needs to happen after the renaming. But since no one depends on us and we have not yet released any version this is a harmless move.

**Comment by maxux** [comment]
We can get a vm with zosv2 up and running quite easily and quickly using qemu doc. With `make kernel` and `make start` (and after setting up the bridge), you are ready to go. That's really cool !

But there are few things missing, important for new users:
- The vm doesn't provide any information about it's status, as soon as `zinit` started. We need to forwards logs to the serial / console. The machine seems frozen and not up and running.
- A new user won't be able to ssh the machine, it's key won't be added (but that's maybe okay)
- We need a walkthrough / quickstart, as soon as your vm is up and running, there is no help to know what to do
- We need some kind of separation between developer documentation and usage documentation. I should not need to know how the internal stuff works to use it

**Edit:** some stuff are available on the `doc-update` branch

**Comment by zaibon** [comment]
PR for contribution guideline is open at https://github.com/threefoldtech/zosv2/pull/292

**Comment by maxux** [comment]
Since my last comment, mostly everything is fixed/included now. I'll go further on the walkthrough with new qemu documentation up-to-date.
