### ISSUE TITLE
Tests and coverage workflow fails

### ISSUE THREAD

**Issue by rawdaGastan** [threefoldtech/zos#2405]
## Describe the bug

- Tests and coverage workflow fails

https://github.com/threefoldtech/zos/actions/runs/10505891426/job/29104380307?pr=2404

**Comment by iwanbk** [comment]
i've added the fix on my PR #2395

**Comment by rawdaGastan** [comment]
Please mention the issue there, Thanks :)

**Comment by iwanbk** [comment]
> Please mention the issue there, Thanks :)

done

**Comment by xmonader** [comment]
> i've added the fix on my PR #2395

Hey @iwanbk please create a separate PR for this one to be reviewed and merged separately

**Comment by iwanbk** [comment]
> Hey @iwanbk please create a separate PR for this one to be reviewed and merged separately

The fix actually already committed last week because my PR also broken because of this issue

**Comment by ashraffouda** [comment]
@iwanbk we need this on a separate PR, can u plz do this?

**Comment by iwanbk** [comment]
> @iwanbk we need this on a separate PR, can u plz do this?

i saw @rawdaGastan already working on it on #2423.

**Comment by Omarabdul3ziz** [comment]
all workflow passed
