### ISSUE TITLE
Read only disk not reported on node console

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#2409]
Farmer sent the following image of their node console output:

![image](https://github.com/user-attachments/assets/011ad55d-4359-482d-ae73-30cf9acda765)

But the node is not submitting uptime reports due to read only disk:

![image](https://github.com/user-attachments/assets/6aa8e527-0f87-4a24-85ce-659b56194c2b)

The only clue that something is wrong is the fact that it says "registration still in progress". I think there should be a clear message regarding the disk issue.

**Comment by mahendravarmayadala93** [comment]
Client shared the log screen, sharing here if it helps.

![img0184_1xl9fx6](https://github.com/user-attachments/assets/df290844-a793-46de-a13e-a8aec82bc158)

**Comment by Eslam-Nawara** [comment]
Verified
tryed running zos3 node 243 and enforced an error message to be returned from the cache check and now it's displayed in zui 
![image](https://github.com/user-attachments/assets/023d7bdb-90d3-40f8-9a78-108b107261d5)

> waiting to be added to zos4

**Comment by Eslam-Nawara** [comment]
tested the update for zos4 node 256 and the cache errors are displayed in zui
![image](https://github.com/user-attachments/assets/24fe0c92-b71e-4e9e-b0eb-119016edba5c)
