### ISSUE TITLE
schemac: missing some datatype support

### ISSUE THREAD

**Issue by maxux** [threefoldtech/zos#242]
From the document: https://github.com/threefoldtech/jumpscaleX_core/tree/development/docs/types

When trying to convert a schema, some type seems not recognized correctly and crash with error like:
```
Error while generating schema: unsupported type in the go generator: &{0   <nil>}
```

This happens with (at least) theses types:
- `T` (date with time)
- `email`

**Comment by muhamadazmy** [comment]
@maxux can u also send me the schema you are trying to compile

**Comment by maxux** [comment]
At that time, it was this one: https://github.com/threefoldtech/jumpscaleX_threebot/blob/5acbd70680643a8fc41e8b1901312bf7adab31e3/ThreeBotPackages/threefold/tfgrid_directory/models/model.toml
