### ISSUE TITLE
add features endpoint for zos3 and zos4

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/zos#2421]
we need an endpoint that gets the supported features for zos node hence we have two different version now 3 and 4 and each one has its own workload types so we need this for dashboard for example to determine which types of workloads are valid for the node we are deploying on
something like the types here https://github.com/threefoldtech/zos/blob/main/pkg/gridtypes/zos/types.go#L10
the endpoint should return the supported types for workload names

**Comment by Omarabdul3ziz** [comment]
Verified 

call a node with `zos.system.node_features_get` rmb endpoint

zos3 nodes 
![image](https://github.com/user-attachments/assets/b88258bb-d723-4e7a-9f40-1e50da17d088)

zos4 nodes 
![image](https://github.com/user-attachments/assets/eb5668a8-a1ef-49e0-9b25-d503461b2fcd)

respond with the expected
