### ISSUE TITLE
NTP check retries in a hot loop on error and doesn't account for availability of the network

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/zos#2425]
If a node does not have a network/network access, the NTP check is done, resulting in an error, and it seems to be executed in a busy loop

![image](https://github.com/user-attachments/assets/ea69a5c6-3322-408b-9613-0a699ce3a06b)

**Comment by Eslam-Nawara** [comment]
what zos version running in this node? this should be fixed after this issue https://github.com/threefoldtech/zos/issues/2380
https://github.com/threefoldtech/zos/pull/2394#issuecomment-2337627983

**Comment by xmonader** [comment]
I'll close it as duplicated
