### ISSUE TITLE
Issue with Deploying Applications Relying on Docker in zos

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/zos#2426]
## Describe the bug

tried to deploy many images but facing an issue with docker while bulding the applications

next cloud:
<img width="1680" alt="Screenshot 2024-09-22 at 2 49 05 PM" src="https://github.com/user-attachments/assets/747a1d9c-82a0-4feb-b4fd-c603ea8c0441">
presearch
<img width="1680" alt="Screenshot 2024-09-22 at 11 53 46 AM" src="https://github.com/user-attachments/assets/725bde06-5c6c-4799-8674-a31d401eafc6">

**Comment by scottyeager** [comment]
How did you deploy these? Can you show the output of `zinit log dockerd`?

**Comment by ashraffouda** [comment]
we have an issue because we reach the pull limit so this will happen with each solution that pulls images
I suggest that we take the username/password of docker hub before deploying those kind of solution and do docker login with his credentials ![Image](https://github.com/user-attachments/assets/c18c0c33-65de-4dea-ad66-2e636a33312d)

**Comment by ashraffouda** [comment]
related to this https://github.com/threefoldtech/test_feedback/issues/327

**Comment by scottyeager** [comment]
@ashraffouda, was some solution implemented for this? I can't find any reference.

**Comment by ashraffouda** [comment]
> @ashraffouda, was some solution implemented for this? I can't find any reference.
this is not related to zos and there are two issues tracking this 
https://github.com/threefoldtech/tf-images/issues/300
https://github.com/threefoldtech/test_feedback/issues/327
the one in tf-images is enough

**Comment by scottyeager** [comment]
Got it, thanks @ashraffouda. I switched it to "not planned" to make this clearer.

**Comment by xmonader** [comment]
Probably the only solution would be running our own registries or we invest more in providing flists for such solutions, but that will require understanding the solution properly and it's interconnection which is usually hidden by the usage of docker-compose
