### ISSUE TITLE
Compare the node clock to tfchain instead of third party API

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#2439]
We are attempting to use `worldtimeapi.org` to check that nodes have functioning NTP. However, the service seems pretty unreliable and there are a lot of errors in node logs about not being able to connect to it. I noticed in a quick test just now that I got a 502 error when trying to load the json response and the website itself was very slow to respond.

Instead of introducing a dependency on an external service, why not just compare the node's clock against the timestamps of blocks on tfchain? It's accurate enough and also highly available.

**Comment by xmonader** [comment]
multiple strategies got added including tfchain in #2457
