### ISSUE TITLE
reduce mycelium logs

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/zos#2441]
mycelium makes a lot of INFO logs which makes it harder to trace its errors or other modules errors. could we change the log level to a higher version if it is acceptable 
![image](https://github.com/user-attachments/assets/a9da1146-0906-43d7-b33e-b757047512cb)

**Comment by Eslam-Nawara** [comment]
added silent flag when running mycelium and now only errors are logged from mycelium
```console
zinit log mycelium
```
![image](https://github.com/user-attachments/assets/32ead1fb-b8bf-4b53-85cd-367ad4ca92c8)

```console
zinit log
```
![image](https://github.com/user-attachments/assets/51c6062a-6dbf-4861-a51e-bcc1a5166058)

**Comment by Omarabdul3ziz** [comment]
Verified 

now it shows only the error msgs
![image](https://github.com/user-attachments/assets/c844ebea-869b-4a45-995f-cea4fb6cfafc)
