### ISSUE TITLE
Only allow verified user to deploy

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/zos#2444]
require: https://github.com/threefoldtech/tfgrid-kyc-verifier/issues/5

The account's status can be queried from the KYC service using the account's address.

**Comment by Eslam-Nawara** [comment]
## WIP 
After the kyc server is updated I tested the status endpoint and now it's working as expected

I was able to boot a zos node on mainnet that is able to restrict deployments to users with verified accounts and I was able to only deploy on this node with a verified account, deployment failed if the account is not verified

**Note:** this only works with mainnet as there's only one kyc server instance is up only for mainnet, for all other stacks the check is skipped for now

- Deployment with verified account
![image](https://github.com/user-attachments/assets/6254a971-c031-432c-b29b-fd9364533e19)

- Deployment with unverified account 
![image](https://github.com/user-attachments/assets/2b583eab-0e34-4db1-bb69-fad46d7ea4a3)

**Comment by rawdaGastan** [comment]
## Verification for zos3 and zos4

#### Failure scenarios

- Tried to deploy with unverified account and got `unverified` error

![Screenshot from 2024-10-30 13-24-09](https://github.com/user-attachments/assets/b77e1b90-39ce-4ae0-b3f8-97018d9b3426)

- Tried to deploy with unverified account without verification trials and got `no verification` error

![image](https://github.com/user-attachments/assets/4ef054ad-846e-4e04-b27b-246a4a06d9fc)

#### Success scenario

- Tried with a verified account and I could deploy without any errors

Tried a local running nodes `255` on zos4 and `197` on zos3
