### ISSUE TITLE
Review the macvlan -> veth migration 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/zos#2461]
[#2449 ](https://github.com/threefoldtech/zos/pull/2449)

While this has been applied on devnet without a problem as seen in the verification steps, it's suspected to have broken qanet, also worthy to mention, newly booted nodes in qa net worked fine too

**Comment by xmonader** [comment]
@iwanbk please have a look at this one

**Comment by iwanbk** [comment]
> it's suspected to have broken qanet

By this, we don't see error logs or we can't see error logs?

**Comment by xmonader** [comment]
the only thing we got is these nodes could no longer reach outside nor resolve domains e.g geoip service nor worldtimeapi service 
![image](https://github.com/user-attachments/assets/01932c69-737a-43f8-8fbd-e6fae70c766d)

**Comment by xmonader** [comment]
![image](https://github.com/user-attachments/assets/b0537f6c-b32a-4248-ae20-e720fe88a48d)
![image](https://github.com/user-attachments/assets/91e76bf3-2298-425c-b8b5-7d72d3c07831)
![image](https://github.com/user-attachments/assets/43adf5af-38b8-45eb-99c3-25a324ec4fc5)


That's all of the context so far

**Comment by iwanbk** [comment]
quickly check,

possible errors

there is no `rollback` mechanism if it failed in these places
- `MakeVethPair` & `setupNamespace`, what if the old links already deleted, but the new one is broken.

https://github.com/threefoldtech/zos/blob/fef77d50aae534662b104063b6bf1bf0dcd8ce21/pkg/network/migrate_macvlan.go#L73

https://github.com/threefoldtech/zos/blob/fef77d50aae534662b104063b6bf1bf0dcd8ce21/pkg/network/migrate_macvlan.go#L81

- `deleteOldLink`, we should add rollback handler for this case

https://github.com/threefoldtech/zos/blob/fef77d50aae534662b104063b6bf1bf0dcd8ce21/pkg/network/migrate_macvlan.go#L63

It is also with assumption that the three funcs above are implemented correctly.
Will check it further tonight/tomorrow to check the funcs implementation

**Comment by iwanbk** [comment]
another thing to note is this line
```go
veths, err = getOldInterfaces()
```
the old interfaces are `macvlan`, not `veths`. So it is a bit confusing at first

**Comment by xmonader** [comment]
more checking on qanet

system.version twin 10 
```
➜  rmbcmd git:(main) ✗ ./rmbcmd -cmd 'zos.system.version' -twinID=10 -chainUrl='wss://tfchain.qa.grid.tf' -gridProxyUrl='https://gridproxy.qa.grid.tf' -relayUrl='wss://relay.qa.grid.tf' 
{"level":"debug","url":"wss://tfchain.qa.grid.tf","time":"2024-11-01T13:59:11+02:00","message":"connecting"}
2024/11/01 13:59:11 Connecting to wss://tfchain.qa.grid.tf...
{"level":"debug","url":"wss://tfchain.qa.grid.tf","time":"2024-11-01T13:59:12+02:00","message":"connecting"}
2024/11/01 13:59:12 Connecting to wss://tfchain.qa.grid.tf...
{"level":"info","twin":15,"session":"test-client","time":"2024-11-01T13:59:12+02:00","message":"starting peer"}
{"level":"debug","url":"wss://relay.qa.grid.tf","time":"2024-11-01T13:59:13+02:00","message":"connecting"}
========
{
  "zinit": "v0.2.11",
  "zos": "3.12.1"
}

```

diagnostics on twin 10

```
➜  rmbcmd git:(main) ✗ ./rmbcmd -cmd 'zos.system.diagnostics' -twinID=10 -chainUrl='wss://tfchain.qa.grid.tf' -gridProxyUrl='https://gridproxy.qa.grid.tf' -relayUrl='wss://relay.qa.grid.tf' 
{"level":"debug","url":"wss://tfchain.qa.grid.tf","time":"2024-11-01T14:00:47+02:00","message":"connecting"}
2024/11/01 14:00:47 Connecting to wss://tfchain.qa.grid.tf...
{"level":"debug","url":"wss://tfchain.qa.grid.tf","time":"2024-11-01T14:00:48+02:00","message":"connecting"}
2024/11/01 14:00:48 Connecting to wss://tfchain.qa.grid.tf...
{"level":"info","twin":15,"session":"test-client","time":"2024-11-01T14:00:49+02:00","message":"starting peer"}
{"level":"debug","url":"wss://relay.qa.grid.tf","time":"2024-11-01T14:00:49+02:00","message":"connecting"}
========
{
  "healthy": false,
  "modules": {
    "container": {
      "status": {
        "objects": [
          {
            "Name": "container",
            "Version": "0.0.1"
          }
        ],
        "workers": [
          {
            "state": "free",
            "time": "2024-10-31T17:07:53.993904729Z"
          }
        ]
      }
    },
    "flist": {
      "status": {
        "objects": [
          {
            "Name": "flist",
            "Version": "0.0.1"
          }
        ],
        "workers": [
          {
            "state": "free",
            "time": "2024-11-01T12:00:47.510876096Z"
          }
        ]
      }
    },
    "gateway": {
      "error": {},
      "status": {
        "objects": null,
        "workers": null
      }
    },
    "identityd": {
      "status": {
        "objects": [
          {
            "Name": "manager",
            "Version": "0.0.1"
          },
          {
            "Name": "monitor",
            "Version": "0.0.1"
          }
        ],
        "workers": [
          {
            "state": "free",
            "time": "2024-11-01T12:00:47.512361008Z"
          }
        ]
      }
    },
    "network": {
      "error": {},
      "status": {
        "objects": null,
        "workers": null
      }
    },
    "node": {
      "error": {},
      "status": {
        "objects": null,
        "workers": null
      }
    },
    "provision": {
      "error": {},
      "status": {
        "objects": null,
        "workers": null
      }
    },
    "qsfsd": {
      "status": {
        "objects": [
          {
            "Name": "manager",
            "Version": "0.0.1"
          }
        ],
        "workers": [
          {
            "state": "free",
            "time": "2024-10-31T04:35:24.8231712Z"
          }
        ]
      }
    },
    "storage": {
      "status": {
        "objects": [
          {
            "Name": "storage",
            "Version": "0.0.1"
          }
        ],
        "workers": [
          {
            "state": "free",
            "time": "2024-11-01T12:00:46.727246075Z"
          }
        ]
      }
    },
    "vmd": {
      "status": {
        "objects": [
          {
            "Name": "manager",
            "Version": "0.0.1"
          }
        ],
        "workers": [
          {
            "state": "free",
            "time": "2024-10-31T17:07:55.121944571Z"
          }
        ]
      }
    }
  },
  "system_status_ok": false
}
========

```

network.interfaces

```
➜  rmbcmd git:(main) ✗ ./rmbcmd -cmd 'zos.network.interfaces' -twinID=10 -chainUrl='wss://tfchain.qa.grid.tf' -gridProxyUrl='https://gridproxy.qa.grid.tf' -relayUrl='wss://relay.qa.grid.tf' 
{"level":"debug","url":"wss://tfchain.qa.grid.tf","time":"2024-11-01T14:08:12+02:00","message":"connecting"}
2024/11/01 14:08:12 Connecting to wss://tfchain.qa.grid.tf...
{"level":"debug","url":"wss://tfchain.qa.grid.tf","time":"2024-11-01T14:08:13+02:00","message":"connecting"}
2024/11/01 14:08:13 Connecting to wss://tfchain.qa.grid.tf...
{"level":"info","twin":15,"session":"test-client","time":"2024-11-01T14:08:14+02:00","message":"starting peer"}
{"level":"debug","url":"wss://relay.qa.grid.tf","time":"2024-11-01T14:08:14+02:00","message":"connecting"}
========
{
  "zos": [
    {
      "IP": "10.4.0.38",
      "Mask": "////AA=="
    },
    {
      "IP": "2a02:1802:5e:14:a3b1:e36e:1b66:7dec",
      "Mask": "//////////8AAAAAAAAAAA=="
    }
  ]
}
```



list_wg_ports doesn't exist which is weird given it doesn't exist in zos4 image, while this should be a zos3 one


```
➜  rmbcmd git:(main) ✗ ./rmbcmd -cmd 'zos.network.list_wg_ports' -twinID=10 -chainUrl='wss://tfchain.qa.grid.tf' -gridProxyUrl='https://gridproxy.qa.grid.tf' -relayUrl='wss://relay.qa.grid.tf' 
{"level":"debug","url":"wss://tfchain.qa.grid.tf","time":"2024-11-01T14:08:41+02:00","message":"connecting"}
2024/11/01 14:08:41 Connecting to wss://tfchain.qa.grid.tf...
{"level":"debug","url":"wss://tfchain.qa.grid.tf","time":"2024-11-01T14:08:42+02:00","message":"connecting"}
2024/11/01 14:08:42 Connecting to wss://tfchain.qa.grid.tf...
{"level":"info","twin":15,"session":"test-client","time":"2024-11-01T14:08:43+02:00","message":"starting peer"}
{"level":"debug","url":"wss://relay.qa.grid.tf","time":"2024-11-01T14:08:43+02:00","message":"connecting"}
failed to call peer client: %w function is not found

```

node_features gives context exceeded

```
➜  rmbcmd git:(main) ✗ ./rmbcmd -cmd 'zos.system.node_features_get' -twinID=10 -chainUrl='wss://tfchain.qa.grid.tf' -gridProxyUrl='https://gridproxy.qa.grid.tf' -relayUrl='wss://relay.qa.grid.tf'  
{"level":"debug","url":"wss://tfchain.qa.grid.tf","time":"2024-11-01T14:09:29+02:00","message":"connecting"}
2024/11/01 14:09:29 Connecting to wss://tfchain.qa.grid.tf...
{"level":"debug","url":"wss://tfchain.qa.grid.tf","time":"2024-11-01T14:09:30+02:00","message":"connecting"}
2024/11/01 14:09:30 Connecting to wss://tfchain.qa.grid.tf...
{"level":"info","twin":15,"session":"test-client","time":"2024-11-01T14:09:30+02:00","message":"starting peer"}
{"level":"debug","url":"wss://relay.qa.grid.tf","time":"2024-11-01T14:09:31+02:00","message":"connecting"}
failed to call peer client: %w context deadline exceeded

```

**Comment by iwanbk** [comment]
> node_features gives context exceeded

It is expected, right? Because the `noded` is down?
As logged at https://github.com/threefoldtech/zos/issues/2461#issuecomment-2451554558

**Comment by iwanbk** [comment]
> It is expected, right? Because the noded is down?
As logged at https://github.com/threefoldtech/zos/issues/2461#issuecomment-2451554558

Oh, `zinit` will restart the `noded`

**Comment by Omarabdul3ziz** [comment]
i tried to reproduce the issue locally,

to test the two possible scenarios for the migration code to work either a fresh node or live upgrade for the services, i tried
- a node booted from the `fef77d5` the latest zos commit. booted all services successfully and accepted a zdb deployment with veth setup
- a node booted from `c812462` the previous version for all the macvlan/veth work. deployed a zdb on it. then upgraded the services (networkd/noded/provisiond/powerd) with binaries built from `fef77d5` the latest. and it worked as expected converting macvlan to veth.

also checking the code
- the zdb migration work is run by the `provisiond` service. so if it failed it will not break networked neither noded services.
- and checking the possible side effects.. all the setup/deletion we do is for `zdb-ns-*` namespace or one of `eth0`/`ygg0`/`my0` interfaces inside it. the host bridges `br-pub`/`br-ygg`/`br-my` is not affected by the code. so if the process fails and will not rollback *we should handle this indeed* this will not take the whole node network down.

trying to boot a node from bootstrap with `qa` runmode. i got these errors:
![Pasted image 20241102040235](https://github.com/user-attachments/assets/7655b775-1de1-4c40-93b6-d25bdb3be002)

- the failing connection to the `worldtimeapi` is just a check. so it will not block the `noded` service. this node still respond to rmb calls
- even the node got the latest release `v3.12.1` which has the chain client updates it is failing. this error is fatal so `provisiond` service is broken. but also this doesn't explain all nodes doesn't respond to rmb calls.

**Comment by xmonader** [comment]
Can you confirm that the node after the upgrade is a zos3 node not a zos4 node? and show the output of zos.system.node_features_get?

**Comment by Omarabdul3ziz** [comment]
the nodes booted from the src (either booted from latest commit, or an old commit with live upgrade for the services) respond as zos3 nodes, here is the features
![image](https://github.com/user-attachments/assets/7a010ddd-f535-40ed-9c09-a10ae54ef9c9)

but the node that booted from bootstrap in qa mode responds with zos4 features
![image](https://github.com/user-attachments/assets/a9ebec64-769b-4f64-b830-7aee16ac043d)

also found only one `UP` node on test net https://gridproxy.test.grid.tf/nodes/95  it reports with a zos4 features set

this explains the chain error we got when booting from bootstrap but not when booting from src. also why the  `zos.network.list_wg_ports` endpoint doesn't exists

**Comment by xmonader** [comment]
@Omarabdul3ziz please close the ticket and open new one for iwan's notes the rollback and the confusion of the interfaces names

**Comment by Omarabdul3ziz** [comment]
- https://github.com/threefoldtech/zos/issues/2473
