### ISSUE TITLE
Farm : 615 (Certified) Node : 2150 - Registration is still in progress

### ISSUE THREAD

**Issue by mahendravarmayadala93** [threefoldtech/zos#2484]
The client reached out on Nov 8, 2024, inquiring about the status of Node 2150. The last reported uptime for the node was August 22, 2024, at 01:10:12 GMT. I recommended that he connect the node to the Monitor and share a screenshot, which displayed the error "Registration is still in progress."

The [Dashboard](https://dashboard.grid.tf/#/deploy/node-finder/?farm-id=615&nodeId=2150) and [Gridproxy](https://gridproxy.grid.tf/nodes/2150/status) indicate that the node is offline. There have been three recent uptime events, with the latest occurring on Mon, Nov 11, 2024, at 23:52:30 GMT.

A screenshot was received from the farmer.

![image0 (4)](https://github.com/user-attachments/assets/58a44cee-b0b9-4edc-a7fe-0db90f8a6198)

Node logs as per mon.grid

![6168161916183232785](https://github.com/user-attachments/assets/26bd92d5-6ce8-44cc-9c1f-3bd83505d7e6)

**Comment by mahendravarmayadala93** [comment]
Hi @xmonader ! Would you mind sharing your insight here? Thanks in advance.

**Comment by ashraffouda** [comment]
it seems the nodes is not getting updates the node has read-only file system, so if it is rebooted this should be solved the problem
