### ISSUE TITLE
update tfuser to work with revised network

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#287]
Since https://github.com/threefoldtech/zosv2/pull/278/commits/8a4b100375139ef7f0d8b13573c9d6389e014385 the network definition has changed and tfuser doesn't build anymore.

We should update tfuser to make it compatible with the new network design.

**Comment by maxux** [comment]
We need to update `tfuser` to be able to talk with bcdb, maybe we can group into this issue.
