### ISSUE TITLE
networkd: failes to apply nft rules

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#304]
it fails with the following error
```
[-] networkd: 10:06AM FTL failed to create DMZ error="failed to apply nft rule set: failed to execute nft: : exit status 1"
```

**Comment by zaibon** [comment]
required version of nft is 0.9.1 to works with our current code base.
upgrade has been done at https://github.com/threefoldtech/0-initramfs/pull/24 build is on the way

**Comment by zaibon** [comment]
with the updated image I don't hit the bug anymore. @muhamadazmy can you double check ?
link to the image: https://bootstrap.grid.tf/kernel/zero-os-development-zos-v2-generic-5ad8ab3534.efi
