### ISSUE TITLE
Secure Boot process validation for HPE hardware

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/zos#309]
We need to test the usage of the Silicon Root of Trust for certified farming equipment.

HPE makes servers which use silicon with keys embedded in the motherboard which TF can use to create the unique identifier for the farming equipment.

Documentation is available here: https://drive.google.com/open?id=1zxf29102vNHrdupdGCKRYtvJgdqKsPg-

**Comment by maxux** [comment]
Actually, what we would need is HSM Module integrated.
https://en.wikipedia.org/wiki/Hardware_security_module

A device not (or difficult to) removable, unique identifiable, which contains pair of keys and never expose private key, which can encrypt/decrypt data. Secureboot things are basic and standard features...

**Comment by weynandkuijpers** [comment]
That would be great - and is probably the way forward for other hardware.  For the HPE relationship (partnership) we need to incorporate what they create/have on offer.  iLo5 is that thing.  Can we please have a look at this?

**Comment by zaibon** [comment]
> Actually, what we would need is HSM Module integrated.

Indeed, this issue is not about what we could have, but just to test how we can integrate with what HPE currently provide in it's hardware

**Comment by gneumann333** [comment]
> Actually, what we would need is HSM Module integrated.
> https://en.wikipedia.org/wiki/Hardware_security_module
> 
> A device not (or difficult to) removable, unique identifiable, which contains pair of keys and never expose private key, which can encrypt/decrypt data. Secureboot things are basic and standard features...

Hi, 
The HPE Server all support the Trusted Plattform Module V2.0 would that be what we need?
It would mean that this has to be installed in the Servers.
As far as i know if you installed/activated this module in a Server and then remove it the Server will be disabled until the that specific Module is back in the Server or you make a full reset.

**Comment by gneumann333** [comment]
https://en.wikipedia.org/wiki/Trusted_Platform_Module

**Comment by gneumann333** [comment]
@weynandkuijpers: we also discussed with Miro Polski the concept that the node has a basic Startup script in the locked down bios which then connects to the TF Servers and identifies itself with its UUID which is then connected to a Farmer/Farm.

Question is how would the TPM Module play into this? The Keypairs would have to be enter in the cockpit by the Farmer

**Comment by weynandkuijpers** [comment]
Let's close this one and re-open when we do the pensando review.  the pensando card is able to store private-public keypairs.
