### ISSUE TITLE
networkd: DMZ cannot start if farm dhcp doesn't give IPV4 to public interface of DMZ

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#316]
```
[-] networkd: 10:32AM FTL failed to create DMZ error="public interface in ndmz didn't not received an IP. make sure dhcp is working"
```

**Comment by delandtj** [comment]
DMZ's network interface should:
- have a static mac address (a bit like in [this](https://github.com/threefoldtech/zos/commit/83fe24d5f682aab0db37e38c9ae88410bc23718c#diff-9fc4ae920164ac128184c5f3b9c954d3R95) but where the mac is derived from the Node ID or something)
- a user/farmer-assigned IPv4 address --or-- a deterministic IPv6 address (that is static when the mac is static, so nothing to do here)
