### ISSUE TITLE
bring bcdb mock to same `data` interface as gedis client

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#327]
Currently we have a bcdb mock we use for development and testing, and a gedis client that actually works against bcdb/gedis. 

Currently both the mock and gedis are growing a part, we need to have similar `data` inputs/outputs from both

**Comment by zaibon** [comment]
I started doing the change in bcdb_mock. Opened a draft PR: https://github.com/threefoldtech/zos/pull/336

it contains the update for nodes and farms. I did a quick test and it seems this code is compatible with the cockpit frontend. So that's a good start.
