### ISSUE TITLE
Node and farmer migration to grid 2.0 documentation

### ISSUE THREAD

**Issue by andhartl** [threefoldtech/zos#328]
we have 66 farmers and 600 plus nodes which need to be migrated to grid 2.0.
the main topics are:
- migrate farmers from iyo to 3bot auth
- Zero OS v1.x to Zero OS 2.0
- Zero Tier to Zero Network

Need to prep documentation which farmers can use to migrate

Tasks:
- [x] [Farm network documentation](https://github.com/threefoldtech/zos/pull/325)
  - [x] How does a farm need to look network wise for 0-OS to behave properly
  - [x] Do and don't
  - [x] Explanation about difference between and public and an hidden node
  - [x] IPv6 getting started for farmer
- [x]  Nodes migration
  - [x] [test migration from v1 to a v2](https://github.com/threefoldtech/zos/issues/339)

**Comment by zaibon** [comment]
Documentation wise I want us to have the following topic covered for farmers:
- Farm network documentation
  - How does a farm need to look network wise for 0-OS to behave properly
  - Do and don't
  - Explanation about difference between and public and an hidden node
  - IPv6 getting started for farmer

> Zero Tier to Zero Network

@andhartl : This is not really a farmer specific topic. This concern more the users. Or did I miss the point  ?

> migrate farmers from iyo to 3bot auth

This is going to be covered in the cockpit. A migration procedure will be available there.

**Comment by andhartl** [comment]
@zaibon for me 100% farmer topic.

**Comment by andhartl** [comment]
@zaibon what do you mean with a hidden node?

**Comment by zaibon** [comment]
> @zaibon for me 100% farmer topic.

can you elaborate. Cause in the current version farmer doesn't have to deal with zerotier network at all. So I must be missing the point.

> @zaibon what do you mean with a hidden node?

That is also what farmer will ask, thus the documentation about this concept :-)

**Comment by andhartl** [comment]
@zaibon mean here the network in the datacenter and ho two set up a datacenter farm. not zero network.

**Comment by zaibon** [comment]
@andhartl ok got it. So this fall into the first point I made about networks. So we're round. cool :-)

**Comment by zaibon** [comment]
We have just merged the first documentation regarding the network setup: https://github.com/threefoldtech/zos/tree/master/docs/network

Specifically some documentation on how a farm network should look like: https://github.com/threefoldtech/zos/blob/master/docs/network/setup_farm_network.md

**Comment by andhartl** [comment]
got the point on network config home versus multi node farm.

not sure if the following questions belong to this repo but they have definitely to do with migration:
- how do we migrate a farmers iyo identity to 3bot authentication?
I mean not automated migration but rules on which naming to use etc.
-how do we match node ids (farm organization name in iyo) in previous and new grid version?
this is needed to check how many month the node is still farming (60 - x). Or are there other ways to do this?

**Comment by zaibon** [comment]
> got the point on network config home versus multi node farm.

:+1: 

> how do we migrate a farmers iyo identity to 3bot authentication?

This is not covert in this documentation. I'm working on a more high level document about how to create a farm on the new grid. There I'll cover these question. Here we focus on the hardware only.

**Comment by weynandkuijpers** [comment]
Few comments/remarks from my side:
- more out of interest than anything:  "Obtain an IPv4 subnet from the provider. At least one IPv4 address per node is needed, where all IP addresses are publicly reachable".  Will this go away over time eg. will we continue to need IPv4 addresses or is more convenient for today.  These addresses are rare and therefore more costly by the day.
- I would more the IPv6 section to the beginning of the document.  IPv6 is what's needed for this to work.
- multi-NIC nodes.  I understand you can use multiple NICS - and this has advantages - but what's missing is how I specify (do I need to) what NIC is for booting and which NIC's are for user workloads.

Are you okay for me to change this around and then you tell me if it is still accurate and true?  I will also add in some sections some more questions to explain (if okay?)

**Comment by zaibon** [comment]
>  Will this go away over time eg. will we continue to need IPv4 addresses or is more convenient for today.

Today we support both ipv4 and ipv6 cause we know not all part of the world are ipv6 enable. But our intent is really to drive farmer to have ipv6 enabled node. Ultimate goal with be to have everyone to use ipv6 only. Feel free to submit a PR on the documentation to stress that a bit more if this is not clear.

> I would more the IPv6 section to the beginning of the document. IPv6 is what's needed for this to work.

:+1: 

> multi-NIC nodes. I understand you can use multiple NICS - and this has advantages - but what's missing is how I specify (do I need to) what NIC is for booting and which NIC's are for user workloads.

This is indeed something that is not yet documented. The flow would be the following: 
- Farmer boots its node. 
- The node automatically register into the directory.  (for testnet that is : https://cockpit.testnet.grid.tf/capacity)
- Then the farmer from his 3bot will have a farm management UI where he can specify which NIC the node should use and assign IP to a NIC if needed. 

As soon as this farm management UI is ready I'll add documentation about it here too.
