### ISSUE TITLE
upgrade: support removing services from

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#329]
Currently upgrade, will make sure to start new introduced services from the new image, but now way to remove services that are no longer needed. 

To support this, i have the following plan:
- Create a list of all the services that has been started from the current version. this can be done by remounting the "current" version of the flist or simply get the file listing from the hub (this can be easier) 
- After copying all the services, from new version, a diff is made between new and old version services, and then delete the services that are no longer needed.

**Comment by zaibon** [comment]
This rely on the fact that we can at any point in time get back to a previous version flist. And with the current way of working we only have a pointer to the latest version. We have no way to know which flist to get for the "current" version. And there is also guarantee that the flist will still exists at all.

I also don't think we should rely on the hub special feature for anything, so using file listing should be avoided IMO.

Maybe this is out of scope but this proposal doesn't solve the issue we have for upgrading other component of 0-OS. Like libraries, coreX, or other tools that comes from the base image.

**Comment by muhamadazmy** [comment]
Yes, and No. 
Currently we actually keep the flist information (in /tmp) that does have the linked flist. hence we have the FULL flist that we currently uses (not just the 'latest' symlink) which means we can always check it as long as it was not deleted on the hub.

**Comment by muhamadazmy** [comment]
> Maybe this is out of scope but this proposal doesn't solve the issue we have for upgrading other component of 0-OS. Like libraries, coreX, or other tools that comes from the base image.

No it does not. It's idd out of scope of this issue as u mentioned.

**Comment by zaibon** [comment]
> which means we can always check it as long as it was not deleted on the hub.

That is one of my concern. Since we have no way to prevent an flist from being removed except us not screwing up. So we could live with it for now but I would prefer we have something really immutable for it.

> Currently we actually keep the flist information (in /tmp) that does have the linked flist. hence we have the FULL flist that we currently uses

Can you develop on that. What exactly do we keep in tmp ?

**Comment by zaibon** [comment]
> No it does not. It's idd out of scope of this issue as u mentioned.

But I'm just thinking that if we come up with something to kinda manually deal with the files present or not. We might just as well try to find a solution that solve all our problem at once. Because I think these 2 problems are very similar. How do we manage some file that needs to be deleted and some other that needs to be copied.
