### ISSUE TITLE
Detect if 3Node is physical hardware or virtual machine

### ISSUE THREAD

**Issue by andhartl** [threefoldtech/zos#337]
right now we can not detect if capacity is generated by physical or virtual hardware. virtual hardware can be heavily oversubscribed and would help to cheat the system. that's why we need a detector which makes it clear what we are dealing with.

- [x] research how to detect virtual machines
- [ ] implement VM detection in 0-OS
  - [ ] add new IsVM method on the `ResourceOracle` type https://github.com/threefoldtech/zos/blob/f90d4fdfa516266d74eb391118d5fe4b9b63c8fd/pkg/capacity/capacity.go#L19-L21. The method will call `virt-what` command and parse its output
  - [ ] update main function of capacityd to send the IsVM value to BCDB: https://github.com/threefoldtech/zos/blob/f90d4fdfa516266d74eb391118d5fe4b9b63c8fd/cmds/capacityd/main.go#L61-L62
 - [ ] Update nodes schema so it store the VM detection result: https://github.com/threefoldtech/zos/blob/f90d4fdfa516266d74eb391118d5fe4b9b63c8fd/pkg/gedis/types/directory/tfgrid_node_2.go#L10

**Comment by zaibon** [comment]
I think we don't really care if 0-OS is run from bare metal or virtual machine as long as the capacity it claims it has can actually be delivered. 

What do you have in mind when we detect that 0-OS is running form a VM ?

**Comment by andhartl** [comment]
we should care as the virtualised capacity can spoof capacity which is physically not there (oversubscription). plus we need the distinction between both to introduce managed capacity which is designed for vm capacity and will have most likely a higher difficulty factor which leads to lower tft.

**Comment by zaibon** [comment]
> we should care as the virtualised capacity can spoof capacity which is physically not there (oversubscription)

This issue is not only for VM. And this comes back to the same discussion we already had many times before. If we don't have proper capacity proof. I don't see how we can solve this problem.

> plus we need the distinction between both to introduce managed capacity which is designed for vm capacity

Do we have a document explaining all the different types of capacity ? Does managed is only VM ? is running in a VM automatically makes it managed ? This seems to be a more broad problem then just identifying is 0-OS runs from a VM or not.

**Comment by andhartl** [comment]
for hardware we have the proofs we store with the minting data, correct?
working on the doc for all types of capacity. will reach out to kids tomorrow to get signed off. yes, managed will only be VMs
Talked to @delandtj this morning about if vm vs hardware could be detected. he said that him and maxux already investigated

**Comment by zaibon** [comment]
> for hardware we have the proofs we store with the minting data, correct?

Yep, so for now we can leave with that.

>  working on the doc for all types of capacity. will reach out to kids tomorrow to get signed off. yes, managed will only be VMs

ok sounds good.

**Comment by delandtj** [comment]
http://git.annexia.org/?p=virt-what.git;a=summary

For what I see, that thing does it all. I wonder if it wouldn't be better to have it in an flist, so that it can't be tampered with, and be called once during boot...

I'll assign it to Maxime (not XuX)

**Comment by zaibon** [comment]
We can ship it onto the node from an flist, this is totally fine and we have everything needed in place.
