### ISSUE TITLE
Test migration from node v1 to a v2

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#339]
sub task of https://github.com/threefoldtech/zos/issues/328

In order to prepare the migration of node from the v1 to v2. We need to identify the potential data migration that will be required.

I think the only things we want to migrate is the data on disks. 
Networking, containers and VM are not something we will migrate.

To do so lets try the following test plan:
- boot a node with a v1 kernel.
- create some storage pool / filesystem
- write some data to it.
- shutdown the node
- update the kernel to v2 and boot
- check that storaged can mount the storage pool properly
- try to mount the storage pool into a container.

**Comment by muhamadazmy** [comment]
I will test if the partitioning schema and subvolumes from v1 are compatible with v2. While I highly doubt it.
We can of course automate migration of labels and volume names to work with v2 without any loss of data, but there is noway we can reference this data anymore in v2:

- You would never know which sub-volume goes where
- Also you would have sub-volumes with no reservations, so you won't know what belongs to whom!

I will still look into the migration-ability of the partitions, and if we need to introduce a migration script to migrate or wipe the partitions entirely.

**Comment by muhamadazmy** [comment]
Okay, after some offline discussions we come to the following process for node migration:
- Detect old disk partitioning schema 
- Wipe
