### ISSUE TITLE
Networkd : support port forward 

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#352]
This issue describe a new network primitive we want to add to 0-OS. Port forward.

The first use case for it would be to allow the `tf_gateway` to connect to public nodes to forward traffic from public internet to the public ipv6 address of the nodes and inside the private network of the users.
Routing traffic like that allow nodes to not have to share a wireguard network with the TF gateway, which has shown to be a management nightmare.

Introducing this means all public nodes eventually becomes high traffic point of the network. We probably should keep that in mind and assess if that could become a problem. This also raise the question on how are we going to monetize these port forward since they will induce more traffic on the farmer network.

Now from a technical perspective, how are we going to implement this.
I see one major issue that needs to be solve for this feature to be implemented. The sharing of the spare resource that are ports on a node.
We already pretty much deal with this problem for the wireguard port. Which mean we can probably tackle it the same way.

Every time a node has one of its port reserved. The node send the list of all of its used port to BCDB. So a 3bot/users can always see what is available or not. For a first early version that should be enough.
We know this solution won't scale very well as soon as we'll have a lot of reservation happening concurrently though.

From user interface perspective. I think we need to add the port forward to the [provision.Network](https://github.com/threefoldtech/zos/blob/master/pkg/provision/container.go#L19) struct.
```go
// Network struct
type Network struct {
	NetwokID pkg.NetID `json:"network_id"`
	// IP to give to the container
	IPs []net.IP `json:"ips"`
       PortsForward []PortForward
}

type PortForward struct{
   SrcPort uint
   DstPort uint
   DstAddr uint
   Protocol PortProtocol
}

type PortProtocol string
var (
    PortProtocolTCP PortProtocol = "tcp"
    PortProtocolUDP PortProtocol = "udp"
)
```

`SrcPort` would be the external port on the node and always using the public IP
`DstPort` would be a port into the container
`DstAddr` would be one of the ip from the Network struct
`Protocol` would be the protocol to forward, nothing special here.

**Comment by muhamadazmy** [comment]
If the `src` port are limited to what is available on the node, it does not make sense to allow the user to set it like that. Instead, a user should just ask for destination ip/port. and an automatic public port is gonna be assigned to him.

This also will prevent people fighting for known ports (80, 443, 22, etc...) I imagine some people will just book these ports even if the destination does not exist yet.

Another note, i really think this should be part of the container reservation (or the vm in the future) not part of the network resource. for many reasons:
- Destination won't exist before the network itself is provisioned
- Port forward (port allocation) should live only during the destination existence. In other words, they are tightly coupled.
- Avoid of hoarding ports, without actual use on a node

**Comment by zaibon** [comment]
> If the src port are limited to what is available on the node, it does not make sense to allow the user to set it like that. Instead, a user should just ask for destination ip/port. and an automatic public port is gonna be assigned to him.

That would be the simplest solution yes, but we cannot do that cause 100% of the workload needs to be define before hands. No dynamic selection of anything would be ip or port is allowed.

> Another note, i really think this should be part of the container reservation (or the vm in the future) not part of the network resource. 

This is what I said too. `provision.Network` is the network part of a container reservation, check the link in my first comment again.

**Comment by muhamadazmy** [comment]
> This is what I said too. `provision.Network` is the network part of a container reservation, check the link in my first comment again.

My fault, i thought it's part of the NetworkResource. sorry

**Comment by delandtj** [comment]
let's rethink that a bit:
what are the requirements:
- Constraints
  - __some__ machines on the BBI (big bad internet) are proxies for SNI domain names (*1)
  - the proxy destinations are containers that live in Network Resources of a user network
  - the communications between the proxies and the destinations will be IPv6
  - the destinations are services in a User Network (wireguard mesh), that have **only** IPv4, and thes IP addrs are described __somewhere__ , we need to glue that together in a proxy-IP-Port -> destination-ip-port

- caveats
  - as IPv4 and IPv6 protocol boundaries are (extremely) difficult to cross, we'll need proper IPv6 in the containers that host the destination services. We can eventually do NAT66 as that is supported by the kernel (nftables), but NAT64 is a can of worms we don't want to open.
  - then suddenly the containers, NRs, wg mesh need IPv6. When IPv6 is back in the mix, we might as well have kept the previous implementation ;-)
  - Either way, we will need some form of IPv6 allocation for the NRs, be it derived frome the IPv4 addrs, __or__ by using bcdb as a record keeper for prefixes allocated to NRs.

**Comment by delandtj** [comment]
*1 SNI proxies are not a panacea, as the visibility part in the logs of the servers get reduced to the IP of the proxy.

**Comment by delandtj** [comment]
So for IPv6, we can then choose to use IPv6 Private space, `fd00::/8` and do some NAT66, so effectively keeping the same type of crufty thing to counter the IPv4 problem, but then why would IPv6 be created. Having properly routable IPv6 Addresses will be beneficial in the long run. 
Either way, we have to add IPv6 in the NRs and in the containers... The only question that needs answering is: Private (bad, bad) or Normal Public (good) (or both, but that could very well get hairy in terms of routing)?

**Comment by zaibon** [comment]
Well we need to be pragmatic here. We don't have time to change the all networkd again now.
Only thing we need is to be able to forward traffic from a tf_gateway into a private network resource.
If the less work is we just do NAT66, then be it. It will add some overhead, but that's ok for now.

From how I see things, the easier and faster is just to allocate ipv6 we derivate from the ipv4 of the network resource, make the ipv6 routing work between network resource and be done with it for now.

It seems we will need to have a proper fully routable ipv6 but don't think we have time now.

**Comment by delandtj** [comment]
:'( ok then, I'll cook some specs to add...

**Comment by delandtj** [comment]
Closing this as we will probably __or__ not do this, __or__ take a completely different approach to it
