### ISSUE TITLE
Redundant Network Setup for Certified Capacity

### ISSUE THREAD

**Issue by gneumann333** [threefoldtech/zos#358]
In the current Specs of ZeroOs 2 the Network setup is shown as singular (one router, one Internetfeed)
The Farming Rules/SLA require 99,5% uptime if a node is offline  to long (3 Months SLA not met) it has to be re-registered, possibley for a wosre Token Price
That would mean a potential lose of tokens for the Farmer.

A basic redundant Network setup has to be part of the Documentation as guideline.
@delandtj lets discuss this next week

**Comment by zaibon** [comment]
Hello @gneumann333, thanks for you comment.

I get your point. In the documentation we indeed have the simplest possible setup defined. While this is good for home farming. It is maybe a bit too simplistic for bigger farm with more advanced network capabilities. 

@delandtj Let's indeed plan to improve the documentation with a example for a bigger farm.
@gneumann333 a PR on the documentation to improve it is welcome. If you have some example of how you setup your farm maybe ?

**Comment by delandtj** [comment]
uhm for proper redundant setups, we'll need to be able to specify some level of bonding, be it with standard linux ling aggregation or openvswitch. Let's discuss indeed, I'll add an issue for networkd to be able to setup a bond.

**Comment by delandtj** [comment]
will be followed up in [here](https://github.com/threefoldtech/zos/issues/408)
