### ISSUE TITLE
upgraded: mechanism to update core utils and potential kernel patches

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#364]
Related to #248 

The current upgrade mechanism only works for zos binaries (from this repo) where we can control the release version and changes that ships to the node. 

The ZOS ecosystem also include other binaries that is not part of zos repo, and developed by other developers from the open-source community, they have different release cycles, and strategies. This forces us to develop a new mechanism to update the core utils separately. By separately we mean separate from zos release cycle, and also separate from each other. In other words, if there is a new version of `redis` available, we should be able to publish an update for redis alone, without the need to also build/publish the rest of the utils.

## Proposal 
Introduce a new `hub` repository `tf-zos-core-utils` (feel free to suggest better name, I already hate this one)
- On boot, the bootstrap will list all available flists in this repository
  - For each flist, the node will mount, copy all files. (Even if we gonna introduce hooks, they should not fire on boot since nothing is in use already)
  - The zos binaries bootstrap comes after the core utils update.
- After boot, the `upgraded` daemon will watch this (full) repository for new or updated flists (the name, version doesn't matter only change in the content (hash of flist) or if a new one is added.
- If a new flist has changed, the flist is mounted, files are copied and hooks are fired as usual only for the new/updated flist.

### Flist content.
The content of the flist should have only the required files for a single core util. (redis, 0-fs, containerd, etc...). The name of the content should be part of the flist name. For example `redis:v5.0.flist` or `0-fs:v2.0.1.flist`. Again the name should not matter since ONLY the latest binaries should be available in this repo. otherwise an override with older version might be possible.

Hence, it's necessary to remove the older version of the binary before creating the new one. (I suggest we drop the version from the name entirely to avoid problems) and only use the hash to track what has changed.  Otherwise we will have to sort all releases of the same `util` to choose the last one to install

**Comment by zaibon** [comment]
That approach sounds reasonable we should give it a try.

**Comment by muhamadazmy** [comment]
Points for discussions:
 - Keep the version in the flist name, or drop it?
 - If we keep the version in the name, do we keep all versions or just the latest?
    - Note, keeping all version of the same util in the repo will make it harder to boot via bash script, and we will probably have to move to a different boot util (rust) to handle the json properly.
- Listing the repo content repeatedly is a lot of traffic, I think it's better if there is a lighter version of the list (HEAD repo) that just returns some info like last modifications time of the repo) then get the content once we detect a change. @maxux

**Comment by zaibon** [comment]
> Keep the version in the flist name, or drop it?

Yes let's keep it so it is easy to see at which version we are right now.

> If we keep the version in the name, do we keep all versions or just the latest? 

we just keep one single version. But we will have 3 flist, one for each network (dev,test,prod)

> Listing the repo content repeatedly is a lot of traffic

This already exists I believe: https://hub.grid.tf/api/flist/zaibon

**Comment by muhamadazmy** [comment]
> This already exists I believe: https://hub.grid.tf/api/flist/zaibon

This is what I mean by a lot of traffic, imagine this same call done by thousands of nodes, all the time. I was considering a more generic overview of the repo, like last modification time of the repo (basically a `mtime of the directory on the file system` so we know if an update happened, then the node can do the full listing as returned by this call

**Comment by maxux** [comment]
Ideas and things which will be tested to see if it's viable:
- Separate initrd from kernel
  - The initramfs is shipped inside the kernel for legacy reason (historically we were shipping the kernel, not an ipxe bootloader which download the kernel). Since we use `iPXE`, we can load 2 files instead of one without changes.
  - Separation will reduce build time since only initrd changes can be repacked and kernel is not touched.
- Only include strict necessary files in the initrd
  - Only `mandatory` packages (`0-fs`, `fuse`, `dhcpcd`, `zinit`, `busybox` and `libc`, maybe some more) will be included on the initramfs, everything else will be downloaded on runtime
- Review current build process and do static build of packages to not deal with shared libraries on runtime
  - We need to see if binaries size won't grow up too much by doing static link for everything. But I pretty sur next to all the Go binaries we use, that's won't be that significant.
- Like @muhamadazmy suggested, shipping packages in flist with only needed files (which should be a reduced set of files if everything is static, some config file)

**Comment by muhamadazmy** [comment]
I think the boot process is getting more sophisticated, and hence we probably need to move away from `bash`.

I will create an issue regarding this and may be start the rewrite in rust _again_

**Comment by zaibon** [comment]
OK this is interesting. Having a really minimal image and get everything else from flist could be nice. 
But it raises a question. How does the node know what it needs to download ?
I would be like all the things in the hub directory ?
Then how do you remove something ?
Also, what would be the impact on a huge farm that has hundreds of node. Booting the farm would DDOS the hub no ?

**Comment by muhamadazmy** [comment]
> I would be like all the things in the hub directory ?

Yes

> Then how do you remove something ?

The upgrade (and the boot) can track the download file paths in a db under /tmp/. Once a change is detected on the hub (some flist removed), the db can be used to query which files to delete before install the new one.

> Also, what would be the impact on a huge farm that has hundreds of node. Booting the farm would DDOS the hub no ?

The hub will definitely require some read-only mirrors in distributed areas. The main hub will be the only place to upload files, but the mirrors can use the same technique as upgrade to mirror the main hub. I assume same should be done for the data blocks
