### ISSUE TITLE
Can we have an overview of all drivers / hardware compatible to the ZOS linux kernel

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/zos#365]
AS we attract more farmers - can we have a list/wiki of all supported drivers.

If it is the standard list of drivers in the Linux kernel (which version?) then lets point to that.

Can we have nonstandard supported drivers (china?) being added (Not Intel but CHIntel)?

**Comment by zaibon** [comment]
Having a full list of supported driver is not possible.
What we could do is start to maintain a list of all hardware we've encounter and mark them compatible or not. 

But as a general rule of thumb we're running linux. If the hardware works out of the box a on linux machine without custom driver building, then we should assume it will work too on 0-OS.

**Comment by delandtj** [comment]
there are some HCL lists, and __some__ old (like methusalem old) scsi controllers are not by default added to the supported list... if need be we can add them.
Also, sometimes ipxe has some compatibility issues with RTL NICs, and althought RTL nics ar ubiquitous in many desktop-type machines, we would advise to refrain to use them. RTL nics have abysmally small buffers generating too many interrupts under load.

**Comment by delandtj** [comment]
when googling for [linux hardware compatibility list](https://www.google.com/search?q=linux+hardware+compatibility+list&oq=linux+hardware+compatibility+list) you can basically assume that things are going to work out all right, and if not, we'll advise. 
In short, if you get Iron from established vendors, you'll be all right. Esoteric desktop motherboards, where everything is don to maximize profitability and lose quality... there, no promises can be made

**Comment by weynandkuijpers** [comment]
ok - good enough.
