### ISSUE TITLE
bootstrap: reimplement boostrap script in rust

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#367]
Part of #364 

Currently the bootstrap is fairly simple, and hence it was okay to use bash scripting to implement the logic. 

Now, the bootstrap process is getting more sophisticated (and might grow more complex in the future) hence, it's a good time to move away from bash to rust.

**Comment by zaibon** [comment]
~let's hold our horses here :-) Nothing has been decided yet. So I'll put this on low prio until we have decided how to tackle #364~
