### ISSUE TITLE
containerd zero-fs integration

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#37]
- Check if it's possible to implement a new image type to support zero-fs directly in containerd
- Plan B, the rootfs of the container is mounted first then sent to containerd in the runc specs

**Comment by zaibon** [comment]
I managed to start a container using containerd client on top of an flist. example code is there: https://github.com/threefoldtech/zosv2/blob/container_module/examples/container.go

**Comment by zaibon** [comment]
We now know there is no problem using 0-fs and containerd together.
I"ll close this one so we can just use the draft PR to follow progress: https://github.com/threefoldtech/zosv2/pull/31
