### ISSUE TITLE
correctly map the node farmer's id to the farmer id

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/zos#372]
Currently when listing all the farmer ID's they are produced as integers, which is fine. But when listing all the nodes, the farmer ID's in the nodes results are string values. In some cases they are mapped to the farmer's name.

**Comment by zaibon** [comment]
fixed in
- https://github.com/threefoldtech/zos/pull/373
- https://github.com/threefoldtech/jumpscaleX_threebot/pull/204
