### ISSUE TITLE
add physical server power management depending on capacity required

### ISSUE THREAD

**Issue by mpolski** [threefoldtech/zos#376]
Add power management to servers in a farm to save energy (cost, CO2 emisssions) and become even more green.

- Power off servers when capacity not reserved/in-use.
- Power on servers when capacity reservation exceeds currently available capacity of powered on servers in the farm.

Capacity of servers should be made available without having them powered on.
Farming tokens should be generated even when servers are powered off.
Physical servers presence on the management network is a must.

Requires access to mgmt newtork of physical servers (multiple options exist)
Can be standardized across vendords.

I would be more than happy to discuss the architecture of this feature.

For a quick start HPE already has software which provides a single API to multiple servers and programming languages SDKs/bindings to ease integration.

**Comment by delandtj** [comment]
this is **very** valid now

**Comment by xmonader** [comment]
obsoleted by the power management milestone.
