### ISSUE TITLE
Design storage module

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#4]
The storage module will be responsible for everything that is related to storing information on a long term medium, usually a disk.

Sub components:
- 0-db management
  - capacity planning, reservation of 0-db and 0-db namespaces
- disks management
  - formatting of the disk
  - health monitoring
  - management of volume used by containers

**Comment by zaibon** [comment]
I started working on the design of the module. Opened a PR for it : https://github.com/threefoldtech/0-OS_research/pull/12

I used go as the language to define the interface since it is quite nice to work with.

**Comment by LeeSmet** [comment]
After discussion yesterday with @delandtj, it turns out the envisioned architecture is a bit different from what you already have. We should probably have some discussion about this @zaibon

**Comment by LeeSmet** [comment]
The way we discussed it yesterday, we would expose only a zero-Db (still needs a lot of discussion), and a filesystem. Internally, the module manages volumes, but a volume is never exposed. In case someone requests a filesystem or volume, a subvolume is created on some existing volume (or new top lvl volume is created), and then a filesystem is placed on this subvolume. Finally, the filesystem is exposed to the consumer. 

To reserve storage, you can't exactly specify what filesystem you want, but rather a type of utilisation for the filesystem, so the storage module can decide on the best fs / volume / ... Either Fast or slow storage, or somewhat more finegrained (if required) such as cache | archive | database | ... 

Setup such as raid would generally not be exposed to the client, but handled internally based on the needs of the consumer

**Comment by zaibon** [comment]
Well this is nearly exactly inline with the interfaces describe in the storage spec: https://github.com/threefoldtech/zosv2/tree/master/specs/storage

Now keep in mind that the module is a low level component. This is not the public interface of the storage.
So everything describe in the [disk management interface](https://github.com/threefoldtech/zosv2/tree/master/specs/storage#interface) still need to exist for 0-OS to be able to do everything you describe.

**Comment by muhamadazmy** [comment]
@zaibon & @LeeSmet 

IMHO the storage module (even if it's low level) should NOT expose operations on the disk level. This means that the logic to group, and format disks comes from a higher layer which is not defined atm. 

I think the storage module should track disk and create the raid volumes automatically and only expose the functionality to "reserver" or allocate a new tenant subvolume, either this subvolume will be used as a mount point for container, VM, or a device attached to a VM. (I already can only see 2 possible ways to group disks, HDD, and SSD. We can try to define a policy for the module to group disks)

Also, we need to consider encryption on the sub-volumes, so people with physical access to the nodes won't be able to read users data even if they unplugged the disks.

**Comment by LeeSmet** [comment]
After talking a bit more with @delandtj, it seems we will use the following architecture:

The system will have some disks, which expose volumes. Depending on the setup, a volume can be either a disk itself, or a partition on the disk. We are also thinking to separate the volumes into "primary" volumes, and "secondary" volumes. In this scenario, the "primary" volume would be a disk or partition, and a secondary volume would be one or more primary volumes (i.e. filesystem over multiple partitions). Finally, we have a filesystem on top of a volume . 

The first thing the module does when it is started will be to see if a filesystem with a pre defined label exists for the storage of modules itself, since these will need to have persistent storage to save their configuration across module restart / system reboot. The storage module itself can also use this space to store its existing configuration, allowing it to rebuild its state, and know which volumes have been reserved already, etc..

It is also my understanding that flists (and thus containers) are always started on the cache filesysten. Which would then in turn mean that any excess disks are only used to create filesystems on top of which 0-DB's will run.

for an interface, this would mean we have 4 methods: 

```go
type storage interface {
    ReserveFilesystem(size int, config Config) (MountPoint, error)
    ReleaseFilesystem(MountPoint)
    ReserveZDB(size int, mode Mode, password string) (ZDB, error)
    ReleaseZDB(ZDB)
```

**Comment by zaibon** [comment]
> We are also thinking to separate the volumes into "primary" volumes, and "secondary" volumes. In this scenario, the "primary" volume would be a disk or partition, and a secondary volume would be one or more primary volumes (i.e. filesystem over multiple partitions).

I don't really understand what does this bring. To me this really shoulnd't matter and just be totally abstracted. If a user request a huge storage capacity or if there is no one disk with enough space to provide the capacity asked, then the module should automatically choose to use multiple disks in order to provide the required capacity.

> The first thing the module does when it is started will be to see if a filesystem with a pre defined label exists for the storage of modules itself, since these will need to have persistent storage to save their configuration across module restart / system reboot.

I'm not sure this should be done by the module itself. The logic to do this can of disk reservation/preparation be live in the module sure, but I think actually calling this code should come from a higher layer. How I see it there will be a process run just after boot to finish to bootstrap the node. 
It prepare the disks etc, then signal to all other modules that they can start since there is now a disk available for them to use.

> It is also my understanding that flists (and thus containers) are always started on the cache filesysten. 

The 0-fs does use a disk as cache for the flist data. But any container can request persistent volume, and thus a disk needs to be prepared and assign to the container.
So 0-db is not the only use case for the remaining disks.

**Comment by zaibon** [comment]
There is something we have not yet talked about regarding disk management.
It is how are we going to deal with the different use case we have for a disk.

For example, 0-db is supposed to be running on top of a full disk. So we can be gentle on how we write onto the disk. But 0-db can run using different mode.
So if we only allow 1 0-db per disk and if 0-db has different mode, it means the first time we deploy 0-db on top of a disk, this disk is going to be exclusively usable for the mode the 0-db is running in.

Since all nodes are independent and doesn't have any "role" How can we prevent the case where a node has all it's disk reverse for a certain 0-db mode, thus locking the disk capacity for this mode. while maybe it could be use for something else ?

This is the same question if we use different disk layout/filesystem for different disk use cases. How can we maximize the usage of a disk ?

**Comment by muhamadazmy** [comment]
@zaibon may I ask what is the technical limitation that prevent us from having multiple 0-db running on the same disk? I know that 0-db uses a fileysystem to write to the disk so i don't see why we can't have as many as we need (as long as the benchmarks are fine) 

A suggestion that might not make much sense, but would it be a problem if we can create a partition on disk per namespace? I know the performance will still be limited by the entire disk IO. but in case there are other limitations that i don't know about.

**Comment by zaibon** [comment]
> what is the technical limitation that prevent us from having multiple 0-db running on the same disk?

The quality of the disk mostly. On top of cheap HDD, if we want to have minimum write performance we need to have a single write process doing some append only writes, to avoid any random movement of the write head of the disk.
Now this is only for cheap HDD. Maybe we could detect the quality/speed of the disk that are actually used in the node and have different policies based on that. But this starts to make things a bit complex.
