### ISSUE TITLE
build pipeline might deletes build from other version while it is still being used by other version 

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#401]
- [x] update 0-hub to support cross repo symlink
- [x] update 0-flist to support cross repo symlink creation
- [x] update Github action to support cross repo symlink
- [x] update Github action to support renaming
- [ ] update github action workflow on zos repo.

**Comment by muhamadazmy** [comment]
I think the simplest solution is the following:
- All builds (with version number in names) are always kept under tf-autobuilder 
- On releases, a symlink is made (cross repos) from tf-zos to the tf-autobuilder flist.

This way, new builds will not cause older versions (releases) to be deleted. And we can keep full build history.

**Comment by maxux** [comment]
That's the easiest way I see too, and seems good enough

**Comment by zaibon** [comment]
alright is everyone agrees let's do it like that. @maxux you take care of opening the issue on 0-hub. Once is it live, we can update our GA workflow here.

**Comment by maxux** [comment]
https://github.com/threefoldtech/publish-flist#cross-link
https://github.com/threefoldtech/publish-flist#rename
