### ISSUE TITLE
failed to decommission reservation

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#403]
In the logs I see a lot of error like
```
[-] provisiond: {"level":"error","error":"decommissioning of reservation failed: failed to inspect container 112-1: container \"112-1\" in namespace \"nsFuy6CatZGmmtWby13MESN2dYZUJi1ThjPR493w9TyWz1\": not found","time":"2019-11-25T10:53:46Z","message":"failed to decommission reservation 112-1"}
```
I'm not sure of why exactly this happens, but it seems this already shows a problem. The decommission should not fail if the container is already not existing.

**Comment by delandtj** [comment]
well it's a stacked error, where  the Inspect req to the zbus of a nonexistent container returns it's own error... I guess... but that would mean that there needs to be an `Exists` on zbus, and check for that before.
OTOH how come something non-existent needs decommissioning ?

**Comment by zaibon** [comment]
Yep, I traced it down to a container already gone but the reservation stays in cache for some reason. This PR https://github.com/threefoldtech/zos/pull/430#event-2850025416 should fix this.
