### ISSUE TITLE
networkd: be able to setup link aggregation for meeting 99.7 SLA in case of connectivity problems where a switch would die in a farm

### ISSUE THREAD

**Issue by delandtj** [threefoldtech/zos#408]
following: https://github.com/threefoldtech/zos/issues/408

Building the bond is 'just' some glue. But we'll need to be able to convey to 0-OS that specific NICs should be bonded and with what parameters. 
-  Right now,we have no primitives to tell a node what it's network should look like (like we had in the mock), or do we ?
- Or with proper setup of a boot machine, we could specify that on the cmd line of the kernel

**Comment by zaibon** [comment]
To me this seems to fall under the same kind of problem as configuring a public IP address on a specific NIC.

So I think we can solve it exactly the same way. Let the farmer configure the bonding configuration. We just need to decide how we're going to create the bond (plain linux, openvswitch, ...)
From there we can create the proper structure, add it to the model used in BCDB and adapt networkd to also watch this configuration.

**Comment by delandtj** [comment]
let's not OVS for now, too many spinning wheels to get that working properly and easily

**Comment by DylanVerstraete** [comment]
Closing because it's not relevant in 3.0 anymore.
