### ISSUE TITLE
zinit panic!()s in ringbuffer sending the node to a screeching halt

### ISSUE THREAD

**Issue by delandtj** [threefoldtech/zos#412]
Nothing to add here, need to reset the node.
as for __why__ it's __only__ on __that__ node, anyone's guess is welcome

![image](https://user-images.githubusercontent.com/5995555/69701842-2c512e00-10ee-11ea-801e-e2a37e57b75b.png)

**Comment by zaibon** [comment]
fixed by https://github.com/threefoldtech/zinit/commit/ae5c273609f1376b34c1618f4710e0ef363e8cbb
