### ISSUE TITLE
allow to stream container logs to remote endpoints

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#43]
Since there will be no way for user to connect directly to a 0-OS node, we want to add the possibility to a node to stream the logs of a container to remote endpoint.

During the creation of the container, the user will specify the endpoint location and type. Then during the lifetime of the container, the 0-OS node will stream the logs to the endpoint.

As a first supported endpoint type:
- redis
- 0-db

**Comment by muhamadazmy** [comment]
Can we leverage on the logging infrastructure that we are building now for zos logs for this as well. The only problem will be making sure only the tenant can view his own logs.

**Comment by zaibon** [comment]
Well that was not the plan no. I see this as 2 different things.
Internally I want to have some logs from 0-OS for us to analyse and be able to improve and find bugs.

But the logs from users, this is something we do not want to deal with. The only thing we would provide is a way for 0-OS to steam the logs somewhere. At the moment only a redis endpoint is supported.

Let's see what are the requests from the users in term of protocol/endpoint before we move here.

**Comment by zaibon** [comment]
fixed by #578
