### ISSUE TITLE
k8s: Research exact network requirements

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#436]
story: https://github.com/threefoldtech/home/issues/449

**Comment by zgorizzo69** [comment]
![TFGRID k8s DDNS HAPROXY](https://user-images.githubusercontent.com/16853695/70423324-8e564f80-1a6d-11ea-9bd6-c5a0aad43c53.jpg)

**Comment by zaibon** [comment]
@zgorizzo69 can you create some document into the /specs repo explaining this drawing.

**Comment by zgorizzo69** [comment]
I could still test with the k3os VMs if metalLB is an option or not. Indeed we still don't know yet if we can propose a load balancer type ingress as a cluster resources

**Comment by delandtj** [comment]
this is still (kinda) relevant in the sense that:
  - an ingress node  has __also__ a public IP, statically or through dhcp, where:
the k3OS VM is connected with it's tap to a birdge. That bridge has as slave a macvlan in mode passthru, that is created on the public interface.

__IN__ the VM, we do some proper setup of the routing, so it's also publicly reachable:
  - put a static ip on the public iface (whatever you name it, it'll be `eth1`)
  - set it's default gateway for public in table 100
  - add the public subnet route in the table 100
  - add a rule for to/from public subnet to lookup in table 100

**Comment by zgorizzo69** [comment]
- For public access we tried successfully [inlet](https://github.com/inlets/inlets)

- We used metalLB to provision an ip for our ingress controller the external trafic (on port 80 and 443) is redirected to that ip thanks to inlet

- for now flannel is good enough in a next version we could try to install calico to have support for ingress and egress

- For HA of the master node we used dqlite successfully but we still need one fixed ip to load balance the masters. In a next version we will investigate HA Proxy
