### ISSUE TITLE
k8s: prepare hardware for tests

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#437]
story: https://github.com/threefoldtech/home/issues/449

In order to be able to proceed with the development of the integration of k8s we should have some hardware setup and dedicated for it.

For the phase 1, the node needs to be connected to the same switch so they can communicate between each other without any special overlay network.

**Comment by delandtj** [comment]
we'll use the 10.5.0.{11..18} nodes, which IMHO would be typical for a farm, where a (small) IPv4 allocation is issued. (stiil waiting for k3s to properly address it's IPv6 bug, though)

**Comment by zaibon** [comment]
10.5.0.{11..18} are testnet nodes, you cannot use them for development. So new one needs to be put in place.

**Comment by zaibon** [comment]
4 nodes have been added and are dedicated for k8s integration development: https://explorer.devnet.grid.tf/nodes?farm=3
