### ISSUE TITLE
define clear boot flow

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#44]
We can organize the services boot in stages by creating pseudo stages. For example we can create a service called `init` that exec 'true' as one shot and depends on all boot services (`udev`, `settle`, `network`, `etc`) then all other second stage services can depend only on `init`

**Comment by zaibon** [comment]
From the current init services we have, I created an order:
```
boot:
    haveged
    udev-trigger
    udevd
    local-modprobe
    cgroup

network:
    networkd
    routing
    ntp

before modules:
    redis

storage:
    storaged

modules:
    containerd
    containerd
    flistd
    upgraded


other:
    debug-tty
    sshd-setup
    sshd
    telnetd
```

**Comment by muhamadazmy** [comment]
Lots of services in this tree don't have to have such solid dependency on each other. For example, telnetd will not fail to start if it started before networking (same for sshd) so this config can be simplified dramatically.

for example here
https://github.com/threefoldtech/zosv2/pull/68/files#diff-41b602314f3ea42f8e0e00d5101c3912

**Comment by zaibon** [comment]
everything that is in the `other` section is only for debugging this won't exist in a production release.
So that doesn't matter really, I could have left them out completely.

**Comment by muhamadazmy** [comment]
Draft PR #72
