### ISSUE TITLE
tfuser: generate correct schema.json

### ISSUE THREAD

**Issue by delandtj** [threefoldtech/zos#453]
`tfuser gen network` is a dev tool, I admit, but creating the json is woefully inadequate to start testing multiple peering (ipv4-6) and  scenarios. .

`tfuser gen network create --name booo -cidr 172.18.0.0/16` 
That is ok to create the start.

As each node has it's ip addrs registered, we can read that out and fill in the peer addrs with tfuser itself. so:
`tfuser gen --schema booo.json network add-node --node $nodeid --subnet 1 --port 12345 --l3 6` can then have as well the proper peer address as everything filled in. 

`--subnet 1` translates to `172.18.1.0/24` as NRs always have a `/24` subnet
`--l3 [46]` specifies what public peer address to use

`tfuser gen --schema booo.json network add-access --subnet 192.168.123.0/24 --node $nodeid -l3 4` 
adds an access and the routing to that network , plus generates a wireguard config file usable by `wg-quick`.

This FR handles things 2-fold.
- have the building blocks for using `tfuser` to create a network on as well a devnet, as on a BCDB test/prod net
- there are still some things to think about in terms of calls where we haven't yet ventured:
  - ipv4<->ipv6 peering  choice, selecting preference would be ipv6, but if x% nodes are by default only ipv4, we might reconsider
  - I sill have the feeling we haven't considered everything, and generating the json from some 3bot will need to be coded evenly and in sync..

**Comment by zaibon** [comment]
So let me clarify and explain what already exists today.
For the network generation we have 3 commands:
- create
- add-node
- remove-node

The `create` command seems to be doing what it should and I also don't think it needs to be adapted.

The `add-node` command could use some love indeed.
What is does at the moment is adding a new network resource to the network. It takes care of adding the new peer to all the existing network resources too. 
But there is a bug where the peer has never its endpoint filled.
This was design like this cause having a endpoint or not depend on the topology of your network.

Now the proposal of @delandtj to change the flag of this command are nice and I think we could even automate most of it.

Currently the flags for `add-node` are :
```
 --node value    node ID of the node to add to the network
 --subnet value  subnet to use on this node. The subnet needs to be included in the IP range of the network
 --port value    Wireguar port to use. if not specified, tfuser will automatically check BCDB for free fort to use (default: 0)
```

So here we could make the `--subnet` optional. And based on the network CIDR and all the existing network resource pick a new available sub-net automatically.

`--port` is already optional and automated so nothing to change there.

The new `--l3` flag propose is what could allow to automate the selection of an endpoint. I would rename it to `--protocol` though to make it more explicit. 
What it would do is, if `--protocol` is given, `tfuser` would go to BCDB and check the detail of the node.
Based on the selected protocol, it would select the ip address to use as endpoint. Logic is the following:
1. check if the node has public interfaces configured. If yes and it match the selected protocol, use this address
2. If not public interfaces configured, walk the list of interfaces and select an address that is both public and match the selected protocol.
3. If still not found, the node is a hidden node and cannot be reached directly, so endpoint needs to be empty.


Lastly the `add-access` command is actually something that we used to have in tfuser. It was removed along the way but I think this is a good to have it back.
`add-access` is used to add an `non 0-OS` member to the network. That could be a user laptop or a 'normal' server ....
I'm not not entirely sure what @delandtj had in mind with this command flags though. @delandtj can you elaborate what each one is supposed to do ?

Here are some link to old code that was implementing part of this feature:
https://github.com/threefoldtech/zos/blob/9bc80a2e9eae904e88cd73c40fa5b919185ea901/tools/tfuser/wg_quick.go
https://github.com/threefoldtech/zos/blob/9bc80a2e9eae904e88cd73c40fa5b919185ea901/tools/tfuser/cmds_network.go#L55


Lastly,
> I sill have the feeling we haven't considered everything, and generating the json from some 3bot will need to be coded evenly and in sync..

I've no idea what you mean by that. Can you elaborate ?
