### ISSUE TITLE
networkd: registers node interface config only once

### ISSUE THREAD

**Issue by delandtj** [threefoldtech/zos#455]
when a IPv6 Router advertisement daemon is slow to react (+10 seconds) , networkd registers an incomplete network config.

networkd should reissue it's config if interfaces have received some IP address, or when the network has changed ...

**Comment by zaibon** [comment]
Indeed I've seen the same problem where some of the interfaces detail sent to BCDB are sometime not complete.

Netlink allows to subscribe to event from links, so I think I can implement some kind of watcher that will send update to BCDB anytime there is an address update on certain links. https://pkg.go.dev/github.com/vishvananda/netlink?tab=doc#AddrSubscribe
