### ISSUE TITLE
'sometimes' reprovisioning an NR fails with a nic veth endpoint in ndmz alraedy existing

### ISSUE THREAD

**Issue by delandtj** [threefoldtech/zos#456]
Wile I suspect a bug in 4.14 and the fact that there have been big changes in 4.18->4.19 to address issues with removing network interfaces that have been sent into namespaces (read: __when__ are we going to have 4.19.or 5.4?) , We still should not rely on the kernel to tear everything down.

Instead, before removing an NS, we should remove the interfaces __in__ the ns before deleting it.

OTOH... if 4.19 (or 5.4) solves that problem, I can live with it.

**Comment by zaibon** [comment]
I've seen this error in our logs:
`[+] networkd: 2019-12-26T14:31:14Z fatal failed to create DMZ error="failed to create veth pair to connect zos bridge and ndmz bridge: container veth name provided (to-dmz) already exists"`
