### ISSUE TITLE
Update/fix tfuser unit tests

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/zos#469]
in PR #458, the `generatePeers` method was added. Some unit tests should be written for this function to verify everything works as intended (and more importantly everything keeps working if the function ever changes). While doing this, the other tfuser unit tests should also be fixed as these currently don't compile. Lastly, it seems the unit tests are not part of the CI, so these should also be added as well

**Comment by zaibon** [comment]
fixed in https://github.com/threefoldtech/zos/pull/483
