### ISSUE TITLE
Networkd does not release ports when a NR is removed

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/zos#484]
as a result, deploying the same network after it has expired fails until networkd is restarted

**Comment by zaibon** [comment]
I would like to have a way to reproduce or a test that fails and how the problem.
Cause the code is there: https://github.com/threefoldtech/zos/blob/master/pkg/network/networker.go#L428

**Comment by DylanVerstraete** [comment]
Cannot reproduce

**Comment by zaibon** [comment]
duplicate of #556
