### ISSUE TITLE
Build toolchain for bins-extra

### ISSUE THREAD

**Issue by maxux** [threefoldtech/zos#486]
Let's get like initramfs, a build system ready to rebuild (and easily update) flist we need on zos runtime.

We can reuse script used for initramfs when tools was integrated to image and used on runtime now. Using github action we can upload separate flist easily, everything is already in place.

**Comment by maxux** [comment]
Progression:
- [x] Base script for toolchain
- [x] Script for firecracker, containerd, promtail
- [x] Script for k3s image
- [x] Write a proper README
- [x] Remove old version from hub when new is uploaded
  - **UPDATE:** we do symlink and doesn't remove old files

**Comment by zaibon** [comment]
fixed in https://github.com/threefoldtech/zos/pull/503
