### ISSUE TITLE
nodes don't boot any more (20200130)

### ISSUE THREAD

**Issue by delandtj** [threefoldtech/zos#497]
since noon, we can't boot nodes any more ... the symlinks appear to go nowhere any more.
the ash on alt-f2 works, and tab-tab on the ash effectively shows what is in the path, but all calls say 'no such file or directory' 
![photo_2020-01-30_17-16-53](https://user-images.githubusercontent.com/5995555/73468218-bd5db300-4384-11ea-86be-dbb1a5a31497.jpg)
![photo_2020-01-30_17-16-46](https://user-images.githubusercontent.com/5995555/73468219-bd5db300-4384-11ea-9183-04616c774f66.jpg)
![photo_2020-01-30_17-16-41](https://user-images.githubusercontent.com/5995555/73468220-bdf64980-4384-11ea-9c71-495c2f2b30d2.jpg)
![photo_2020-01-30_17-16-27](https://user-images.githubusercontent.com/5995555/73468221-bdf64980-4384-11ea-8081-ce601ccdedea.jpg)

**Comment by zaibon** [comment]
I'm suspecting this last patch: https://github.com/threefoldtech/zos/pull/493/files#diff-c0139b19f9d2230f278d37a2d35a7079R79 broke it

I do not think we should delete anything during install of the binaries in flist during bootstrap, even if they are symlinks.

**Comment by zaibon** [comment]
fixed in https://github.com/threefoldtech/zos/pull/498
