### ISSUE TITLE
Update network documentation

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#508]

**Comment by zaibon** [comment]
```
| number of NIC | public network isolated | Required IP | DHCP config |
| ---           |  ---                    | ---         |  ---        |
| 1             |  false                  |             |             |
| 2             |  false                  |             |             |
| 1             |  true                   |             |             |
| 2             |  true                   |             |             |
```

**Comment by zaibon** [comment]
@andhartl @weynandkuijpers 
Documentation is written, please do a review of the content https://github.com/threefoldtech/zos/blob/master/docs/network/Network-V2.md
and let us know if you have any remarks

**Comment by andhartl** [comment]
a few typos. text makes sense to me. would structure the yeah yeah section a bit better (headlines, bold, ...)

<img width="707" alt="image" src="https://user-images.githubusercontent.com/18591016/77418022-9b9e0c80-6dc6-11ea-9f17-18af4e913c3b.png">
