### ISSUE TITLE
Sometimes during boot , Internet selects the wrong interface

### ISSUE THREAD

**Issue by delandtj** [threefoldtech/zos#522]
leading to this 

![photo_2020-02-12_15-48-37](https://user-images.githubusercontent.com/5995555/74345983-2e529100-4daf-11ea-950c-c4d7960b719a.jpg)

from the mac address of zos, we can deduce it used the wrong interface

**Comment by zaibon** [comment]
fixed by https://github.com/threefoldtech/zos/pull/538
