### ISSUE TITLE
logger: disk quota exceeded -> no system

### ISSUE THREAD

**Issue by delandtj** [threefoldtech/zos#541]
after a day of playing on a node to get networking working, we arrived to a hosed system because:

```
~ # zinit list
logger: Error(Exited(Pid(11569), 1))
flistd: Error(Exited(Pid(11571), 2))
~ # zinit log logger
[-] logger: sh: can't create /var/cache/log/system.log: Disk quota exceeded
[-] logger: sh: can't create /var/cache/log/system.log: Disk quota exceeded
[-] logger: sh: can't create /var/cache/log/system.log: Disk quota exceeded
[-] logger: sh: can't create /var/cache/log/system.log: Disk quota exceeded
~ # ls /var/cache/log/system.log -lh
-rw-r--r--    1 root     root       20.0G Feb 13 20:14 /var/cache/log/system.log
~ # > /var/cache/log/system.log
-ash: can't create /var/cache/log/system.log: Disk quota exceeded
~ # btrfs quota disable /var/cache/log/
```

I guess I need to

```
~ # truncate -s 0 /var/cache/log/system.log
```
to get the node to be able to boot at all

**Comment by zaibon** [comment]
https://github.com/threefoldtech/zos/blob/master/etc/zinit/logger.yaml this file configure the redirection of the zinit logs into this file.

I think the reason we did that was for promtail to be able to read these logs from a file.
Now of course this is going to be a problem cause we never clean up this file. I'm not sure what is the solution here.

`zinit` logs was made to be able to read from memory specifically not too have these kind of disk storage issue. We should probably try to find a way to allow promtail to read from the zinit socket directly

**Comment by muhamadazmy** [comment]
The solution is that we need to avoid logging to the disk by implementing a promtail plugin that reads logs directly from ring-buffer, without the need to go through disk storage.

After all, that's the only reason we log to this file in the first place.

**Comment by zaibon** [comment]
It seems promtail support to send data to it using pipe: https://github.com/cyriltovena/loki/blob/eb76b55c0ec9b30da149aa7aaa841951c745676c/docs/clients/promtail/troubleshooting.md#pipe-data-to-promtail

I've been trying to make it work but without success.
I tried starting promtail with 
```
zinit log | promtail -log.level debug -config.file /etc/promtail/promtail.yaml -client.url http://explorer.devnet.grid.tf:3100/loki/api/v1/push --client.external-labels=node=$(identityd --id)
```

But promtail fail to detect we're using pipe so it doesn't read the data from stdin. This function https://github.com/cyriltovena/loki/blob/eb76b55c0ec9b30da149aa7aaa841951c745676c/pkg/promtail/targets/stdin_target_manager.go#L49-L60 always return false.

**Comment by zaibon** [comment]
https://github.com/threefoldtech/zos/pull/548
