### ISSUE TITLE
tfuser live , no output 

### ISSUE THREAD

**Issue by hteibler** [threefoldtech/zos#549]
I've provisioned a Kubernetes Cluster on devnet, everything works as expected, except that

`
hteibler@u19:~/3fold$ ./tfuser live --seed user.seed --end 3000
`
`
hteibler@u19:~/3fold$
`
has no output, no error, just nothing...

**Comment by zaibon** [comment]
I just did a quick test and tfuser does show the Kubernetes reservations just fine:
```
ID:3270-1 Type:kubernetes expired at:25-Feb-2021 14:37:03state:     ok	ip: 172.23.1.20 master
ID:3271-1 Type:kubernetes expired at:25-Feb-2021 14:37:03state:     ok	ip: 172.23.2.20
ID:3272-1 Type:kubernetes expired at:25-Feb-2021 14:37:03state:     ok	ip: 172.23.3.20
```
I also double checked the code and it seems to be ok too
https://github.com/threefoldtech/zos/blob/ee4ff0088a71b8d9ff2e32cb8d0fa09c3a95ea99/tools/tfuser/cmds_live.go#L97-L108

@hteibler maybe try to make sure build `tfuser` from the latest code ?

**Comment by hteibler** [comment]
I found the problem,
default end=500 ( which is not a good choice)
and IDs are greater 3000 now
and if you specify only --start, end is still 500

**Comment by zaibon** [comment]
yeah this is implemented like that cause tfuser itself cannot know what is the latest reservation number.
So in most cases you need to specify the `--end` flag.
