### ISSUE TITLE
Still errors for udev for btrfs (probably 0-initramfs)

### ISSUE THREAD

**Issue by delandtj** [threefoldtech/zos#551]
udevd[1012]: failed to execute '//lib/udev/${exec_prefix}/bin/udevadm' '${exec_prefix}/bin/udevadm trigger -s block -p ID_BTRFS_READY=0': No such file or directory

Could be related to https://github.com/threefoldtech/zos/issues/550

**Comment by zaibon** [comment]
fixed by https://github.com/threefoldtech/0-initramfs/pull/39
