### ISSUE TITLE
unclear error when using wrong farmer id

### ISSUE THREAD

**Issue by maximevanhees** [threefoldtech/zos#580]
As I didn't know that I couldn't use a random farmer ID anymore, I've had some troubles starting my Qemu vm. 

This is the current error message: 
`[+] identityd: 2020-03-17T13:29:56Z info start registration of the node version="not booted from flist"
[+] identityd: 2020-03-17T13:29:56Z error  error="wrong response status code received: 500 Internal Server Error"
[+] identityd: 2020-03-17T13:29:56Z warn registration failed error="wrong response status code received: 500 Internal Server Error" sleep=46.982049071s
`
Should we add a better error message telling the farmer_id is not correct?

PS: Thank you very much @muhamadazmy and @LeeSmet for the help!

**Comment by DylanVerstraete** [comment]
Server returning this error should be return a 400 response and message instead of 500 internal server error.

**Comment by zaibon** [comment]
What was farmer id you used when you got the error?

**Comment by DylanVerstraete** [comment]
Any farmer ID that is not in the database

**Comment by zaibon** [comment]
Explorer should returns a proper error message that the farmer ID is not found.
So the node can print the error logs and the farmer can then detect he messed up the farmer ID.
