### ISSUE TITLE
networkd: address watcher push addresses update way to often

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#583]
https://github.com/threefoldtech/zos/blob/master/cmds/networkd/addr_watcher.go

We should improve this so we do not DOS BCDB with useless requests

**Comment by DylanVerstraete** [comment]
@zaibon Right now the `initialInterval` is 500ms. So when an error is returned it starts retrying after 500ms and increases with a multiplier of 1.5 each time. Should we increase this `initialInterval` to let's say 2 seconds?

**Comment by zaibon** [comment]
The problem is not in the backofff retry. The problem is the netlink lib sends a lot of updates though the channel:
https://github.com/threefoldtech/zos/blob/c47cd8bb1dc08e7f164cb937fb116a8d38de4e06/cmds/networkd/addr_watcher.go#L76-L86

And we do not have any way to control this. Anytime the kernel gets an event it just forward it to us.
Some kind or rate limiting id what we need here I believe. So we can say that we send and address update at most once every X minutes.

Another id I had was to actually make sure that the update we received from the channel contains actual changes. From what I've seen in the log it seems we just keep sending the same information again and again to BCDB. Which is useless

**Comment by DylanVerstraete** [comment]
The only thing I see in the logs of my qemu is somethings like this:

```
[+] networkd: 2020-03-18T11:38:58Z debug addr update received {LinkAddress:{IP:192.168.123.22 Mask:ffffff00} LinkIndex:3 Flags:128 Scope:0 PreferedLft:4294967295 ValidLft:4294967295 NewAddr:false}
[+] networkd: 2020-03-18T11:38:58Z info send network interfaces update to BCDB
[+] networkd: 2020-03-18T11:38:58Z info check if interface has a cable plugged in iface=lo
[+] networkd: 2020-03-18T11:38:58Z info check if interface has a cable plugged in iface=zos
[+] networkd: 2020-03-18T11:38:58Z info check if interface has a cable plugged in iface=br-ndmz
[+] networkd: 2020-03-18T11:38:58Z info try to publish interfaces to TNoDB
[+] dhcp-zos: Recreating /etc/resolv.conf
[+] dhcp-zos:  Adding DNS server 192.168.123.1
[-] dhcp-zos: udhcpc: entering listen mode: none
[-] dhcp-zos: udhcpc: waiting 1799 seconds
[+] networkd: 2020-03-18T11:38:58Z debug addr update received {LinkAddress:{IP:192.168.123.22 Mask:ffffff00} LinkIndex:3 Flags:128 Scope:0 PreferedLft:4294967295 ValidLft:4294967295 NewAddr:true}
```

So the first time it receives an updated it marks the address as `false` and then it does something else and receives again an update and marks it as `true`. But it is the same address.

**Comment by DylanVerstraete** [comment]
@zaibon is there any node that has this behaviour? I cannot reproduce locally.

**Comment by zaibon** [comment]
@DylanVerstraete I cannot reproduce on my development VM either. But you find node having this behavior on the [logs](http://10.4.0.250:3000/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Loki%22,%7B%22expr%22:%22%7Bmodule%3D%5C%22networkd%5C%22%7D%20%7C%3D%20%5C%22send%20network%20interfaces%5C%22%22%7D,%7B%22mode%22:%22Logs%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D)

**Comment by DylanVerstraete** [comment]
When looking at the logs in Loki and searching for these node that have this behaviour all of them seem to be running on version `0.2.2-rc4`.

**Comment by DylanVerstraete** [comment]
@zaibon I think something fishy is happening on the GECaustria nodes (these seem to behave this way). The netlink package only detects address changes if they in fact change on the watched interfaces. Maybe we can check in one these nodes whats happening there?

**Comment by zaibon** [comment]
Yeah we had some weird behavior with those nodes.

> The netlink package only detects address changes if they in fact change on the watched interfaces.

I'm actually not sure this is the case, I've seen update coming in even when the address received in the update is already present on the system. It seems that when SLAAC refresh an ip address, an update is triggered.

> Maybe we can check in one these nodes whats happening there?

We could indeed.
