### ISSUE TITLE
Implement gateway network namespace

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#59]
The flist for exit node container need to have:
- dnsmasq
- ntfables
- UTS namespace

**Comment by delandtj** [comment]
I suspect this is not applicable any more in this form.
  - For dnsmasq, right now, we don't need it. OTOH, some coredns for registering services and/or names of containers having an IPv6 addr would be important, as typing in addresses will be euhm .. cumbersome ;-)
  - Firewalling needs to be specified, but as far as I have it in my head some templates will suffice
  - For UTS namespacing, well it would be good that every container sets an UTS, as well as the network namespaces of network resources, so we can register them properly and they can resolve themselves on their own. A lot of server services rely on proper hostnames.
