### ISSUE TITLE
allow to enable/disable debug logging at runtime

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#599]

**Comment by maxux** [comment]
We need (and already have) a debug/production initramfs.

- Debug release is the one we know and use for now
- Release will drop:
  - init-debug which enable overlay feature
  - openssh server and keys
  - debugfs tool

Release image already drop some stuff but not everything.

To enable ssh or debug stuff on the node, tools should be started in a container which have access to the host.

**Comment by muhamadazmy** [comment]
This feature was dropped a long time ago. It's safe to close this issue now. Users already can forward their workloads logs to remove locations and we collect node logs already with loki
