### ISSUE TITLE
Clean up duplicated types in the code base.

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#600]

**Comment by muhamadazmy** [comment]
I think this means that:
- gedis
- mock
- and tfuser 

Should all use the same data structures.

Can we also while at it, create a unified client ?
@zaibon

**Comment by zaibon** [comment]
> Can we also while at it, create a unified client ?

Yes please ! Having a single client for the explorer (let's not forget to rename it to explorer) API is also needed to finish #602. Once we enable authentication on the API, having it implemented in a single place in the client will makes everything so much easier
