### ISSUE TITLE
ZerOs V2 wont boot with DELL and IBM Server

### ISSUE THREAD

**Issue by fl0wm0ti0n** [threefoldtech/zos#616]
i run into a big problem running „ZeroOs V2“ with Dell and IBM Servers.

# In case of the IBM Servers…
**Server & Hardware Infos:**
Product name: IBM System x3850 X5 / x3950 X5
Machine type and model:  7143B5G
Serial number:  06L7845

SAS-Controller: LSI MegaRAID/ServeRAID M1015 SAS/SATA Controller - SAS-MFI BIOS (V 4.30.00 (Build October 26, 2011))
Harddisks: 3x HGST Ultrastar 7K4000 (4 TB) (SAS)
Networkinterface: INTEL Gigabit CT Desktop Adapter PCIe (EXPI9301CT)

### Timeline:
1.	ZOS-V2 is getting an IPV6 Address and is downloading the ZOS-V2.
2.	ZOS-V2 is booting
3.	After Stage 3/3 its doing nothing… -> See „1.IBM-Server1_StuckAtStart.png“
a.	Waited >1 hour
b.	ALT+F3 doesnt show the Dashboard.

If i hit ALT+F2 i can look for disks and connectivity…
•	the disks are mounted…
•	i have an IPv6 Address where i can ping6 ipv6.google.com
-> See „2.IBM-Server1_MountedDisks_and_IPv6.png“
-> See „IBM-Server1&2_Ping6_OK.png“
-> i have a sharp video of the boot - unfortunately i cant upload it here. please ask me if it is needed.

**Sideinfo:** with ZOS-V1 it worked well

# In case of the DELL Servers…
**Server & Hardware Infos:**	
Product name:	DELL PowerEdge R910	
Systemrevision: II	
Lifecycle-Controller Firmware: 1.6.0.73

Raid-Controller: „PERC H700“ (Chipset LSI 2108 ROC)
Tried Harddisks: WD, Mircon SSD, HGST …
Networkinterface: INTEL Gigabit CT Desktop Adapter PCIe (EXPI9301CT)

### Timeline:
1.	ZOS-V2 is getting an IPV6 Address and is downloading the ZOS-V2.
2.	ZOS-V2 wont boot. It says „Probing EDD“ -> See „DELL_wontBoot.png“
a.	Tried all variations of settings in the Raid-Controller
b.	Tried different disks.
c.	If i disable all disks. It boots but gets stuck at same Stage (3/3) like i described for the IBM Servers.

# Infos:
ZeroOs V2 Release: 0.2.2-rc4
Chain: https://bootstrap.grid.tf/kernel/zero-os-development-zos-v2-generic.efi

# Screenshots:
![1 IBM-Server1_StuckAtStart](https://user-images.githubusercontent.com/24993288/77351258-d14ae300-6d3d-11ea-9784-7089562ca4db.png)
![1 IBM-Server2_StuckAtStart](https://user-images.githubusercontent.com/24993288/77351261-d1e37980-6d3d-11ea-8439-4d32237cf714.png)
![2 IBM-Server1_MountedDisks_and_IPv6](https://user-images.githubusercontent.com/24993288/77351262-d27c1000-6d3d-11ea-8c44-faed63717169.png)
![2 IBM-Server2_MountedDisks_and_IPv6](https://user-images.githubusercontent.com/24993288/77351263-d314a680-6d3d-11ea-973d-bb0016fda55e.png)
![DELL_wontBoot](https://user-images.githubusercontent.com/24993288/77351264-d314a680-6d3d-11ea-8d26-753b5822451a.png)
![IBM-Server1 2_Ping6_OK](https://user-images.githubusercontent.com/24993288/77351265-d314a680-6d3d-11ea-8b94-f2014888acab.png)
![IBM-Servers_SAS-Controller](https://user-images.githubusercontent.com/24993288/77351268-d3ad3d00-6d3d-11ea-9313-d89176cea6c0.png)

**Comment by fl0wm0ti0n** [comment]
**Update!** 
With Version ZOS v0.2.3 (https://github.com/threefoldtech/zos/releases/tag/v0.2.3) all Servers are booting now.

IBM Servers are booting with Disks in it
DELL Server are only booting without Disks in it.

Details with DELL Servers:

Again: 
With activated Disks in the Raid Controller, ZOS doesnt boot (hang after downloaded it).
With disabled Disks in the Raid Controller, ZOS does boot.

Attention: i dont use a RAID! i just use a Raid-controller to create Virtual Disks
These DELL Servers uses Raid-Controller „PERC H700“ (Chipset LSI 2108 ROC)" to handle disks.

**Comment by DylanVerstraete** [comment]
@fl0wm0ti0n Do you still have this issue?

**Comment by fl0wm0ti0n** [comment]
> @fl0wm0ti0n Do you still have this issue?

Thanks for asking, i forgot about this - its solved months ago ;) i close it
