### ISSUE TITLE
Storaged fails to start when no disks are detected

### ISSUE THREAD

**Issue by siddiquagig** [threefoldtech/zos#617]
Node gets stuck on log screen and does not boot further till main screen (Alt+f3)

![image](https://user-images.githubusercontent.com/25789724/77408829-bd50c100-6dd1-11ea-9814-43ba3bd9f25b.png)

Storaged fails to start when no disks are detected.

The Server has 2 HDDs but no SSDs in it.

Storaged fails :

![image](https://user-images.githubusercontent.com/25789724/77408626-719e1780-6dd1-11ea-827b-250b64dc6fad.png)

For ```zinit log storaged```

![image](https://user-images.githubusercontent.com/25789724/77408664-81b5f700-6dd1-11ea-90bb-bcc216bba657.png)

lsblk also shows as empty :  

![image](https://user-images.githubusercontent.com/25789724/77408728-97c3b780-6dd1-11ea-85d1-a036a59bc4a3.png)

But the node actually has Disks as shown in BIOS execution : 

![image](https://user-images.githubusercontent.com/25789724/77408870-d0fc2780-6dd1-11ea-9bdf-3c1c6dd860c0.png)

Also tried added the disks as Virtual Drives , but same results , node is stuck on logs screen : 

![image](https://user-images.githubusercontent.com/25789724/77408937-effab980-6dd1-11ea-9f87-0f0a684c82e1.png)

Server Hardware : Supermicro X9DRi-LN4+/X9DR3-LN4+

**Comment by zaibon** [comment]
The problem was on the node itself, wrong bios configuration that prevent the linux kernel to see the disks.
