### ISSUE TITLE
ssh move default port to 34022

### ISSUE THREAD

**Issue by delandtj** [threefoldtech/zos#621]
nodes with IPv6 will be accessible over ssh.
although it's all key besed, we should better move the port to something else than 22 to avoid being probed

**Comment by maxux** [comment]
Anyway, IMO we still should not ship ssh at all on production. Maybe with a really specific way including flist (obviously) for debugging in production when nothing else can be used. But we claim to have an OS without shell, ssh should not be included in prod.

This issue should at least be renamed, changing the port is useless.

**Comment by zaibon** [comment]
At some point we will disable but for now during migration we need to keep it.
Having the zinit service define here also prepare for this cause the day we want to shut it down we just have to change the content of the service to a no-op, and hop ssh is gone :-)

**Comment by xmonader** [comment]
there's an issue to disable debugging all together #1597
