### ISSUE TITLE
networkd: improve network validation to allow better error message

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#624]
Let's try to improve https://github.com/threefoldtech/zos/blob/6169ccb7fd0092f3045d1e0c82810181467f847b/pkg/network/networker.go#L142
So we can catch most common mistake made by users when defining networks and creating containers.

We should have proper error message for cases like:
- container creation with an ip that is not part of the network resource of the node
- conflicting network resource ip range
- ...

**Comment by muhamadazmy** [comment]
A lot has improved regarding this. but the user can still cause conflicts if for example he used the same ip twice in 2 different VMs on the same node (same subnet). there is noway this can be detected (cleanly) before the system checks against each single user deployment on the node.
