### ISSUE TITLE
User ipaddr is of type ipaddr

### ISSUE THREAD

**Issue by grimpy** [threefoldtech/zos#627]
https://github.com/threefoldtech/zos/blob/6169ccb7fd0092f3045d1e0c82810181467f847b/tools/bcdb_mock/models/schema/phonebook/tfgrid_phonebook_user_1.toml#L6

We need a way to reference to the user (3bot) with a hostname instead of ipaddr
So I would suggest to migrate ipaddr to host which is validated for valid hostname/domain

**Comment by zaibon** [comment]
@grimpy @muhamadazmy 
>  So I would suggest to migrate ipaddr to host which is validated for valid hostname/domain

`host` is a type supported by the JSX schema ? Does host also support IP addresses ? 
Cause I do want to support both.

**Comment by zaibon** [comment]
The type use for this field in jumpscale is actually a `string`, not `ipaddress`. I'll update to string in our code base too.
