### ISSUE TITLE
Explorer should reject reservations for farms which do not have a valid address

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/zos#631]
as all payments are done through stellar, a reservation which includes nodes on a farm which does not have a valid stellar address need to be rejected. otherwise we end up with funds on escrow addresses we can not payout.

Note: a valid stellar address here means that the address itself is a valid format, and the address has a trustline set up for the TFT asset (or we can not pay it either)

**Comment by muhamadazmy** [comment]
Would it make more sense to not allow creating farms with invalid addresses, hence we don't have to check the addresses of farmer of the node with each request.

**Comment by LeeSmet** [comment]
Well, the problem is we already have a lot of farms in production. And these currently have a TFT address set (no address). So the owners will need to update the address. but the nodes are already live

**Comment by zaibon** [comment]
fixed in #623
