### ISSUE TITLE
Zero OS does not barf if node is only connected via IPV4

### ISSUE THREAD

**Issue by andhartl** [threefoldtech/zos#632]
Farmers like GEC connect nodes on ipv4 addresses only. they are listed as node in the explorer but can not be connected to for capacity usage. can we implement a  mechanism which doe snot allow ipv4 only connection in combination listing? thx

**Comment by zaibon** [comment]
This is becoming a more present issue now.
There seems to be a lot of nodes that are booted but don't have a proper network configuration:
http://10.4.0.250:3000/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Loki%22,%7B%22expr%22:%22%7Blevel%3D%5C%22fatal%5C%22%7D%22%7D,%7B%22mode%22:%22Logs%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D

To solve this we can send a mail to the farmers. I propose we create a script that query all the nodes that report this kind of error, we extract the node ID from the result, then send a mail to all farmer concerned to invite them to review their IPV6 network farm configuration.

**Comment by muhamadazmy** [comment]
@zaibon  Can we check this only by revising nodes `public_config` and then see if they have ipv6 or not?  Also `public_config = null` is still allowed/possible, no?

**Comment by zaibon** [comment]
> @zaibon Can we check this only by revising nodes public_config and then see if they have ipv6 or not? Also public_config = null is still allowed/possible, no?

No this is not how it works. `public_config` is an optional configuration. Most of the node won't have this.  I don't think we have that information in the explorer at the moment.

CC @delandtj

**Comment by zaibon** [comment]
>  can we implement a mechanism which doe snot allow ipv4 only connection in combination listing? thx

instead I prefer we do the following. The node is still registered in the explorer. So the farmer can have some information about the network interfaces, capacity and he can earns its farming token.
But in addition to this, we need a way to show that the node network is not right. 

An extra field in the node object ?
Maybe we could have some kind of health check for each daemon. And report this health check to the explorer ?

@DylanVerstraete @muhamadazmy

**Comment by DylanVerstraete** [comment]
sounds like a good idea, this will force the farmer not as much as sending him an email about some missing configuration. But then again, will the farmer check the explorer and notice these health checks?

**Comment by muhamadazmy** [comment]
@zaibon Don't we already report all interfaces of the node to the explorer ? Can't we check this and show a warning if no interface has a valid ipv6 ? 
Implementing a health checks for the daemon is more generic and better idea but is way much work.

**Comment by zaibon** [comment]
> Don't we already report all interfaces of the node to the explorer 

We do it seems we do not report the info for the `ndmz` network namespace and interface, which is where we can detect if the node is all good or not. 
I guess the code reporting the interfaces needs to be adapted to also include it

**Comment by DylanVerstraete** [comment]
Whilst looking for reporting the `ndmz` network namespace I noticed that the macaddress for all the interfaces is not properly reported.
Also we seem to report the `ndmz` bridge: 

```
"ifaces": [
{
"name": "lo",
"addrs": [
"127.0.0.1/8",
"::1/128"
],
"gateway": null,
"macaddress": ""
},
{
"name": "eth0",
"addrs": [
"fe80::5645:46ff:fef6:261/64"
],
"gateway": null,
"macaddress": ""
},
{
"name": "zos",
"addrs": [
"192.168.123.22/24",
"fd74:cc1c:6079:0:5645:46ff:fef6:261/64",
"fe80::ac15:adff:fe7b:b3ae/64"
],
"gateway": [
"192.168.123.1"
],
"macaddress": ""
},
{
"name": "br-ndmz",
"addrs": null,
"gateway": null,
"macaddress": ""
}
],
```

**Comment by zaibon** [comment]
We need do not care about the IP address of the ndmz bridge. We want the IP of the interface in the ndmz network namespace.

**Comment by DylanVerstraete** [comment]
Once we have these IP's, how do we indicate if a node is healthy?

**Comment by zaibon** [comment]
@andhartl here are some screenshot of the new feature in the farm mangement app. Have a look and let us know what you think and if you believe we need anything else.

![2020-05-19_1582x394_scrot](https://user-images.githubusercontent.com/303164/82315705-fe2d1680-99cb-11ea-9e37-21bfa2de008b.png)
![2020-05-19_1607x414_scrot](https://user-images.githubusercontent.com/303164/82315709-fec5ad00-99cb-11ea-873e-d7cb30d753b2.png)
![2020-05-19_1801x617_scrot](https://user-images.githubusercontent.com/303164/82315711-ff5e4380-99cb-11ea-8fe4-892cd4f3983c.png)
![2020-05-19_3199x211_scrot](https://user-images.githubusercontent.com/303164/82315712-fff6da00-99cb-11ea-87be-da4c3f5757e7.png)
