### ISSUE TITLE
Network documentation rewriting

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#638]
All the information is now in the documentation, but it is not organized enough. We need to restructure the doc into a readable and easy searchable documents.

We can also update the documentation now that ipv4 only is supported:
- dhcp config for farmers
- ...

**Comment by weynandkuijpers** [comment]
This issue has not been updated for a long time.  Please reconsider if this is part if this release or the next.  I'll remove it if not update and considered part of this release.  Bump it up to in progress is this needs to be done in this release or push it to the next one.

**Comment by delandtj** [comment]
things are a bit different now, so reorg of doc would be more of a rewrite. 
so not sure if we keep this or create a new one

**Comment by delandtj** [comment]
Also: I have talked with @maxux while he was in EG, and he as well had problems to transfer data over wireguard... I suspect Egypt has catched up for WG DPI and blocks it.

I built a wg connection just fine to that node from here at home, but no handshake from your ip.
can't ping the endpoint though, nor the ipv6 addr.

```peer: GqoPXVsGDaqO+0fq25vNmizLb//yIygtwQh+igV34WQ=
  endpoint: 197.61.48.52:40175
  allowed ips: fdd0:ba9f:71ae:4ecc:ca39:8134:ee4c:6ecb/128
  transfer: 296 B received, 26.63 MiB sent
  persistent keepalive: every 25 seconds
```
so some packets arrived on that port, but no handshake

provided your config is correct, I don't see anything wrong

that's how it should look like:

```
peer: 73p+0AymmGtrFvaou9VmeRh3neyT6EI+3BBpzoyLRgI=
  endpoint: 197.162.238.165:443
  allowed ips: 192.168.251.11/32
  latest handshake: 19 seconds ago
  transfer: 137.62 MiB received, 157.94 MiB sent
  persistent keepalive: every 25 seconds
```

**Comment by delandtj** [comment]
https://github.com/delandtj/network_setup_doc/blob/main/Basic_network.md

**Comment by weynandkuijpers** [comment]
@delandtj Can you please agree with Geert what to do?  I am okay with rewrite if we have a different setup today.  but please keep in mind:
- we need to have a description for release 2.5 and the next ones (pre-3.0) with is valid and true
- when we release 3.0 on testnet we need to have the 3.0 version live and take down the 2.5 version.

@gmachtel Can you plan and discuss with @delandtj ?

**Comment by weynandkuijpers** [comment]
Sorry - wrong button

**Comment by sasha-astiadi** [comment]
https://github.com/delandtj/network_setup_doc/blob/main/Basic_network.md

**Comment by gmachtel** [comment]
Based on feedback from GE (on their deployment on testnet), we see that a few steps are missing/unclear in the process. Propose to move it to grid 2.6, based on feedback collected from GE as use case.

**Comment by weynandkuijpers** [comment]
we cannot keep postponing this.  So we're now committed to delive this for TF Grid 3.0.

**Comment by muhamadazmy** [comment]
https://github.com/threefoldtech/zos/tree/main/docs/internals/network
