### ISSUE TITLE
tfuser provision requires seed flag to be set twice

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/zos#646]
When trying to create a provision using tfuser, you now need to set the `--seed` flag both after `tfuser` and after `provision`, since the flag is declared on both, and is required on both. If the `seed` flag is set only once, it will fail with an error noting a required flag is missing.

**Comment by zaibon** [comment]
This would be solved with #660

**Comment by zaibon** [comment]
fixed in #673
