### ISSUE TITLE
Reservation cancel is not working

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/zos#648]
### Steps
1- Create network
```python
zos = j.sal.zosv2
r = zos.reservation_create()
network = zos.network.create(r, ip_range="10.237.0.0/16", network_name="test")
nodes = zos.nodes_finder.nodes_search(farm_name="freefarm")
node_ipv6 = next(filter(zos.nodes_finder.filter_public_ip6, nodes)) 
node_ipv4 = next(filter(zos.nodes_finder.filter_public_ip4, nodes))
zos.network.add_node(network, node_ipv4.node_id, "10.237.94.0/24")
zos.network.add_node(network, node_ipv6.node_id, "10.237.98.0/24")
wg_config = zos.network.add_access(network, node_ipv4.node_id, "10.237.200.0/24", ipv4=True)
expiration = j.data.time.epoch + (3600 * 24)
network_rid = zos.reservation_register(r, expiration)
zos.reservation_result(network_rid)
```
2- Make sure that there is no error in this result
3- Create k8s cluster with one master and one worker on the same node.
```python
zos = j.sal.zosv2
r = zos.reservation_create()
master = zos.kubernetes.add_master(reservation=r, node_id=node_ipv6.node_id, network_name="test", cluster_secret="test_k8s", ip_address="10.237.98.21", size=1, ssh_keys=<sshkeys>)
worker = zos.kubernetes.add_worker(reservation=r, node_id=node_ipv6.node_id ,network_name="test", cluster_secret="test_k8s", ip_address="10.237.98.22", size=1, master_ip="10.237.98.21", ssh_keys=<sshkeys>)
kubers_rid = zos.reservation_register(r, expiration)
zos.reservation_result(kubers_id) 
```
4- Cancel reservation.
```python
zos.reservation_cancel(kubers_rid)
```
### Expected Result
Can't ssh on k8s cluster

### Actual Result
Still can ssh on the cluster.

![ssh_k8s](https://user-images.githubusercontent.com/41957921/77892043-389ef080-7272-11ea-83ca-cf49c513f7cd.png)

**Comment by zaibon** [comment]
@AhmedHanafy725 can you provide the reservation ID  where you reserve the k8s cluster please.

**Comment by AhmedHanafy725** [comment]
458409

**Comment by zaibon** [comment]
I managed to reproduce. raise this to major, we need to find the root cause.

**Comment by muhamadazmy** [comment]
![image](https://user-images.githubusercontent.com/10920323/78276717-b9304c00-7513-11ea-8464-6c5a26a8f22f.png)

I checked the reservation [here](https://explorer.testnet.grid.tf/explorer/reservations/458409) and it seems the reservation is created with wrong delete signing request

**Comment by zaibon** [comment]
Indeed, and I had the same error when I reproduced the error. So it's a client error.
We could improve the reservation validation to avoid this kind of error though. But this issue can be closed.

follow up at https://github.com/threefoldtech/jumpscaleX_libs/issues/148
