### ISSUE TITLE
allow farmer to mark some node as free to use

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#667]
In order to allow people to play with the capacity on mainnet without having to spend real money, a new stellar asset [FreeTFT](https://github.com/threefoldfoundation/tft-stellar/#freetft) [has been created](https://gist.github.com/robvanmieghem/324d7b33fb5961af0adb3225fa33d315#initial-grid-launch-only-with-stellar-tft).
The goal of this token is for any user to received a one time "gift" or a certain amount of FreeTFT.
Since these FreeTFT are meant to be free, the farmer need the ability to mark some of their node as free to use. Having this flag enabled on a node means the users can pay for reserved capacity on this node with FreeTFT. The FreeTFT will then be burn in the explorer instead of being transfered to the farmer.

**Comment by LeeSmet** [comment]
While I understand the idea, i.e. we want to give people a small sample of how he can use the grid, I wonder who will actually do this. Not only will a farmer not get paid for the capacity on the node, if anything is actually deployed, this will lead to an increased cost for the farmer (for example more cpu work therefore more electricity is used therefore a higher electricity bill).

Perhaps we could expand testnet a bit, and let people play with capacity here? This is also free, and then we have real workloads on the testnet while we test new features / bug fixes

**Comment by zaibon** [comment]
I thought about the same first but then I realize there are 2 problems with this:
- on testnet is minting doesn't not happens. So they would not get money twice. 
- We do push newer code on testnet. So stability there is not guarantee

**Comment by zaibon** [comment]
We still need to implement the burning of FreeTFT
