### ISSUE TITLE
Design node identity

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#67]
We need to decide how we are going to identify a node.

Since most of the tfgrid identity system will be based on a key pair, we could for each node, generate a key pair. Use the base64 encoded version of the public key as identity of a node.

Example: https://play.golang.org/p/IycmGa1USUi

Now this brings one problem, this key pair will have to be stored on the node disk itself. Which means we bring some state in 0-OS. That is something we want to avoid.
Once possible solution for that would be to use a deterministic seed to generate the key pair that is unique for a node (hardware serial number,...)
This would allow to always be able to generate the key pair. But I'm not sure this is doable without compromising the full security. Since if someone can deduct the seed, he can then make himself looks like a certain node.

**Comment by LeeSmet** [comment]
The problem with deterministic generation of a keypair is  that a malicious party can generate the same pair if it knows the inputs. So we would need something which we can assume is private information, and has enough entropy (so someone can not just exhaust every value in the field).

On a related note, what is the main reason we would need a persistent node identity/key?

**Comment by zaibon** [comment]
> The problem with deterministic generation of a keypair is that a malicious party can generate the same pair if it knows the inputs. So we would need something which we can assume is private information, and has enough entropy (so someone can not just exhaust every value in the field).

Yep exactly, and so far I don't really see anything that could provide us with this.

> On a related note, what is the main reason we would need a persistent node identity/key?

A node needs to be uniquely identify inside the grid, this is required for both reservation and network configuration.

**Comment by muhamadazmy** [comment]
First, I totally agree with @LeeSmet that deterministic generation is a bad idea, i can see @zaibon  also agree with this. We even tried this approach with `zerotier` before.

Speaking of zerotier, i think the way zerotier manages and generates IDs is actually pretty good and should work in our case. A managed entity, like the hub, or capacity.threefold.tech where farmers registers their farms, will boot their nodes, and ask them to join the farm (this can be as easy as boot with the correct kernel params with this farmer id) the node will generate the ID and persist it on cache (bear with me). The farmer then can authorize the node to be part of his farm if he knows for sure that this is his node (may be push some node info like the hostname, etc.. to make the farmer identify his nodes) once the node is authorized, it then can act as a farmer node. 

Persisting an ID on the disk in that case won't be an issue, it's up to the farmer to make sure his node identity is not leaked, but even if it's leaked, he can always unauthorized this identity on the farm portal, and ask the node to generate a new identity, and authorize it again.

Once all farmer ids are registered, a node can publish it's capacity and appear in the search results (or on the block chain offers) as "certified" node.

**Comment by zaibon** [comment]
I like the idea that a farmer can managed its own node. This indeed can help to ease the recover of a lost node or something.

We could have something like:
- the farmer register his farm.
- the farm will also have an identify (key pair)
- Farmer boots a node with its farmer identify as kernel parameter.
- The node bootstrap itself, and generate its own identity.
- The node will then register itself on the grid, and send a none signed with the public key of the farmer that it has as kernel params
- The node will then be marked as ready to be claimed by the farmer
- The farmer validate that the new node is indeed his
- The node is accepted and can now start serving workloads

**Comment by zaibon** [comment]
The identity package has been created and used for out test during networkd development.
We recently change base64 encoding of public key to base58 so the identity generated is URL friendly.

https://github.com/threefoldtech/zosv2/tree/master/modules/identity

This seems to do the job we want quite effectively so I'm going to close this issue for now. feel free to re-open if some problem with the current implementation arise
