### ISSUE TITLE
capacityd spams explorer when he fails to send total resources at boot

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#679]
![2020-04-04_2465x1198_scrot](https://user-images.githubusercontent.com/303164/78421687-e0913100-7659-11ea-9c8a-5b98a5a53ab2.png)
This is a snapshot of the network bandwidth of the testnet explorer when some node were trying to boot with a farm ID that did not exist.

What happens is a cascade of things:
- identity fails to register the node because the explorer return a 404 because the farm ID is not known
- capacity at the same time is trying to push the total capacity on the node. Because the node failed to register itself, the explorer returns a 404 also here because it doesn't know about the node yet.
- capacity then log.Fatal on this error and restarts forever creating a very busy loop resulting of a LOT of useless traffic to the explorer

To solve this we need to address multiple things:
- [ ] make capacity smarted and add a backoff on the function that tries to send the total capcity
- [ ] make sure capacity doesn't try to push information before identity has actually registered the node

**Comment by LeeSmet** [comment]
I assume the main bandwith usage comes from the dmi dumps here
