### ISSUE TITLE
explorer: invalid account address: horizon error: "Resource Missing"

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#687]
```
2020-04-07T10:50:02+02:00 error invalid account address: horizon error: "Resource Missing" - check horizon.Error.Problem for more information
```

**Comment by DylanVerstraete** [comment]
How to reproduce?

**Comment by zaibon** [comment]
I think this happens when the farm has not wallet address set for the configured asset

**Comment by LeeSmet** [comment]
This is from before the refactor for multiple assets then I guess? because that should invalidate this issue afaik

**Comment by zaibon** [comment]
> This is from before the refactor for multiple assets then I guess? because that should invalidate this issue afaik

yes indeed.

**Comment by zaibon** [comment]
@DylanVerstraete Closed because this cannot happen anymore with the latest code ?
