### ISSUE TITLE
Escrow: reduce amount of xlm used to active account

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/zos#692]
Currently new escrow accounts get activated by funding them with a static fee of 10 xlm. This amount can be reduced (need to calculate exactly how much we set), so we waste less xlm

At the same time, we already fund txes from escrow accounts using the base account. So we should investigate if we can recover these funds after the account is set up correctly

**Comment by DylanVerstraete** [comment]
Official docs: All Stellar accounts must maintain a minimum balance of lumens. The minimum balance is calculated using the base reserve, which is currently 0.5 XLM:

Minimum Balance = (2 + # of entries) * base reserve

**Comment by DylanVerstraete** [comment]
So in our case we have 3 assets and a potential minimum of 3 signers

so this would result in a minimum balance of: (2 + 6) * 0.5 = 4

Also if more signers are given we should increase the minimum balance
