### ISSUE TITLE
v2 Node boots up but no Storage pools  are shown (even no SSD shows up)

### ISSUE THREAD

**Issue by siddiquagig** [threefoldtech/zos#712]
We booted a node for a farmer : ```edersfarm``` on main explorer

Farmer-ID : 173618

His node booted up till the main screen but no storage pools were shown even though the node has both SSDs and HDDs present:

![image](https://user-images.githubusercontent.com/25789724/79135821-012b5a80-7dc1-11ea-9140-d62223cad2a9.png)

Though the node booted up : 

![image](https://user-images.githubusercontent.com/25789724/79135954-39329d80-7dc1-11ea-8452-90b5051eef7d.png)

from ```zinit``` 

![image](https://user-images.githubusercontent.com/25789724/79136060-6f701d00-7dc1-11ea-9286-3a63c7bde5cf.png)

from ```zinit log storaged```

![image](https://user-images.githubusercontent.com/25789724/79136095-7eef6600-7dc1-11ea-890e-81fab8fb9340.png)

**Comment by DylanVerstraete** [comment]
@siddiquagig can you verify this is still an issue with the lastest image we provide on https://bootstrap.grid.tf/? Thanks

**Comment by DylanVerstraete** [comment]
Looks like this is resolved.
