### ISSUE TITLE
k8s: cluster errored after the reservation

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/zos#721]
### Environment
Testnet
### Error
- After 2 days of the reservation, I found that the cluster is deleted due to this error.
- This happens twice
#### First reservation
![image](https://user-images.githubusercontent.com/41957921/79310748-b7e02580-7efc-11ea-8dd7-e27beda3d210.png)
#### Second reservation
![image](https://user-images.githubusercontent.com/41957921/79310930-fb3a9400-7efc-11ea-98ab-adb0df4ceaaa.png)

**Comment by zaibon** [comment]
You reservation has been deleted cause it reached its expiration time. What exactly did you expect to see instead ?
```python
JSX> r = cl.reservations.get(458953)                                                                                                                                                                     
JSX> str(datetime.datetime.fromtimestamp(r.data_reservation.expiration_provisioning))                                                                                                                    
'2020-04-08 12:07:28'
```

**Comment by AhmedHanafy725** [comment]
```python
JSX> r = zos.reservation_get(459128)                                                                                                           
JSX> str(datetime.datetime.fromtimestamp(r.data_reservation.expiration_provisioning))                                                          
'2020-04-13 09:03:47'
JSX> str(datetime.datetime.fromtimestamp(r.data_reservation.expiration_reservation))                                                           
'2021-04-13 08:58:12'
```
This for second reservation as I remember its date
`expiration_provisioning` date was the reservation date, and this reservation was for 1 year and I was working on yesterday, it was deleted by the end of 14-4-2020

**Comment by zaibon** [comment]
ha yeah ok indeed my bad I checked the wrong field.

**Comment by DylanVerstraete** [comment]
Does not seem like an issue anymore
