### ISSUE TITLE
GPU Support

### ISSUE THREAD

**Issue by andhartl** [threefoldtech/zos#741]
Many potential farmers approached us asking for GPU support. Next to all classic coin miners who have spare GPU power recently HPE came up with the idea of a research grid for universities and high performance computing (hpc) institutes. In this research grid next to CU and SU in addition GPU support would be needed. Right now exchange of GPU resources amongst universities and hpc institutes is available. With adding GPU we would open our classic grid to the research community and complete our offering.

**Comment by muhamadazmy** [comment]
- Some research has been done already over the usage of GPU with VMs 
- Need zos nodes with GPU to develop and test against.

**Comment by muhamadazmy** [comment]
Closed as duplicate for #1293
