### ISSUE TITLE
Reservation payment: next_action wasn't updated after PAY

### ISSUE THREAD

**Issue by ranatrk** [threefoldtech/zos#745]
When creating a reservation with a payment, then paying(transfer) for the transaction with the stellar wallet client, the next_action of the reservation wasn't updated for a very long time until eventually the expiration provisioning was reached and so it was changed to DELETE.
- reservation id: 78
- escrow details:
![Screenshot from 2020-04-22 11-23-54](https://user-images.githubusercontent.com/17128393/79964998-c6de4f00-848b-11ea-846f-cf48a894eb5a.png)
- payment:
![Screenshot from 2020-04-22 11-24-19](https://user-images.githubusercontent.com/17128393/79965054-d65d9800-848b-11ea-9650-52cf7e6909b7.png)
- next_action:
![Screenshot from 2020-04-22 11-24-49](https://user-images.githubusercontent.com/17128393/79965128-f2f9d000-848b-11ea-86da-9922b3bc875f.png)

**Comment by zaibon** [comment]
This is because you did not inlcude the required message into your stellar transaction. The expected way to work is to use the zos SAL only. Now you are doing the transfert manually which leads to error.

Check the documentation at https://github.com/threefoldtech/jumpscaleX_libs/tree/development/JumpscaleLibs/sal/zosv2#payment-of-a-reservation

**Comment by ranatrk** [comment]
Ok thank you. I tried using the message like the code in `payout_farmers(..)` and it was successful and went to DEPLOY. But when directly using the function  it didn't work because the asset was different from the asset in the escrow details. Should the function be using the asset in the registered_reservation provided instead?

**Comment by zaibon** [comment]
> Should the function be using the asset in the registered_reservation provided instead?

Well it should it it can. But the function accepts a wallet. So you need to check that the wallet actual has the required currency and it has enough of it. Otherwise an error must be raised.

**Comment by ranatrk** [comment]
> > Should the function be using the asset in the registered_reservation provided instead?
> 
> Well it should it it can. But the function accepts a wallet. So you need to check that the wallet actual has the required currency and it has enough of it. Otherwise an error must be raised.

Created a seperate [issue](https://github.com/threefoldtech/jumpscaleX_threebot/issues/642)  to handle that check in the chatflows , so far the response that the funds are not enough are just shown to the user
