### ISSUE TITLE
bad file descriptor: zos container

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/zos#747]
Using [simulator playground](http://play.grid.tf) to provision a jsx container and starting a simulator webapp sometimes when we create a new simulator

# what's expected
smooth usage of simulator webapp and being able to run/render notebooks

# what happens
 we get errors like

![image](https://user-images.githubusercontent.com/64129/80100138-cdde8d80-856f-11ea-970b-c434043d88e2.png)

![image](https://user-images.githubusercontent.com/64129/80100127-c61ee900-856f-11ea-9e0a-9b0784387fd6.png)
as soon as we interact with the notebooks.

# links
- [simulator playground](http://play.grid.tf) 
- [simulator playground code](https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/tfgrid_solutions/simulator_playground/chatflows/simulator_playground.py)

- Containers expire in 1 hour on the playground service

**Comment by zaibon** [comment]
maybe linked to https://github.com/threefoldtech/zos/issues/728

**Comment by DylanVerstraete** [comment]
Closing because this is not happening anymore.
