### ISSUE TITLE
failed to create container with attached volume in a single reservation

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#759]
https://explorer.testnet.grid.tf/explorer/reservations/459798

**Comment by zaibon** [comment]
I think the problem lies in the fact that when creating a container and attaching a volume to it, we need to first check that the volume actually belong to the same user. We do not want random people mounting from other users into their container, that would be pretty bad.

To do this, during the container provision, we get the volume reservation from the reservation cache: https://github.com/threefoldtech/zos/blob/9f29a631ed98594cc0101362f340b3d2bbfa8ccd/pkg/provision/primitives/container.go#L141 using its full ID (reservationID-workloadID)

The problem lies in the fact that when we create a volume and a container in the same reservation. We don't have the reservation ID yet. So when creating the mount object https://github.com/threefoldtech/zos/blob/9f29a631ed98594cc0101362f340b3d2bbfa8ccd/pkg/provision/primitives/container.go#L30-L33 in the container reservation we don't know the full volume ID.

At some point we had a trick where when use this notation in the mount object. 
Let's says in the reservation the volume has a workoad ID of 2, we would set the mount.VolumeID value to `-2`. Then the explorer when receiving the reservation would detect this and full the reservation ID when it is known so things would fall into place later on.

This is actually a problem cause that means we change the content of the reservation and this invalidated the signature of the user. I think we need another solution.

**Comment by LeeSmet** [comment]
Well we actually only need the full volume ID on the node itself. At this point, we are in the provision engine, which has both the reservation ID and the workload ID. So the provision engine can then manually assemble the full ID for the volume, without requiring anything to be changed in the reservation field afaik?

**Comment by zaibon** [comment]
This is right. I guess the code that convert the Explorer reservation type into the internal workloads type could fill the missing information since it has it.

Somewhere there: 	https://github.com/threefoldtech/zos/blob/9f29a631ed98594cc0101362f340b3d2bbfa8ccd/pkg/provision/primitives/converter.go#L44-L49

**Comment by DylanVerstraete** [comment]
@zaibon @LeeSmet  I am looking in the code but I cannot see where I should get this reservationID..

**Comment by zaibon** [comment]
I think there you have it: https://github.com/threefoldtech/zos/blob/9f29a631ed98594cc0101362f340b3d2bbfa8ccd/pkg/provision/primitives/converter.go#L211
