### ISSUE TITLE
Getting a failure while creating an gitea reservation

### ISSUE THREAD

**Issue by BolaNasr** [threefoldtech/zos#763]
why gives me this error although  it should give me a random farm that has enough space.

explorer: Testnet

https://explorer.testnet.grid.tf/explorer/reservations/459935

![image](https://user-images.githubusercontent.com/10259267/81061629-f9993600-8ed4-11ea-80bb-402916bf32f7.png)

**Comment by zaibon** [comment]
This is not an expected error. The node used in this reservation reported a total of 0 SRU. So the error message is consistent.
