### ISSUE TITLE
Can we support externally connected sensors in zos?

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/zos#773]
HPE is considering using TF Tech technology to create services for smart cities.  This would require having the ability to interact with a USB device.  I think this is not in the standard version of zos, is it? 

The simple answer is to only use a network-enabled sensor device but is this the only way this can be done?

**Comment by zaibon** [comment]
This requires more information. 

> interact with a USB device

Define interact? and What does this user "Devices" does ?

Ultimately I think this is not really a use case for 0-OS indeed. 0-OS just exposes raw capacity: Storage, Compute and Network. 

You can run any software in some containers, but if you need to access hardware specific "devices" this requires customization in all the layers, from the 0-OS kernel up to the IT contract.
