### ISSUE TITLE
network deployment failed: Container: couldn't load network with id 

### ISSUE THREAD

**Issue by hteibler** [threefoldtech/zos#775]
Sorry your reservation 9331 has failed :
CONTAINER: COULDN'T LOAD NETWORK WITH ID (W7A4GRZKGFA4T): OPEN /VAR/RUN/CACHE/NETWORKD/NETWORKS/W7A4GRZKGFA4T: NO SUCH FILE OR DIRECTORY

![image](https://user-images.githubusercontent.com/24313736/81648997-eab00780-942f-11ea-9b2d-7a06e15ec87e.png)

but payment succeeded

![image](https://user-images.githubusercontent.com/24313736/81649063-061b1280-9430-11ea-8ee8-2b531fcf0119.png)

**Comment by zaibon** [comment]
@hteibler This can happen indeed that for one reason or another a node fails to actually deploy a workload. If you check your wallet you will see that you have been refunded for the reservation and the reservation has been cancelled.

**Comment by MathiasDeWeerdt** [comment]
I got the exact same issue. 

![image](https://user-images.githubusercontent.com/7256303/81693532-5742fa80-9460-11ea-800e-0b38cc97da6b.png)

**Comment by DylanVerstraete** [comment]
@MathiasDeWeerdt do you still get this error? If so, which network are you testing against?

**Comment by DylanVerstraete** [comment]
Closing becuase this is not causing an issue anymore
