### ISSUE TITLE
setting cgroup config for procHooks process caused "failed to write 2097152 to memory.limit_in_bytes

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/zos#779]
Updating the examples for the SDK and while deploying networks and lists I came across an error while trying to pay for his reservation

https://explorer.grid.tf/explorer/reservations/9429

Then network deployed for this is here:

https://explorer.grid.tf/explorer/reservations/9428

The actual error is at the end of the reservation:
```
state":0,"message":"error starting container: OCI runtime create failed: container_linux.go:346: starting container process caused \"process_linux.go:449: container init caused \\\"process_linux.go:415: setting cgroup config for procHooks process caused \\\\\\\"failed to write 2097152 to memory.limit_in_bytes: write /sys/fs/cgroup/memory/ns129/9429-1/memory.limit_in_bytes: device or resource busy\\\\\\\"\\\"\": unknown","epoch":1589432322,"node_id":"FCxp4JG2kr76dCnc2FzniApdwBak52uaSfbuigknS5Jx"}]}
```

**Comment by zaibon** [comment]
I see in the reservation the amount of memory reserved is 2:
```json
"capacity":{"cpu":1,"memory":2}
```
The units of the memory in this field is actually bytes. 2 is not a viable value. I'm suspecting this is the issue.

We need to validate this theory and if it is indeed the problem we should add some sanity check for these value in 0-OS and in tfexplorer.
