### ISSUE TITLE
review CPU resource allocation in containerd

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#781]
containerd has implemented CPU resource management, we should have a look and see if we need to use this instead of our custom implementation: https://github.com/containerd/containerd/pull/4083/files

**Comment by DylanVerstraete** [comment]
This change in containterd is release in https://github.com/containerd/containerd/releases/tag/v1.4.0-beta.1. Not sure if we want to use a beta release yet. Maybe we should wait until its released officially.

**Comment by zaibon** [comment]
Since https://github.com/threefoldtech/zos/commit/cf3c2a98c51ca53b566674c1cd8951d65d6151a7 we also use v1.4.0-beta.1

**Comment by DylanVerstraete** [comment]
Looks like we are practically doing the same already. We might need to look if we can use https://github.com/crosbymichael/containerd/blob/a3ca8a0dfc4f2e79487d2479fbb3ee41bc75227b/oci/spec_opts_linux.go#L124

**Comment by zaibon** [comment]
indeed, so doesn't seems to be a point of Changing what we have today.
