### ISSUE TITLE
Document file location of each module

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#79]
I would like to have clear view on all the file that each module need to be able to write/create.

Then from there we can have a reflection if this is the best layout or if we can improve things a bit.

The main idea is I want to avoid that any module can write anywhere on the filesystem. This leads to less security and make things harder do debug.

**Comment by muhamadazmy** [comment]
We can experiment with this. One of the ideas is that we chroot each module to one location so it can't break out of the chroot jail. this has the draw backs that we will have to have all the libs it needs in that location or it won't start. Another approach is to create a specific mount namespace for each module and move it to that namespace on start. 

I can give this a try and see if we can get something working with the namespaces approach.
