### ISSUE TITLE
GE: Node Identification - Show Server Name in Cockpit

### ISSUE THREAD

**Issue by gneumann333** [threefoldtech/zos#798]
In order to identify a Node in the Cockpit you currently need to find the Node-ID and then check which of you servers it is.

If the Server Name would be show in the cockpit (ILO command GET_SERVER_NAME)

That would make the Management much easier.

To consider
- Farmers may not want to share the Server name publicly and User dont need to know
  Can the Server Name only be shown to the Farmer in the Farm Management?

**Comment by zaibon** [comment]
Something like this will be available in the farm management dashboard : ![2020-06-10_1948x415_scrot](https://user-images.githubusercontent.com/303164/84271833-e3fada00-ab2c-11ea-8631-5cd0e2a7ec61.png)

https://github.com/threefoldtech/jumpscaleX_threebot/commit/e2f1119a1b083ba963af8a33689ebb0786a8f651
