### ISSUE TITLE
Design flist module

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#8]
The flist module will be responsible for managing everything related to [0-fs](https://github.com/threefoldtech/0-fs)

**Comment by muhamadazmy** [comment]
I am working on this https://github.com/muhamadazmy/rfs I hope we can use it in v2. It already uses much less memory. I need to do a decent benchmarking regarding performance, but once i have a fully working version

**Comment by zaibon** [comment]
@muhamadazmy that's cool, looking forward to see the benchmark results.

I also want to add that 0-fs is only going to be the daemon for the flist. This task is also about all the API that the flist module will expose to the upper layers. So all the code that wraps 0-fs all make it easy to use.
