### ISSUE TITLE
GE: When a deployment fails, then other already working deployment is not reachable anymore

### ISSUE THREAD

**Issue by hteibler** [threefoldtech/zos#807]
deployed network 9392 :  OK
deployed ubuntu 9393 : OK, ssh to shell OK
deployed k8s: 9410  failed
now ubuntu is not reachable anymore
wg network still working
deployed a new ubuntu 9416: ok ssh OK

**Comment by zaibon** [comment]
The new reservation system is not on testnet, which should fix this issue.

**Comment by zaibon** [comment]
as of Grid 2.2, this behavior is not yet present. If any workload failed to deploy properly it doesn't affect/cancel any other anymore.
