### ISSUE TITLE
IPV6 not working Debian 10

### ISSUE THREAD

**Issue by mooleshacat** [threefoldtech/zos#810]
Hi,

My host machine is Debian 10, I am using VirtualBox to run my 3bot with network on NAT.

I just got my IPV6 working on my router, and my host has been assigned IPV6 address.

I have everything installed and running but when it loads up it only shows an IPV4 address, no IPV6 address is there. I tried in 3box shell to enable but it says read only filesystem.

How to enable IPV6?

Thanks

**Comment by zaibon** [comment]
You don't have to tweak anything manually. 0-OS does all the required configuration automatically. 

What is your setup regarding DHCP and router advertisement for your VM? This is what 0-OS use to get its IP addresses.

You can have a look here https://github.com/threefoldtech/zos/tree/master/qemu they are some example setup to run 0-OS in a VM.

**Comment by mooleshacat** [comment]
No, 0-OS does not do it automatically. If that were the case it would have detected the NAT and assigned ipv4 and ipv6 addresses.

Furthermore, you just referred me to a link of documentation which is not referred to in the install instructions.

Either way, I have tried both methods. Method 1) does not work (connection times out and cant even download 0-OS) and Method 2 has a connection to download 0-OS but it clobbers my main network interface and I lose connections on it.

I am not sure if you noticed, I said I am using Virtualbox. I am not sure what this vm.sh is that this doc refers to, as it never says anything about vm.sh during setup and installation. Either way, creating the zos0 bridge and adding it in virtualbox does not work.

You need to clear up your documentation, fix the spelling errors, and add the missing information because I had to fill in several holes just to get where I am currently.

I was told it should be as simple as enabling NAT in the docs, which I did on the VM and it does not work.

The confusing thing is my interface enp7s0 is working with a 10/10 ipv6 score.

Please advise further steps.

**Comment by mooleshacat** [comment]
vm.sh does not even exist ... all I have is 3sdk and the 0-OS iso file to run in virtualbox... I have tried Virtualbox NAT, bridge to enp7s0, bridge to zos0, bridge to forzos, bridge to docker0 (for the hell of it) and none of them work... None of my solutions nor yours (method 1 & 2) work.

and the /etc/qemu directory does not exist on my Debian 10 install.

If this is the new internet I am very afraid for the noobs.

**Comment by abdulgig** [comment]
@leshacat , are you on telegram ? if so, please ping me here @arrajput

I'll try to help you out 

Thanks,

**Comment by zaibon** [comment]
ok let's restart from the beginning cause it seems you are mixing plenty of different topics here.
What exactly are you trying to achieve ? I might have wrongly understood what you are trying to achieve cause you posted this issue in the 0-OS repository. While reading a second time you first post, it seems you are just trying to run the 3bot container ?

So can you please exactly explain what is your goal and I can redirect you to the right repository. Cause it seems you're at the wrong place.

**Comment by DylanVerstraete** [comment]
Closing because this is not causing an issue at this time
