### ISSUE TITLE
Disks Detected but not shown on explorer

### ISSUE THREAD

**Issue by siddiquagig** [threefoldtech/zos#814]
We have  a IPv4 Farmer who has 3 Disks ( 2TB SSDs and 1 5TB HDD )  inserted into the node , the main final screen shows all 3 nodes there , but on the explorer he only sees 1 SSD on the explorer.

Node ID : 3RgGWEi1Gfj83Qkoy9PEm4jcXc3RCrUNUpSS5b57eKKD
Node version : 0.3.3
Farm :  Ukrain_Farm (173633)

All 3 disk detected by the OS:

![image](https://user-images.githubusercontent.com/25789724/83743662-15c2fb00-a66c-11ea-9ee1-c33c0f81be7d.png)

Explorer showing only 1 SSD Disk:

![image](https://user-images.githubusercontent.com/25789724/83743727-2a9f8e80-a66c-11ea-9e1a-bdbe5ea79e79.png)

**Comment by muhamadazmy** [comment]
You have SRUs! no ?

**Comment by siddiquagig** [comment]
Only 1 SSD is showing on explorer , whereas on ZeroOS main screen , the farmer can see all his 3 Disks ( 2 2TBs SSD and 1 5TB HDD)

**Comment by zaibon** [comment]
@siddiquagig in v0.3.3 [a change](https://github.com/threefoldtech/zos/commit/df021440c6d44df56be00d834dc57d65bc194cf6) has been made into capacityd so it doesn't start before networkd is completely ready. From what I can see this node is in this situation where networkd just wait to get an ipv6. I think once this is fixed. capacity will continue booting and report the proper numbers.

**Comment by siddiquagig** [comment]
@zaibon , also as mentioned this is for one of the IPv4 Farmers.

**Comment by DylanVerstraete** [comment]
Closing in favor of grid 3.0
