### ISSUE TITLE
check reservation signature on the node itself

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/zos#821]

**Comment by muhamadazmy** [comment]
To verify the reservation on the node you need:
- the reservation
- the public key(s) of the signer(s) 

You get both from the explorer. If we don't trust the explorer about the reservation (that it's valid) why should we trust the users public keys? 

Unless we have another "trusted" source for the keys, this issue does not make any sense.

**Comment by zaibon** [comment]
You see it like this because everything looks like it comes from the same place. But ultimately the node directory, the phonebook and the reservation are 3 different components. You indeed do trust the phonebook. But I would like the node themself check the reservation signature instead of blindly trusting the explorer.

**Comment by muhamadazmy** [comment]
Also the node receives ONLY "workloads". it never receives the full reservations. Hence also not receiving the signature to verify. Sending the full reservation to all the nodes (that are mentioned in the reservation) is kinda costly.

**Comment by DylanVerstraete** [comment]
We can perhaps add the customer signature to the workload as well?

**Comment by zaibon** [comment]
Hum we need to review this then. Cause there is a signature field on the reservation struct:
https://github.com/threefoldtech/zos/blob/master/pkg/provision/reservation.go#L36
And we used to validate this back in the days: https://github.com/threefoldtech/zos/blob/master/pkg/provision/reservation.go#L101

We migh need to add some signature field though

**Comment by DylanVerstraete** [comment]
> And we used to validate this back in the days:

Any reason we don't do that anymore?

> We migh need to add some signature field though

Where do we add the signature field?

**Comment by muhamadazmy** [comment]
This part is I think from the time of the mock before it grow up to be tfexplorer. the mock was only dealing with workloads, not full reservations. 
If we have to do this, then the customer is probably need to sign each workload separately (in the data reservation) and may be a final signature for the full reservation. This is going to be a backward compatibility breaking change

**Comment by zaibon** [comment]
> This part is I think from the time of the mock before it grow up to be tfexplorer. the mock was only dealing with workloads, not full reservations.

Right... and I didn't get in account that we sign the reservation and not the workloads separately. This actually raises an issue we should try to solve. Cause the node should be able to validate that what they receives is legit.
