### ISSUE TITLE
GE: network unstable

### ISSUE THREAD

**Issue by hteibler** [threefoldtech/zos#823]
Network: 9889
[wg-9889-10_100 -conf.txt](https://github.com/threefoldtech/home/files/4757930/wg-9889-10_100.-conf.txt)

k3s: 9891

something wrong inside the network
since a few days 
for example just now
deployment ok
could reach master node but always interrupted 

ping to  k3s: ( in Vienna2 node 6mVGwQ41R9f7VJpNoJ6QLs4V15dsfMNXfEmQYhVEwCz6 )

ping 10.100.28.2
PING 10.100.28.2 (10.100.28.2) 56(84) bytes of data.
missing 1-32
64 bytes from 10.100.28.2: icmp_seq=33 ttl=62 time=131175 ms
64 bytes from 10.100.28.2: icmp_seq=34 ttl=62 time=130150 ms
64 bytes from 10.100.28.2: icmp_seq=35 ttl=62 time=129127 ms
64 bytes from 10.100.28.2: icmp_seq=36 ttl=62 time=128104 ms
64 bytes from 10.100.28.2: icmp_seq=37 ttl=62 time=127079 ms
--- 37 -513 ok
64 bytes from 10.100.28.2: icmp_seq=513 ttl=62 time=71.8 ms
64 bytes from 10.100.28.2: icmp_seq=514 ttl=62 time=71.9 ms
64 bytes from 10.100.28.2: icmp_seq=515 ttl=62 time=71.6 ms
missing  516-1095
64 bytes from 10.100.28.2: icmp_seq=1096 ttl=62 time=71.1 ms
64 bytes from 10.100.28.2: icmp_seq=1170 ttl=62 time=71.7 ms
64 bytes from 10.100.28.2: icmp_seq=1340 ttl=62 time=71.7 ms
64 bytes from 10.100.28.2: icmp_seq=1468 ttl=62 time=72.1 ms
missing

**Comment by zaibon** [comment]
Most probababy similar to https://github.com/threefoldtech/zos/issues/822

**Comment by gneumann333** [comment]
We deployed a Zabbix instance in a Container in our Vienna 2 Farm
I run a 2 hour ping on the on it this is what it looks like 
FYI Ping over 3000ms are considered Packet drop.
In 2 hour we have over 56% Packet drop

![image](https://user-images.githubusercontent.com/39131062/84434962-3cb39b00-ac31-11ea-8fb6-3408cbbd624a.png)

**Comment by hteibler** [comment]
any update ?
this is critical !

**Comment by zaibon** [comment]
We have identified 3 things that could be cause of this. 
The best guess at the moment is some weird configuration of some peers in the network reservation that could creates this. And we have indeed raises this issue to critical so it has highest priority.

**Comment by hteibler** [comment]
deployed a network with only 4 nodes for a k8s cluster
but same problem, 
no connection for minutes ( sometimes more than 30 min ! )

**Comment by zaibon** [comment]
So we identified the problem. There was a problem in the configuration of the network of freefarm. You seems to be using `CBDY1Fu4CuxGpdU3zLL9QT5DGaRkxjpuJmzV6V5CBWg4` as access-node for your network. That's why you had some issue with the traffic going through this node and not with the traffic going p2p between the nodes.

**Comment by hteibler** [comment]
but the problem still exists !

**Comment by hteibler** [comment]
should I deploy a new network, or is it self healing...
```
64 bytes from 10.102.12.2: icmp_seq=544 ttl=62 time=59.3 ms
64 bytes from 10.102.12.2: icmp_seq=545 ttl=62 time=59.4 ms
64 bytes from 10.102.12.2: icmp_seq=546 ttl=62 time=59.5 ms
... missing
64 bytes from 10.102.12.2: icmp_seq=563 ttl=62 time=59.7 ms
64 bytes from 10.102.12.2: icmp_seq=564 ttl=62 time=59.5 ms
64 bytes from 10.102.12.2: icmp_seq=565 ttl=62 time=59.5 ms
64 bytes from 10.102.12.2: icmp_seq=566 ttl=62 time=59.2 ms

--- 10.102.12.2 ping statistics ---
570 packets transmitted, 328 received, 42% packet loss, time 569488ms
rtt min/avg/max/mdev = 58.631/59.733/92.574/2.113 ms
``` 
always around 50% packet loss

**Comment by zaibon** [comment]
@hteibler can you confirm this is solved, and if so close please :-). thanks

**Comment by hteibler** [comment]
still packet loss
problem not solved !!!

**Comment by zaibon** [comment]
So after further investigation, it turns out the same wireguard configuration us used by multiple people. This is the root cause of all your problem. You should create a new wireguard configuration  FOR EACH user you want to allow in the network.

So when creating a network reservation using the ZOSv2 SAL. use the `zos.network.add_access` method as many time as you need.

**Comment by hteibler** [comment]
# not working
just created a new wg-config with:
```
zos = j.sal.zosv2
ipv4_gateway='CBDY1Fu4CuxGpdU3zLL9QT5DGaRkxjpuJmzV6V5CBWg4'
gwnode = j.clients.explorer.explorer.nodes.get(ipv4_gateway)
network=j.clients.explorer.explorer.reservations.get(9889) 
n0=network.data_reservation.networks[0] 
wg_config = zos.network.add_access(n0, gwnode.node_id, '10.100.254.0/24', ipv4=True)
```
the result is  nearly the same as the old one
only keys are different
## same IPs inside 
# not working
