### ISSUE TITLE
GE: wrong node status

### ISSUE THREAD

**Issue by hteibler** [threefoldtech/zos#849]
JSX> dnode.node_id                                                                                                                                                                                                   
'DUF2knurdMuX2eJVp9o7tXq4eNBy2fbxBoWhrMXWPEtF'

JSX> zos.nodes_finder.filter_is_up(dnode)                                                                                                                                                                            
False

JSX> dnode.updated                                                                                                                                                                                                   
1593161654
= GMT: Friday, 26. June 2020 08:54:14

at the same time in Explorer 
![image](https://user-images.githubusercontent.com/24313736/85856557-83200280-b7b8-11ea-96dc-beb6d54a38cf.png)

**Comment by DylanVerstraete** [comment]
Closing in favor of grid 3.0
