### ISSUE TITLE
Disks not being detected in ZeroOS 

### ISSUE THREAD

**Issue by siddiquagig** [threefoldtech/zos#857]
We have a old IPv4 farmer who bought 2 new Gigabyte Motherboards and some new HDDs and SSDs.

Issue is the disks are being detected in the BIOS but not in ZeroOS , we have tried all options like RAID / AHCI but still the disks do not show up.

BIOS disks:
![image](https://user-images.githubusercontent.com/25789724/86098437-29c11780-bac7-11ea-9451-1a73b1b3388a.png)

Options in BIOS:
![image](https://user-images.githubusercontent.com/25789724/86098721-920ff900-bac7-11ea-8645-8f496b6dcea8.png)

ZeroOS Screen:
![image](https://user-images.githubusercontent.com/25789724/86098391-17df7480-bac7-11ea-8439-e12c9b740563.png)

As per the farmer , he booted Windows also on it and all the disks showed up there.

Motherboard : GA-970A-UD3P rev. 2.0, BIOS FC (latest)

Farmer Telegram : @korobkovalentin

**Comment by delandtj** [comment]
when there was __something__ on the disk, we default to not remove the data. Imagine booting your pc with a usb stick with 0-os on it. Oops, you now have a hosed system.
So to be able to use the disks, you need to empty them first . 
For example : by booting an Archlinux iso, and issuing these commands : 
```
parted /dev/sda -s "mklabel msdos" ; dd if=/dev/zero of=/dev/sda bs=1M count=100
```
do that for all `/dev/sdX` found with command `lsblk`

**Comment by mveplus** [comment]
Thanks, @delandtj for the tip! 
I was playing with my HP microServer Gen8 with two 6TB HDD and one 120G SSD and 0-OS was running but not displaying the disks as available however during boot, they were detected in the 0-OS boot log. Disks had ZFS partitions coming from former FreeNAS setup. I did what you suggested using CloneZilla, and "hdparm" issuing "ATA secure erase" for each one, after that disks showed in 0-OS, I have not created any partitions on. I guess 0-OS recognize that disk is not initialized&empty and does it for me?
Cheers,

**Comment by zaibon** [comment]
> I guess 0-OS recognize that disk is not initialized&empty and does it for me?
Cheers,

Indeed, 0-OS will "claim" the free disks and prepare them the way they need to be so they can be used by 0-OS.

**Comment by DylanVerstraete** [comment]
Closing because this is not an issue anymore
