### ISSUE TITLE
Provisiond should only keep one single instance of a network in cache

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#861]
Instead of just keeping all reservation ever made for a same network in cache, only the latest one should be kept. 
When a new version come to the node, the it should replace the deprecated one from cache instead of just being stored next to it.

**Comment by zaibon** [comment]
we could do that indeed to avoid using cache storage for nothing, but it doesn't really hurt anymore since the introduction of the capacity pool there is no more expiration so there is no risk to decommission an old version of a network.

**Comment by muhamadazmy** [comment]
What does that solve ? I mean the current "generic" reservation cache solution works fine for all types, why break this generic code on favor for a special case one?

**Comment by zaibon** [comment]
Network resources are a bit of a special workload. It is the only one that you can update/modify at runtime.
So usually the same node will have multiple version of the same network resource. The problem with keeping all of them in cache is that if for any reason, any of the version of the network resource workload is cancelled, the full network on this node is going to be removed.

So by only keeping the last version, we make provisiond only be able to decomission the last version which makes more sense I think. Most probably provisiond should also marked the older version as deleted to keeps things tidy on the explorer.
