### ISSUE TITLE
Allow container to have an ygg interface

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#868]
Same kind of feature then the public ipv6 for container, but instead of getting a public IP we assign an yggdrasil IP

**Comment by delandtj** [comment]
that fact that having a container on a pulbic network wiil need us to refect properly on how to protect the container itself from a public network

**Comment by zaibon** [comment]
I'll reopen this one cause the solution I proposed doesn't work properly:
- https://github.com/threefoldtech/zos/issues/942
- https://github.com/threefoldtech/zos/issues/941

We need to review the architecture of the network to  properly support both yygdrasil use cases: 0-DB and container.

**Comment by muhamadazmy** [comment]
Duplicate
