### ISSUE TITLE
Network update failed on mainnet

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/zos#871]
https://explorer.grid.tf/explorer/reservations/10589

the network contains 7 resources on different nodes but the result contains only 6 objects until the reservation expired.
the same problem happened with different reservations

**Comment by zaibon** [comment]
I checked the node and I didn't see anything special there. So I'm not sure why the reservation was never processed by this node.

**Comment by DylanVerstraete** [comment]
Closing becasue we overhauled the network code anyway. Can be reopened if needed.
