### ISSUE TITLE
Farm Management doesn't show SRU reservations

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/zos#880]
I have a few containers deployed on my own farm with SRU reservations, but 3Bot's Farm Management section does not show them:

![image](https://user-images.githubusercontent.com/17682591/89371588-a9c73800-d698-11ea-8c62-36844903eea2.png)

**Comment by zaibon** [comment]
Can you give us the reservation ID that are supposed to consume SRU please ?

**Comment by scottyeager** [comment]
Unfortunately, they have expired since I opened this. Let me try deploying some new ones and I'll report back if issue persists. Thanks.

**Comment by scottyeager** [comment]
Hi @zaibon, I've deployed another Ubuntu container to my farm, with a nice big SRU allocation this time. Reservation ID: 10719. CPU/RAM is shown in the graphs as expected, but still showing 0 SRU reserved.
