### ISSUE TITLE
Change error message when deploying 2 k8s VM on the same node and same network

### ISSUE THREAD

**Issue by BolaNasr** [threefoldtech/zos#881]
https://explorer.testnet.grid.tf/api/v1/reservations/workloads/464103

**Error message:** 

```"message": "could not set up tap device: could not add tap device: Tuntap IOCTL TUNSETIFF failed [0], errno device or resource busy```

**Comment by zaibon** [comment]
are you trying to deploy 2 k8s VM on the same node using the name network ?

**Comment by BolaNasr** [comment]
I used chat-flow with normal scenario , it's by default create K8s cluster ( 1 master and 1 slave) 
so it's create 2 k8s VM on the node it chosen by ZOS sal ( the same node)  with the same network.

**Comment by zaibon** [comment]
So this is indeed the problem, both are trying to deploy on the same node, which is not authorized:
https://explorer.testnet.grid.tf/api/v1/reservations/workloads/464102
https://explorer.testnet.grid.tf/api/v1/reservations/workloads/464103

An extra check needs to be done in the chatflow to avoid this. I will also try to return a more explicit error message from zos itself.

**Comment by DylanVerstraete** [comment]
@m-motawea can this be closed?

**Comment by m-motawea** [comment]
I just added a check in the chatflow to choose different nodes for each vm in the same cluster.
it still won't help if the user tries to deploy another cluster in the same network.

**Comment by zaibon** [comment]
> @m-motawea can this be closed?

Before we close we need to change the error message returned by the node to make it more explicit and explain the problem to the user.
