### ISSUE TITLE
can't create a container on testnet

### ISSUE THREAD

**Issue by PeterNashaat** [threefoldtech/zos#887]
- trying to create container on freefarm with tft or freetft is failling 
 - tft error
<img width="1022" alt="Screen Shot 2020-08-03 at 3 58 30 PM" src="https://user-images.githubusercontent.com/13523434/89191669-8e2e3580-d5a3-11ea-9613-2c4dfe15ccca.png">

- freetft error is due to no resources available

**Comment by ranatrk** [comment]
I also got the same error `failed to load network resource: failed to create veth pair in namespace (1424-1): container veth name provided (eth0) already exists` when trying to deploy a container using this [flist](https://hub.grid.tf/bishoy.3bot/threefolddev-mastodon-latest.flist):

I created a pool, then a network, then was creating a container with mounted volume on "/" (which realised shouldn't be done on /). They were all done using reservation_chatflow sal not zos sal directly.

The workload https://explorer.devnet.grid.tf/api/v1/reservations/workloads/1424

**Comment by zaibon** [comment]
I found one problem in the mastodon chatflow. it was trying to deploy a container with 1byte of memory which cause the container to fail to install. It seems we have some bug in the way we handle error during container creation and another one that make the same reservation to be provisioned twice which lead to the error describe in the bug

**Comment by ranatrk** [comment]
> I found one problem in the mastodon chatflow. it was trying to deploy a container with 1byte of memory which cause the container to fail to install. It seems we have some bug in the way we handle error during container creation and another one that make the same reservation to be provisioned twice which lead to the error describe in the bug

yes it was an issue caused when refactoring the chatflow. Thank you.
