### ISSUE TITLE
Can't create container on mainnet with FreeTFT

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/zos#889]
I had tried to deploy more than network and ubuntu container on mainnet, and I couldn't ssh on the container or ping it.
e.g
https://explorer.grid.tf/explorer/reservations/10871
https://explorer.grid.tf/explorer/reservations/10872

**Comment by zaibon** [comment]
Reason is the network was created with a wrong IP address as access point effectively preventing the second node to be part of the overlay network.
Fixed by https://github.com/threefoldtech/js-sdk/commit/3b1949b5529c42dc08b795511cd74493fc6f6940
