### ISSUE TITLE
EDD Probe error on server

### ISSUE THREAD

**Issue by siddiquagig** [threefoldtech/zos#890]
One of the farmers ( Recover-EFarm ) has their node stuck in the EDD probing error as shown below, he was being supported by someone from the team in setting up the 3SDK and then making a Farm through it.

He contacted us through the support chat , that his node is stuck on the below error:

![image](https://user-images.githubusercontent.com/25789724/89918854-9c1b3080-dc0b-11ea-8ceb-48387d670d02.png)

I then send him a production flag boot file through through the bootstrap which resulted in the node now being stuck here:

![image](https://user-images.githubusercontent.com/25789724/89919022-d08eec80-dc0b-11ea-9483-71fc9a8d0fa6.png)

Farmer-ID: 173647
Farmer Network: Supports only IPv4
Server Specs : 2 Dell PowerEdge R810 met 6x180GB Intel SSD’s (2.5” SATA 600) refurbished servers.

Telegram-ID : Jan-Paul Kimmel ( is in the farmers telegram channel)

**Comment by delandtj** [comment]
machine check exception.
Most probably memory... see if reseating mem helps
on his IPMI he should see the MCE log somewhere

**Comment by DylanVerstraete** [comment]
@siddiquagig Do you still have this issue?
