### ISSUE TITLE
volume: quota was not fully utilized. 10GB was the maximum written to a 20GB volume 

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#895]
Node: `BSusuRh6qFzheQFwNPe1S5FA5pdSZVJwVLhpNS6GN4XD` (production)
Volume: https://explorer.grid.tf/explorer/reservations/10996

This volume is created with 20G limit, but it gives a `Quota Exceeded Error` while it's only 10GB full.

**Comment by zaibon** [comment]
```
root@zosv2tst-5:/mnt# dd if=/dev/urandom of=file bs=1M count=10204 status=progress
10691280896 bytes (11 GB, 10 GiB) copied, 45 s, 238 MB/s 
10204+0 records in
10204+0 records out
10699669504 bytes (11 GB, 10 GiB) copied, 45.0375 s, 238 MB/s
root@zosv2tst-5:/mnt# dd if=/dev/urandom of=file bs=1M count=10204 status=progress
10667163648 bytes (11 GB, 9.9 GiB) copied, 45 s, 237 MB/s
10204+0 records in
10204+0 records out
10699669504 bytes (11 GB, 10 GiB) copied, 45.1548 s, 237 MB/s
root@zosv2tst-5:/mnt# dd if=/dev/urandom of=file_2 bs=1M count=1 status=progress
dd: failed to open 'file_2': Disk quota exceeded
```
So I tried on node `2m3nHPSAMyZFSeg5HPozic2NGBMtrXrBkhtNcVmd5Ss6` and couldn't reproduce. So I don't think this is a bug in 0-OS itself. So I would more thing about something in btrfs itself.

**Comment by muhamadazmy** [comment]
@zaibon how big was this disk ?  did u try a 20G disk ?

**Comment by zaibon** [comment]
actually there is already an issue in my previous test.
I wrote 2 time 10GiB but on the same file. So the total amount of data stored is still only 10GiB. Which means I shouldn't have had a quote exceeded error. Need to review how btrfs quota works cause it doesn't seems to only take in account actually stored data...

**Comment by muhamadazmy** [comment]
Yeah i noticed, this is why i was asking what disk size you used.

**Comment by muhamadazmy** [comment]
I really think may be setting the limit on the exclusive space instead of the referenced space might actually fix the problem. I will try to do some tests locally and see how it goes

**Comment by muhamadazmy** [comment]
- Trying to reproduce on 
  - Loop device
  - Local disk
  - ZOS running in qemu

I couldn't reproduce the issue on either of the previous setups. So I am can't be sure that setting the exclusive flag will fix the issue. Also it makes it very wrong to just double the allocated space!

Can we have a node where this issue is produced, to try to set the limit on the exclusive space instead of the referenced space to see if it has any effect?

@zaibon @delandtj

**Comment by muhamadazmy** [comment]
- So I managed to reproduce the issue on node `2m3nHPSAMyZFSeg5HPozic2NGBMtrXrBkhtNcVmd5Ss6` but happened only when the subvol was created (and mounted) as part of a container reservation.

> Subvol: `/mnt/f64fddd6-3c36-4b04-a31d-4fa37e8d9d49/470742-1`  (this can be de-provisioned anytime, no grantee it will stay)

- Creating a subvolume manually and setting the same limit, when tested we managed to utilize the full allocated quota space.
- Deleting the container and trying again to allocate space on the volume (the one created via the reservation) we still can't allocate the full space.
- using a qouta rescan  also does not fix the problem.


![image](https://user-images.githubusercontent.com/10920323/91453377-ec3af980-e87f-11ea-8bf2-a663b6e5419d.png)

> Note, the limit in the screen shot is set on the exclusive space, by default it's set on the ref space instead. but I was testing if this will make any difference.

**Comment by muhamadazmy** [comment]
This subvolume was created manually

![image](https://user-images.githubusercontent.com/10920323/91455568-84d27900-e882-11ea-833f-041fdcb737d5.png)

> Note that the limit is set on the ref space. but setting it on exclusive space has the same effect.

**Comment by zaibon** [comment]
Possible related bugs:
- https://bugzilla.kernel.org/show_bug.cgi?id=91031
- https://bugzilla.kernel.org/show_bug.cgi?id=103001
- https://bugzilla.kernel.org/show_bug.cgi?id=152071
