### ISSUE TITLE
networkID: this method doesn't grantee a unique networkID

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#898]
https://github.com/threefoldtech/zos/blob/d693d0656a8cc2bd7e72f10f1ef9d6082e43cec5/pkg/provision/primitives/network.go#L64

The method computes the hash of 2 parts (name + user) then hash them. The problem is since both inputs are strings that 2 unique strings can still concatenated to build up a not-unique string 
 
For example both (`test`, `user`) and (`testu`, `ser`) while unique pair will still add up to `testuser`

Proposal:
```go
id := hash(hash(user) + hash(name))
```

**Comment by zaibon** [comment]
User ID is already unique. So there is no way to have a conflict. We use this technique just to allow different user to use the same network name.
