### ISSUE TITLE
Design pid 1

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#9]

**Comment by muhamadazmy** [comment]
## Ideas:
- minimalistic with almost no features, this only reads config files from the image to spawn and monitor system services. 
- Setup networking as configured.
- Just make sure that critical boot services are up and running, (redis, libvirtd, syslogd, etc... )
- Can't be restarted. And can't updated without a full system reboot, so minimal code should live as PID 1.
- Personally I suggest we build this in a system language, like C or rust.

**Comment by zaibon** [comment]
I think what you describe is already way too big.
Configuring network, starting services these are not thing that the pid 1 should take care of.
The only thing It should managed is to make sure the main process manager (used to be core0) is up and running and that's it. nothing more. We want to have something so small that will can cover all its uses cases and won't have to update it ever anymore.

**Comment by zaibon** [comment]
@maxux can you describe what you did in https://github.com/maxux/0-init so we can see if that work can maybe be used for our use case.
