### ISSUE TITLE
Prepare hardware to setup first testnet

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#90]

**Comment by zaibon** [comment]
Hardware and network is ready. We now need to configure an exit node and install the tnodb for the testnet.

**Comment by zaibon** [comment]
@delandtj can you write an issue about the requirement of the exit node routing advertisement.

**Comment by delandtj** [comment]
Need to move some network parts:
the S5850 (switch) we have here is basically not IPv6 aware enough to get all our requirements for being a router in our grid.
I'll need to move the routing part out of that switch, and implement it in a linux box so we can handle proper routing.

**Comment by delandtj** [comment]
IPv6 is not a panacea, you need some things to support it.
I know a network should be ubiquitous, but to get there, there are constraints to be taken into account.
A network doesn't configure itself, contrary to many beliefs ;-) (actually, it does, when using proper routing protocols and prefix delegations, but then... yeah that's a whole different can of worms)

Again, read this:
https://github.com/threefoldtech/zosv2/blob/master/specs/network/Requirements.md

**Comment by zaibon** [comment]
Network has been redone by @delandtj  in TF office. Everything should be in place now
