### ISSUE TITLE
Failed to deploy volume

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/zos#905]
error message: `failed to create subvolume, logs might have more information`

https://explorer.testnet.grid.tf/api/v1/reservations/workloads/467940

**Comment by m-motawea** [comment]
same error happened again on the same node
https://explorer.testnet.grid.tf/api/v1/reservations/workloads/468217

**Comment by m-motawea** [comment]
again on the same node
https://explorer.testnet.grid.tf/api/v1/reservations/workloads/468544

**Comment by muhamadazmy** [comment]
For some reason I don't see my comment here anymore. But as explained on the chat the physical disk on this machine is dead and need replacement. So machine is not usable atm.
