### ISSUE TITLE
Deploying volumes randomly fails with "not enough space left in pools of this type ssd"

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/zos#910]
the workload was registered but failed wih the mentioned error. the pool has "sus": 9336.877083333338 and the node should have enough sru for the volume
https://explorer.testnet.grid.tf/api/v1/reservations/workloads/470017

**Comment by zaibon** [comment]
Multiple things to take in account here.
1. At the moment having capacity in a pool doesn't mean this capacity it actually locked on the node. More detail from the [specification](https://github.com/threefoldtech/tfexplorer/blob/master/specs/modify_IT_contract_over_time.md): 
> Now some downsides. Since it is no longer known when and how the pool will be used, capacity planning is pretty hard. The idea for now would be to not worry about this, however. Is is the responsibility of the user to select nodes which have enough capacity to deploy individual workloads. If there is no capacity available on any of the nodes in the pool, this likely means that there is a lot of usage of the grid. In reality, today this is not the case. But even if it were, this is something that might be approached completely differently on a farmer by farmer basis. Therefore, this is a non issue which should be solved by the arrival of the (farmer) threebot. In case a user deploys after only a certain time, the same logic applies. Importantly, an extension of an existing workload can never fail since it is already deployed. The client simply extends the pool, and the workload won't be decomissioned.
2. The fact that the node report free storage and fail to allocate it seems it could be related to those issues:
- https://github.com/threefoldtech/zos/issues/879
- https://github.com/threefoldtech/zos/issues/709
Which are being addressed in https://github.com/threefoldtech/zos/pull/883 which should land on devnet soon.
3. Joining the point 1. Now that you have a capacity pool available, the usual  behavior to adopt is when one node fails to provision something, try on another one. The capacity pool let you do that very easily and without any additional cost. So a more try and error approach can be put in place for code that deploys things automatically.

**Comment by OmarElawady** [comment]
Had the same issue for two workloads on the node "A7FmQZ72h7FzjkJMGXmzLDFyfyxzitDZYuernGG97nv7".

Workloads: [482883](https://explorer.testnet.grid.tf/api/v1/reservations/workloads/482883) [482995](https://explorer.testnet.grid.tf/api/v1/reservations/workloads/482995)

**Comment by waleedhammam** [comment]
also today

![image](https://user-images.githubusercontent.com/10658229/93460758-05195680-f8e4-11ea-8ae4-e658b62b7fb8.png)

workload: 483423
node: `A7FmQZ72h7FzjkJMGXmzLDFyfyxzitDZYuernGG97nv7`

**Comment by RafyAmgadBenjamin** [comment]
![image](https://user-images.githubusercontent.com/46320202/93482297-d90bce80-f8ff-11ea-876a-8f75e71dede3.png)
workload : 483693
node : `A7FmQZ72h7FzjkJMGXmzLDFyfyxzitDZYuernGG97nv7`

**Comment by waleedhammam** [comment]
on mainnet, I got it with these reservations too

`"message": "failed to create read-write subvolume for 0-fs: Not enough space left in pools of this type ssd",`
`"message": "Not enough space left in pools of this type ssd",`

- https://explorer.grid.tf/api/v1/reservations/workloads/14576
- https://explorer.grid.tf/api/v1/reservations/workloads/14478
- https://explorer.grid.tf/api/v1/reservations/workloads/14122
- https://explorer.grid.tf/api/v1/reservations/workloads/14384
- https://explorer.grid.tf/api/v1/reservations/workloads/14858
- https://explorer.grid.tf/api/v1/reservations/workloads/14975
- https://explorer.grid.tf/api/v1/reservations/workloads/15040
- https://explorer.grid.tf/api/v1/reservations/workloads/15074

**Comment by waleedhammam** [comment]
More nodes:

- https://explorer.grid.tf/api/v1/reservations/workloads/15461

**Comment by LeeSmet** [comment]
> More nodes:
>    https://explorer.grid.tf/api/v1/reservations/workloads/15461


related logs on the node:

```

  | 2020-09-30 13:12:24 | [+] storaged: 2020-09-30T11:12:24Z debug Found 0 candidates in unmounted pools
-- | -- | --
  |   | 2020-09-30 13:12:24 | [+] storaged: 2020-09-30T11:12:24Z debug Checking unmounted pools
  |   | 2020-09-30 13:12:24 | [+] storaged: 2020-09-30T11:12:24Z debug Found 0 candidates in mounted pools
  |   | 2020-09-30 13:12:24 | [+] storaged: 2020-09-30T11:12:24Z debug usage of pool c4601219-2851-496f-a5bc-cd3bfbac1a84 max size=240057409536 new size=283488813056 reserved=281341329408
  |   | 2020-09-30 13:12:24 | [+] storaged: 2020-09-30T11:12:24Z debug pool usage device=/dev/sdak size=240057409536
  |   | 2020-09-30 13:12:24 | [+] storaged: 2020-09-30T11:12:24Z debug checking pool c4601219-2851-496f-a5bc-cd3bfbac1a84 for space
  |   | 2020-09-30 13:12:24 | [+] storaged: 2020-09-30T11:12:24Z info Disk does not have enough space left to hold filesystem
  |   | 2020-09-30 13:12:24 | [+] storaged: 2020-09-30T11:12:24Z info Creating new volume with size 2147483648
  |   | 2020-09-30 13:12:24 | [+] provisiond: 2020-09-30T11:12:24Z error failed to provision reservation 15461-1 error="failed to create read-write subvolume for 0-fs: Not enough space left in pools of this type ssd"
  |   | 2020-09-30 13:12:24 | [+] provisiond: 2020-09-30T11:12:24Z error failed to apply provision error="failed to create read-write subvolume for 0-fs: Not enough space left in pools of this type ssd" id=15461-1
  |   | 2020-09-30 13:12:24 | [+] provisiond: 2020-09-30T11:12:24Z error failed leave container network namespace error="failed to unmount NS: at /var/run/netns/15461-1: device or resource busy"
  |   | 2020-09-30 13:12:24 | [+] provisiond: 2020-09-30T11:12:24Z info check for expired reservation
  |   | 2020-09-30 13:12:24 | [+] provisiond: 2020-09-30T11:12:24Z info provision statistics container=3 cru=3 delegateDomain=0 hru=20 k8sVM=0 mru=3 network=9 proxy=0 reverseProxy=0 sru=20 subdomain=0 volume=19 zDBNamespace=2
  |   | 2020-09-30 13:12:24 | [+] provisiond: 2020-09-30T11:12:24Z info reservation have already been processed id=15461-1
  |   | 2020-09-30 13:12:24 | [+] provisiond: 2020-09-30T11:12:24Z info start provisioning reservation duration=2562047h47m16.854775807s expired=false id=15461-1 tag= to-delete=false type=container
  |   | 2020-09-30 13:12:24 | [+] provisiond: 2020-09-30T11:12:24Z info assigned an IP container=15461-1 ipv4=10.100.75.2 ipv6=fd43:6954:5044:4b::2 ygg=<nil>
  |   | 2020-09-30 13:12:24 | [+] networkd: 2020-09-30T11:12:24Z info delete container network namespace container=15461-1 namespace=15461-1
  |   | 2020-09-30 13:12:24 | [+] networkd: 2020-09-30T11:12:24Z info leaving network network-id=CiTPD83rXgmbN
  |   | 2020-09-30 13:12:24 | [+] networkd: 2020-09-30T11:12:24Z info set route to container container=15461-1 namespace=15461-1 route="{Ifindex: 3 Dst: ::/0 Src: <nil> Gw: fe80::1 Flags: [] Table: 0}"
  |   | 2020-09-30 13:12:24 | [+] networkd: 2020-09-30T11:12:24Z info set route to container container=15461-1 namespace=15461-1 route="{Ifindex: 3 Dst: 0.0.0.0/0 Src: <nil> Gw: 10.100.75.1 Flags: [] Table: 0}"
  |   | 2020-09-30 13:12:24 | [+] networkd: 2020-09-30T11:12:24Z info set ip to container container=15461-1 ip=fd43:6954:5044:4b::2 namespace=15461-1
  |   | 2020-09-30 13:12:24 | [+] networkd: 2020-09-30T11:12:24Z info set ip to container container=15461-1 ip=10.100.75.2 namespace=15461-1
  |   | 2020-09-30 13:12:24 | [+] networkd: 2020-09-30T11:12:24Z info Create veth pair in net namespace container=15461-1 namespace=15461-1 veth=eth0
  |   | 2020-09-30 13:12:24 | [+] networkd: 2020-09-30T11:12:24Z info joining network network-id=CiTPD83rXgmbN
  |   | 2020-09-30 13:12:24 | [+] flistd: 2020-09-30T11:12:24Z info create new subvolume 15461-1 storage= url=https://hub.grid.tf/waleedhammam.3bot/waleedhammam-js-sdk-latest.flist
  |   | 2020-09-30 13:12:24 | [+] flistd: 2020-09-30T11:12:24Z info check if subvolume 15461-1 already exists storage= url=https://hub.grid.tf/waleedhammam.3bot/waleedhammam-js-sdk-latest.flist
  |   | 2020-09-30 13:12:24 | [+] flistd: 2020-09-30T11:12:24Z info flist already in cache url=https://hub.grid.tf/waleedhammam.3bot/waleedhammam-js-sdk-latest.flist
  |   | 2020-09-30 13:12:24 | [+] flistd: 2020-09-30T11:12:24Z info request to mount flist storage= url=https://hub.grid.tf/waleedhammam.3bot/waleedhammam-js-sdk-latest.flist
  |   | 2020-09-30 13:12:23 | [+] provisiond: 2020-09-30T11:12:23Z info Polling for reservations next=15461
  |   | 2020-09-30 13:12:13 | [+] provisiond: 2020-09-30T11:12:13Z info Polling for reservations next=15461

```

one thing which is interesting is the reported `size` when creating a new subvolume, which is actually max int32 + 1, not sure if this is a coincidence or not. It also seems that we start the provision twice

**Comment by zaibon** [comment]
> one thing which is interesting is the reported size when creating a new subvolume, which is actually max int32 + 1

I guess it's coincidence, we use uint64 for all size of disks.

> It also seems that we start the provision twice

There is an open bug for this: #922

**Comment by zaibon** [comment]
handled in https://github.com/threefoldtech/zos/issues/709

**Comment by dmahmouali** [comment]
reopen because it still happened with me.
reservation: https://explorer.devnet.grid.tf/api/v1/reservations/workloads/56544
