### ISSUE TITLE
Process gets randomly killed

### ISSUE THREAD

**Issue by tobiaschielens** [threefoldtech/zos#915]
### Description

Processes that take too many resources (build...) get killed randomly causing the build to fail

### Version information

* OS: e.g. Ubuntu 20.04, Windows 10
* project commit/version: 519c894c87b0feeb5ac05381df99ce0bd022d989
* Browser: chrome 84.0.4147.135
*
### Installation method

Via poetry

### Steps to reproduce

Deploy a list, run a process that builds something (yarn build vue-project). The process gets killed instead of being limited in resources.

**Comment by despiegk** [comment]
is per container, if a process uses more mem than container has, then it will get killed
this is normal behaviour.

**Comment by delandtj** [comment]
not much 'random' about it... you request a certain amount of mem, exceeding it (trying to allocate more than requested) will have the process in that cgroup killed

**Comment by delandtj** [comment]
> @xmonader indeed a supervisord process for crystaldrive
> 
> @abom Indeed, but it is just a quick way of getting to the core of the issue ( processes being killed for using more memory than provided ) putting a big load on the flist will also work but building is quicker
> 
> @OmarElawady reserving more resources won't fix the issue as I didn't really need the recourses. In docker, resources can be limited and the process is not killed right away

we're using the same runc as docker has, I can't think of a situation where a process doesn't get killed if it tries to allocate more mem than reserved. that's how cgroups work.
