### ISSUE TITLE
zdb: deploy zdb gives error 'address already in use'

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#916]
While deploying the workload https://explorer.testnet.grid.tf/api/v1/reservations/workloads/472974 it failed with 

`failed to ensure zdb containe running: failed to prepare zdb network: address already in use`

`~ # ip netns|grep zdb

zdb-ns-201a81e7
zdb-ns-ee1fd86b
zdb-ns-119049e0
zdb-ns-652bde38
zdb-ns-1f1e6307
zdb-ns-5801d929
zdb-ns-fc7ff3d6
zdb-ns-c96a5865
zdb-ns-19520456
zdb-ns-7a7ea7d4
`

Question: Why we create random namespaces names if we have a predicted hw address?

Suggestion: Since the hw address is computed from the volume path, we can create a predicted namespace, and then be sure that only one namespace is created by zdb. Then check that the macvlan is already create, or create a new one. 

> I can't really find out why we recieve the 'address already in use' error

**Comment by m-motawea** [comment]
more debugging info
https://explorer.testnet.grid.tf/api/v1/reservations/workloads/474629
![image](https://user-images.githubusercontent.com/32568986/92327194-3a0de980-f058-11ea-8a0d-f2fe91f29b71.png)
