### ISSUE TITLE
Failed to retrieve owner of volume

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/zos#919]
Saw this error on the explorer: https://explorer.testnet.grid.tf/api/v1/reservations/workloads/474031

**Comment by muhamadazmy** [comment]
I checked the node, and it seems the cache subvolume was removed from the filesystem while mounted under /var/cache 

Possible cause is the scheduled clean up didn't detect that this is a required subvolume and was force deleted. Will investigate code

**Comment by muhamadazmy** [comment]
So it seems this cleanup code actually is not deployed on testnet, so it can't be it. So the only possible causes are:
- Someone has manually deleted the subvol 
- Some freaky btrfs bug. But i don't see any errors in the kernel logs or anything regarding btrfs subvolumes.

We will try to fix the node manually.

**Comment by muhamadazmy** [comment]
Manual fix is not possible, the `/var/cache` can't be mounted while it's broken. a full node restart is needed

**Comment by muhamadazmy** [comment]
Unfortunately since `cache` volume is gone, the node will reboot with a new identity.

**Comment by zaibon** [comment]
I did tested the cleanup code on one of the testnet node so it's probably this one. The cache subvolume was indeed deleted by the cleanup code.

**Comment by muhamadazmy** [comment]
Ah okay then, this can be closed then. Thanks
