### ISSUE TITLE
Containers can't resolve domain names

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/zos#927]
suddenly deployed containers can't resolve any domain name.
https://explorer.testnet.grid.tf/api/v1/reservations/workloads/477332
![image](https://user-images.githubusercontent.com/32568986/92520352-be5c9a00-f21b-11ea-8f79-525ed6a2609d.png)
![image](https://user-images.githubusercontent.com/32568986/92520357-c288b780-f21b-11ea-92bc-48f000202414.png)

**Comment by zaibon** [comment]
~~zos is not modifying the DNS configuration of your container. Did you check how `/etc/resolv.conf` is configured?
I also didn't managed to reproduce this.~~

zos actually does bind mount /etc/resolv.conf inside containers, so it could be the network of the farm itself is the problem.

**Comment by xmonader** [comment]
@zaibon in resolve.conf (wasn't touched)

```
search lan
nameserver 1.1.1.1


```

**Comment by zaibon** [comment]
Can you still reproduce the problem ?

**Comment by xmonader** [comment]
> Can you still reproduce the problem ?

Not since yesterday

**Comment by zaibon** [comment]
ok so I'll put that on some networking glitch in the farm DC. I'll close for now feel free to re-open is that problems comes back.

**Comment by xmonader** [comment]
I've to reopen this, that networking error been happening almost daily around 6 pm   and 11:50 pm

summary of today's issues that happened

![image](https://user-images.githubusercontent.com/64129/93139369-e303b680-f6e0-11ea-9eea-16ed262a2549.png)
https://github.com/threefoldtech/tfgateway/issues/27

I created this flist ( https://hub.grid.tf/ahmedthabet.3bot/xmonader-ubudebug-latest ) to debug ubuntu + some nettools and when deploying https://explorer.testnet.grid.tf/api/v1/reservations/workloads/480689  
message: "failed to load network resource: failed to create file /var/run/netns/480689-1: open /var/run/netns/480689-1: operation not permitted",

- also on mazraa too https://explorer.testnet.grid.tf/api/v1/reservations/workloads/480705
and this node 3P6i8QnhByJUMXHVU9ZULQivHS8GGhjvSLHJ8dBGfbb6

![image](https://user-images.githubusercontent.com/64129/93139433-062e6600-f6e1-11ea-97f3-629060a3f38f.png)

**Comment by xmonader** [comment]
again around midnight zeroCI got  reachable again after downtime of 6 hours 
```
[Forwarded from UptimeRobot]
Monitor is UP: ZeroCI (https://zeroci.grid.tf). It was down for 5 hours, 54 minutes and 54 seconds.
```
and these too i couldn't reach are suddenly reachable 

ahmedthabet-threebot-myx.tfgw-testnet-01.ava.tf  
ahmedthabet-threebot-aay.tfgw-testnet-01.ava.tf

**Comment by zaibon** [comment]
I've started a container on the same farm and started some ping and dns lookup in an infinite loop. Let's see if we can catch some glitch from the node itself.
