### ISSUE TITLE
Add a flag to nuke a node and it's disks

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/zos#936]
Currently we don't wipe / nuke any disks. There is a use case where this would be usefull.

**Comment by muhamadazmy** [comment]
IMHO the flag should do the following:
- run custom script to wipe out all disks
- shut the node down.

> The node never fully booted, this is to force the admin to remove the flag from ipxed, otherwise it can cause issues next time the nodes are restarted (to get wiped out again)


> I am wondering if it's better to have a separate nuker image that does this instead of hacking it into zos because the boot path does not support such scenarios

**Comment by muhamadazmy** [comment]
not gonna be implemented. We "can" change zos to take ownership of any disk that has not cleaned up by users before using it with zos. But i still think this can be dangerous and it's better to leave it up to the user to clean up
