### ISSUE TITLE
Only create storagepools when needed

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/zos#94]
Right now the storage module greedily takes all available devices and creates storagepools on them when it starts, this should be changed to only create a storagepool when a filesystem is requested and there is no more space in the existing pools

**Comment by muhamadazmy** [comment]
I don't think this is required anymore since we do a spin down for unused disks. I suggest we close this issue

**Comment by DylanVerstraete** [comment]
Closing in favor of the new design of storaged where storagepools are created forehand but not mounted when they are not needed.
