### ISSUE TITLE
netoworkd: ygg interface in container should not receive IP from SLAAC

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#941]
The goal is to integrate Yggdrasil into 0-OS.
Use cases are:
- Use Yggdrasil as gobal routing network so IPv4 only nodes can still be part of the Grid
- 0-DB are always accessible over Yggdrasil (so ipv4 only nodes can still host 0-DB)
- User can ask to have an extra network interface in their container or k8s VM that has an Yggdrasil IP

Todo:
- [ ] Specification for networkd internal architecture (How and Where does yggdrasil daemon must run)
- [ ] Modification of networkd
- [ ] Testing
  - [ ] ZDB reachable over Yggdrasil
  - [ ] Container can be accessed over Yggdrasil
  - [ ] K8S VMs can be accessed over Yggdrasil

**Comment by delandtj** [comment]
the more, we should __also__ block dhcp requests emanating from that iface

**Comment by delandtj** [comment]
arf no, the container can't do anything on the network stack

**Comment by sasha-astiadi** [comment]
irrelevant / obsolote. closing
