### ISSUE TITLE
Container logs forwarding error

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/zos#943]
- Test reservation (minio): https://explorer.testnet.grid.tf/api/v1/reservations/workloads/481698
- Test reservation (threebot): https://explorer.testnet.grid.tf/api/v1/reservations/workloads/481589
- container logs configuration

![Screenshot from 2020-09-15 14-26-56](https://user-images.githubusercontent.com/10658229/93214655-bcd42a00-f765-11ea-9957-dfdcb1efebf7.png)

- Remote redis: 

```
redis-cli -h 192.241.158.21 -p 6378
```
- Scenarios:
- Working with ring logs

```
zosv2tst-6:~# zinit list
minio: Running
userkey: Success
sshd: Running
```

- doesn't work with forwarded logs

```
zosv2tst-6:~# zinit list
minio: Error(Signaled(Pid(13643), SIGPIPE, false))
userkey: Success
sshd: Running
```

**Comment by muhamadazmy** [comment]
I check the following:
- The redis instance deployed was running in protected mode, hence it accepts connections but it doesn't allow any read/write operations. this probably what caused the SIGPIPE to be received.
- Fixing redis it seems will not allow minio to work again, hence i assume the shim crashed, and noway to restore it for that container
- Asked @waleedhammam to try a new container (with non-protected redis)

**Comment by waleedhammam** [comment]
- It worked with deploying a redis instance using non-protected mode `redis-server --port 6378 --protected-mode no`

**Comment by muhamadazmy** [comment]
We have 2 issues here:
- shim failure to forward the errors causes a SIGPIPE. IMHO if the shim fails for forwarding the logs it still should keep reading the pipe from the process to not cause this issue.

- We need now to find a way to allow using protected redis (with a password) without exposing the password on the public grid. Hence the redis url should be encrypted with the node public key, the same way we protect secured environment variables.
