### ISSUE TITLE
contd: improve retry logic when container fails to start

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#957]
![2020-09-22_3494x695_scrot](https://user-images.githubusercontent.com/303164/93847610-af5bfa00-fca7-11ea-9217-127bbd64e36a.png)

**Comment by zaibon** [comment]
So what seems to have happened is the the 0-fs process providing the files for the container crashed:
```
2020-09-07T13:28:59.591Z: main I > mount ready 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x725e62]

goroutine 650422 [running]:
github.com/threefoldtech/0-fs/meta.(*Dir).Name(0x0, 0xc0033f8980, 0x5)
	/gopath/src/github.com/threefoldtech/0-fs/meta/dir.go:31 +0x22
github.com/threefoldtech/0-fs/meta.(*sqlStore).get(0xc000176a80, 0xc001d26eb0, 0x42, 0x10, 0x964300, 0xc0010e5c01, 0xc0033d1340)
	/gopath/src/github.com/threefoldtech/0-fs/meta/store.go:253 +0x1dd
github.com/threefoldtech/0-fs/meta.(*sqlStore).Get(0xc000176a80, 0xc001d26eb0, 0x42, 0xc0033d1340, 0x1, 0x1)
	/gopath/src/github.com/threefoldtech/0-fs/meta/store.go:267 +0x3f
github.com/threefoldtech/0-fs/rofs.(*filesystem).GetAttr(0xc000168bc0, 0xc001d26eb0, 0x42, 0xc002d84858, 0x0, 0x0)
	/gopath/src/github.com/threefoldtech/0-fs/rofs/rofs.go:69 +0x159
github.com/threefoldtech/0-fs/vendor/github.com/hanwen/go-fuse/fuse/pathfs.(*readonlyFileSystem).GetAttr(0xc0001ba240, 0xc001d26eb0, 0x42, 0xc002d84858, 0xc0039ac000, 0xc0010e5e78)
	/gopath/src/github.com/threefoldtech/0-fs/vendor/github.com/hanwen/go-fuse/fuse/pathfs/readonlyfs.go:26 +0x51
github.com/threefoldtech/0-fs/vendor/github.com/hanwen/go-fuse/fuse/pathfs.(*pathInode).GetAttr(0xc00070d2f0, 0xc002d847c0, 0x0, 0x0, 0xc002d84858, 0x481a5c)
	/gopath/src/github.com/threefoldtech/0-fs/vendor/github.com/hanwen/go-fuse/fuse/pathfs/pathfs.go:603 +0x7c
github.com/threefoldtech/0-fs/vendor/github.com/hanwen/go-fuse/fuse/nodefs.(*rawBridge).GetAttr(0xc000176db0, 0xc002d84840, 0xc002d847b0, 0x958b20)
	/gopath/src/github.com/threefoldtech/0-fs/vendor/github.com/hanwen/go-fuse/fuse/nodefs/fsops.go:139 +0x88
github.com/threefoldtech/0-fs/vendor/github.com/hanwen/go-fuse/fuse.doGetAttr(0xc0001d2000, 0xc002d846c0)
	/gopath/src/github.com/threefoldtech/0-fs/vendor/github.com/hanwen/go-fuse/fuse/opcode.go:246 +0x64
github.com/threefoldtech/0-fs/vendor/github.com/hanwen/go-fuse/fuse.(*Server).handleRequest(0xc0001d2000, 0xc002d846c0, 0xc002d846c0)
	/gopath/src/github.com/threefoldtech/0-fs/vendor/github.com/hanwen/go-fuse/fuse/server.go:404 +0x30c
github.com/threefoldtech/0-fs/vendor/github.com/hanwen/go-fuse/fuse.(*Server).loop(0xc0001d2000, 0xc002c59c01)
	/gopath/src/github.com/threefoldtech/0-fs/vendor/github.com/hanwen/go-fuse/fuse/server.go:376 +0x14d
created by github.com/threefoldtech/0-fs/vendor/github.com/hanwen/go-fuse/fuse.(*Server).readRequest
	/gopath/src/github.com/threefoldtech/0-fs/vendor/github.com/hanwen/go-fuse/fuse/server.go:284 +0x332
```

And thus the container also crashed, and since the workloads was not asked to be deleted, containerd just keep trying to restart the container, but fail because of the 0-fs process that is dead

**Comment by zaibon** [comment]
We should probably improve the retry logic used by containerd. Instead of blindly trying to restart a container forever we should be smarter and if we detect the container just keep restarting immediately, we stop trying to restart and send an error in the workload result, so the user know he should decommission the workload

**Comment by muhamadazmy** [comment]
This has the following setbacks:
 - The restart option in containerd does not have the option to control how many times to restart, delay or even a hook to an external binary on container crash.
 - BUT the containerd provides an event system where clients can subscribe to. So we can still subscribe to events from containerd (not sure yet about the kind of events provided by this channel). there is a method Subscribe available on the go client. then contd can turn off container restarting for that instance.
 - Updating the "reservation" result is probably gonna be challenging because even if the failure is detected (by contd) it's not possible for contd to update reservation since only provisiond can/should do it. but reservation is already out of provisiond context by then, and also contd is not aware of anything regarding the reservation itself

**Comment by zaibon** [comment]
I was also looking into the event system to solve this. I think this is a nice way to solve it. 
I did inspect what kind of even are emitted by container when stopping a container: https://gist.github.com/zaibon/7cdc6901677b562405bcc2ad57019442

I only have one concerned in your proposal. Provisiond must be notified when contd stops trying to run a container. If provisiond is not notified, then the workload will remain marked as deployed on the explorer and the capacity it consumes will continue to be drained from the attached capacity pool.
I had an idea to solve this by exposing provisiond over zbus too, so other lower level component like contd and vmd could notify provisiond in case they stop trying to run a certain workload.

**Comment by muhamadazmy** [comment]
Yeah, i already did the same check, and I have all the events i needed already. working on the code in contd already to process the events in the right way to decide when to kill the container.

Regarding provisiond it's either we have to expose a method on zbus from provisiond to handle this kind of notifications. it will mark the reservation on the explorer as failed, and also set the cache.
