### ISSUE TITLE
decommissioning of reservation failed: failed to connect to 0-db: zdbd47bbb48-3070-4cdf-bd3f-fb8d3103980a: dial unix /var/run/zdb_zdbd47bbb48-3070-4cdf-bd3f-fb8d3103980a/zdb.sock: connect: resource temporarily unavailable

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#958]
![2020-09-22_3511x548_scrot](https://user-images.githubusercontent.com/303164/93847685-dfa39880-fca7-11ea-9662-62fe9ea8d85b.png)

**Comment by muhamadazmy** [comment]
Resource temporarily unavailable means that the unix socket backlog is full and it can't accept more connections. or the process ran out of open file descriptors.

We need to review the code for potential leaks.
