### ISSUE TITLE
GE: Question: How do we configure ZeroOS to use SSDs as memory swap space?

### ISSUE THREAD

**Issue by joefoxton** [threefoldtech/zos#964]
When we originally purchased our hardware, ThreeFold advised us to include SSDs as swap space. We have reserved the SSDs for this purpose, but we are not sure that ZeroOS is using them as such. ie. we are not allocating SSDs to our S3 solutions. How can we configure ZeroOS to use the SSDs as swap space?

**Comment by zaibon** [comment]
0-OS doesn't use [swap](https://en.wikipedia.org/wiki/Paging#Unix_and_Unix-like_systems) in the sense we usually talk about swap for linux system. Instead, 0-OS does reserve a portion of one of the disk (preferably an SSD if available) of the node to use it as a cache for all the files required to run the containers (flist). 

So there is nothing to do or configure yourself, this disk selection is done automatically when the node boots the first time.
