### ISSUE TITLE
GE: Feature Request: Allow selection of specific disks for a storage cluster

### ISSUE THREAD

**Issue by joefoxton** [threefoldtech/zos#965]
We would like the ability to select specific disks to go into a min.io cluster. This will allow us to manage performance and over/under subscription.

So when reserving min.io, please allow us to:
- select specific disks;
- implies that each disk has an id under node id;
- implies that there's a disk object

**Comment by muhamadazmy** [comment]
No development on min.io anymore, since it's getting replaced with zdb-fs (zstore2)
