### ISSUE TITLE
zos: network instability

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#966]
It's been a couple of weeks we get some weird issue reported for 0-OS node that have some instability in the network.
We should investigate the root cause and address the problem. Here is a list of all the issues that might be related:

Container network doesn't work for outbound traffic:
- [x] https://github.com/threefoldtech/js-sdk/issues/1239
- [x] https://github.com/threefoldtech/zos/issues/927

Inbound traffic doesn't not reach the container when using gateway proxy and tcp router client:
- [x] https://github.com/threefoldtech/tfgateway/issues/27

**Comment by xmonader** [comment]
also there was this workload 

```
1) "message"
2) "mainet-stdout"
3) " * Restarting OpenBSD Secure Shell server sshd\n"
1) "message"
2) "mainet-stdout"
3) "   ...done.\n"
1) "message"
2) "mainet-stdout"
3) "[*] Switching to the correct version (development) ...\n"
1) "message"
2) "mainet-stdout"
3) "Fetching origin\n"
1) "message"
2) "mainet-stderr"
3) "fatal: unable to access 'https://github.com/threefoldtech/js-sdk.git/': Failed to connect to github.com port 443: Network is unreachable\n"
1) "message"
2) "mainet-stderr"
3) "error: Could not fetch origin\n"
1) "message"
2) "mainet-stdout"
3) "HEAD is now at 90446f0 Merge pull request #1142 from threefoldtech/development_fix_workloads_ui_epoch\n"
```

https://explorer.grid.tf/api/v1/reservations/workloads/11847

- workloads: 11846, 11848, 11847, 11849
and it was on vcc

**Comment by xmonader** [comment]
possible problem https://github.com/threefoldtech/tfgateway/issues/30

**Comment by xmonader** [comment]
vcc problem https://github.com/threefoldtech/zos/issues/972

**Comment by zaibon** [comment]
> vcc problem #972

This is unrelated to the issue from this story. But a bug nonetheless and will be addressed in another PR.

Regarding the issue for container that fail to reach outside IPs, We have discovered that for an unknown reason yet, some of the routing table from the node are messed up. the default route is gone. This means no IPV4 traffic can go out of the node anymore. So this could explain why containers cannot resolve DNS and also why containers exposed using TCP router client are also unreachable.

**Comment by zaibon** [comment]
Fixes for all the linked issue are now live on mainnet. Closing the issue.
