### ISSUE TITLE
cache: some nodes are complaining that quota limit has been reached

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#973]
- We need to do one (or all) the following:
 - Increase or remove cache limit all together
 - Periodic clean up of 0-fs cache removed stall files that hasn't been accessed in long time

**Comment by zaibon** [comment]
@muhamadazmy do you have the node ID of the affected node by any chance ?
Cause we do set the cache filesystem quota to 100GiB now: https://github.com/threefoldtech/zos/blob/2b7427b915cd6fc1b7c52ef92d3021f2213d730b/pkg/storage/storage.go#L29

we might have reached it on some node, but I doubt it.

**Comment by muhamadazmy** [comment]
It seems that this node qouta was not updated, I had to manually remove the limit on the node cache. 

![image](https://user-images.githubusercontent.com/10920323/94260011-ba28c000-ff2f-11ea-89f7-c906058925a8.png)


![image](https://user-images.githubusercontent.com/10920323/94260043-c3b22800-ff2f-11ea-9dc8-627fdee14966.png)

The node id was: `3dAnxcykEDgKVQdTRKmktggL2MZbm3CPSdS9Tdoy4HAF`

**Comment by zaibon** [comment]
hum this is pretty weird. I check the code path and the line where should set the quota should always be reached when storaged starts...

**Comment by zaibon** [comment]
I was wrong, I did find a code path that prevent the quota to be set on the cache filesystem. Opened https://github.com/threefoldtech/zos/pull/977 to fix it.
