### ISSUE TITLE
Container with two network connection only sees one interface

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/zos#979]
I created a container workload and added a second network connection to it but it sees only one nic in the deployed container

https://explorer.testnet.grid.tf/api/v1/reservations/workloads/487754

```
root@zosv2tst-2:/# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.243.2.100  netmask 255.255.255.0  broadcast 10.243.2.255
        inet6 fe80::405a:97ff:fe53:dedc  prefixlen 64  scopeid 0x20<link>
        inet6 fd45:685a:7959:2::64  prefixlen 64  scopeid 0x0<global>
        ether 42:5a:97:53:de:dc  txqueuelen 0  (Ethernet)
        RX packets 415  bytes 228433 (228.4 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 365  bytes 405899 (405.8 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

root@zosv2tst-2:/# 
```

**Comment by delandtj** [comment]
?? a second network interface ??

**Comment by m-motawea** [comment]
> ?? a second network interface ??

yes a second network interface. is that not supported?

**Comment by zaibon** [comment]
At the moment 0-OS only read the first network config from the workload description. The reason you can define multiple was to allow support multiple private network in a container. But this was never tested enough to be enabled. If this is now a requirement for something we can re-add it into our sprint to spend some time on it.

**Comment by xmonader** [comment]
@zaibon is there a way around it at this moment (I know Yggdrasil not happening right now too)?

 The current use case we create a 3bot container on a network `A`  owned by the 3bot deployer and @despiegk wants the ability to
1- create a network from that 3bot `mgmt`
2- connect the 3bot running on network `A` to network `mgmt`
3- allow solutions to deploy on that `mgmt` network 

If there's a way around it we can try it, but if not I guess it will need to go in, but also a question won't working on Yggdrasil be more important (if it can fix this issue along the way) ?

**Comment by zaibon** [comment]
There is no work around for such a scenario at the moment no.
And there is problem in this flow. There is no way for a container to connect to a new network after it has been created. So even if container could have 2 private networks today, the point 2 would still not be possible.

**Comment by delandtj** [comment]
shouldn't we close that issue and work out an FR for that ?

**Comment by xmonader** [comment]
> shouldn't we close that issue and work out an FR for that ?

Don't think so, this one is for a feature to define multiple networks for containers which isn't working correctly, I'll create another issue for the scenario we're trying to achieve and suggested solutions

**Comment by xmonader** [comment]
@DylanVerstraete still needed feature

**Comment by DylanVerstraete** [comment]
>  I'll create another issue for the scenario we're trying to achieve and suggested solutions

@xmonader I though you were going to crete this feature request. It will be easier to follow up.

**Comment by xmonader** [comment]
> > I'll create another issue for the scenario we're trying to achieve and suggested solutions
> 
> @xmonader I though you were going to crete this feature request. It will be easier to follow up.

Not sure our scenario is relevant anymore, but still this issue is for a feature that's not working correctly yet
