### ISSUE TITLE
make zos report the version of each daemon to the explorer

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zos#995]
By sending to the explorer the version of all the component, we can more easily identity issues. This information could also be used to decide if a node is healthy or not by comparing what version each daemon is running to the expected version it is supposed to run.

**Comment by maxux** [comment]
Could be possible to keep somewhere information like date when it was updated ? (and maybe more information, don't know)

**Comment by DylanVerstraete** [comment]
Closing because the explorer will be deprecated soon
